### ISSUE TITLE
 AcmeUserBundle declaration missing in the installation guide

### ISSUE THREAD

**Issue by ellioh-thoto** [FriendsOfSymfony/FOSUserBundle#1013]
Hi, 
I think it would be quite easy to add two points in the installation documentation that would fairly help: 

Just before Step 7 you could specify that according to the User class described in the exemple, the AcmeUserBundle must be  added to the Appkernel.php file : 

<code>new Acme\UserBundle\AcmeUserBundle()</code>

In addition, the corresponding bundle class declaration must be created ( not an evidence for beginners) : 

``` php
<?php
// src/Acme/UserBundle/AcmeUserBundle.php
namespace Acme\UserBundle;

use Symfony\Component\HttpKernel\Bundle\Bundle;

class AcmeUserBundle extends Bundle
{
}
```

Otherwise, the installation documentation is nice to follow!

**Comment by XWB** [comment]
Closing this outdated issue.
