### ISSUE TITLE
Support for Multiple Entity Managers and Connections

### ISSUE THREAD

**Issue by mohdshakir** [FriendsOfSymfony/FOSUserBundle#1017]
Symfony supports using multiple entity managers/connections (http://symfony.com/doc/current/cookbook/doctrine/multiple_entity_managers.html), but FOSUserBundle will only use the default entity manager/connection.

**Comment by xub** [comment]
the link to the solution is broken , you can tell me how to solve it ?? Thank you

**Comment by xabbuh** [comment]
@xub see http://symfony.com/doc/master/bundles/FOSUserBundle/doctrine.html (the documentation was transformed to reStructuredText recently to be rendered on symfony.com)

**Comment by xub** [comment]
very good, but as I can do if my database changes according to my domain? now I have a function that captures the domain in my code ... 

$this->getDoctrine()->getRepository('AppBundle:Blocks',Core::getDomain() );

but not how to do the same in FOSUserBundle...

**Comment by xabbuh** [comment]
I am sorry but I do not understand your question. Can you explain a bit more what you need to achieve other than what is described in the documentation?

**Comment by xub** [comment]
my EntityManager changes with the URL accessed by the user, for example: 

default.com
$this->getDoctrine()->getRepository('AppBundle:Blocks','default') ;

other.com
$this->getDoctrine()->getRepository('AppBundle:Blocks','other') ;

howto I can modify the code FosUser ?

config.yml change does not help me

**Comment by darkenergy66** [comment]
Did you resolve this issue @xub? - I have exactly the same problem

**Comment by xub** [comment]
no

**Comment by flaushi** [comment]
Hey I have a similar issue:
I defined one connection and corresponding entity manager for mysql, postgresql and mssql.

Whenever my schema changes, I produce a migration for each database type

```
bin/console doctrine:migrations:diff --em=postgres
bin/console doctrine:migrations:diff --em=my
bin/console doctrine:migrations:diff --em=ms
```
and then replace the `abortIf` - fence by `skipIf` so all migrations can run on any system.
This fails for mysql, because my default is postgres.

Is it possible to set the `fos_user. model_manager_name` to the entity manager that was supplied by the `--em=xxx` argument?

**Comment by stof** [comment]
@flaushi no that's not possible, as this CLI argument cannot influence the configuration of the container.

**Comment by flaushi** [comment]
Hmm, I see. I was thinking if environment variables could help? This solution:

```
parameters:
    env(MY_DEF_EM): 'default'
    doctrine.orm.default_entity_manager: '%env(MY_DEF_EM)%'
    fos_user.model_manager_name: '%env(MY_DEF_EM)%'

```
unfortunately does not work so far: 

`You have requested a non-existent service "doctrine.orm.%env(MY_DEF_EM)%_metadata_driver". `

**Comment by stof** [comment]
Aliases cannot be dynamic at runtime. The container needs to be able to resolve them at compile time for things to work. So using env variables won't be supported there.

**Comment by flaushi** [comment]
Thanks for your prompt support! What a pity that this does not work.

Do you have any good hint for me how to solve my problem?
