### ISSUE TITLE
Refreshing check-email route during registration throws 404

### ISSUE THREAD

**Issue by jmcclell** [FriendsOfSymfony/FOSUserBundle#1024]
This is a tiny issue, but if a user refreshes the check-email route during registration if email confirmation is turned on, the page throws a 404 because the email address has already been cleared from session:

```
if (null === $user) {
         throw new NotFoundHttpException(sprintf('The user with email "%s" does not exist', $email));
 }
```

It would be better if it were consistent with the behavior of the rest password workflow, whereby if the email address is null the user is simply redirected back to the beginning of the flow - in this case the registration page. It's less jarring/confusing than a 404, which isn't all that accurate considering the route does exist.

Pull request: https://github.com/FriendsOfSymfony/FOSUserBundle/pull/1023

**Comment by XWB** [comment]
This was fixed.
