### ISSUE TITLE
[Registration] Array to String convertion + Translator.php

### ISSUE THREAD

**Issue by Adraesh** [FriendsOfSymfony/FOSUserBundle#1042]
Hi everyone,

When I try to create a new account via the registration form, I've got this issue :

An exception has been thrown during the rendering of a template ("Notice: Array to string conversion in C:\wamp\www\Symfony\vendor\symfony\symfony\src\Symfony\Component\Translation\Translator.php line 150") in "FOSUserBundle:Registration:confirmed.html.twig".

If I refresh my page, I'am correctly redirected to the confirmed.html.twig and the user is correctly created too.

If someone has an idea ?

Thank you in advance.

**Comment by nyded** [comment]
thanks guys :) :) :+1:
