### ISSUE TITLE
How to activate bundle (symfony 2.2)?

### ISSUE THREAD

**Issue by zmaximov** [FriendsOfSymfony/FOSUserBundle#1043]
I use Composer, result:

"Loading composer repositories with package information
Updating dependencies (including require-dev)
- Installing friendsofsymfony/user-bundle (v1.3.1)
  Downloading: 100%

Writing lock file
Generating autoload files
Clearing the cache for the dev environment with debug true
Installing assets using the hard copy option
Installing assets for Symfony\Bundle\FrameworkBundle into web/bundles/framework
Installing assets for Acme\DemoBundle into web/bundles/acmedemo
Installing assets for Sensio\Bundle\DistributionBundle into web/bundles/sensiodi
stribution"

But there is no FosUserBundle in a list of Active Bundles on:
http://localhost/symfony/web/app_dev.php/_profiler/51440ae39c2be?panel=config

**Comment by ufhy** [comment]
i'm has follow instruction "Getting Started With FOSUserBundle" i've got a message

Cannot load resource "@FOSUserBundle/Resources/config/routing/all.xml". Make sure the "FOSUserBundle/Resources/config/routing/all.xml" bundle is correctly registered and loaded in the application kernel class. If the bundle is registered, make sure the bundle path "@FOSUserBundle/Resources/config/routing/all.xml" is not empty.

**Comment by ufhy** [comment]
Please update documentation about routing,

**Comment by xabbuh** [comment]
@ufhy Well, when you use FOSUserBundle 1.3, you should read its documentation and not the one for the 2.0 release.

**Comment by ufhy** [comment]
thanks
