### ISSUE TITLE
How can I get logged user id in the SecurityController?

### ISSUE THREAD

**Issue by lukeman83** [FriendsOfSymfony/FOSUserBundle#1051]
How can I get logged user id in the SecurityController in particular in the renderLogin function?

**Comment by MarwenBenTalebAli** [comment]
it didn't work for me. i got an error: You have requested a non-existent service "security.context".

**Comment by WickedSilver** [comment]
@MarwenBenTalebAli, please see [this](http://symfony.com/blog/new-in-symfony-2-6-security-component-improvements) post for more information regarding the non-existent service `security.context` which is deprecated starting from symfony 2.6 and removed in symfony 3.0
