### ISSUE TITLE
how to overriding fosuserbundle registration form style

### ISSUE THREAD

**Issue by lichnow** [FriendsOfSymfony/FOSUserBundle#1077]
I want to use bootstrap style apply in fosuserbundle registration form.and the login cant overriding,but because of  registration form use "{{ form_widget(form) }}",so I can't overriding it,I use symfony2.2,I also test use form theme,like this

```
{% block form_row %}
{% spaceless %}
<div class="control-group">
    {{ form_label(form, label|default(null),{ 'attr': {'class': 'control-label'} }) }}
    {{ form_errors(form) }}
    <div class="controls">{{ form_widget(form) }}</div>
</div>
{% endspaceless %}
{% endblock form_row %}
```

and

   in form template
   the code is

```
{% form_theme form with '@user/form/fields.html' %}
{% trans_default_domain 'FOSUserBundle' %}
<form action="{{ path('fos_user_registration_register') }}" {{ form_enctype(form) }} method="POST" class="fos_user_registration_register form-horizontal form-box">
    {{ form_widget(form) }}
    <div>
        <input type="submit" value="{{ 'registration.submit'|trans }}" />
    </div>
</form>
```

but it output this

```
  |form action="/register/"  method="POST" class="fos_user_registration_register form-horizontal form-box"|
        |div id="fos_user_registration_form"|
            |div class="control-group"|
                |label for="fos_user_registration_form_username" class="required"|用户名：|/label|
                |div class="controls"|
                    |input type="text" id="fos_user_registration_form_username" name="fos_user_registration_form[username]" required="required" /|    
                |/div|
            |/div|
            |div class="control-group"|
                |label for="fos_user_registration_form_email" class="required"|电子邮箱：|/label|
                |div class="controls"|
                    |input type="email" id="fos_user_registration_form_email" name="fos_user_registration_form[email]" required="required" /|    
                |/div|
            |/div|
            |div class="control-group"|
                |label for="fos_user_registration_form_plainPassword_first" class="required"|密码：|/label|
                |div class="controls"|
                    |input type="password" id="fos_user_registration_form_plainPassword_first" name="fos_user_registration_form[plainPassword][first]" required="required" /|    
                |/div|
            |/div|
            |div class="control-group"|
                |label for="fos_user_registration_form_plainPassword_second" class="required"|确认密码：|/label|
                |div class="controls"|
                    |input type="password" id="fos_user_registration_form_plainPassword_second" name="fos_user_registration_form[plainPassword][second]" required="required" /|    
                |/div|
            |/div|
            |input type="hidden" id="fos_user_registration_form__token" name="fos_user_registration_form[_token]" value="622a4c73bfc48b4944c5b97ff4fc46c7fa8e9e91" /|    
        |/div|
        |div|
            |input type="submit" value="注册" /|    
        |/div|
    |/form|
```

its not what I want,so what I can do for it?thx!

**Comment by Dimentar** [comment]
Override "register_content.html.twig"

```twig
    <form action="{{ path('fos_user_registration_register') }}" {{ form_enctype(form) }} method="POST">
    <div class="form-group" id="fos_user_registration_form">
        {{ form_widget(form.email, { 'attr': {'class': 'form-control', 'placeholder': 'form.email'|trans } }) }}
        {{ form_errors(form.email) }}

        {{ form_widget(form.username, { 'attr': {'class': 'form-control', 'placeholder': 'form.username'|trans } }) }}
        {{ form_errors(form.username) }}

        {{ form_widget(form.plainPassword.first, { 'attr': {'class': 'form-control', 'placeholder': 'form.password'|trans } }) }}
        {{ form_errors(form.plainPassword.first) }}

        {{ form_widget(form.plainPassword.second, { 'attr': {'class': 'form-control', 'placeholder': 'form.password_confirmation'|trans } }) }}
        {{ form_errors(form.plainPassword.second) }}

        {{ form_rest(form) }}

    </div>
    <div>
        <input class="btn btn-lg btn-primary btn-block" type="submit" value="{{ 'registration.submit'|trans }}">
    </div>
</form>

**Comment by DaniSancas** [comment]
Just came to say +1 to @Dimentar explanation and to point that @carlcraig 's coment's first link is broken, now is https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Resources/doc/overriding_templates.rst (notice `.rst` instead of `.md`), just in case you want to keep that explanation up to date.

Thank you all for your advice, and sorry for the interruption.

**Comment by xabbuh** [comment]
You should better view the docs on http://symfony.com/doc/master/bundles/FOSUserBundle/overriding_templates.html (it's much easier to read as everything will be rendered properly on symfony.com).

**Comment by jalpeshmakadia** [comment]
I want to overriding below files in FOSUserBundle. can any body guide how can i do that?

/vendor/friendsofsymfony/user-bundle/Model/User.php
/vendor/friendsofsymfony/user-bundle/Model/UserInterface.php
/vendor/friendsofsymfony/user-bundle/Resources/config/doctrine-mapping/User.orm.xml

Thanks.

**Comment by geoffreyhale** [comment]
Can FOSUserBundle default form appearance be configured via config.yml as Twig can be?:
`twig:
form_themes:
        - bootstrap_3_layout.html.twig`

**Comment by AmaliDeveloper** [comment]
You can get the solution in this tutorial [Link](https://youtu.be/u4q_VqewQe4)

**Comment by maninder1516** [comment]
Helped in customizing my registration template. Thanks...

**Comment by saidaLachgar** [comment]
**Override "register_content.html.twig" in symfony 4**
<form action="{{ path('fos_user_registration_register') }}" {{ form_enctype(form) }} method="POST">
{{ form_start(form, {'method': 'post', 'action': path('fos_user_registration_register'), 'attr': {'class': 'fos_user_registration_register'}}) }}
    <div class="form-group" id="fos_user_registration_form">
        {{ form_widget(form.email, { 'attr': {'class': 'form-control', 'placeholder': 'form.email'|trans } }) }}
        {{ form_errors(form.email) }}

        {{ form_widget(form.username, { 'attr': {'class': 'form-control', 'placeholder': 'form.username'|trans } }) }}
        {{ form_errors(form.username) }}

        {{ form_widget(form.plainPassword.first, { 'attr': {'class': 'form-control', 'placeholder': 'form.password'|trans } }) }}
        {{ form_errors(form.plainPassword.first) }}

        {{ form_widget(form.plainPassword.second, { 'attr': {'class': 'form-control', 'placeholder': 'form.password_confirmation'|trans } }) }}
        {{ form_errors(form.plainPassword.second) }}

        {{ form_rest(form) }}

    </div>
{{ form_rest(form) }}
        <div>
            <input type="submit" value="{{ 'registration.submit'|trans }}" />
        </div>
{{ form_end(form) }}
