### ISSUE TITLE
Deserialize json to user object "You must define a type"

### ISSUE THREAD

**Issue by artworkad** [FriendsOfSymfony/FOSUserBundle#1090]
```
$this->get('request')->getContent()
```

returns 

```
{"id":2,"username":"...@gmail.com","username_canonical":"...@gmail.com", ... }
```

Deserialization:

```
$data = $serializer->deserialize($this->get('request')->getContent(), 'My\SpecialBundle\Entity\User', 'json');
```

throws:

"request.CRITICAL: Uncaught PHP Exception JMS\Serializer\Exception\RuntimeException: "You must define a type for FOS\UserBundle\Model\User::$username." at ...\vendor\jms\serializer\src\JMS\Serializer\GenericDeserializationVisitor.php line 170 [] []"

Whats wrong?! How can I deserialize the json to a user object correctly? I use symfony 2.3

**Comment by apatkinson** [comment]
Anyone else that stumbles upon this issue and is using annotations:

````PHP
Class Model
{
    /**
     * @ORM\Column(type="boolean", nullable=true)
     * @Type("boolean")
     */
    protected $boolean;
}
```

**Comment by jtaylor100** [comment]
Similarly if you are trying to de-serialize objects like the OP, this worked for me:
```php
use App\MyClass;

class Model
{
    /**
     * @var MyClass
     * @Type(MyClass::class)
     */
    private $property;
}
```
