### ISSUE TITLE
move doctrine listeners to Doctrine directory to not pollute the main namespace

### ISSUE THREAD

**Issue by dbu** [FriendsOfSymfony/FOSUserBundle#1115]
follow up of #1081 - i can do the PR but wanted to ask how exactly first, to safe some effort :-)

we should move the doctrine listeners to a better directory. they are specific to the persistence layers... on the symfony list we discussed a namespace like Persistence\Doctrine if generic, a subdirectory Orm|Mongo|Couch|Phpcr for this. shall i moved them to Persistence\Doctrine or do we want to cut out the Persistence thing and just call it Doctrine?

and should i create BC classes or do you not expect people to rely on those class names (extended them, instanceof, declaring custom services)?

**Comment by stof** [comment]
We have them in a ``Doctrine`` namespace since quite some time now
