### ISSUE TITLE
Perhaps a Security Issue

### ISSUE THREAD

**Issue by venu** [FriendsOfSymfony/FOSUserBundle#1124]
I was reading this doc (http://phpsecurity.readthedocs.org/en/latest/Insufficient-Entropy-For-Random-Values.html) (potential issues in using mt_rand etc), even zf2 has updated their code (http://framework.zend.com/security/advisory/ZF2013-02).

It looks like our TokenGenerator (https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Util/TokenGenerator.php) could be vulnerable.

I have checked security bundle SecureRandom class (https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Security/Core/Util/SecureRandom.php) this looks bit more secure than FOSUserBundle Token Generator.

So, We could use this Security Bundle Secure Random class instead of our Existing Token Generator (as Default). or we could use this https://github.com/ircmaxell/RandomLib (but one more dependency)

Please let me know if I am wrong.

**Comment by XWB** [comment]
See above.
