### ISSUE TITLE
Can't create new user - "Array to string conversion"

### ISSUE THREAD

**Issue by adachauer** [FriendsOfSymfony/FOSUserBundle#1168]
Hi,

I tried to create a new user via the console and got the following error:  Notice: Array to string conversion in /vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php line 103

I used the following command: fos:user:create test test@test.de test

Thanks for help!

Anton

**Comment by XWB** [comment]
:+1:

**Comment by Yohanan26** [comment]
j
