### ISSUE TITLE
UserProvider should enforce UserInterface, not User

### ISSUE THREAD

**Issue by jaspernbrouwer** [FriendsOfSymfony/FOSUserBundle#1172]
In `FOS\UserBundle\Security\UserProvider`:

```
    if (!$user instanceof User && !$user instanceof PropelUser) {
        throw new UnsupportedUserException(sprintf('Expected an instance of FOS\UserBundle\Model\User, but got "%s".', get_class($user)));
    }
```

IMHO the `refreshUser()` method shouldn't enforce the concrete `FOS\UserBundle\Model\User` class, but instead check for the `FOS\UserBundle\Model\UserInterface` interface. It could also check for the `FOS\UserBundle\Model\GroupableInterface`, but I'm not really sure that's needed here.

I've created my own `User` entity, implementing the `UserInterface` and `GroupableInterface`, but cannot use it due to the above.

PS: The proposed change would also make the check for `FOS\UserBundle\Propel\User` obsolete (as it implements `UserInterface` and `GroupableInterface` too).

PPS: I'm going to create a fork in order to address this issue. If others agree I'm happy to do a Pull Request.

**Comment by XWB** [comment]
This was changed to `UserInterface` some time ago.
