### ISSUE TITLE
Array to string conversion by editing an user

### ISSUE THREAD

**Issue by qmarlats** [FriendsOfSymfony/FOSUserBundle#1181]
Hello,

I just report a bug I have when I edit an user profile (array to string conversion):

```
An exception has been thrown during the rendering of a template ("Notice: Array to string conversion in /var/www/Symfony/vendor/symfony/symfony/src/Symfony/Component/Translation/Translator.php line 188") in "FOSUserBundle:Profile:show.html.twig".
```

It's an important bug because we can't put online a site where if you edit your profile you get a "500 Internal Server Error". ;) I precise after a page refresh the user has been edited, so the bug is just when you was redirected in profile page after editing it.

Thank!

**Comment by stopsopa** [comment]
+ same problem
