### ISSUE TITLE
[Symfony2] [FOSUserBundle] plusieurs utilisateurs

### ISSUE THREAD

**Issue by mhamdiamine** [FriendsOfSymfony/FOSUserBundle#1188]
Salut à tous !
Je dois réaliser un site dans lequel il doit y avoir deux types d'utilisateurs qui ont des champs différents à persister dans la base de données ,Cependant FOSUserBundle ne peux en gérer qu'un seul. je dois générer une table pour chaque type en plus d'une table générique utilisé pour la connexion contient les champs communs des utilisateurs .

j'ai utilisé une solution impropre qui regroupe tous les champs dans la classe de mon bundle qui hérite de FOS et de affecter NULL aux champs qui ne correspond pas utilisateurs exacte 

Je ne veux pas utiliser PUGXMultiUserBundle . il ce qu'il y a une solution de faire séparer les champs 

Merci d'avance pour votre aide !

**Comment by jeromine7680** [comment]
as tu réglé ton problème ?

**Comment by sstok** [comment]
I do not speak French, but you can have a look at.
https://github.com/rollerworks/RollerworksMultiUserBundle

**Comment by XWB** [comment]
See above.

**Comment by sstok** [comment]
FYI, the RollerworksMultiUserBundle is no longer maintained.
