### ISSUE TITLE
Override resetting templates / Problem with route token

### ISSUE THREAD

**Issue by Bubelbub** [FriendsOfSymfony/FOSUserBundle#1214]
Hello,

Reference: #878 (is closed!?)

**Problem is:**

```
An exception has been thrown during the rendering of a template
("Some mandatory parameters are missing ("token") to generate
a URL for route "fos_user_resetting_reset".") in
FOSUserBundle:Resetting:reset.html.twig at line 4.
```

The templates be total normal ...
**Information:** I could override ALL templates except the one with the "token" parameter.
**And second information:** I could override the templates "normal" without "extends" or "include" tags... Then everythink is okay. But if i use extends or include tag i get the error =.=

**FOSUserBundle:Resetting:reset.html.twig**

```
{% extends "FOSUserBundle::layout.html.twig" %}

{% block fos_user_content %}
    {% include "FOSUserBundle:Resetting:reset_content.html.twig" %}
{% endblock fos_user_content %}
```

**FOSUserBundle:Resetting:reset_content.html.twig**

```
{% extends "FOSUserBundle::layout.html.twig" %}

{% block contentmain %}
    <form action="{{ path('fos_user_resetting_reset', {'token': token|default('123abc')}) }}" {{ form_enctype(form) }} method="POST">
        {{ form_widget(form) }}
        <div>
            <input type="submit" value="{{ 'resetting.reset.submit'|trans }}" />
        </div>
    </form>
{% endblock %}
```

**FOSUserBundle::layout.html.twig**

```
{% extends '::base.html.twig' %}

{% block contentmain %}
    {% block fos_user_content %}{% endblock %}
{% endblock %}
```

**Dont know why there is a problem with this... Only one parameter in route...**

**Comment by HVSoftware** [comment]
I still had the same issue. Looks like a small issue in the Mailer\Mailer

    public function sendResettingEmailMessage(UserInterface $user)
    {
        $template = $this->parameters['resetting.template'];
        $url = $this->router->generate('fos_user_resetting_reset', array('token' => $user->getConfirmationToken()), true);
        $rendered = $this->templating->render($template, array(
            'user' => $user,
            'confirmationUrl' => $url
        ));
        $this->sendEmailMessage($rendered, $this->parameters['from_email']['resetting'], $user->getEmail());
    }

token is not passed to template

 $rendered = $this->templating->render($template, array(

Only user and confirmationUrl

**Comment by anil-ku-in** [comment]
try This

{% trans_default_domain 'FOSUserBundle' %}
<form id="form-reset-pwd" action="{{ path('fos_user_resetting_reset', {'token': token}) }}" {{ form_enctype(form) }} method="POST" class="fos_user_resetting_reset">
    {#<input type="hidden" name="token" value="fos_user_resetting_form[token] }}" />#}
    <div class="form-group form-group-default">
        <div class="controls">
            <div id="fos_user_resetting_form">
                <div>
                    {#<label for="fos_user_resetting_form_plainPassword_first" class="required" aria-required="true">New password</label>#}
                    <input type="password" id="fos_user_resetting_form_plainPassword_first" class="form-control" name="fos_user_resetting_form[plainPassword][first]" placeholder="New password" required="required" aria-required="true">
                </div>
                {#<input type="hidden" id="fos_user_resetting_form__token" name="fos_user_resetting_form[_token]" value="3ZYXKngRraf4fDGRj7gGwbQNmDKpTs9a_gmvMPKH1zo">#}
            </div>
        </div>
    </div>
    <div class="form-group form-group-default">
        <div class="controls">
            <div id="fos_user_resetting_form">
                <div>
                    {#<label for="fos_user_resetting_form_plainPassword_second" class="required" aria-required="true">Repeat new password</label>#}
                    <input type="password" id="fos_user_resetting_form_plainPassword_second" class="form-control" name="fos_user_resetting_form[plainPassword][second]" placeholder="Repeat new password" required="required" aria-required="true">
                </div>
                {#<input type="hidden" id="fos_user_resetting_form__token" name="fos_user_resetting_form[_token]" value="3ZYXKngRraf4fDGRj7gGwbQNmDKpTs9a_gmvMPKH1zo">#}
            </div>
        </div>
    </div>
    <button id="validate-login" type="submit" value="{{ 'resetting.reset.submit'|trans }}" class="btn btn-orange btn-cons btn-animated from-left fa fa-arrow-right action submit" style="display: block;">
        <span>{{ 'resetting.reset.submit'|trans }}</span>
    </button>
    {{ form_row(form._token) }}
</form>

**Comment by shakaran** [comment]
For other sufering this behaviour (and arrive here from google) when extend templates over the resetting template (for example for modify the layout) with twig variables that contains "_", in my case it was "_route" (via app.request.attributes.get('_route')) like this:

```
{% set current_path_name = app.request.attributes.get('_route')|url_encode|default('myapp_index') %}

{% set current_path = path(current_path_name) %} 
```
		
My workaround was set always by default a value for the "token" which was complaning, passing a default value since it is not picking the right one for the extends.

```
{% set current_path_name = app.request.attributes.get('_route')|url_encode|default('myapp_index') %}

{% set current_path = path(current_path_name, {token : token|default('1234') }) %} 
```
In my opinion, I don't understand why we cannot use _variables in extends, it should be supported or fosuser bundle should change the approach for allow easy extends in his templates, because probably a lot people has this bug at some point in customization

**Comment by vasoft** [comment]
Using Symfony 4, in my case the issue was that in the database, User table, the field confirmation_token was empty '' and it should be NULL. It worked for me with NULL value.
It was empty because I forgot it so during several debugging moments.
