### ISSUE TITLE
Resetting : Request : No csrf_token token

### ISSUE THREAD

**Issue by GeoffreyHervet** [FriendsOfSymfony/FOSUserBundle#1217]
Hello,

Is it good if you don't have csrf_token in your request new password form ?

Regards

**Comment by ekut** [comment]
Just add
`{{ form_widget(form._token) }}`
to your reset.html.twig (or other template you use).

**Comment by jorrit** [comment]
Can you give a more detailed example? I get `Variable "form" does not exist in FOSUserBundle:Resetting:request_content.html.twig at line 2`.
I think the resetting request form should have the same csrf facility as the login form, just for the sake of consistency.

**Comment by XWB** [comment]
Closing this outdated issue.
