### ISSUE TITLE
Resetting token_ttl: Provide separate timeout for token time to live and wait before retry request.

### ISSUE THREAD

**Issue by PeterWooster** [FriendsOfSymfony/FOSUserBundle#1231]
The parameter resetting.token_ttl is used for two different things.  It is used to determine the time to live for the token and the time the user must wait before retrying the request.

These two times are inherently different,  the token life should be relatively long, about the day that is the default, the time the user has to wait should be relatively short, a minute or two at the most.  A user who is trying to retry their password reset is often retrying because they somehow messed up the previous reset: eg. lost the email.

Also the message about the wait has the 24 hours wired into the i18n, so it's hard to change.  

I've added the second parameter to my bundle and feel it should be added to the FOS User Bundle.   Adding to my bundle required: override the controller, add the config for the new parameter to the DIC, override the translations.  A lot of work for an additional parameter.

**Comment by VeN** [comment]
:+1:

**Comment by mattvick** [comment]
:+1:

**Comment by xDaizu** [comment]
:+1: I tried to set it to 0 so it wouldn't have to wait for reset and now they immediately expire

**Comment by cheesecase** [comment]
:+1:

**Comment by greg606** [comment]
👍

**Comment by bwenstar** [comment]
Also would love to see a fix for token_ttl to separate its functionality

**Comment by hellomedia** [comment]
Indeed the current behaviour does not pass the real-life test.

**Comment by chrislebaron** [comment]
👍

**Comment by core23** [comment]
Maybe someone could provide a PR with this feature instead of posting stupid 👍 comments. This feature wouldn't come automatically when there are 1452 👍 s

**Comment by Artem-G** [comment]
3.5 years and still was not fixed?
Does everyone these days have their own user management bundle or something? )

**Comment by XWB** [comment]
Can you guys have a look at https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2418 ?
