### ISSUE TITLE
How to print the role of user with FOSUserBundle

### ISSUE THREAD

**Issue by vuquanghoang** [FriendsOfSymfony/FOSUserBundle#1232]
I use FOSUserBundle for user management. I want to create a user management page that list all of user.In twig file, I can print username, email,... but roles. I get massage "cannot convert array to string". Can anyone help me?.

By the way, I just wanna print the name of role. For example: admin for ROLE_ADMIN, user for ROLE_USER. Do you have any ideas?

Thank in advance :)

**Comment by erevos-13** [comment]
Hello i am in this problem can @vuquanghoang  say how you solve this?

**Comment by beany-vu** [comment]
I followed @haphan's recommendation.

**Comment by rokerbp** [comment]
> If you only want to display the raw roles, you can use the `join` filter.
> 
> ```
> {{ user.roles|join(', ') }}
> ```

Thank you! I solve with this!
