### ISSUE TITLE
Never-ending redirected to the login page

### ISSUE THREAD

**Issue by AliceMakk** [FriendsOfSymfony/FOSUserBundle#1278]
Hello.

I'm using Symfony 2.1.x with FOSUserBundle.

Some people, who using my login page, can't authorized, becouse they write login and pass and next if password and login are right, they move again on the this login page, but if they write, example, not right password, they see error 'Password or login is not rigth'.
Some people clean cache browser and it's help them, but some clean cache and cookie and e.t.c and all the same can't enter to the secret page, they redirect again to the login page.

Who knows what is it? And how i can resolve my problem?

Very sorry about my english.

**Comment by muhiddingithub** [comment]
I have changed role name IS_AUTHENTICATED_ANONYMOUSLY to PUBLIC_ACCESS  it's is working for me, Symfony 6 > mine

**Comment by PululuK** [comment]
> I have changed role name IS_AUTHENTICATED_ANONYMOUSLY to PUBLIC_ACCESS it's is working for me, Symfony 6 > mine


Thanks @muhiddingithub
