### ISSUE TITLE
install FosUserBundle in symphony 2.3

### ISSUE THREAD

**Issue by karimdev** [FriendsOfSymfony/FOSUserBundle#1293]
hi,
I started to work in this famous framework. I want to know if I can install FosUserBundle in symphony 2.3? And the how I do this "install the bundle manually, without composer" if yes, if no can you give me the link to download version 2.1 with vendor(the official link does not work).
thank you

**Comment by AmaliDeveloper** [comment]
you can get th solution in this tutorial [link](https://youtu.be/KT2JHTKziPo)
