### ISSUE TITLE
Multiple User classes for different entity managers

### ISSUE THREAD

**Issue by drgomesp** [FriendsOfSymfony/FOSUserBundle#1294]
Hey!

I use multiple entity managers, as this is a common use case for any symfony application, but I want to have two different `User` entities, with different relationships and fields, for each entity manager.

Currently I have both entities already extending the base `User` class, but only the one that uses the default entity manager gets the database correctly setup on the `schema:update` command.

The other table remains only with the `id` field.

Any solutions for that? Maybe I need to change the manager at runtime, somehow...

**Comment by khalid-s** [comment]
i do agree with @stof that its not a common use case to have multiple user manager and FOSUser cannot handle this as this would imply too much complexity (for as far as I am concern, the most common case scenarios you only need 1 user manager) for all fosuser community.

But I also agree that its often happens that we do need to handle multiple user managers and would be great if there was a bundle for it :-)

**Comment by stof** [comment]
Closing this as configuring the whole bundle multiple times is not something I want to provide.
People really wanting to have multiple user managers should configure services themselves (and wire controllers to do it)
