### ISSUE TITLE
[2.3] Use Sf 2.3 form features (allows better twig theming)

### ISSUE THREAD

**Issue by kaiwa** [FriendsOfSymfony/FOSUserBundle#1305]
Symfony 2.3 provides new button field types which makes it possible to pre-define the full form.

FOSUserBundle / Resources / views / Registration / register_content.html.twig

```
{% trans_default_domain 'FOSUserBundle' %}

<form action="{{ path('fos_user_registration_register') }}" {{ form_enctype(form) }} method="POST" class="fos_user_registration_register">
    {{ form_widget(form) }}
    <div>
        <input type="submit" value="{{ 'registration.submit'|trans }}" />
    </div>
</form>
```

In the best case the form should be completely rendered with the `{{ form() }}` function in order to make full use of twig theming:

FOSUserBundle / Resources / views / Registration / register_content.html.twig

```
{% trans_default_domain 'FOSUserBundle' %}

{{ form(form, {'method': 'POST'}) }}
```

**Comment by XWB** [comment]
We now support Symfony >= 2.7
