### ISSUE TITLE
check on request method on the registration -> confirm action?

### ISSUE THREAD

**Issue by DynomiteSoul** [FriendsOfSymfony/FOSUserBundle#1312]
Recently I've had an issue with the registration of new users.

In the configuration I've enabled the confirmation by email option. But when the email was sent, there can be a request to the confirmation URL causing the confirmation token to be reset to null and the user being enabled. I see the request in the Apache access log.

I've not yet located the exact source of this request but I've solved the issue by checking on the request method in the confirm action.

I thought I'd report this issue in case it hasn't been reported already.

**Comment by stof** [comment]
We now have method requirements in the routing in 2.0
