### ISSUE TITLE
Roles field is an object in MongoDB

### ISSUE THREAD

**Issue by Hast** [FriendsOfSymfony/FOSUserBundle#1322]
Why the 'roles' field has type HASH for MongoDB mapping?

I have a problem when I attempt to find users, which have ROLE_SOMETHING or ROLE_SOMETHING_ELSE as one of their roles. It would be a simple query if 'roles' is an array:

```
db.User.find({roles: {$in: ['ROLE_SOMETHING', 'ROLE_SOMETHING_ELSE']}})
```

But I can't do that, because 'roles' field is a hash, not a collection.
Even If I can make a query to do what I want, storing roles in such way is not a good idea, is it?

**Comment by stof** [comment]
Fixed in 2.0
