### ISSUE TITLE
No way to add Loggable extension to FOSUser

### ISSUE THREAD

**Issue by dialogik** [FriendsOfSymfony/FOSUserBundle#1357]
I'm trying to implement the [StofDoctrineExtensionsBundle](https://github.com/stof/StofDoctrineExtensionsBundle) into my Symfony2 + FOSUserBundle project. But I can't add the loggable behaviour to username or email, because as soon as I try to define them via annotations or via yml I get a

```
[Doctrine\ORM\Mapping\MappingException]
Duplicate definition of column 'email' on entity
'Acme\MyBundle\Entity\User' in a field or discriminator
column mapping.
```

Do you see any way to handle this?

I think not just for integrating third party libraries, but also to provide the possibility to insert validation constraints via annotations should be provided.

**Comment by XWB** [comment]
Closing this as the PR was rejected.

**Comment by Assigyn** [comment]
Well, it's been a while since this problem was discovered, still here's the solution I've found in case someone still has issues with that.

In my App\Entity\User, I just overrode the needed attributes like this (here the username for example)

```
    /**
     * @var string
     * @Gedmo\Versioned
     */
    protected $username;
```

It's working just fine.
