### ISSUE TITLE
Missing argument 1 for Group::__construct()

### ISSUE THREAD

**Issue by sunviwo** [FriendsOfSymfony/FOSUserBundle#1375]
I can't create a new group in SonataAdminBundle. I integrated the Group entity in my admin space but whenever I hit the create button, it returns this error: ContextErrorException: Warning: Missing argument 1 for Svi\UserBundle\Entity\Group::__construct(), called in C:\wamp\www\Project\vendor\sonata-project\doctrine-orm-admin-bundle\Sonata\DoctrineORMAdminBundle\Model\ModelManager.php on line 411 and defined in C:\wamp\www\Project\src\Svi\UserBundle\Entity\Group.php line 20
Any help?

**Comment by huitiemesens** [comment]
@etoileweb  i have meet the same problem for the very first time , did you solve this ?

**Comment by etoileweb** [comment]
Yes, I got to use SonataUser in conjunction with SonataAdmin

**Comment by huitiemesens** [comment]
Found it, for a unknown reason i had to calll

Parent::construct in my group entity then init the $name .

-----Message d'origine-----
De : "etoileweb" <notifications@github.com>
Envoyé : ‎17/‎09/‎2015 23:48
À : "FriendsOfSymfony/FOSUserBundle" <FOSUserBundle@noreply.github.com>
Cc : "Charles-Antoine Fournel" <charles@huitiemesens.fr>
Objet : Re: [FOSUserBundle] Missing argument 1 for Group::__construct()(#1375)

Yes, I got to use SonataUser in conjunction with SonataAdmin

**Comment by zhil** [comment]
@huitiemesens @etoileweb 
you can fix it by adding to your GroupAdmin class
```
public function getNewInstance()
    {
        $class = $this->getClass();
        return new $class('', array());
    }
```

**Comment by huitiemesens** [comment]
@zhil  thx , i finally did after digging in code :+1:

**Comment by zhil** [comment]
I ended installing Sonata-User, it have nice role selection for groups :)
