### ISSUE TITLE
fos_user.registration.form service not found exception

### ISSUE THREAD

**Issue by musonic** [FriendsOfSymfony/FOSUserBundle#1408]
I'm not sure if this is a bug or not, but I can't work out a fix. I'm getting a ServiceNotFoundException relating to the fox_user.registration.form service. I'm using ~2.0@dev.
Everything works ok on my local machine running OS X, but fails when I upload to my Ubuntu 12.04 server. 
Could it possibly be a case sensitivity bug?

**Comment by ZhaoMuqiang** [comment]
I met the same problem, looking forward to solution...
