### ISSUE TITLE
[RFC] LoginManager does not call UserChecker->checkPreAuth()

### ISSUE THREAD

**Issue by simshaun** [FriendsOfSymfony/FOSUserBundle#1409]
A bit of background first:

I'm adding an option that enables "Users require Admin Approval" functionality. The way it works is like so (if admin approval is required):

| Step | Description |
| --- | --- |
| 1 | User registers for an account, email confirmation is sent. |
| 2 | User clicks button in email to confirm his email address. |
| 3 | User sees "confirmed" page |
| 4 | Approval email sent to admins |
| 5 | Admin approves user's account |
| 6 | User receives welcome email |

**Step 3** is where I need to diverge from default FOSUser functionality. I need FOSUser to **not** login the user on `FOSUserEvents::REGISTRATION_CONFIRMED` like it currently does, because their account has not been approved by an admin.

There are two methods of solving this problem that I'm aware of.
1. Replace FOSUser's [`AuthenticationListener`](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/EventListener/AuthenticationListener.php) to check both `$user->isEnabled()` and `$user->isApproved()`. This is not a good option because I would have to duplicate the logic eventually to account for non-approved users trying to login elsewhere in the application.  Also, there is no config option to tell FOSUser what AuthenticationListener class to use, so it needs to be replaced by using a compiler pass, afaik.
2. The User entity implements `AdvancedUserInterface`. Modify `isAccountNonLocked()` on the User entity to return false if the user is not approved. This method relies on Symfony's [`UserChecker->checkPreAuth()`](https://github.com/symfony/Security/blob/master/Core/User/UserChecker.php#L35) method because that's where `isAccountNonLocked()` is verified. Unfortunately, FOSUser's [LoginManager](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Security/LoginManager.php#L47) does not call `UserChecker->checkPreAuth()`. It only calls `checkPostAuth()`.

So, is there a reason why the LoginManager doesn't call `checkPreAuth()`? I feel like it should.

**Comment by rtuin** [comment]
Is this solved with https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2210 ?
