### ISSUE TITLE
Locked user can login by resetting his password

### ISSUE THREAD

**Issue by EmmanuelVella** [FriendsOfSymfony/FOSUserBundle#1413]
A locked user can login if he resets his password and click the email link. Maybe a check should be added in the controller ?

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2210

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSUserBundle/commit/5c45199985b8c95ccad6b4d538765ff47830e9e4
