### ISSUE TITLE
Pb with Symfony 2.3 UPGRADE

### ISSUE THREAD

**Issue by MrGreenStuff** [FriendsOfSymfony/FOSUserBundle#1424]
I every one i just upgraded Symfony (and many bundle) from 2.2 to 2.3.

FOSUserBundle currently installed version is : 1.3.3 
FOSRestBundle  currently installed version is : dev-master
FOSFacebookBundle  currently installed version is : dev-master
FOSAdvancedEncoderBundle  currently installed version is : dev-master

I have an fatal error : 

```
Expected argument of type "string or Symfony\Component\PropertyAccess\PropertyPath", "boolean" given
```

Come from : **RegistrationController -> registerAction**
On this line : 

```
$form = $this->container->get('fos_user.registration.form');
```

But it's when i try to get any FOSUser service.

If somebody have an idea ?

Thanks

**Comment by XWB** [comment]
Closing this outdated issue (Symfony 2.3 is really old).
