### ISSUE TITLE
Overriding Controllers

### ISSUE THREAD

**Issue by aitboudad** [FriendsOfSymfony/FOSUserBundle#1441]
Hi,
What do you think to define FOSUserBundle Controllers as services.
The main advantage is that it allows us to overriding Default Controllers without registering the FOSUserBundle as the "parent" of  bundle.

**Comment by patrick-mcdougle** [comment]
Overwriting controllers as services is a lot easier than having to extend the whole bundle to get it done. I'd vote for this. :+1:

**Comment by sarabkohli** [comment]
:+1:  Controllers as services...

**Comment by aitboudad** [comment]
I'll work on it this week then :)

**Comment by stof** [comment]
Closing this as I don't want to change this now (as I want to release 2.0)
