### ISSUE TITLE
Resetting password, link in email whihtout token...

### ISSUE THREAD

**Issue by Airclic** [FriendsOfSymfony/FOSUserBundle#1451]
Hello,
sometimes, when a user use the resetting password, the link in email received not content the token:
http://mysite.com/resetting/reset/
And of course the link is not good and the page is:
No route found for "GET /resetting/reset/"
It's not always...i don't now what's the problem...
Do you now this problem ?
Tanks a lot.

**Comment by XWB** [comment]
I believe this was resolved.
