### ISSUE TITLE
RESETTING_RESET_REQUESTED Event

### ISSUE THREAD

**Issue by rdohms** [FriendsOfSymfony/FOSUserBundle#1452]
I was looking into available events in the Bundle and noticed there is not an event that is thrown when a password reset is requested.

In our audit bundle we would like to track these events to be able to notice any abuse of the feature, or to help identify users with trouble in that aspect.

Would it be interesting for me to send a PR with this new event? Do you agree with having it? If so i'll send the PR.

**Comment by boRk3D** [comment]
+1

**Comment by XWB** [comment]
We now have several events in `ResettingController`.
