### ISSUE TITLE
User login doesn't work (CouchDB)

### ISSUE THREAD

**Issue by roberthills** [FriendsOfSymfony/FOSUserBundle#1476]
I've used FOS user bundle many times with ORM and it works perfect. However, on my latest project I am using CouchDB and the user bundle doesn't seem to be working 100%.

I can register, create users on the command line and these show in CouchDB Futon. If I type in an incorrect password it displays "Bad Credentials", however with the correct login details it does nothing and I am not logged in.

My set up is the same as the documentation examples. Any help is appreciated.
Symfony version 2.4.3

**Comment by XWB** [comment]
Closing this as we do not have CouchDB maintainers.
