### ISSUE TITLE
refreshing `fos_user_resetting_send_email` page fails

### ISSUE THREAD

**Issue by gondo** [FriendsOfSymfony/FOSUserBundle#1488]
when user tries to reset password and enters wrong password, user ends up on `fos_user_resetting_send_email` route. however this route has defined just `POST` method therefore if the user refresh the page (or reopen browser with pre-opened tabs), error page is displayed.

this is because template rendering is happening in `ResettingController:sendEmailAction` when `null === $user` https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Controller/ResettingController.php#L51
same for `if ($user->isPasswordRequestNonExpired($this->container->getParameter('fos_user.resetting.token_ttl')))`
https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Controller/ResettingController.php#L55

possible solutions are:
- change temlpate rendering to redirects - the problem is that `invalid_username` have to be captured by `ResettingController:requestAction` and passed to template
- add `GET` method to `fos_user_resetting_send_email` - the problem here is, that on page refresh, the `invalid_username` will be empty, but user will be presented with error message `resetting.request.invalid_username` with empty user

additional fix:
additional check if `invalid_username` is not empty in `Resetting\request_content.html.twig`.
original: `{% if invalid_username is defined %}`
changed: `{% if invalid_username is defined and invalid_username is not empty %}`

**Comment by stof** [comment]
This has been fixed by the refactoring of the password resetting system
