### ISSUE TITLE
Can't login user

### ISSUE THREAD

**Issue by ghost** [FriendsOfSymfony/FOSUserBundle#1494]
I followed the documentation and everything worked perfectly fine. 
But I have a problem now and that is I can't login user on localhost but everything works fine when I deploy it to my web server. Do you have any idea what could the problem be?

**Comment by kedrap** [comment]
If you don't want to change storage layer /file/ to something else /e.g. memcache(d)/ as a workaround, you can use the same solution like in https://github.com/FriendsOfSymfony/FOSUserBundle/issues/689#issuecomment-66284220:

```
...
framework:
...
    session:
        handler_id: ~ 
...
```
