### ISSUE TITLE
Request a new password

### ISSUE THREAD

**Issue by AlexSanzharevskyy** [FriendsOfSymfony/FOSUserBundle#1500]
Hi! When i try to request a new password, i got the error:

The user with email "" does not exist.

User really exist. Also, i get the email with a link. Seems, everything works, but the error... Thank you.

upd.

I did some debug, and now i know, that

$email = $this->container->get('session')->get('fos_user_send_confirmation_email/email'); returns NULL

**Comment by XWB** [comment]
Closing this outdated issue.
