### ISSUE TITLE
Email only registration with unique validation on EmailCanonical

### ISSUE THREAD

**Issue by wavyx** [FriendsOfSymfony/FOSUserBundle#1516]
Hi,

I wonder if the Email unique constraint is applied for custom forms.
Or maybe I'm just struggling to configure FOSUserBundle with Email only registration without any username ;)

I switched to username_email provider
```yaml
# app/config/security.yml
security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
```
adapted my User class:
```php
    public function setEmail($email)
    {
        parent::setUsername($email);
        return parent::setEmail($email);
    }

    public function setEmailCanonical($emailCanonical)
    {
        parent::setUsernameCanonical($emailCanonical);
        return parent::setEmailCanonical($emailCanonical);
    }
```
Then created a custom form
```php
class RegistrationFormType extends BaseType {

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options);
        $builder->remove('username');
    }

    public function getName()
    {
        return 'data_user_registration';
    }
} 
```
and added the following custom validation.xml
```xml
        <constraint name="Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity">
            <option name="fields">emailCanonical</option>
            <option name="errorPath">email</option>
            <option name="message">fos_user.email.already_used</option>
            <option name="groups">
                <value>Registration</value>
                <value>Profile</value>
            </option>
        </constraint>
```

But I keep getting exceptions: duplicate key value violates unique constraint. As if the validation was not performed on the EmailCanonical value?!
Did I skip a configuration step?
Is there any documentation for this classic need: email + password only registration?
If not I'm willing to write a documentation section, once I get this working ;)

**Comment by stuzzo** [comment]
Hi, is possible that I have the same issue in Symfony 2.6.6?
In my registrationType I use as parent the fos_user_registration type and I added this

```
@UniqueEntity(fields="email", errorPath="email", message="fos_user.email.already_used", groups={"Registration", "Profile"})
```

Instead of the validation error, I receive error 500 for the duplicate entry.

**Comment by stof** [comment]
@stuzzo no. symfony 2.6 does not suffer from this bug. If your validation is not applied, please open a dedicated issue.

I'm closing this issue as the bug was resolved in Symfony.
