### ISSUE TITLE
 Bad credentials - still the same error

### ISSUE THREAD

**Issue by poolerMF** [FriendsOfSymfony/FOSUserBundle#1523]
hello ...

I think, you have error in login ... 
when someone try to login, it STILL SAYS "Bad credentials" (doesn't matter which language, or what is configured in FOSUserBundle.XX.yml, variable "Bad credentials")

in login, it calls "throw new BadCredentialsException('Bad credentials', 0, $notFound);"
so ... it passes string ...not translated string

can you solve it ?

**Comment by XWB** [comment]
This should work in 2.0
