### ISSUE TITLE
On Installation:  An exception occurred while executing 'CREATE UNIQUE INDEX UNIQ_8D93D64992F  C23A8 ON user (username_canonical)':  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'UNIQ_8D93D64992FC23A8'

### ISSUE THREAD

**Issue by JonnyD** [FriendsOfSymfony/FOSUserBundle#1546]
Getting this error when I enter this command "php app/console doctrine:schema:update --force", anyone know what's up?

An exception occurred while executing 'CREATE UNIQUE INDEX UNIQ_8D93D64992F C23A8 ON user (username_canonical)': SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'UNIQ_8D93D64992FC23A8'

**Comment by XWB** [comment]
This should be resolved now.
