### ISSUE TITLE
The field 'usernameCanonical' is not mapped by Doctrine, so it cannot be validated for uniqueness

### ISSUE THREAD

**Issue by nomasprime** [FriendsOfSymfony/FOSUserBundle#1565]
I'm currently getting the following error:

```
The field 'usernameCanonical' is not mapped by Doctrine, so it cannot be validated for uniqueness
```

Here's a gist of `composer show -i` https://gist.github.com/d9f2536f1145d297cd48.

**Comment by chrisg123** [comment]
use FOS\UserBundle\Entity\User as BaseUser; worked for me!. thanks

**Comment by fritzmg** [comment]
The `2.x` documentation says that you should use `use FOS\UserBundle\Model\User as BaseUser;`, is this still correct for `2.x` and in `1.3.x` you should use `use FOS\UserBundle\Entity\User as BaseUser;`?

**Comment by stof** [comment]
@fritzmg yes, it is correct. 1.3.x and 2.x have different needs. 2.x removes the class in the Entity namespace.

**Comment by fritzmg** [comment]
I see, thx for confirmation :).
