### ISSUE TITLE
MappingException

### ISSUE THREAD

**Issue by prybus** [FriendsOfSymfony/FOSUserBundle#1569]
Hello, 
I have problem: 

MappingException: The class 'Acme\UserBundle\Entity\User' was not found in the chain configured namespaces FOS\UserBundle\Entity, FOS\UserBundle\Model

my file Acme\UserBundle\Entity\User

<?php
// src/Acme/UserBundle/Entity/User.php

namespace Acme\UserBundle\Entity;

use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;

/**
- @ORM\Entity
- @ORM\Table(name="fos_user")
  _/
  class User extends BaseUser
  {
  /_*
  - @ORM\Id
  - @ORM\Column(type="integer")
  - @ORM\GeneratedValue(strategy="AUTO")
    */
    protected $id;
  
  public function __construct()
  {
      parent::__construct();
      // your own logic
  }
  }

**Comment by jarrettg** [comment]
For anyone else that found this thread looking for the solution to having a separate UserBundle in the Acme folder to follow FOSUserBundle docs verbatim:

1) Add the following line to AppKernal.php (this will add the needed mapping but continue to keep the Acme bundles out of the prod environment)
if (in_array($this->getEnvironment(), array('dev', 'test'))) {
....
$bundles[] = new Acme\UserBundle\AcmeUserBundle();
....
}

2) Create AcmeUserBundle.php in the Acme/UserBundle folder and put the following into it and save:
<?php
namespace Acme\UserBundle;
use Symfony\Component\HttpKernel\Bundle\Bundle;
class AcmeUserBundle extends Bundle
{
}

3) You will need to quit the server in command line if you're running it, then re-run the 'Update your database schema' step. This will allow the new User Entity to be found and proper database table to be created.

After this you can restart your server and go to localhost:8000/register for example and it will be working. Also after you create a user and log in with it the other secured areas of the Acme demo will become accessible.

**Comment by Tharindu-Diluksha** [comment]
I am also getting the same problem

"The class 'application\MainBundle\Resources\Entity\User' was not found in the chain configured namespaces FOS\UserBundle\Model"

I created the User class is in the bundle called MainBundle which I had created before.
I have added the FOS bundle to appKernel and my doctrine auto mapping is true.
But I still get the above exception can anyone help me?

**Comment by xabbuh** [comment]
Afaik the `Resources` directory of your bundle is not a location Doctrine will treat as a default location for entities when `auto_mapping` is enabled. Put it in `Application\MainBundle\Entity\User` instead.

**Comment by Tharindu-Diluksha** [comment]
yes that was the problem thank you xabbuh
