### ISSUE TITLE
Translate or change routes ?

### ISSUE THREAD

**Issue by Chrysweel** [FriendsOfSymfony/FOSUserBundle#1570]
Hello.

How can I translate or change the names of routes by default ?

i.e. I want to change the names of routes:

 I want translate some as  /profile/change-password  by /perfil/cambiar-contraseña 

And to change route /register/check-email by /register/my-name-of route by example.

And I want have one route only, I do not want to have duplicate routes /profile/change-password and route /perfil/cambiar-contraseña.

Can anyone tell me the correct way?

Thanks

**Comment by XWB** [comment]
See above.
