### ISSUE TITLE
Error while updating with composer.json

### ISSUE THREAD

**Issue by HexenZ** [FriendsOfSymfony/FOSUserBundle#1584]
Hi, I'm getting this error when trying to update my dependencies:
- Updating friendsofsymfony/user-bundle dev-master (3969d7f => 094bea6)
  
  [RuntimeException]  
  Failed to execute git status --porcelain --untracked-files=no  
  "git" no se reconoce como un comando interno o externo,  
  programa o archivo por lotes ejecutable.

I'm working with Netbeans so git is allready installed, the problem seems to be with FOSUserBundle. I leave my composer.json require here:

"require": {
        "php": ">=5.3.3",
        "symfony/symfony": "~2.4",
        "doctrine/orm": "~2.2,>=2.2.3",
        "doctrine/doctrine-bundle": "~1.2",
        "twig/extensions": "~1.0",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~2.3",
        "sensio/framework-extra-bundle": "~3.0",
        "sensio/generator-bundle": "~2.3",
        "incenteev/composer-parameter-handler": "~2.0",
        "ob/highcharts-bundle": "1._",
        "friendsofsymfony/user-bundle": "~2.0@dev",
        "codeconsortium/ccdn-forum-bundle": "2.0._"
    },

**Comment by darki666** [comment]
Bonjour stof, j'ai la même erreur que HexenZ, sauf que moi j'ai bien le dossier .git, le même que sur ma version local, et quand je lance "composer update" en local pas de soucis mais sur mon serveur il me met l'erreur :
- Updating friendsofsymfony/user-bundle dev-master (e39b040 => 8f1fc22)
[RuntimeException]
  Failed to execute git status --porcelain --untracked-files=no
  sh: 1: git: not found
J'ai tenté de supprimer le dossier .git et remettre celui en local, toujours pareil, j'ai essayé de relancer "composer require friendsofsymfony/user-bundle "~2.0@dev"", mais j'ai toujours l'erreur...

Pour infos je suis en symfony 2.8.2

**Comment by stof** [comment]
@darki666 Composer is telling you that ``git`` is not found on your server. you need to install it (and make sure it is available in the path).

**Comment by darki666** [comment]
Thank you ! It's quite simple, sorry for inconvenience
