### ISSUE TITLE
FOSUser Bundle login : No forms were submitted for this request Error

### ISSUE THREAD

**Issue by anouerH** [FriendsOfSymfony/FOSUserBundle#1595]
Hi all,
I'm working on  a new  website  with SF2, I included FosUserbundle for users management.
Everything works well  in my localhost, but when I deployed on  test subdomain (Ovh), the login and register page didn't react, the forms did not submitted.
In the profiler I got always the Error : No forms were submitted for this request Error.

bellow the register page : 
http://beta.starannonces.tn/register

**Comment by damienalexandre** [comment]
It's really hard to help you without code or error trace and the link provided is broken. Do you have more details about your error?
If you resolved this issue already, you can close the ticket, thanks!
