### ISSUE TITLE
Not able to ad roles in group administration

### ISSUE THREAD

**Issue by TLyngeJ** [FriendsOfSymfony/FOSUserBundle#1597]
Is there a particluare reason why one can't edit roles in the group admin interface? Or is it possible, but very well hidden? :-)

If there is no reason I'd like to make a PR with a patch that makes it possible.

**Comment by foaly-nr1** [comment]
@stof Since this is still open, would it be worth for me to create a PR for a form type `RolesFormType` that fills `ChoiceType` with all roles from the `security.role_hierarchy.roles` container parameter?

**Comment by XWB** [comment]
@foaly-nr1 Feel free to open a PR. Will close this issue for now.

**Comment by foaly-nr1** [comment]
@XWB I created https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2158. @stof and yourself rejecting the idea as a whole following the review of my PR.
