### ISSUE TITLE
Missing trailing dots in validator messages

### ISSUE THREAD

**Issue by umpirsky** [FriendsOfSymfony/FOSUserBundle#1601]
In [validators.en.yml](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Resources/translations/validators.en.yml) messages are missing trailing dot. Because they are sentences, and they deserve to end with a dot.

If you look at Symfony [messages](https://github.com/symfony/symfony/blob/master/src%2FSymfony%2FComponent%2FValidator%2FResources%2Ftranslations%2Fvalidators.en.xlf), they all end with a dot. This should be consistent since now it happens to have some messages coming from Symfony ending with a dot, and some from user bundle that do not.

**Comment by damienalexandre** [comment]
Yes I think you should add dots on flash messages too, as they are sentences :+1:

**Comment by robertfausk** [comment]
@damienalexandre Sorry for deleting my message. I will create an own PR for trailing dots on flash messages.

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2344
