### ISSUE TITLE
PSR_4: Problem with propel

### ISSUE THREAD

**Issue by opichon** [FriendsOfSymfony/FOSUserBundle#1616]
Since you've switched to PSR-4, propel generates the BaseUser and related base classes under vendor/FOS/UserBundle/Propel.
This seems to be a general problem with Propel 1.x and PSR-4.
The only fix I have found is to add a "package" attribute to the propel schema with a value of "vendor/friendsofsymfony/user-bundle/FOS/UserBundle/Propel/". Of course, this sorts of hard-codes the path for the bundle as vendor, which is not strictly a good thing.
I've filed a question in stackoverflow (http://stackoverflow.com/questions/25712075/does-propel-support-psr-4-in-a-symfony-bundle) but the propel guys claim it's "not propel-related".

**Comment by standaniels** [comment]
PropelBundle 1.4.4 should include this fix, but still Propel generates the classes in the vendor dir:
```
[propel-om]     -> Creating vendor/friendsofsymfony/user-bundle/AppBundle/Model/User/User.php (table: fos_user, builder: PHP5ExtensionObjectBuilder)
```

Is this an issue of PropelBundle or FOSUserBundle?

**Comment by standaniels** [comment]
Any news on this?
