### ISSUE TITLE
Warning: Erroneous data format for unserializing 'SSIT\ProEduca\UserBundle\Entity\User' in /app/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php line 872 

### ISSUE THREAD

**Issue by messheno** [FriendsOfSymfony/FOSUserBundle#1630]
hi

I have a problem with the unserialize function File << doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataInfo.php to 872 >>
After my research I constact it's hard at the php version, I use version 5.6.1

**Comment by TopBusiness1** [comment]
hi.
Use the symfony version2.2
i am developed doctors site.
but it has following errow.
### erreur : Warning: Erroneous data format for unserializing 'Ben\UserBundle\Entity\User' in D:\xampp\htdocs\projectfolder\vendor\doctrine\orm\lib\Doctrine\ORM\Mapping\ClassMetadataInfo.php line 872
