### ISSUE TITLE
The field 'usernameCanonical' is not mapped by Doctrine, so it cannot be validated for uniqueness.

### ISSUE THREAD

**Issue by GarraouiMarwen** [FriendsOfSymfony/FOSUserBundle#1638]
i started to install fosuserbundle , but after installing  i tried to add a user ,it shows me this error " An exception occurred while executing 'INSERT INTO Af_user (username, usern
 ame_canonical, email, email_canonical, enabled, salt, password, last_login,
  locked, expired, expires_at, confirmation_token, password_requested_at, ro
 les, credentials_expired, credentials_expire_at) VALUES (?, ?, ?, ?, ?, ?,
 ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["fakher", "fakher", "fakher@gar
 raoui.com", "fakher@garraoui.com", 1, "1vwk6ns74ba8ggoco404408kcc88k04", "P
 8SeLDhNOd1Bc1q9McAvzInu8j5I5DGlBLC9EUElV6SEJ1w6sJDdkM8dmF1tV1sinVq+jDo1iBcv
 qtgYVyMk4w==", null, 0, 0, null, null, null, "a:0:{}", 0, null]:
 SQLSTATE[42S22]: Column not found: 1054 Champ 'username' inconnu dans field
  list

 [PDOException]
 SQLSTATE[42S22]: Column not found: 1054 Champ 'username' inconnu dans field
  list" 

i need help plz!!

**Comment by novuscom** [comment]
same problem

**Comment by Aaadi** [comment]
same problem i am using v 1.3.6

**Comment by nigeljohnwade** [comment]
I have the same issue, can anything be done about it? It seems a bit off to ignore us for nearly two years...

**Comment by XWB** [comment]
See https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2234 for some feedback.
