### ISSUE TITLE
CID embedded images in E-mails (not attachments)

### ISSUE THREAD

**Issue by pculka** [FriendsOfSymfony/FOSUserBundle#1644]
Hello,

is there any possibility to embed images in the generated e-mail communication (Registration, forgot password etc) in some kind of easy way? SwiftMailer supports this, question is if TwigSwift mailer supports this aswell

I can imagine extending TwigSwiftMailer->sendMessage() to parse some variables from blocks with paths to the images ...

{% block body_embedded %}
cid1:/web/vendor/bundle/Resources/images/image1
cid2:/web/vendor/bundle/Resources/images/image2
{% endblock %}

parsing it and attach it with ->embed

Any tips/ideas on this problem ?

**Comment by damienalexandre** [comment]
Thanks for posting you solution, extending the mailer is the way to go, and I don't think that's should be the responsibility of FOSUserBundle to support this, as this this related to HTML emails, which the bundle does not provide (only txt part is provided).

**Comment by pculka** [comment]
well as FOSUserBundle really does SEND e-mails, maybe some logic or documentation should reflect the possibility to adapt the E-Mails being sent from a project. The way I've done it is rather crude and FOSUB is lacking support for this particular feature, which is rather cruicial in developing user-friendly software.
I would recommend at least better documentation in this matter
