### ISSUE TITLE
Event on forms errors

### ISSUE THREAD

**Issue by WedgeSama** [FriendsOfSymfony/FOSUserBundle#1655]
I gess people used events from this bundle, like `PROFILE_EDIT_INITIALIZE` or `PROFILE_EDIT_COMPLETED`, but I do not see any `*_ERROR`.

I think it can be a good idea to add some events to handle forms errors. For example, it can be helpful to add some flash messages, or set a logger on forms errors.

What do you thinks about it?

**Comment by airv-b** [comment]
The problem is still there. (master)
A fix would be possible?

**Comment by damienalexandre** [comment]
Can you describe more precisely the use case for this feature? Because when a form has an error, it's testable from the twig view too.

**Comment by XWB** [comment]
Symfony offers several form events that should do the job.
