### ISSUE TITLE
There should be a way to disable AuthenticationListener

### ISSUE THREAD

**Issue by fatganz** [FriendsOfSymfony/FOSUserBundle#1658]
I am on v2-alpha, and there is no simple way to disable automatic authentication.
Looking for one of the ways to disable it:
- via fos_user configuration
- via class override

Any ideas?

**Comment by RamyRais** [comment]
well me too i did not succed in disabling the automatic authentication.
I tried to override the ressource : Resources\config\listeners.xml and change the class of the service to an authentication listener implement by me where i deleted "FOSUserEvents::REGISTRATION_COMPLETED" and "FOSUserEvents::REGISTRATION_CONFIRMED" from the method getSubscribedEvents() 
but this did not work.
I think, i am missing a details that prevent to override listeners.xml

**Comment by RamyRais** [comment]
hello i fin what was missing it is simply to import the listeners.xml in config.yml using "@"
http://symfony.com/doc/current/cookbook/bundles/inheritance.html
