### ISSUE TITLE
Document that a user needs to sign out and back in for role changes to be active

### ISSUE THREAD

**Issue by hubgit** [FriendsOfSymfony/FOSUserBundle#1679]
In [the command line tools documentation](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Resources/doc/command_line_tools.md), there should be a mention of the fact that a user needs to sign out and back in before changes to their roles take effect (i.e. after running `fos:user:promote` or `fos:user:demote`).

**Comment by damienalexandre** [comment]
Related to https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1866

**Comment by damienalexandre** [comment]
Related to #1979

**Comment by steveWinter** [comment]
I've created PR https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2350 to include documentation updates

**Comment by steveWinter** [comment]
And PR https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2351 to include a note in the command output.
