### ISSUE TITLE
AccessDeniedListener modifies BadCredentialsException messages, how can I disable this ?

### ISSUE THREAD

**Issue by vishalmelmatti** [FriendsOfSymfony/FOSUserBundle#1684]
Hi,

I am working on use case where I need to Authenticate user through REST API calls from my SPA. I have used FOSOAuthServerBundle for API security and exposing APIs to third party apps. 

As I want to use consistent mechanism to authenticate user, I am using FOSOAuthServerBundle to Authenticate users on my SPA using Resource owner credential mechanism.

For that, I have written loginAction which calls FOSOAuthServer  token endpoint by passing user credentials with client credentials to that end point. 

In case of Bad Credentials from user as per OAuth2 specs, FOSOAuthServer returns invalid_grant. 

But I need more specific response code and error so I am trying to catch and rethrowing

```
throw new BadCredentialsException('Bad credentials');
```

If I throw this exception, I cant see the error message I am throwing  but it displays 'You are not authenticated' message.

After investigating It seems FOSUserBundle has AccessDeniedListener which modifies it to 

```
  $exception = new HttpException(401, 'You are not authenticated', $exception);
```

Is there any way I can disable this ? 

If I use normal form_login it returns proper messages
    'Bad credentials': 'Invalid username or password'

How can I make this work in my above use case ?

**Comment by damienalexandre** [comment]
There is no AccessDeniedListener anymore.

**Comment by stof** [comment]
AFAIK, we never had such a listener.
