### ISSUE TITLE
Roles serialization different implementation Propel / Doctrine

### ISSUE THREAD

**Issue by sloba88** [FriendsOfSymfony/FOSUserBundle#1685]
I have two applications using Propel and Doctrine that share same fos user table.

It seems that their Role persistence format is different and when I try to manage roles with Propel it saves them in strange format with "|" separators

Doctrine saves roles as serialized array as it should.

Here is the current Propel setRoles function

    public function setRoles(array $v)
    {
        if ($this->roles_unserialized !== $v) {
            $this->roles_unserialized = $v;
            $this->roles = '| ' . implode(' | ', $v) . ' |';
            $this->modifiedColumns[] = UserPeer::ROLES;
        }
        return $this;
    }

Is there any special reason for this?

**Comment by stof** [comment]
We let each tool handle the storage of arrays on its own. Today, I would use ``simple_array`` in Doctrine rather than ``array`` (having a serialized PHP structure in the DB is not a good idea)
