### ISSUE TITLE
FOSUserBundle profile/edit or profile/registration Translator issue

### ISSUE THREAD

**Issue by DFA38** [FriendsOfSymfony/FOSUserBundle#1687]
Hi ,

Brand new with symfony and FOS too, i'm trying to use the registration form.
The form appears and is usable but when the "registration/confirmer" redirection occurs i have an error message 'exception thrown(array to string) in translator.php in FSOUserBunlde::layout.html.twig at line 12.
{{ 'layout.logout'|trans({},'FOSUserBundle')}}
If my understanding is right, layout.logout is an array but i don't know why.
I uses the views 'as is' with no change from my side, but i might missed something.

**Comment by damienalexandre** [comment]
Without more informations we can't help you. If this issue is resolved feel free to close it as it's looks like it was an issue on your code.
