### ISSUE TITLE
[Propel Login] Login with * or %

### ISSUE THREAD

**Issue by stood** [FriendsOfSymfony/FOSUserBundle#1688]
When I login with \* and my password I am identified

For example 
My username is : "myusername" and password is : "mypwd"

If I fill login fields wih username "myuserna*" and password "mypwd"  I am identified

The sql generate : Criteria: SQL (may not be complete): SELECT FROM `fos_user` WHERE fos_user.username_canonical LIKE :p1 Params: fos_user.username_canonical => 'myuserna%'

**Comment by JHGitty** [comment]
This sounds like a security issue.

**Comment by stof** [comment]
@stood can you send a PR (to the 1.3.x branch) ? I'm not using Propel myself. The implementation was contributed by the community.
