### ISSUE TITLE
Error on login_check with sql server

### ISSUE THREAD

**Issue by farsonline** [FriendsOfSymfony/FOSUserBundle#1689]
I have a project with SQL server DB. I use FOSUserBundle. after submit login form my apache server resets.
SQL server 2012. Apache/2.4.9
PHP 5.5.11

**Comment by aondarra** [comment]
I have the same problem. ¿Have you solved the problem?

**Comment by heidyz** [comment]
Hello. I have exactly the same problem.
With different versions of Apache 2.4 and trie differrent versions of php 5.5 too.
Did you solve your ptoblem ?

**Comment by farsonline** [comment]
Hello. I found the problem. but I cannot solve it. Please help me!!!!
\vendor\doctrine\dbal\lib\Doctrine\DBAL\Platforms\SQLServerPlatform.php line 805 to 825
 $start   = $offset + 1;
        $end     = $offset + $limit;
        $orderBy = stristr($query, 'ORDER BY');
        $query   = preg_replace('/\s+ORDER\s+BY\s+([^\)]*)/', '', $query); //Remove ORDER BY from $query
        $format  = 'SELECT * FROM (%s) AS doctrine_tbl WHERE doctrine_rownum BETWEEN %d AND %d';

        // Pattern to match "main" SELECT ... FROM clause (including nested parentheses in select list).
        $selectFromPattern = '/^(\s*SELECT\s+(?:\((?>[^()]+)|(?:R)*\)|[^(])+)\sFROM\s/i';

        if ( ! $orderBy) {
          
            //Replace only "main" FROM with OVER to prevent changing FROM also in subqueries.
            $query = preg_replace(
                $selectFromPattern,
                '$1, ROW_NUMBER() OVER (ORDER BY (SELECT 0)) AS doctrine_rownum FROM ',
                $query,
                1
            );

**Comment by heidyz** [comment]
Hello, it's not a solution but here is what I 've done.
My main connection is still on SQL Server
but all FOSuserBundles entities are now stored in a SQLLite3 database => a spectific connection for FOS.
I have lost too much time trying to make FOSUserBundle work on SQL Server.

**Comment by farsonline** [comment]
Solve it in this way!!!
I make this change on file 
 // vendor\doctrine\dbal\lib\Doctrine\DBAL\Platforms\SQLServerPlatform.php line 813

 $selectFromPattern = '/^(\s*SELECT\s+(?:(.*)(?![^(]*\))))\sFROM\s/iU';

**Comment by xabbuh** [comment]
@farsonline Looks like you should report it to the Doctrine DBAL project when it is an issue with that package.
