### ISSUE TITLE
Class 'FOS\UserBundle\FOSUserBundle' not found

### ISSUE THREAD

**Issue by kumaranuj8** [FriendsOfSymfony/FOSUserBundle#169]
I am new to symfony2. I tried to install this plugin but getting an error " Class 'FOS\UserBundle\FOSUserBundle' not found" Please let me the resolution for this.

**Comment by AmaliDeveloper** [comment]
You can get the solution in this tutorial [Link](https://youtu.be/u4q_VqewQe4)
