### ISSUE TITLE
Translation of login error messages

### ISSUE THREAD

**Issue by esmedo** [FriendsOfSymfony/FOSUserBundle#1692]
Hi,

I did the update of fosuser and now i have in my login : {{ error.messageKey|trans({}, 'FOSUserBundle') }}

When the user put the wrond pwd or id i have this message : "Invalid credentials."
I don't know how to overide the translation with the new error.messageKey.

Cheers

**Comment by IcarusHU** [comment]
+1 For this

I've tried overriding  in messages file in custom UserBundle
# Security
"Invalid credentials.": Invalid username or password
but doesn't work

**Comment by IcarusHU** [comment]
Oh, problem solved, it has to be put in FOSUSerBundle.en.yml instead of the earlier solution of messages.en.yml
