### ISSUE TITLE
Custom User Provider Query

### ISSUE THREAD

**Issue by austinh** [FriendsOfSymfony/FOSUserBundle#1699]
Is there anyway to create a custom user provider query for the refreshUser property? I have been trying to override the default query by adding in some joins. I'd like the least messy scenario.

For example, I need to join my authenticated user with Profile data, as well as the user's "notifications". I would prefer not to do another query for this data and instead just do a left Join in addition to the regular findUserBy id=>user_id.

How does one do this?

**Comment by damienalexandre** [comment]
As you can see in the providers, all the "find" methods are calling the UserManager, which is calling the doctrine repository: https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Doctrine/UserManager.php

So you just have to override the doctrine `findOneBy` method to add your join.

**Comment by stof** [comment]
The other solution would be to register the ``entity`` provider instead of using the FOSUserBundle if you need a custom DB query (which will be specific to the ORM/ODM you use anyway).
