### ISSUE TITLE
isAccountNonExpired and the 2038 year problem

### ISSUE THREAD

**Issue by coelhoricardo** [FriendsOfSymfony/FOSUserBundle#1700]
Hi,
In isAccountNonExpired(), $this->expiresAt->getTimestamp() return false in the  2038 year problem context.

A workaround is to use DateTime diff function to get a DateInterval object and test the seconds.

Thanks

EDIT :
Look at http://php.net/manual/fr/datetime.gettimestamp.php#114590

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2343
