### ISSUE TITLE
The confirmation token field should be unique

### ISSUE THREAD

**Issue by waldermort** [FriendsOfSymfony/FOSUserBundle#1720]
The UserManager class has a method findUserByConfirmationToken() but the database column (in doctrine at least) is not configured to be unique. I know the chances of generating two identical tokens are a billion to one, but, there is still a chance.

I know MySQL supports these constraints (unique and null), not sure about other DBM's though. If the behavior cannot be implemented at the database level then perhaps the exception should be caught and try again with a new token.

**Comment by steveWinter** [comment]
This issue appears to have been addressed:
```
            <index>
                <key name="confirmationToken" order="asc" />
                <option name="safe" value="true" />
                <option name="sparse" value="true" />
                <option name="unique" value="true" />
            </index>
```
and results in the correct construction in the DB:

<img width="551" alt="screen shot 2016-12-03 at 16 03 04" src="https://cloud.githubusercontent.com/assets/1171712/20860175/14daa764-b972-11e6-9fbc-9378911869ca.png">
