### ISSUE TITLE
Merge back PR #957 in 1.3.x branch

### ISSUE THREAD

**Issue by xavierleune** [FriendsOfSymfony/FOSUserBundle#1721]
Hi,

The [PR#957](https://github.com/FriendsOfSymfony/FOSUserBundle/pull/957) have been merged in master in jan, 2013. Actually the branch has not been merged into the 1.3.x branch and I have trouble working on my custom driver implementation on the 1.3.5 version. I have the problem described in the issue #458.
Is it possible to merge back this correction and tag a new version ? Or I can make a PR if needed with the same changes.

Thanks,

**Comment by stof** [comment]
This is a BC break (interface change), so it cannot go in the 1.3.x branch

**Comment by xavierleune** [comment]
@stof thanks for your answer, do i have any solution to use this without going to dev-master ? I've seen a project of 2.0 but it's not stable actually :-(
