### ISSUE TITLE
[FOSUserBundle 2.0*] How to override controllers ?

### ISSUE THREAD

**Issue by Grogro2000** [FriendsOfSymfony/FOSUserBundle#1726]
Hi,

Sorry for this simple question, I am new with Symfony/FOSUserbundle.

How can I override ProfileController ?
I have found the following documentation (<a href="https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Resources/doc/overriding_controllers.md"> here </a>)  but, as I understood, the function : 
<ul>
<li> $form = $this->container->get('fos_user.profile.form'); </li>
</ul>
Isn't working any more with the 2.0 revision of FOSUserbundle.

Thanks for your help !

**Comment by XWB** [comment]
Please check Symfony docs on how to override controllers.
