### ISSUE TITLE
Reset token empty with Gmail addresses

### ISSUE THREAD

**Issue by Mentalow** [FriendsOfSymfony/FOSUserBundle#1728]
Hello,

When resetting a password with a Gmail e-mail address, the token is strangely truncated from the e-mail. It only happens with Gmail addresses ...

The link in the e-mail is truncated as follow when using a Gmail address :

```
https://domain.tld/user/resetting/reset/
```

And this link is like this one when using another address :

```
https://domain.tld/user/resetting/reset/EE2HLWdbQDPfIDK3AJAdrtMoJ2gPcjxyOFCbx4uK9V0
```

Here are the versions used :

```
friendsofsymfony/user-bundle             dev-master 7867dfc
symfony/symfony                          dev-master f15ea50
```

Thanks in advance !

**Comment by Mentalow** [comment]
I just saw it works well using Debug mode (app_dev.php)

```
https://domain.tld/app_dev.php/user/resetting/reset/IcrRax1bSQC7gd1Tr40Xb4I8thBMq00gxhJaa4GARig
```

**Comment by ImChip** [comment]
up

**Comment by damienalexandre** [comment]
Works as expected on beta1,
did you customize anything like the email templates? Could you provide more informations about your issue or how your resolved it maybe?

Thanks

**Comment by Quentin-M** [comment]
This issue has been authored based on the behavior of a commit from Mar 5, 2014. Closing.
