### ISSUE TITLE
How to modify the template rendered by registerAction

### ISSUE THREAD

**Issue by alex205** [FriendsOfSymfony/FOSUserBundle#1733]
Hi,
I'm currently developping a Symfony2 app and the users are managed by FOSUser.
I've a problem with registerAction in the RegistrationController.

I don't know how to change the template rendered by this action without modify the controller :
```php
return $this->render('FOSUserBundle:Registration:register.html.twig', array(
        'form' => $form->createView(),
         ));
```
I'd like to use my own Twig template, I've tried with the event REGISTRATION_INITIALIZE but it's dispatched before the form creation.
I also tried to override the controler like this : 
```php
        /**
         * @Route("/")
         */
        public function registerAction(Request $request)
        {   
                $form = $this->container->get('fos_user.registration.form');
                return $this->container->get('templating')->renderResponse('Registration/register.html.twig', array(
                        'form' => $form->createView(),
                )); 
        } 
```
But I got this error :
**You have requested a non-existent service "fos_user.registration.form".**

If somebody knows how to perform this,
Greetings

**Comment by stof** [comment]
Why not simply using the template overriding feature of Symfony to replace your template ?

And ``fos_user.registration.form`` is the 1.x way of creating the form. If you want to know how the bundle controller looks like for the version you use, the bets way is to open the controller code directly.

**Comment by alex205** [comment]
I've overrided the templates.
But it works if I put the templates in AppBundle/Resources/views
and doesn't work if I put templates in app/Resources/views (where are located my other views).

PS : I found fos_user.registration.form in the master documentation
