### ISSUE TITLE
REMEMBERME cookie is not cleared after session expires

### ISSUE THREAD

**Issue by ryall** [FriendsOfSymfony/FOSUserBundle#1740]
If you attempt a log-out after a session has expired, the REMEMBERME cookie is not removed, causing the user to remain logged in.

**Repro steps:**
- Set the framework session to 15 seconds
- Log-in with REMEMBERME
- Wait 20 seconds
- Log-out
- You will still be logged in via REMEMBERME

**Comment by stloyd** [comment]
IIRC that cookie is being set & cleaned by Symfony Security not by this bundle...

**Comment by stof** [comment]
Indeed, FOSUserBundle is not responsible for the remember me cookie.

and anyway, this is totally expected. The goal of the remember me is precisely to be able to remember the user after the session itself expires (the user will have less right as he will only pass the ``IS_AUTHENTICATED_REMEMBERED`` and ``IS_AUTHENTICATED_ANONYMOUS`` checks but not the ``IS_AUTHENTICATED_FULLY`` one). The remember me feature does not rely on the session, but on a dedicated cookie, which has its own lifetime: http://symfony.com/doc/current/cookbook/security/remember_me.html

**Comment by ryall** [comment]
I'm aware of this but the issue is that clicking logout should trigger the REMEMBERME cookie being removed, even if the session itself has expired. Otherwise, logout is not logging you out. AFAIK, the logout handler in this case is FOSUserBundle.
