### ISSUE TITLE
FOSRestBundle post method to create new user returns error for repeated password field

### ISSUE THREAD

**Issue by sergiu-popa** [FriendsOfSymfony/FOSUserBundle#1742]
Hello,

I'm using this code for a POST method with FOSRestBundle to create a new user:
```php
public function postUsersAction(ParamFetcher $paramFetcher)
{
  $request = $this->getRequest();
  $userManager = $this->container->get('fos_user.user_manager');
  $user = $userManager->createUser();
  $user->setUsername($request->get('username'));
  $user->setEmail($request->get('email'));
  $user->setPlainPassword($request->get('plainPassword'));
  $user->addRole($request->get('role'));
  $validator = $this->get('validator');

  $errors = $validator->validate($user, array('Registration'));
  if (count($errors) == 0) {
    $userManager->updateUser($user);
    $param = array("slug" => $user->getUsername());
    $view = RouteRedirectView::create("byexample_demo_userrest_get_user", $param);
  } else {
    $view = $this->get_errors_view($errors);
  }
  return $view;
}
```
Although I'm sending "plainPassword" in the request, I'm still getting the message error: *Write your password* meaning that the validator fails to validate the password. I know the password field it's a repeated field in the registration form. I also tried to send two parameters: "plainPassword_first" and "plainPassword_second" but to no success.

Any help please?

**Edit:** resolved

**Comment by stof** [comment]
Please add a comment explaining how you solved it, so that someone else facing the same issue in the future can know what the solution is

**Comment by sergiu-popa** [comment]
I was off track because of the error message. I was thinking it was using the registration form, but no, it's using directly the user manager. I changed the code to `php$request->get('password')` but I was still sending 'plainPassword'. A simple rename done it.
