### ISSUE TITLE
user registration error

### ISSUE THREAD

**Issue by juanolon** [FriendsOfSymfony/FOSUserBundle#1744]
Hello,
any way to pass (trigger) an error from UserManager to RegistrationController?

https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Controller%2FRegistrationController.php#L42

Let's say, a user registers but the username is already giving. So it would make sense to catch the error on the controller, and show it with the form.

greets

edit: actually, any exception trigger on the whole register/login/... process

**Comment by tak1n** [comment]
Validation belongs to the form type and to the underlying object which is used by the form type.

You could add your custom validation via an form event listener.

```php

public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(....)
            ->add(....);

        $builder->addEventListener(FormEvents::PRE_BIND, function (FormEvent $event) {
            $form = $event->getForm();
            $data = $event->getData();

            // Check if user already exists
            $user = $this->userRepository->loadUserByLogin($data["username"]);

            if ($user) {
                $form->addError(new FormError("User already exists"), 1));
            }
        });
    }

```

As you can see in https://github.com/symfony/Form/blob/ebb90695dfb1f2648b66b9acfdc7aefa466e23a7/Form.php#L769 after adding an error to your form the isValid check returns false.

**Comment by tak1n** [comment]
This leads to one question, why is the form validation called after a user is created?

Form validation is here: https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Controller%2FRegistrationController.php#L57
User creation here: https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Controller%2FRegistrationController.php#L42

**Comment by toolpixx** [comment]
How you otherwise check if it valid, after submit? You create a new user and add them to the form. After submit the form, the data will validate if true. "You bind the entity and his validations rules to the form". For that you need the entity.

**Comment by tak1n** [comment]
You're completely right, didn't see this line https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Controller%2FRegistrationController.php#L53. :+1:

**Comment by toolpixx** [comment]
An other rule is, that you can use "FOSUserEvents::REGISTRATION_INITIALIZE" with own EventListener and setup user::data before ;)

**Comment by tak1n** [comment]
Thx for the tip :+1: 
But even for binding the user data to the form, how should the validation work.
The created user is just a dummy class without any explicit data in it.

https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Model%2FUserManager.php#L63

Will this be overriden by a custom createUser method to create a User with data in it?

**Comment by damienalexandre** [comment]
createUser just build an User object, the form is then writing the data in it, and then the validation can be called. That's the way to go and it makes sense here.

You are talking about validating the username uniqueness but that's already part of the Bundle: https://github.com/FriendsOfSymfony/FOSUserBundle/blob/4cb7a29869e4a9bef4f51986d48b1a3af76d3f48/Resources/config/storage-validation/orm.xml#L8

You just have to be careful if you extend to form to use the same validation groups.
