### ISSUE TITLE
Phrase translation problem when send incorrect login or password.

### ISSUE THREAD

**Issue by andrewsmm** [FriendsOfSymfony/FOSUserBundle#1746]
Please edit translate validation.ru file. Change "Bad credentials" to "Bad credentials.": Неверный логин или пароль 
I have a problem when translate phrase without a point at the end of "Bad credential". May be it does not work in other translation lang files. I create translation lang file in my bundle and edit this, now it's work fine but not stable for other users of fosuserbundle :)

**Comment by sstok** [comment]
https://github.com/FriendsOfSymfony/FOSUserBundle/edit/1.3.x/Resources/translations/FOSUserBundle.ru.yml here you can edit the file yourself and it will automatically open a pull request.

**Comment by lomaxinformationservices** [comment]
Also had same issue with .en.yml file. Am a relative newbie to Symfony and FOSUserBundle v1.30 and just spent three days (parttime) finding this problem. Just adding the full stop to the end of "Bad credentials." fixed the problem.

**Comment by XWB** [comment]
Should be fixed now.
