### ISSUE TITLE
Question mark in email subject

### ISSUE THREAD

**Issue by stephanvierkant** [FriendsOfSymfony/FOSUserBundle#1747]
When FOSUserBundle sends an email, the subject ends with a question mark. I've changed my charset (http://swiftmailer.org/docs/messages.html#setting-the-character-set) but that didn't help.

How can I find where the question mark is added to the subject? There is no "Welcome!?" in my app

**Comment by mvrhov** [comment]
That's because somehow the newline character get's added into the subject.

**Comment by stephanvierkant** [comment]
Why? And where? I'm using the default settings, even the translation hasn't changed.

**Comment by mvrhov** [comment]
I haven't figured that out. I have a custom mailer so I just added the trim around the string that's returned from the twig. it might be that something changed with twig rendering. The mailer calls `renderBlock` function.. You can try to figure it out.

**Comment by stephanvierkant** [comment]
I've found the problem in Resources/views/Resetting/email.txt.twig.

I've added `spaceless` to the `subject` block and now the new line is gone.

**Comment by michaelkonecny** [comment]
I've had the same problem and just adding `spaceless` didn't work for me.

I actually had to put the subject block on one line, like so:

    {% block subject %}{% autoescape false %}{{ 'registration.email.subject'|trans({'%username%': user.username, '%confirmationUrl%': confirmationUrl}, 'FOSUserBundle') }}{% endautoescape %}{% endblock %}

(I was using Mandrill's SMTP to send the e-mail - I don't know if that's relevant.)

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2352
