### ISSUE TITLE
Remember me cookie and un canonicalized username

### ISSUE THREAD

**Issue by ScullWM** [FriendsOfSymfony/FOSUserBundle#1754]
Hi,

First: I would like to say that this issue mostly concern how the Symfony TokenBasedRememberMeServices interact with this bundle. And I have overriding the Canonicalizer class (doing more than just text cleaning).

Using this bundle I get a very strange bug with user Authentication: the remember me cookie was set has it does, bug when the server session is die, user must re-auth...

Finally I've found why: 
- User log with a non canonicalized username (" ToTo123")
- Fos canonicalized the username and find the correspondant user ("toto123")
- TokenBasedRememberMeServices set a cookie with this UnCanonicalized username
- When session die, TokenBasedRememberMeServices ask FosUserProvider to search for a username called (" ToTo123")
- FosUserProvider doesn't find anybody and user must relog.

When I found this, it sound strange to me that in one way we canonicalize Username, and in one way, we don't.

By overriding TokenBasedRememberMeServices I could set the usernameCanonical instead of the simple username.
And by overriding the FosUserProvider I could had a method to check on the usernameCanonical.
Finally it works great and solve the problem! 

I've would like to make a PR (that deserve username_canonicalizer where it's need) but it's not that easy... It concern this bundle and the Symfony Security Component. What do you think of this ?

**Comment by Nek-** [comment]
On what version of FOSUser did you notice that ? (it looks like on the master version there's no problem)

**Comment by XWB** [comment]
Closing this outdated issue.
