### ISSUE TITLE
Unable to find file "@FOSUserBundle/Resources/config/routing/all.xml"

### ISSUE THREAD

**Issue by jonatasfreitasv** [FriendsOfSymfony/FOSUserBundle#1756]
Unable to find file "@FOSUserBundle/Resources/config/routing/all.xml" in @FOSUserBundle/Resources/config/routing/all.xml

**Comment by luxilio** [comment]
I installed v1.3.5 today and I get the same error. I can't find the file **all.xml** in the folder *routing*.

**Comment by jonatasfreitasv** [comment]
Thx man !

**Comment by xabbuh** [comment]
Please note that the `all.xml` routing file is only present in the `2.0.*@dev` version of FOSUserBundle. In the older `1.3.x` versions, you would indeed have to use the approach described by @luxilio.

**Comment by stof** [comment]
If you use the 1.3.x version, please read the documentation in the 1.3.x version too.

**Comment by mehmetsoylucom** [comment]
thanks lux

**Comment by PrzemekTkaczyk** [comment]
thx

**Comment by bezdelnique** [comment]
thx

**Comment by felixdenoix** [comment]
CHEEEEEEERS

**Comment by rogoit** [comment]
Very good
