### ISSUE TITLE
Register Ajax form

### ISSUE THREAD

**Issue by navalex** [FriendsOfSymfony/FOSUserBundle#1757]
Hi,

I'm a new user of Symfony2, and I have install your FOSUserBundle.
I also transform Security form in ajax, but I don't know how can I do the same form for registration and password lost. I think this two form work with this bundle and not Security, so can you help me please ?

(sorry for my bad english, it's not my mainly lang...)

Thank you. :)

**Comment by JHGitty** [comment]
You can create a child bundle of the FOSUserBundle and modify the view twig templates. :)

**Comment by damienalexandre** [comment]
Sending the form data should not be an issue (serialize the data, build the AJAX request, that's builtin jQuery), the issue is probably displaying the updated form with errors / flash messages...

The way to go is to build your own views, like any other bundle.
