### ISSUE TITLE
Improve the Logging by Username or Email 

### ISSUE THREAD

**Issue by AlexandreHagen** [FriendsOfSymfony/FOSUserBundle#1759]
Hi everyone,

First thanks a lot for you bundle ! It's very great !
During our development we found one problem cases if the Logging by Username or Email is enabled. 
If a user, register with username = "a first email" ! =  "a second email" the account will be create but the user could never sign in.

FOS\UserBundle\Model\UserManager
```
<?php

/*
 * This file is part of the FOSUserBundle package.
 *
 * (c) FriendsOfSymfony <http://friendsofsymfony.github.com/>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace FOS\UserBundle\Model;

use FOS\UserBundle\Util\CanonicalizerInterface;
use Symfony\Component\Security\Core\Encoder\EncoderFactoryInterface;
use Symfony\Component\Security\Core\Exception\UnsupportedUserException;
use Symfony\Component\Security\Core\Exception\UsernameNotFoundException;
use Symfony\Component\Security\Core\User\UserInterface as SecurityUserInterface;
use Symfony\Component\Security\Core\User\UserProviderInterface;

/**
 * Abstract User Manager implementation which can be used as base class for your
 * concrete manager.
 *
 * @author Johannes M. Schmitt <schmittjoh@gmail.com>
 */
abstract class UserManager implements UserManagerInterface, UserProviderInterface
{

.....
    public function findUserByUsernameOrEmail($usernameOrEmail)
    {
        if (filter_var($usernameOrEmail, FILTER_VALIDATE_EMAIL)) {
            return $this->findUserByEmail($usernameOrEmail);
        }

        return $this->findUserByUsername($usernameOrEmail);
    }

....
```
Indeed, if user give email like an username findUserByUsernameOrEmail will search in email fields in DB. In case of username = "a first email" ! =  "a second email" none user with be found. 

I know you will tell me that a case in pretty rare, but one of my friend has created an account like that.  

For me, we have two solution:

-Use contraires validation of symphony to check that username is not an email
-Change findUserByUsernameOrEmail function to search in fields username and email. 

What do you think ? 
See you

**Comment by xabbuh** [comment]
Looks like #1336 addresses this.

**Comment by JHGitty** [comment]
rel #1923

**Comment by XWB** [comment]
I suggest we continue the discussion in https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1923
