### ISSUE TITLE
Unrecognized option "engine" under "fos_user"

### ISSUE THREAD

**Issue by estasenred** [FriendsOfSymfony/FOSUserBundle#1760]
I'd like to use php engine with FOSUserBundle and I change my app/config/config.yml adding this:

    fos_user:
        db_driver:     orm
        firewall_name: main
        user_class:    Nexian\ComunicadosBundle\Entity\User
        template:
            engine:   php

But clearing cache or reloading page I see "InvalidConfigurationException in ArrayNode.php line 309: Unrecognized option "template" under "fos_user" " error.

Thank you

**Comment by xabbuh** [comment]
Seems like your using the `master` branch while reading the documentation for `1.3.x`. FOSUserBundle dropped support for switching the templating engine in 5c03ad26c3857534b8c04644a80073a42d7eee1e.

**Comment by stof** [comment]
We indeed dropped this feature given that only the Twig templates are provided anyway.

**Comment by XWB** [comment]
See above.
