### ISSUE TITLE
Trying to load invalid (unavailable) CouchDB UniqueEntity validator

### ISSUE THREAD

**Issue by dannydorfel** [FriendsOfSymfony/FOSUserBundle#1775]
Symfony version: Symfony 2.7

    Attempted to load class "UniqueEntity" from namespace
    "\Symfony\Component\Validator\Constraints\Doctrine\Bundle\CouchDBBundle\Validator\Constraints".
    Did you forget a "use" statement for "Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity"?

Calling the register form, the metadata for the user document is created and the metadata loader somehow also loads the couchDB validation constraints. Which aren't present and the loader adds the default validator prefix to the classname declaration. Hence: Symfony\Component\...\Doctrine\Bundle...

It seems that the loader behaviour in Symfony2 has changed and also reads all xml files in the validation folder by default. Changing the Resources/config/validation folder would fix the problem.

**Comment by stof** [comment]
I think this is caused by https://github.com/symfony/symfony/pull/13855, which means that our special validation mapping files are now always loaded by Symfony. We will have to rename the folder indeed

**Comment by dannydorfel** [comment]
Indeed, that merge has the same code I traced the issue back to in the FrameworkExtension class.

As a temporary fix, I added a dc compiler pass removing the unwanted xml files in the arguments of the  'addXmlMappings' call to the 'validator.builder' definition.
