### ISSUE TITLE
Schema update creates fos_user table only with id field, missing baseuser fields

### ISSUE THREAD

**Issue by emillosanti** [FriendsOfSymfony/FOSUserBundle#1778]
With a clean/fresh setup of symfony 2.3.25
and composer require friendsofsymfony/user-bundle (installs fosuserbundle v1.3.5)

following steps in
doctrine:schema:update creates a fos_user table with a single id field

*steps work with '~2.0@dev'  

in this case, shouldn't "composer require friendsofsymfony/user-bundle"
automatically resolve to 2.* ?

**Comment by stof** [comment]
If you use FOSUserBundle 1.3.5, please read the documentation in the 1.3.x branch, not the master branch. I'm quite sure you are extending the ``FOS\UserBundle\Model\User`` in your own user class, while you must extend ``FOS\UserBundle\Entity\User`` in 1.3.x

**Comment by emillosanti** [comment]
@stof really appreciate the quick response, you are correct.

apologies for the time-wasting post/issue
