### ISSUE TITLE
Symphony 3.0 Event method 'getDispatcher' deprecated = error in FOSUserBundle events

### ISSUE THREAD

**Issue by mogilvie** [FriendsOfSymfony/FOSUserBundle#1780]
Hi,
The getDispatcher method has been removed from the symfony Event class. This is causing errors in the FOSUserBundle event process.

https://github.com/symfony/EventDispatcher/commit/5d91f7398400f923945df30a8903d5267a87aff0

This is causing an error in the FOSUserBundle authenticationListener.

Any suggestions on how to get the Dispatcher now?

Mark

**Comment by mogilvie** [comment]
Forgot to mention i'm using 3.0

**Comment by stof** [comment]
No need to create a separate issue for each deprecation in Symfony 2.7 (removed in 3.0, or scheduled for a removal not done yet). I know that the bundle has not been updated yet for it (btw, Composer should not let you install it alongside symfony 3.0 if it was not buggy with replaced versions).

and one a side node, Symphony is a totally different project: http://www.getsymphony.com/ :smile:

**Comment by XWB** [comment]
This has been fixed already.
