### ISSUE TITLE
Symfony 3.0 Event method getName deprecated = failure in EventListener/FlashListener

### ISSUE THREAD

**Issue by mogilvie** [FriendsOfSymfony/FOSUserBundle#1781]
Hi,

The getName method of the Symfony Event class has been removed.

https://github.com/symfony/EventDispatcher/commit/aa7baadd807ae1dae680bf5b0bf48fbc8d51dfaf

Any suggestions on how to modify FosUser FlashListener to overcome this?

Mark

**Comment by mogilvie** [comment]
Forgot to mention this is using Symfony 3.0

**Comment by garak** [comment]
:+1:

**Comment by xabbuh** [comment]
This was fixed by #1829.
