### ISSUE TITLE
Issue in documentation.

### ISSUE THREAD

**Issue by Merk87** [FriendsOfSymfony/FOSUserBundle#1782]
I've spotted that the documentation, in the section where how to configure the User there are an error in the usings.

For Doctrine ORM is saying that you need to use FOS\UserBundle\Model\User as BaseUser; but this is not correct, the correct one is use FOS\UserBundle\Entity\User as BaseUser;

Regards.

**Comment by massil31** [comment]
No, Model\User is the correct way, i have installed it manytimes in lot of applications and i always use Model\User.

**Comment by sstok** [comment]
In the 1.3.x you need to use `FOS\UserBundle\Entity\User` in 2.0 (master) you need to use the Model version `FOS\UserBundle\Model\User`.

Please read the documentation for the version you are using.
