### ISSUE TITLE
UserParamConverter

### ISSUE THREAD

**Issue by ogizanagi** [FriendsOfSymfony/FOSUserBundle#1783]
Hi,

Would a UserParamConverter be appreciated when using the `fos_user.user_provider.username_email` provider ? (Or even for the `username` provider, but it's already doable through mapping with the DoctrineParamConverter)
This ParamConverter will allow to load a user from its email or username.

Then, should it be a named converter, a priority registered converter or both ?

**Comment by XWB** [comment]
I don't think adding a ParamConverter would add much value.
