### ISSUE TITLE
Error :: FOSUserBundle Invitation

### ISSUE THREAD

**Issue by edrichard** [FriendsOfSymfony/FOSUserBundle#1784]
I have a big error : 
Catchable Fatal Error: Argument 1 passed to VDM\UserBundle\Form\Type\InvitationFormType::__construct() must be an instance of VDM\UserBundle\Form\DataTransformer\InvitationToCodeTransformer, none given, called in /Users/erichard/Sites/ville-du-mans/src/VDM/UserBundle/Controller/AdminController.php on line 58 and defined 

Here is the stack trace : 

in src/VDM/UserBundle/Form/Type/InvitationFormType.php at line 14
protected $invitationTransformer;
    public function __construct(InvitationToCodeTransformer $invitationTransformer)
    {
        $this->invitationTransformer = $invitationTransformer;
    }

**Comment by massil31** [comment]
Give us more details: AdminController where the the invitation data transformer is called

**Comment by edrichard** [comment]
The details :
public function invitationUserAction(Request $request)
    {
        //$em = $this->getDoctrine()->getManager();
        $em = $this->get("doctrine.orm.entity_manager");
        $invitation = new Invitation();
        $transformerInvitation = new InvitationToCodeTransformer($em);

        $form = $this->createForm(new InvitationFormType($transformerInvitation), $invitation);

        $form->handleRequest($request);

        if ($form->isValid()) {
            $this->get('vdm_mailer')->sendMessage(
                $this->container->getParameter("invitation.email"),
                $invitation->getEmail(),
                $this->container->getParameter("invitation.subject"),
                "VDMUserBundle:Admin:invitationUserEmail.html.twig",
                $this->container->getParameter("invitation.email.name"),
                NULL
            );

            return $this->redirect($this->generateUrl('vdm_user_invitation_confirmation'));
        }

        return $this->render('VDMUserBundle:Admin:invitationUser.html.twig', array(
            'form' => $form->createView()
        ));
    }

**Comment by massil31** [comment]
it seems like everything is ok in the controller
recheck your files, you have something not declared, may be you forgot a use or declaration

**Comment by edrichard** [comment]
where ?

these class :

<?php
namespace VDM\UserBundle\Entity;
class Invitation
{
    private $email;

    /**
     * @return mixed
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * @param String $email
     * @return Invitation
     */
    public function setEmail($email)
    {
        $this->email = $email;
        return $this;
    }
}

and

<?php

namespace VDM\UserBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use FOS\UserBundle\Model\User as BaseUser;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * User
 *
 * @ORM\Table(name="user")
 * @ORM\Entity(repositoryClass="VDM\UserBundle\Entity\UserRepository")
 */
class User extends BaseUser
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="firstname", type="string", length=255)
     */
    protected $firstname;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text", nullable=true)
     */
    protected $description;

    /**
     * @var boolean
     * @ORM\Column(name="isKnow", type="boolean", nullable=true)
     */
    protected $isKnow;

    /**
     * @ORM\OneToOne(targetEntity="VDM\CoreBundle\Entity\Media", cascade={"persist","remove"})
     * @ORM\JoinColumn(nullable=true)
     */
    private $avatar;

    /**
     * @ORM\OneToOne(targetEntity="Invitation", inversedBy="user")
     * @ORM\JoinColumn(referencedColumnName="code")
     * @Assert\NotNull(message="Your invitation is wrong", groups={"Registration"})
     */
    protected $invitation;

and from type :
<?php

namespace VDM\UserBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use VDM\UserBundle\Form\DataTransformer\InvitationToCodeTransformer;

class InvitationFormType extends AbstractType
{
    protected $invitationTransformer;

    public function __construct(InvitationToCodeTransformer $invitationTransformer)
    {
        $this->invitationTransformer = $invitationTransformer;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->addViewTransformer($this->invitationTransformer, true);
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'class' => 'VDM\UserBundle\Entity\Invitation',
            'required' => true,
        ));
    }

    public function getParent()
    {
        return 'text';
    }

    public function getName()
    {
        return 'vdm_invitation_type';
    }
}

and :
<?php

namespace VDM\UserBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use VDM\UserBundle\Form\DataTransformer\InvitationToCodeTransformer;

class InvitationFormType extends AbstractType
{
    protected $invitationTransformer;

    public function __construct(InvitationToCodeTransformer $invitationTransformer)
    {
        $this->invitationTransformer = $invitationTransformer;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->addViewTransformer($this->invitationTransformer, true);
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'class' => 'VDM\UserBundle\Entity\Invitation',
            'required' => true,
        ));
    }

    public function getParent()
    {
        return 'text';
    }

    public function getName()
    {
        return 'vdm_invitation_type';
    }
}

and form DataTransformer :
<?php

namespace VDM\UserBundle\Form\DataTransformer;

use VDM\UserBundle\Entity\Invitation;
use Doctrine\ORM\EntityManager;
use Symfony\Component\Form\DataTransformerInterface;
use Symfony\Component\Form\Exception\UnexpectedTypeException;

/**
 * Transforms an Invitation to an invitation code.
 */
class InvitationToCodeTransformer implements DataTransformerInterface
{
    protected $entityManager;

    public function __construct(EntityManager $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    public function transform($value)
    {
        if (null === $value) {
            return null;
        }

        if (!$value instanceof Invitation) {
            throw new UnexpectedTypeException($value, 'VDM\UserBundle\Entity\Invitation');
        }

        return $value->getCode();
    }

    public function reverseTransform($value)
    {
        if (null === $value || '' === $value) {
            return null;
        }

        if (!is_string($value)) {
            throw new UnexpectedTypeException($value, 'string');
        }

        return $this->entityManager
            ->getRepository('VDM\UserBundle\Entity\Invitation')
            ->findOneBy(array(
                'code' => $value,
                'user' => null,
            )
        );
    }
}

and services.yml :
services:
    vdm_user.registration.form.type:
        class: VDM\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: vdm_userbundle_user_registration }
    vdm_user.profile.form.type:
        class: VDM\UserBundle\Form\Type\ProfileFormType
        arguments: ["%fos_user.model.user.class%"]
        tags:
            - { name: form.type, alias: vdm_userbundle_user_profile }
    vdm_user.change_password.form.type:
        class: VDM\UserBundle\Form\Type\ChangePasswordFormType
        arguments: ["%fos_user.model.user.class%"]
        tags:
            - { name: form.type, alias: vdm_userbundle_user_change_password }
    vdm_user.invitation.form.type:
        class: VDM\UserBundle\Form\Type\InvitationFormType
        arguments: [@vdm.invitation.form.data_transformer]
        tags:
            - { name: "form.type", alias: "vdm_invitation_type" }
    vdm.invitation.form.data_transformer:
        class: VDM\UserBundle\Form\DataTransformer\InvitationToCodeTransformer
        arguments: [@doctrine.orm.entity_manager]

**Comment by damienalexandre** [comment]
It looks like your issue is not related to this bundle implementation. And I suggest you have a look at the Form component documentation ([here](https://symfony.com/doc/current/form/form_dependencies.html#define-your-form-as-a-service)) as it looks like you just need to add a dependency on your form service.
