### ISSUE TITLE
typehintable behavior propel2

### ISSUE THREAD

**Issue by Audax23** [FriendsOfSymfony/FOSUserBundle#1787]
Hi,
when i launch the command to build model in propel2, i get an error on the behavior typehintable.
Unknown behavior "typehintable", is it compatible with this bundle ?
thanks

**Comment by stof** [comment]
The Propel schema shipped in this bundle is for Propel 1. I have no idea whether Propel 2 can read the same file without change.
And I don't know either whether https://github.com/willdurand/TypehintableBehavior is compatible with Propel 2

**Comment by Audax23** [comment]
apparently, there is no branch for propel2 on willdurand repository, 
i posted a question, https://github.com/willdurand/TypehintableBehavior/issues/11
i hope have an answer.

**Comment by loicdev** [comment]
Hi , 
I have exactly the same problem, when i try to use propel 2 with fos user.
I have heard i was possible by using typeHint :  

https://github.com/willdurand/TypehintableBehavior/issues/10

But there is no examples to explain how to use the "typehint"

**Comment by Lionel09** [comment]
Now as this ```TypehintableBehavior``` functionality made it to core Propel2 code, I suppose FOSUserBundle if fully compatible with Propel2?

**Comment by XWB** [comment]
We do not support Propel 2.
