### ISSUE TITLE
no possibilities to use {{form_*}} functions while overriding templates

### ISSUE THREAD

**Issue by allan-simon** [FriendsOfSymfony/FOSUserBundle#1788]
I would like to know what is the rational (I guess there's one) being the fact that this bundle seems to craft the form by hand instead of reliying on twig form methods ?

**Comment by damienalexandre** [comment]
The forms are using the twig functions, except for the Login form which is not relying on the Form component because the content of the form is read by a firewall.

The register form as example:

```
{{ form_start(form, {'method': 'post', 'action': path('fos_user_registration_register'), 'attr': {'class': 'fos_user_registration_register'}}) }}
    {{ form_widget(form) }}
    <div>
        <input type="submit" value="{{ 'registration.submit'|trans }}" />
    </div>
{{ form_end(form) }}
```
