### ISSUE TITLE
[security] reset password token must be treated as password

### ISSUE THREAD

**Issue by zerkms** [FriendsOfSymfony/FOSUserBundle#1791]
Hence it should be stored hashed in the database.

**Comment by sstok** [comment]
The process of resetting a password is to generate a random token (OpenSSL pseudo random data) which is hex encoded for safety. So the token is already hashed, rehashing will only decrease the quality.

There is however something else that concerns me, but as its security related I would rather discuss this privately with (the devs and a security expert) first.

**Comment by zerkms** [comment]
@sstok that's not sufficient.

Few days ago example with slack: http://sakurity.com/blog/2015/03/27/slack_or_reset_token_hashing.html

**Comment by sstok** [comment]
I'm no security expert :) Oh wow, good catch (adding that site to my feeds list).
The remote timing attack is actually what I spotted also.

So basically we should use the password_hash() (bcrypt) function provided by PHP?

**Comment by zerkms** [comment]
@sstok I'd say - the `security.password_encoder` symfony service. It does not need to be super strong - but it must be strong enough so that it was not possible to brute force it during the token timeout (1-several hours).

**Comment by sstok** [comment]
So using MessageDigestPasswordEncoder with sha256 and random salt should be enough?
Can you work on a pull request, and remember that registration with confirm also uses this :+1:

**Comment by zerkms** [comment]
That sounds like a plan.

I'd be glad to contribute if no one else is going to do that concurrently :-)

**Comment by gnutix** [comment]
This would be an alternative implementation that would solve the problem : #2416

**Comment by zerkms** [comment]
@stof it's just a one function call and implementing it would not be a breaking change. Why was it closed?

**Comment by stof** [comment]
@zerkms no. It cannot be implemented without a change in the DB schema, to have a selector and a hash instead of a single token.

**Comment by zerkms** [comment]
It surely can be.
