### ISSUE TITLE
Reason behind private properties in EmailConfirmationListener?

### ISSUE THREAD

**Issue by frankadrian** [FriendsOfSymfony/FOSUserBundle#1796]
Hey,

First off thanks a lot for the great work put into this bundle.

I'm curious why the properties in `FOS\UserBundle\EventListener\EmailConfirmationListener` are private instead of protected. If they where protected one could extend the class and simply change the RedirectRoute.

Feedback will be appreciated.
Regards Frank

**Comment by stof** [comment]
Anything which is protected means we have to guarantee BC. this makes maintenance harder
If you want your own redirection, you can register your own listener on the event with a lower priority and overwrite the response in the event with your own

**Comment by frankadrian** [comment]
Ok, thats understandable, Thank you for explaining.
