### ISSUE TITLE
[security] Password resetting procedure should not indicate that the account does not exist

### ISSUE THREAD

**Issue by Spomky** [FriendsOfSymfony/FOSUserBundle#1797]
The resetting procedure indicates that the username or email does not exist in the database.
A malicious script could try random and then can easily get a list of usernames or emails of all accounts in your database.

After the user validated the form, he should be redirected to a page that displays the same message. For example :
```
If the username or the email exists, you will receive an email...
```

**Comment by lordrhodos** [comment]
I am totallyw with you on this. It is the first thing I recognized yesterday when configuring the user bundle for a current project. I will see if I find some time provide a patch

**Comment by Spomky** [comment]
I close this issue as a PR exists.
