### ISSUE TITLE
FOS\UserBundle\Entity/model\Group

### ISSUE THREAD

**Issue by dodysw** [FriendsOfSymfony/FOSUserBundle#1800]
Using the latest symfony (2.6.6) which pulls Doctrine 2.5 broke FOSUserBundle's entity model path mapping, e.g. during app/console doctrine:schema:update --dump-sql -v, now threw:
 
[Doctrine\Common\Persistence\Mapping\MappingException]
  Class 'FOS\UserBundle\Entity/model\Group' does not exist

I tried to find the point where it started to break, this doctrine file/revision changes seems to be the one that generate the above class name:
https://github.com/doctrine/common/commit/8eb9bb90fca0a6bb653c95df3fddf15fb462d5d2 
SymfonyFileLocator.php, line 191 (nsSuffix)

**Comment by umeku** [comment]
FriendsOfSymfony/FOSUserBundle@047b0e6 "fixes" this behavior, although it's only in dev-master right now.

**Comment by nicolassing** [comment]
Time to make a v2.0.0-alpha2 tag ? 
Thx for the reply anyway :)

**Comment by jhcasado** [comment]
Same problem here but with User:

  [Doctrine\Common\Persistence\Mapping\MappingException]
  Class 'FOS\UserBundle\Entity/model\User' does not exist

+1 to: Time to make a v2.0.0-alpha2 tag.

**Comment by jhcasado** [comment]
The wierd thing is that only happens in my server and not in local under Windows.

**Comment by jhcasado** [comment]
Just removed:

Document/
Entity/
Resources/config/doctrine/Group.*
Resources/config/doctrine/User.*

and it works again.

**Comment by gisoftlab** [comment]
Error appear after pulling latest symfony (2.6.6) and FOSUserBundle => alpha1 during 
php app/console doctrine:schema:update --force

[Doctrine\Common\Persistence\Mapping\MappingException]
Class 'FOS\UserBundle\Entity/model\User' does not exist

Someone solve this problem ?

**Comment by jhcasado** [comment]
If you are in a rush, you could try my temporary solution, 

in vendor/friendofsymfony/user-bundle/FOS/UserBundle/ you can manually delete:

rm -rf Document/ Entity/ Resources/config/doctrine/Group.* Resources/config/doctrine/User.*

**Comment by gisoftlab** [comment]
thx

**Comment by lmetdaoui** [comment]
Thanks

**Comment by stof** [comment]
for Doctrine 2.5, use the master branch of FOSUserBundle rather than the 2.0-alpha1 tag in case you want to use FOSUserBundle 2. The issue has already been fixed

**Comment by brammers** [comment]
Is 1.3.5 meant to be effected by this issue as well or just dev-master?

I've just done a doctrine:schema:update and I've not had any errors in production with a site using Symfony 2.6.6 and Doctrine 2.5.0.

**Comment by stof** [comment]
1.3.5 was not affected at all

**Comment by brammers** [comment]
Thanks for the reply.

**Comment by dodysw** [comment]
Thank you, dev-master works.

**Comment by zajca** [comment]
Is there some specific working commit?
I moved to dev-master but keep getting missing parameter
``` ("The parameter "fos_user.template.engine" must be defined.") ```
but when I define this parameter in config.yml, I get
```Unrecognized option "template" under "fos_user"```

**Comment by henry-vallenilla-developer** [comment]
Thanks @jhcasado was the very way to solve it

**Comment by anahiem** [comment]
Works perfect upgrading to Dev-master, Thanks!
