### ISSUE TITLE
Forgot password e-mail address incorrect

### ISSUE THREAD

**Issue by EwanValentine** [FriendsOfSymfony/FOSUserBundle#1810]
Hi folks,

When I use the 'reset password' feature, I enter a registered email, then it says:

'An email has been sent to ...@gmail.com. It contains a link you must click to reset your password.' 

Which obviously isn't a valid email address, or the email I entered. Any clues? What info do you need from me?

**Comment by sumbobyboys** [comment]
The fos user bundle doesn't send the complete email adresse back to the user for security reason. The email is well send to the given email address.

**Comment by XWB** [comment]
As intended indeed.
