### ISSUE TITLE
Solution for 'Bad credentials' translation problem

### ISSUE THREAD

**Issue by zomberg** [FriendsOfSymfony/FOSUserBundle#1816]
I found many open issues related with this problem.

In this issues people fix 'Bad credentials' message for 'Bad credentials.' in translation file for 1 language, which need for his needs.

The real problem is that 'Bad credentials.' appear only in Symfony 2.6. In earlier versions message stay 'Bad credentials' (without dot).
If only change translation message it is broken tranlation for Symfony < 2.6 versions.

I suggest will add new message 'Bad credentials.' (for Symfony 2.6+ users) and stay 'Bad credentials' message (for Symfony < 2.6 users).

**Comment by tim96** [comment]
+1
I have the same problem.
