### ISSUE TITLE
Possibility to limit number of sessions per user

### ISSUE THREAD

**Issue by benjamitauler** [FriendsOfSymfony/FOSUserBundle#1825]
I think this would classify as a Feature Request.
Haven't found a way to limit number of sessions per user, this is necessary to protect sites against abuse of accounts: i/e: one user gives his username/password to others, and all of them use site resources.  (That would happen when the account has a monthly cost...)

Thank you.

**Comment by neconest** [comment]
What do you mean by sessions, login or page views ?

**Comment by stof** [comment]
This is totally out of the scope of this bundle. We don't handle sessions and we don't handle authentication either (this part is handled by SecurityBundle in Symfony).

**Comment by benjamitauler** [comment]
Hi neconest, what I ment is, to find a way to limit how many , sessions, meaning that: 
- i understand that from one browser, say Chrome, logins to the page with user/pass, that counts as one session, even if multiple tab's are open accessing the website
- If with this user/pass , logins from another computer let's say with firefox, that counts as another session.
Joomla 1.5 used to limit backend users to only one Session, that means that if someone was  logged with user "admin", and someother in another computer logs in with user "admin" at same time, first one's session will be terminated and only the second who is logged in will work.

As I understand, Stof, I have to try to suggest this feature to the Symfony team?
