### ISSUE TITLE
FOS\UserBundle\FOSUserBundle issue

### ISSUE THREAD

**Issue by afoysal** [FriendsOfSymfony/FOSUserBundle#1837]
I am facing this error "Fatal error: Class 'FOS\UserBundle\FOSUserBundle' not found in D:\php\htdocs\my_project\app\AppKernel.php on line 22"

I tried below commands 

`D:\php\htdocs\my_project>php D:\php\php\composer.phar update friendsofsymfony
/user-bundle
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package symfony/icu == 1.2.0.0 could not be found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your min
imum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> f
or more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common
 problems.`

Then I tried following command

`D:\php\htdocs\iHadis\ihadis>php D:\php\php\composer.phar update symfony/icu
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Updating knplabs/doctrine-behaviors dev-master (c78fbb4 => ea0f040)
    The package has modified files:
    D ihadis/app/Resources/assets/plugins/bootstrap/fonts/glyphicons-halflings-r
egular.eot?
    Discard changes [y,n,v,s,?]? y

  [RuntimeException]
  Could not reset changes
  :error: unable to create file ihadis/app/Resources/assets/plugins/bootstrap
  /fonts/glyphicons-halflings-regular.eot? (Invalid argument)
  fatal: Could not reset index file to revision 'HEAD'.

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock]
 [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-
progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader]
 [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [packages1] ... [p
ackagesN]`

How can fix this issue

**Comment by stof** [comment]
Given the path displayed for the changes in ``knplabs/doctrine-behaviors`` (which is outside the ``knplabs/doctrine-behaviors`` package), I suspect that you installed the package from source and then deleted the ``.git`` folder in it. This means that Composer is not able to update the package anymore (it will try to update it with git, as it installed it with git previously, but git commands will actually run in your root project repo). You should not remove the ``.git`` folder (if you prefer not having git repos in your vendors, delete your vendor folder and install them again with the ``--prefer-dist`` option).

In any case, this does not look like a FOSUserBundle issue at all, but as a Composer usage issue.

**Comment by XWB** [comment]
> In any case, this does not look like a FOSUserBundle issue at all, but as a Composer usage issue.

I'm closing this issue then.
