### ISSUE TITLE
Why there is separate UserManagerInterface in FOSUserBundle when there is already UserProviderInterface in core symfony security ? 

### ISSUE THREAD

**Issue by vishalmelmatti** [FriendsOfSymfony/FOSUserBundle#1839]
Hi,

Having UserManagerInterface & UserProviderInterface looks confusing, can there be only 1 interface UserProviderInterface and if UserManagerInterface is really required can it extend UserProviderInterface ?

Its bit confusing to decide which one to use when ?

**Comment by TomasVotruba** [comment]
Hi @vishalmelmatti ,

it looks like `UserProviderInterface` methods in  `UserManagerInterface`, are [deprecated](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/ef7ca325929ff102fff521653a2e3b88c7a40361/Model/UserManager.php#L172).

I guess it's about to get rid of dependency on `UserProviderInterface`.

**Comment by stof** [comment]
UserManagerInterface is about a totally different use case than UserProviderInterface. Look at the methods in the UserManagerInterface. They are what FOSUserBundle needs.
UserProviderInterface is what Symfony needs, and we are providing implementations on top of UserManagerInterface (we were extending in the past, and this was **less** powerful than forcing to have it in the same class)
