### ISSUE TITLE
FOSUserBundle Add Checkbox

### ISSUE THREAD

**Issue by envyj020** [FriendsOfSymfony/FOSUserBundle#1840]
I'm trying to fetch a (subscribed to bulleting tinyint type) from my database to my profile edit view but when i add the input in my custom ProfileFormType :

```
                ->add('newsletter_subscription', 'checkbox', array(
                    'label' => 'form.newsletter_subscription',
                    'translation_domain' => 'FOSUserBundle',
                    'required' => false,

                ))
```
and in my User class :

```
    public function getNewsletterSubscription()
    {
        return $this->newsletterSubscription;
    }

    public function setNewsletterSubscription($subscriptionToNewsletter)
    {
        $this->newsletterSubscription = $subscriptionToNewsletter;
    }

```

In my view i can't get the value of the column and the same when i try to store/update this field, the value of the input checkbox always is 1, how can i fetch the value correctly ?
Thanks!

**Comment by massil31** [comment]
have you add the field to your entity class?

**Comment by envyj020** [comment]
Yes, the problem was solved by adding the following option in the overwritten checkbox field:
```
                ->add('newsletter_subscription', 'checkbox', array(
                    ...
                    'property_path' => 'newsletterSubscription',
                    ...
```
Where the property path value corresponds with my user entity field

Thank you anyway!
