### ISSUE TITLE
Lack of REGISTRATION_FAIL event or something like that.

### ISSUE THREAD

**Issue by idchlife** [FriendsOfSymfony/FOSUserBundle#1842]
I'm making ajax registration with FOSUserBundle, and I want to listen to REGISTRATION_FAIL event, which does not exist. How can I get all errors within registration, when using custom registration process, like ajax registration?

**Comment by Baachi** [comment]
Override the `RegistrationController` should do it.

**Comment by XWB** [comment]
This will be addressed in https://github.com/FriendsOfSymfony/FOSUserBundle/pull/1948
