### ISSUE TITLE
DEPRECATED

### ISSUE THREAD

**Issue by tubssp** [FriendsOfSymfony/FOSUserBundle#1843]
DEPRECATED - The "pattern" option in file "/symfony/vendor/friendsofsymfony/user-bundle/FOS/UserBundle/Resources/config/routing/profile.xml" is deprecated since version 2.2 and will be removed in 3.0. Use the "path" option in the route definition instead. -

    Called from XmlFileLoader::parseRoute() at line 85
    Called from XmlFileLoader::parseNode() at line 61
    Called from XmlFileLoader::load() at line 107
    Called from FileLoader::import() at line 157
    Called from YamlFileLoader::parseImport() at line 93
    Called from YamlFileLoader::load() at line 107
    Called from FileLoader::import() at line 157
    Called from YamlFileLoader::parseImport() at line 93
    Called from YamlFileLoader::load() at line 107
    Called from FileLoader::import() at line 157
    Called from YamlFileLoader::parseImport() at line 93
    Called from YamlFileLoader::load() at line 107
    Called from FileLoader::import() at line 157
    Called from YamlFileLoader::parseImport() at line 93
    Called from YamlFileLoader::load() at line 45
    Called from DelegatingLoader::load() at line 76
    Called from DelegatingLoader::load() at line 54
    Called from Router::getRouteCollection() at line 373
    Called from Router::getMatcherDumperInstance() at line 288
    Called from Router::Symfony\Component\Routing\{closure}()
    Called from call_user_func() at line 46
    Called from ConfigCacheFactory::cache() at line 302
    Called from Router::getMatcher() at line 250
    Called from Router::matchRequest() at line 137
    Called from RouterListener::onKernelRequest()
    Called from call_user_func() at line 61
    Called from WrappedListener::__invoke()
    Called from call_user_func() at line 164
    Called from EventDispatcher::doDispatch() at line 53
    Called from EventDispatcher::dispatch() at line 167
    Called from ContainerAwareEventDispatcher::dispatch() at line 124
    Called from TraceableEventDispatcher::dispatch() at line 3083
    Called from HttpKernel::handleRaw() at line 3056
    Called from HttpKernel::handle() at line 3207
    Called from ContainerAwareHttpKernel::handle() at line 2429
    Called from Kernel::handle() at line 30

DEPRECATED - The "pattern" option in file "/symfony/vendor/friendsofsymfony/user-bundle/FOS/UserBundle/Resources/config/routing/registration.xml" is deprecated since version 2.2 and will be removed in 3.0. Use the "path" option in the route definition instead. -

    Called from XmlFileLoader::parseRoute() at line 85
    Called from XmlFileLoader::parseNode() at line 61
    Called from XmlFileLoader::load() at line 107
    Called from FileLoader::import() at line 157
    Called from YamlFileLoader::parseImport() at line 93
    Called from YamlFileLoader::load() at line 107
    Called from FileLoader::import() at line 157
    Called from YamlFileLoader::parseImport() at line 93
    Called from YamlFileLoader::load() at line 107
    Called from FileLoader::import() at line 157
    Called from YamlFileLoader::parseImport() at line 93
    Called from YamlFileLoader::load() at line 107
    Called from FileLoader::import() at line 157
    Called from YamlFileLoader::parseImport() at line 93
    Called from YamlFileLoader::load() at line 45
    Called from DelegatingLoader::load() at line 76
    Called from DelegatingLoader::load() at line 54
    Called from Router::getRouteCollection() at line 373
    Called from Router::getMatcherDumperInstance() at line 288
    Called from Router::Symfony\Component\Routing\{closure}()
    Called from call_user_func() at line 46
    Called from ConfigCacheFactory::cache() at line 302
    Called from Router::getMatcher() at line 250
    Called from Router::matchRequest() at line 137
    Called from RouterListener::onKernelRequest()
    Called from call_user_func() at line 61
    Called from WrappedListener::__invoke()
    Called from call_user_func() at line 164
    Called from EventDispatcher::doDispatch() at line 53
    Called from EventDispatcher::dispatch() at line 167
    Called from ContainerAwareEventDispatcher::dispatch() at line 124
    Called from TraceableEventDispatcher::dispatch() at line 3083
    Called from HttpKernel::handleRaw() at line 3056
    Called from HttpKernel::handle() at line 3207
    Called from ContainerAwareHttpKernel::handle() at line 2429
    Called from Kernel::handle() at line 30

DEPRECATED - The "pattern" option in file "/symfony/vendor/friendsofsymfony/user-bundle/FOS/UserBundle/Resources/config/routing/change_password.xml" is deprecated since version 2.2 and will be removed in 3.0. Use the "path" option in the route definition instead. -

    Called from XmlFileLoader::parseRoute() at line 85
    Called from XmlFileLoader::parseNode() at line 61
    Called from XmlFileLoader::load() at line 107
    Called from FileLoader::import() at line 157
    Called from YamlFileLoader::parseImport() at line 93
    Called from YamlFileLoader::load() at line 107
    Called from FileLoader::import() at line 157
    Called from YamlFileLoader::parseImport() at line 93
    Called from YamlFileLoader::load() at line 107
    Called from FileLoader::import() at line 157
    Called from YamlFileLoader::parseImport() at line 93
    Called from YamlFileLoader::load() at line 107
    Called from FileLoader::import() at line 157
    Called from YamlFileLoader::parseImport() at line 93
    Called from YamlFileLoader::load() at line 45
    Called from DelegatingLoader::load() at line 76
    Called from DelegatingLoader::load() at line 54
    Called from Router::getRouteCollection() at line 373
    Called from Router::getMatcherDumperInstance() at line 288
    Called from Router::Symfony\Component\Routing\{closure}()
    Called from call_user_func() at line 46
    Called from ConfigCacheFactory::cache() at line 302
    Called from Router::getMatcher() at line 250
    Called from Router::matchRequest() at line 137
    Called from RouterListener::onKernelRequest()
    Called from call_user_func() at line 61
    Called from WrappedListener::__invoke()
    Called from call_user_func() at line 164
    Called from EventDispatcher::doDispatch() at line 53
    Called from EventDispatcher::dispatch() at line 167
    Called from ContainerAwareEventDispatcher::dispatch() at line 124
    Called from TraceableEventDispatcher::dispatch() at line 3083
    Called from HttpKernel::handleRaw() at line 3056
    Called from HttpKernel::handle() at line 3207
    Called from ContainerAwareHttpKernel::handle() at line 2429
    Called from Kernel::handle() at line 30

**Comment by weaverryan** [comment]
@tubssp I believe all the `patterns` have been changed on the master branch, so the issue is already fixed. But we need a new tag that has the update. For example, here's the last alpha release tag (with pattern): https://github.com/FriendsOfSymfony/FOSUserBundle/blob/5a53273c3ae4e3f128c71522cd8398515718bbb8/Resources/config/routing/profile.xml and here's master (with `pattern` gone): https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Resources/config/routing/profile.xml

See #1844.

**Comment by stof** [comment]
yeah. the 1.3.x branch is compatible with 2.7, but it relies on deprecated features.
The 2.x version does not rely on anything deprecated anymore (I will release a new version for it soon).

**Comment by tolry** [comment]
I have a little pet project using FOSUserBundle which I have updated to 2.7 just now, where I would like to give 2.0@alpha a try. It's a really simple use case, user management wise, so I might not run into to many troubles upgrading. Are there any migration information available yet?

**Comment by stof** [comment]
@tolry use ``~2.0@dev`` rather than ``~2.0@alpha`` if you run on 2.7. The alpha release was before we changed the code to stop using deprecated features, while the dev version has this change.

**Comment by tolry** [comment]
@stof thx - seems to work right away, great

**Comment by thomas-koch-comsolit** [comment]
Please also provide a version for the 1.x branch that removes the deprecated features. We can not use alpha versions here but we'd like to start hunting deprecated stuff in our own code. Therefore it's not nice to have noice from high quality packages like FOS.

**Comment by weaverryan** [comment]
@thomas-koch-comsolit I believe the 2.x branch will have an actual release in the coming weeks. Then you can upgrade to that :).

We could remove the deprecated calls in 1.3, but you'd need to increase the required Symfony version to 2.7 (instead of 2.1), so it'd need to ultimately be a `1.4.x` release. @stof is already really busy and this would mean another branch to maintain. I think we should get 2.x released and then - as needed - make any changes to 1.3 to help a smooth upgrade path if needed.

Cheers!

**Comment by XWB** [comment]
This has been resolved.

**Comment by thomas-koch-comsolit** [comment]
How has it been resolved? :-)
