### ISSUE TITLE
Could we have a tagged release with the Symfony 2.7 fixes please?

### ISSUE THREAD

**Issue by NoelLH** [FriendsOfSymfony/FOSUserBundle#1844]
Currently if you have either v1.3.5 or the latest tagged v2 alpha you hit issue #1775 - which completely breaks everything on the now-stable Symfony 2.7.

Would it be worth making some new tags, as the bug's already fixed in both branches' masters?

**Comment by weaverryan** [comment]
+1 I just hit this bug upgrading - it's a stopper :/.

But, kudos to already having it fixed :).

**Comment by NoelLH** [comment]
Btw if anyone else wants to temporarily use the latest from master with the fix (bit riskier generally), you can ask Composer for it with:

    ...
    "friendsofsymfony/user-bundle": "1.3.x-dev",
    ...

Took me a few mins to realise!

**Comment by merk** [comment]
I've tagged a 1.3.6 release, but given the alpha state of 2.0, I will leave the release of that to @stof.

**Comment by weaverryan** [comment]
That's great - thanks!

**Comment by tarjei** [comment]
I've added an extra pr needed for 1.3.x, see #1852

**Comment by XWB** [comment]
The seconds alpha is now available https://github.com/FriendsOfSymfony/FOSUserBundle/releases/tag/v2.0.0-alpha2

**Comment by stof** [comment]
@XWB please don't make a release where unreviewed PRs are merged in it. Ask for review first. Otherwise it makes it very bad for people upgrading to such versions if we need to revert things
