### ISSUE TITLE
Exception :: FOSUserBundle Invitation 

### ISSUE THREAD

**Issue by ezpoko** [FriendsOfSymfony/FOSUserBundle#1846]
Hello !
Any help fo fix this following error would appreciable :

The form's view data is expected to be an instance of class BTF\UserBundle\Entity\Invitation, but is a(n) string. You can avoid this error by setting the "data_class" option to null or by adding a view transformer that transforms a(n) string to an instance of BTF\UserBundle\Entity\Invitation.

Thanks!

**Comment by stof** [comment]
There is not Invitation object in FOSUserBundle, so this looks like an issue in your own code

**Comment by ezpoko** [comment]
Hi!
Is there a best way to let users register themselves and administrator to send invitation by emails.
I have followed the doc : <a href="https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Resources/doc/adding_invitation_registration.md">https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Resources/doc/adding_invitation_registration.md</a> but can't make it work. 

Thanks for any help.
