### ISSUE TITLE
'validation_groups' ignored in custom FormType 'setDefaultOptions()'

### ISSUE THREAD

**Issue by nietonfir** [FriendsOfSymfony/FOSUserBundle#1860]
I know that for overriding/extending the default validation of the FOSUserBundle one has to use custom `validation_groups` and specify it in `config.yml` (see #986, https://github.com/symfony/symfony/issues/3224, https://github.com/symfony/symfony/issues/5953).

``` yml
# config.yml
fos_user:
    registration:
        form:
            type: my_registration_form_type_service
            validation_groups: [Registration, Foo]
```

That usually works perfectly, but yesterday I wanted/needed to use a conditional [validation group](http://symfony.com/doc/current/book/forms.html#groups-based-on-the-submitted-data). So I specified the `validation_groups` options with a Closure:

``` php
// RegistrationFormType
public function buildForm(FormBuilderInterface $builder, array $options)
{
    // …
    $builder->add('complete', 'hidden', array(
        'mapped' => false,
        'data'       => 0
     ));
}

public function setDefaultOptions(OptionsResolverInterface $resolver)
{
    $resolver->setDefaults(array(
        'data_class' => $this->class,
        'validation_groups' => function(FormInterface $form) {
            if ($form->get('complete')->getData() === '1') {
                return array('Bar', 'Registration');
            }

            return array('Registration');
        },
    ));
}
```

This doesn't work, no valid value specified is used at all. So my question is: will this (specifying `validation_groups` as default option) ever be possible? (I'm not even sure if asking this question/issue is in scope of this bundle or not). (edit: Can I maybe fix/hack around that issue in a fork?)
And otoh: wouldn't it be more maintainable to always specify the `validation_groups` in the dedicated FormTypes? This way anyone could choose to use or extend them by overriding the FormType.

**Comment by stof** [comment]
This is because FOSUserVundle configures the validation groups explicitly based on config setting, which means that the default value is not used (default values are used only when the option is not configured explicitly, as their name implies)

**Comment by nietonfir** [comment]
I know. Can I circumvent that somehow (is it even possible)?

I already tried to remove the `arrayNode` in `Configuration.php` as well as removing/overriding the `fos_user.registration.form` service definition in `registration.xml`. But to no avail, then no validation groups are used at all.

I tried to debug, but I get lost some steps after `FormFactory::createNamedBuilder()` and I'm not even sure if I'm on track…

**Comment by Dorwido** [comment]
This looks like something i am looking for myself as well, wrote this already on stackoverflow:

"I am new with Symfony2 and so I am with FOSUserbundle, the registration form I wrote got different fields mandatory based on if it is a company or private person, I set it up etc and if I hardcode the valdiation group in the fos config it will work, but what I need is to set it up dynamic based on the form submit data, I tried to follow: http://symfony.com/doc/current/book/forms.html#book-forms-validation-groups

Seeing that FOSUserbundle use the deprecated OptionsResolverInterface , I even tried it with that one, but whatever I do it is never called.

So my question is kinda, what is the right approach with that bundle to change the valdiation group on the fly based on the submitted data?"

From reading this here now it seems it is impossible todo what I want todo?

**Comment by Dorwido** [comment]
I found a working solution for myself:
in the confing.yml i set the validationgroup like this
validation_groups: [AppBundle\Form\Type\RegistrationFormType, determineValidationGroups]

and inside that class then:

public static function determineValidationGroups(FormInterface $form){
...
}

And that one returns an array with the validations groups, just dont forget to include for registration for example Registration or it wont validate if the user already exists etc
