### ISSUE TITLE
Validate userManager object.

### ISSUE THREAD

**Issue by KrissMcCone** [FriendsOfSymfony/FOSUserBundle#1861]
Hello. I create API and I want to add user with data received in array.

How can I validate userManager? Cos updateUser($user) allows to save user wihout primary data, or string instead of email.

$validator = $this->get('validator');
$errors = $validator->validate($user);

When the user is a object from $userManager->createUser() doesn't work.

Any idea? Thanks :)

**Comment by stof** [comment]
I don't understand what you mean about validating the user manager. the user manager does not contain any data sent by the user.

and if you want to validate the user object, this should be done before calling ``updateUser``. Using the validator for that works, but be aware that constraints defined in FOSUserBundle are not in the ``Default`` validation group but in different validation groups, allowing us to validate different fields depending on the form being submitted. If you only run the ``Default`` validation group (which is the behavior of Symfony when you don't specify which group you want to run), none of the builtin FOSUserBundle constraints will be applied.
