### ISSUE TITLE
Redirect after login and logout has an additional, leading slash

### ISSUE THREAD

**Issue by Brainshack** [FriendsOfSymfony/FOSUserBundle#1864]
Hell,

I am using FOSUserbundle with the SonataUserbundle. I am not sure, which bundle this error belongs to, but I will try here first. Everytime I login and logout I get redirected:
After logging in, I get redirected to /app_dev.php///dashboard (3 leading slashes)
After logging out, I get redirected to /app_dev.php//login (2 leading slashes)

Here us my security.yml

security:
    acl:
        connection: default
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:             ^/.*
            context:             user
            form_login:
                provider:       fos_userbundle
                login_path:     sonata_user_admin_security_login
                use_forward:    false
                check_path:     /login_check
                failure_path:   null
            logout:             true
            anonymous:          true
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: [ROLE_USER] }

    access_decision_manager:
        strategy: unanimous

Can anybody hint me, what I might be missing?

**Comment by stof** [comment]
The redirection after login is handled by the SecurityBundle, not by FOSUserBundle (we don't handle the login itself)
