### ISSUE TITLE
Kill all sessions of a particular user after changing password

### ISSUE THREAD

**Issue by vgross** [FriendsOfSymfony/FOSUserBundle#1866]
I was wondering if there is a proper way to do that ?

If someone can manage to still my password and let's suppose I'm aware of that, then I decide to change my password BUT, if the hacker is still connected within my account, unless his PHP session expire, he is still connected with my user and can continue to use it.

There is a way to disconnect/kill all sessions for a particular user when we change the password ? 

Does that make sense to anyone ?

**Comment by stof** [comment]
The way tokens are compared in Symfony means that if a password is changed, the old token is not considered authenticated anymore, forcing to reauthenticate.
The remember_me feature also has a check whether the hashed password has changed or no.

This means that any call to ``isGranted`` will return false for the other sessions until you reauthenticate.

**Comment by stof** [comment]
note that if you implement the ``EquatableInterface`` interface on your user, this may not be true anymore as you would not be responsible for the comparison rather than letting Symfony perform it.

**Comment by vgross** [comment]
Does the @Secure annotation from JMSSecurity Bundle use isGranted method ? I have secured all my controller with that feature. If I open a session on a browser, and change the password from another one, the first browser can continue to navigate as logged user without any issue.

**Comment by stof** [comment]
it uses them
