### ISSUE TITLE
Validation EmailCanonical Unique just in enabled users

### ISSUE THREAD

**Issue by diegoleft** [FriendsOfSymfony/FOSUserBundle#1867]
The users in mongodb have a variable "enabled:true" when a user is deleted "enabled" changed to false, but continue with the emailCanonical. (i dont want delete it)
How i can replace the validation to search users with the same emailCanonical but with "enabled:true"?

thanks!

**Comment by stof** [comment]
enabled in FOSUserBundle is not about soft-deleting a user.
