### ISSUE TITLE
Can't set up Groups table

### ISSUE THREAD

**Issue by stevedeveloper1** [FriendsOfSymfony/FOSUserBundle#1873]
Sorry if this is not an issue but I can't se it in the documentation.

I am trying to set up groups, I have successfully set up everything else just how do you set up the groups table?

**Comment by Ingannatore** [comment]
Have you followed the documentation at 
https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Resources/doc/groups.md?

**Comment by stevedeveloper1** [comment]
I have followed the docs I have done the following
1. Enabled the group support in app/config/config.yml
2. Set up Group.php and copied the code from the docs and change the relevant namespace
3. Mapped the relation in src/MyProject/MyBundle/Entity/User.php
4.Updated User.orm.xml with the code in the docs and changed the entity to where mine is stored.
5.Enabled the routing in app/config.yml

Now what do I do? I have tried php app/console schema:validate but this throws an error as there is no mapping file. I've copied the Group.orm.xml from the bundle then I get 
[Doctrine\ORM\Mapping\MappingException]                                                                                          
  Duplicate definition of column 'name' on entity 'myProject\myBundle\Entity\Group' in a field or discriminator column mapping.

**Comment by stevedeveloper1** [comment]
I have updated the Group.orm.xml to 

    <?xml version="1.0" encoding="UTF-8"?>
       <doctrine-mapping xmlns="http://doctrine-project.org/schemas/orm/doctrine-mapping"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://doctrine-project.org/schemas/orm/doctrine-mapping
                  http://doctrine-project.org/schemas/orm/doctrine-mapping.xsd">
     <mapped-superclass name="f8creates\ImslBundle\Entity\Group">
        <id name="id" column="id" type="integer">               
            <generator strategy="AUTO" />                                           
        </id>
      </mapped-superclass>
    </doctrine-mapping>

This now maps fine and returns

CREATE TABLE fos_user_group (user_id INT NOT NULL, group_id INT NOT NULL, PRIMARY KEY (user_id, group_id));
CREATE INDEX IDX_583D1F3EA76ED395 ON fos_user_group (user_id);
CREATE INDEX IDX_583D1F3EFE54D947 ON fos_user_group (group_id);
ALTER TABLE fos_user_group ADD CONSTRAINT FK_583D1F3EA76ED395 FOREIGN KEY (user_id) REFERENCES fos_user (id);
ALTER TABLE fos_user_group ADD CONSTRAINT FK_583D1F3EFE54D947 FOREIGN KEY (group_id) REFERENCES [Group] (id);
ALTER TABLE fos_user ALTER COLUMN roles VARCHAR(MAX) NOT NULL;
EXEC sp_addextendedproperty N'MS_Description', N'(DC2Type:array)', N'SCHEMA', dbo, N'TABLE', fos_user, N'COLUMN', roles;
CREATE UNIQUE INDEX UNIQ_957A647992FC23A8 ON fos_user (username_canonical) WHERE username_canonical IS NOT NULL;
CREATE UNIQUE INDEX UNIQ_957A6479A0D96FBF ON fos_user (email_canonical) WHERE email_canonical IS NOT NULL;


Can you check this is correct for updating the schema

**Comment by stevedeveloper1** [comment]
Running the schema update throws
    [PDOException]                                                                                                                           
      SQLSTATE[HY000]: General error: 1750 General SQL Server error: Check messages from the SQL     Server [1750] (severity 16) [ALTER TABLE fos  
      _user_group ADD CONSTRAINT FK_583D1F3EFE54D947 FOREIGN KEY (group_id)     REFERENCES [Group] (id)]

**Comment by xabbuh** [comment]
Which version of FOSUserBundle do you use?

**Comment by stevedeveloper1** [comment]
I am using 
friendsofsymfony/user-bundle         dev-master 3efbc08  Symfony FOSUserBundle

**Comment by Ingannatore** [comment]
Can you please paste the definition of your `Group` class?
It seems that Doctrine is unable to create the `fos_group` table because of the error

> Duplicate definition of column 'name' on entity 'myProject\myBundle\Entity\Group'

The `fos_user_group` table is just the linking table for the many-to-many relation between users and groups.

**Comment by stevedeveloper1** [comment]
<?php

    // src/myProject/myBundle/Entity/Group.php

    namespace myProject\myBundle\Entity;

    use FOS\UserBundle\Model\Group as BaseGroup;
    use Doctrine\ORM\Mapping as ORM;

    /**
     * @ORM\Entity
     * @ORM\Table(name="fos_group")
     */
    class Group extends BaseGroup
    {
        /**
         * @ORM\Id
         * @ORM\Column(type="integer")
         * @ORM\GeneratedValue(strategy="AUTO")
         */
         protected $id;
    }

**Comment by Ingannatore** [comment]
If you use Doctrine's annotations (ie, `@ORM\Entity` and the like), you do not need the `Group.orm.xml` file; remove it from your project and then launch again the schema update command.

**Comment by stevedeveloper1** [comment]
Phew thank you, sorry for the late response I had to work on a different branch and come back to this. I think my problem came from having to use an existing database and mixing orm.xml from mapping the database and trying to create this.

**Comment by xabbuh** [comment]
@stevedeveloper1 If your issue has been solved, it would be nice to close the issue.

**Comment by Ingannatore** [comment]
Glad to be of any help, Steve :)

**Comment by stevedeveloper1** [comment]
@xabbuh Sorry I thought admin did that this is now closed
