### ISSUE TITLE
New releases

### ISSUE THREAD

**Issue by theofidry** [FriendsOfSymfony/FOSUserBundle#1875]
Is there any update regarding newer releases? The 1.X got one in june but the 2.X is still in alpha since last year.

**Comment by stof** [comment]
My plans were to do it during the last 2 weekends, but I had to change them because I had to do other things than OSS work. So it will have to wait until after my vacations (so after July 14th)

**Comment by theofidry** [comment]
Ok, thanks for the answer.

**Comment by JHGitty** [comment]
Any updates?
