### ISSUE TITLE
"Attempted to call an undefined method named "findOneBy"

### ISSUE THREAD

**Issue by artgreg** [FriendsOfSymfony/FOSUserBundle#1876]
Hello.

Here is the problem I encounter after having installed FOSUserbundle (same problem occured with current 2.0 and previous 1.3 version):

(I use sf v 2.7 and did not created a dedicated bundle for this new entity and used an already existing one)

When i tried to login (at the /login page) with any types of credentials

CRITICAL - Uncaught PHP Exception Symfony\Component\Debug\Exception\UndefinedMethodException: "Attempted to call an undefined method named "findOneBy" of class "Pulzo\Bundle\ReportesPautaBundle\Entity\FOSUser"." at /home/pulzo/Documents/reportes-pautas/vendor/friendsofsymfony/user-bundle/FOS/UserBundle/Doctrine/UserManager.php line 68

-  i have an error before in my User class entity i called FOSUser

CRITICAL - Fatal Error: Call to undefined method Pulzo\Bundle\ReportesPautaBundle\Entity\FOSUser::findOneBy()

This type of error make me think I have probably misunderstood something in the process install.

But in another way when in the sf2 CLI i use the command to promote an user (fos:user:promote) I have the same fatal error:

{"type":1,"file":"/home/pulzo/Documents/reportes-pautas/vendor/friendsofsymfony/user-bundle/FOS/UserBundle/Doctrine/UserManager.php","line":68,"level":-1,"stack":[]} 

Obviously if i put an empty method findOneBy() in my Pulzo\Bundle\ReportesPautaBundle\Entity\FOSUser class the error disappear.

I am sure I am mistaken on something basic but I did not find a documentation that explained what should clearly be available and working after a simple installation.

Thanks a lot for reading me.

**Comment by stof** [comment]
It looks like we get your entity class when asking Doctrine for the repository object. So something looks broken in your Doctrine setup.

**Comment by artgreg** [comment]
Thanks for the swift reply.
(en fait on pourrait parler en français car j'ai vu que vous travaillez pour une boîte développant des solutions dans le même domaine que ma précédente entreprise, mais je continue en anglais pour les lecteurs...)

If something is broken in my Doctrine setup what do you recommend me to do: (steps).

How could i debug if its possible? (is it just a misconfiguration in my parameters & config files)
Or do I have to update or reinstall something?

Thanks again (I am still junior in sf2 and sometimes difficulties to interpret the errors...)

**Comment by artgreg** [comment]
Found it. If it can help someone later.

In my orm xml file i have a duplicated value of repository-class attribute

  <entity name="Pulzo\Bundle\ReportesPautaBundle\Entity\FOSUser" repository-class="Pulzo\Bundle\ReportesPautaBundle\Entity\FOSUser">

I just removed it and it worked.
