### ISSUE TITLE
Add missing getRedirectionUrl in ProfileController

### ISSUE THREAD

**Issue by shakaran** [FriendsOfSymfony/FOSUserBundle#1878]
I was upgrading a Symfony project from Symfony 2.1 to 2.3 and after to 2.7 and I switch to the master version for FOSUserBundle.

There are not a lot documentation for upgrade old versions (all the events stuff, form factory and others undocumented changes).

I finally migrate all, but there are some methods like getRedirectionUrl() in ProfileController that was removed without a reason, so the API is very inconsistent.

As you can see in this commit:

https://github.com/FriendsOfSymfony/FOSUserBundle/blob/7a360d360a68b233bc3f313a0cc93d2139b7acdf/Controller/ProfileController.php

The method is added and present for v2.0.0-alpha1 but I think that it was mistakinly removed when you remove the ContainerAware and replace extending via symfony Controller https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Controller/ProfileController.php

I fix this just copying the code in my controller, but I think that should be included by default or at least announce as breaking change in the changelog.

**Comment by sstok** [comment]
v2.0.0-alpha1 is already very old - https://github.com/FriendsOfSymfony/FOSUserBundle/releases/tag/v2.0.0-alpha1 ( 109 commits to master since this tag ). Use dev-master or use `~2.0,>v2.0.0-alpha1@dev` as version constraint.

**Comment by XWB** [comment]
See above.
