### ISSUE TITLE
Problem to migrate to 1.3.6

### ISSUE THREAD

**Issue by JuanDaniel** [FriendsOfSymfony/FOSUserBundle#1879]
My web application run ok over Symfony2.3.25 and FOSUserBundle 1.3.x...
Today when i updated to Symfony2.7 and all dependencies was updated, the FOSBundle was updated to 1.3.6.
The problem appear when i execute the command line "doctrine:schema:update --force". The result was that the table that i use to extend to FOS\UserBundle\Model\User, lost the parent field. Now there are only the fields own fields.
Can you give some tips for resolve this problem?
Thanks in advance.

**Comment by Ingannatore** [comment]
Could you please explain better the phrase

> The result was that the table that i use to extend to FOS\UserBundle\Model\User, lost the parent field. Now there are only the fields own fields.

**Comment by damienalexandre** [comment]
@JuanDaniel Is this issue still relevant? Did you manage to understand this problem on your projet?

We can't help you without informations.

**Comment by stof** [comment]
if you use 1.3.6, the entity must extend ``FOS\UserBundle\Entity\User``, not ``FOS\UserBundle\Model\User``.
It looks like you were mixing things from 2.0.x (where the intermediate ``FOS\UserBundle\Entity\User`` class is indeed gone)
