### ISSUE TITLE
generated schema for User only has 'id' column, missing others defined in the model

### ISSUE THREAD

**Issue by rparsi** [FriendsOfSymfony/FOSUserBundle#1880]
I have a new Symfony 2.7.1 app started from scratch, am using FOSUserBundle 1.3.x and following the documentation for setting it up.

When I run:
php app/console doctrine:schema:update --dump-sql

I only get:
CREATE TABLE fos_user (id INT UNSIGNED AUTO_INCREMENT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB;

So columns are missing.  Reading the model class I see there are no Doctrine annotations, for $username for example.  Am I supposed to manually add the annotations in my custom User class?

I'm missing a step here, please advise.

Thanks.

**Comment by JuanDaniel** [comment]
I had the similar error..
I resolved it using the version dev-master or use ~2.0,>v2.0.0-alpha1@dev as version constraint.

**Comment by rparsi** [comment]
@JuanDaniel seriously? why isn't this fixed in the supposedly "stable" version?

**Comment by rparsi** [comment]
@stof Should I use version ~2.0 or will 1.3.6 get a fix for this soon?
Thanks in advance.

**Comment by xabbuh** [comment]
Did you extend the `User` class from the `Model` namespace or the one from the `Entity` namespace?

**Comment by rparsi** [comment]
@xabbuh From the model (FOS\UserBundle\Model\User as BaseUser) as per the documentation at https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Resources/doc/index.md

The same docs mentions something about a compiler pass, so I thought the rest of the Doctrine mappings would be added by whatever that does.

**Comment by xabbuh** [comment]
@rparsi You should read the [documentation for 1.3.x](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/1.3.x/Resources/doc/index.md) when you don't use 2.0. :)

**Comment by rparsi** [comment]
@xabbuh then it's a linking problem.  If you read the 'readme.md' for 1.3.x it says to read the documentation for master, which is what I did.
I'll try the 1.3.x specific install instructions and hopefully that's the end of it.

**Comment by rparsi** [comment]
@JuanDaniel @xabbuh it's fixed now, I needed to apply the auto mapping to the default entity manager

**Comment by xabbuh** [comment]
@rparsi I proposed changed references in #1883 now (honestly I did not see the wrong links before).
