### ISSUE TITLE
Servicies public = "false"

### ISSUE THREAD

**Issue by feyyazesat** [FriendsOfSymfony/FOSUserBundle#1884]
Under Resources/config/*.xml,  services generally public = "false" is there any reason that have to be private ?

Example : I need to use send confirmation mail with generate confirmation token.
FOSUserBundle/Resources/config/mailer.xml

Infact I solved my problem to define those services in my services.yml with different names but it is a bit nasty workaround.

**Comment by Ingannatore** [comment]
From the official documentation (http://symfony.com/doc/current/components/dependency_injection/advanced.html#marking-services-as-public-private), a `public` service means that you __can__ fetch it from the container using the `get()` method of the service container:

```
$myService = $container->get('my_service_id');
```

On the other side, a `private` service only exists to be __injected into another service__ and is __not intended__ to be fetched directly from the container as shown above.

You should read all the documentation to check all the other implications (inlined instantiation, performances, etc.).

**Comment by feyyazesat** [comment]
I see, I didn't know about that aliasing access, thanks sir.
