### ISSUE TITLE
Twig error for route /register/confirmed, Notice: Only variable references should be returned by reference") in FOSUserBundle::layout.html.twig at line 9

### ISSUE THREAD

**Issue by rparsi** [FriendsOfSymfony/FOSUserBundle#1885]
Hi I'm using Symfony 2.7.1 with FOSUserBundle 1.3.6.
After registering a user I get redirected to /register/confirmed as expected but the Twig template throws the following error:

Notice: Only variable references should be returned by reference") in FOSUserBundle::layout.html.twig at line 9

FYI I am NOT overriding any FOSUserBundle templates as I just want to get the basic functionality working first.

**Comment by xabbuh** [comment]
Did you do something special in your `User` class?

**Comment by rparsi** [comment]
@xabbuh No, I copied/pasted what's in the docs.  As an aside, I noticed that the generated schema doesn't have an index for the password column, are we supposed to add that ourselves?

**Comment by xabbuh** [comment]
Can you show the code of it nonetheless?

**Comment by rparsi** [comment]
@xabbuh nvm it works now, something screwy with the twig cache.  I cleared it and tried user registration again.
