### ISSUE TITLE
Ajax

### ISSUE THREAD

**Issue by fredleput** [FriendsOfSymfony/FOSUserBundle#1888]
Hi and thx for yhis bundle,

Is it possible to ajaxify all the route of the bundle with FOS js routing bundle ? If so is there a doc anywhere...

Fred (France)

**Comment by stof** [comment]
FOSJsRoutingBundle is not about ajaxifying routes at all.

**Comment by fredleput** [comment]
So i don't understood what the goal of the fos js routing bundle...

**Comment by stof** [comment]
@fredleput FOSJsRoutingBundle is only about generating URLs from the JS side. It does not perform any AJAX calls.

**Comment by fredleput** [comment]
Yes i agree... Is it possible to call in JavaScript thé route of thé fos
user bundle with thé option "exposé" of of thé fos js routing ?
