### ISSUE TITLE
UserProvider::refreshUser should test against Interface not abstract User class

### ISSUE THREAD

**Issue by fatganz** [FriendsOfSymfony/FOSUserBundle#1889]
```
if (!$user instanceof User && !$user instanceof PropelUser) {
```
why not to replace `$user instanceof User` to `$user instanceof UserInterface`?
This can give freedom in User class implementation and further extension.

**Comment by stof** [comment]
This is because the code currently relies on a method which is not part of the interface

**Comment by fatganz** [comment]
Thanks for answering.
I am wondering if we can extend `UserInterface` with `getId()` method. 
It is very specific to the project and anyway won't give you to work with classes which implement UserInterface and do not have `getId()` because of `UserProvider::refreshUser` method which explicitly requires `getId()`.

**Comment by fatganz** [comment]
It basically makes UserProvider::refreshUser wrong because it requires `SecurityUserInterface` as parameter but calls method which doesn't belong to it.
https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Security/UserProvider.php#L57
So it shouldn't be wrong to add getId() to interface.

**Comment by stof** [comment]
No, it does not require ``SecurityUserInterface``. The ``UserProviderInterface`` does, and asks to throw an ``UnsupportedUserException`` when the user is not supported. And ``getId`` would not be added in ``SecurityUserInterface`` anyway, but in our own ``UserInterface`` anyway (which is something I'm thinking about for the 2.0 release btw)

**Comment by fatganz** [comment]
> No, it does not require SecurityUserInterface.

Sorry mixed interfaces somehow - my bad.
> but in our own UserInterface anyway (which is something I'm thinking about for the 2.0 release btw)

This will be great as this will free hands for those like me who need own class tree to work with FOS User bundle.

**Comment by XWB** [comment]
This was resolved in https://github.com/FriendsOfSymfony/FOSUserBundle/commit/5e52e0809d65bcdea955b31b4ea72f0a57ea67bf
