### ISSUE TITLE
How to login only user that have specific ROLE

### ISSUE THREAD

**Issue by houssrad** [FriendsOfSymfony/FOSUserBundle#1893]
I am working to override Login_Check, I have to ROLE in my list of users, "ROLE_ADMIN" and "ROLE_SIMPLE", I have an identification ' s form, and I want to make form only for users that have "ROLE_SIMPLE".

Can I override the function of authentification??

**Comment by stof** [comment]
this does not make sense. roles are related to the authorization system of Symfony. Using them for the authentification layer is wrong.

**Comment by houss2040** [comment]
Thanks for the rapid answer.

**Comment by damienalexandre** [comment]
@houssrad Is this issue still open for a reason? How can we help you?

**Comment by stof** [comment]
Closing as this is not about FOSUserBundle anyway (this is about a bad understanding of the Security component itself)
