### ISSUE TITLE
Using third-person's emails? Registration, confirmation and resetting default logic

### ISSUE THREAD

**Issue by AlexanderMatveev** [FriendsOfSymfony/FOSUserBundle#1894]
1. Let's imagine if Jane registers an account using Jack's email.
2. After that, Jack wants to register, but he is getting "Email already registered" error.
3. Jack wants to reset password, but he can't, because it's possible to reset password using username only. But Jack doesn't know username Jane used while registering an account.
4. So Jack will never access a service with it's Email.
   This is a default logic of fresh-installed FOSUserBundle.

**Comment by dossantospat** [comment]
Which version of FOSUserBundle are you using ?

I just tried and used an email for password resetting. The field for password resetting says "username or email"

**Comment by damienalexandre** [comment]
Yes the reset password controller call `findUserByUsernameOrEmail` now, so this issue is not valid anymore.
