### ISSUE TITLE
User can login even if the account is not enabled.

### ISSUE THREAD

**Issue by JulienItard** [FriendsOfSymfony/FOSUserBundle#1895]
Hi,

I found a strange behavior and I wonder if it's a bug or a "normal" feature.
**The user must enable the account after register to login.**

If the user follows these steps:
- register
- does not enable the account with the link inside the mail
- request a password resetting
- reset his password
- after resetting the user is automaticly login and the account becomes enable.

I think that this is strange because the user enable is account without using the first email asking him to enable his account.

Is it a bug or not ?

*(sorry for my english)*

**Comment by EmmanuelVella** [comment]
See https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1413

**Comment by JulienItard** [comment]
@EmmanuelVella Ok thx !

**Comment by JulienItard** [comment]
You can close it

**Comment by xabbuh** [comment]
@JulienItard It's your own issue so you can close it yourself too. :)
