### ISSUE TITLE
set roles to user on  REGISTRATION_SUCCESS

### ISSUE THREAD

**Issue by l2a** [FriendsOfSymfony/FOSUserBundle#1896]
Hello

I have add an event listener on REGISTRATION_SUCCESSto set roles but it's not working for me

<?php

// src/Acme/DemoBundle/EventListener/RegistrationListener.php

namespace Utilisateur\UtilisateurBundle\EventListener;

use FOS\UserBundle\FOSUserEvents;
use FOS\UserBundle\Event\FormEvent;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;

/**
- Listener responsible for adding the default user role at registration
  */
  class RegistrationListener implements EventSubscriberInterface
  {
  public static function getSubscribedEvents()
  {
      return array(
          FOSUserEvents::REGISTRATION_SUCCESS => 'onRegistrationSuccess',
      );
  }
  
  public function onRegistrationSuccess(FormEvent $event)
  {$doctrine = $this->container->get('doctrine');
  $em = $doctrine->getManager();
  
   $user = $event->getUser();
  $user->addRole('ROLE_BLOGGER');
  
  $em->persist($user);
  $em->flush();
  
  }
  }

**Comment by xabbuh** [comment]
@l2a You should provide some more information if you want people to be able to give you feedback.

**Comment by Ingannatore** [comment]
Try subscribing to the `REGISTRATION_COMPLETED` event instead of the `REGISTRATION_SUCCESS` one.

**Comment by Ingannatore** [comment]
Remember that FOSUserBundle uses an entity manager for the user entity:

```php
/** @var $userManager \FOS\UserBundle\Model\UserManagerInterface */
$userManager = $this->get('fos_user.user_manager');
```

In your code, try to remove the lines

```php
$em->persist($user);
$em->flush();
```

After dispatching of the `REGISTRATION_SUCCESS` event, FOSUserBundle already executes an user update:

```php
$dispatcher->dispatch(FOSUserEvents::REGISTRATION_SUCCESS, $event);
$userManager->updateUser($user);
```
