### ISSUE TITLE
can't create new group in fosuserbundle

### ISSUE THREAD

**Issue by fcpauldiaz** [FriendsOfSymfony/FOSUserBundle#1897]
I followed the steps in the official docs to implement groups but when I go to localhost/8000/group/new and submit a group name i get "Unrecognized field: name". Any ideas?

**Comment by tmli3b3rm4n** [comment]
‎It's a Saturday night. 12am here. Go out!!!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         From: Pablo Díaz MárquezSent: Sunday, July 19, 2015 12:15 AMTo: FriendsOfSymfony/FOSUserBundleReply To: FriendsOfSymfony/FOSUserBundleSubject: [FOSUserBundle] can't create new group in fosuserbundle (#1897)I followed the steps in the official docs to implement groups but when I go to localhost/8000/group/new and submit a group name i get "Unrecognized field: name". Any ideas?

—Reply to this email directly or view it on GitHub.

**Comment by Ingannatore** [comment]
Could you please post your Group class definition?

**Comment by fcpauldiaz** [comment]
I managed to fix it by adding the name attribute to my class Group class but I think that is not the correct way. This class is using the group class from FosUserBundle so it should use the attribute name from that class.

<pre><code>
/**
 * @ORM\Entity
 * @ORM\Table(name="fos_group")
 */

class Group extends BaseGroup
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
     protected $id;

      /**
     * 
     * @ORM\Column(name="name",type="string",length=255)
     * 
     */
     protected $name;

</pre></code>

**Comment by stof** [comment]
Please paste the complete code. Your snippet is missing use statements, meaning we cannot know what BaseGroup is, and it is probably the issue.

And please also tell us which version of the bundle you are using

**Comment by whcass** [comment]
I had the same problem and fixed it by extending BaseGroup through:
```
use FOS\UserBundle\Entity\Group as BaseGroup;
```
rather than what the docs say which is to do it as:
```
use FOS\UserBundle\Model\Group as BaseGroup;
```
I'm not quite sure why the docs ask you to reference the Model Group class rather than the Entity?

**Comment by stof** [comment]
@whcass because you are reading the doc of FOSUserBundle 2 (master branch) while using FOSUserBundle 1.3. Please read the documentation for FOSUserBundle 1.3.
