### ISSUE TITLE
Work with symfony 2.7 version?

### ISSUE THREAD

**Issue by dannyalfonzo** [FriendsOfSymfony/FOSUserBundle#1899]
I not work with symfony since 2012, and the documentation says For Symfony 2.0.x

**Comment by Ingannatore** [comment]
I'm currently using FosUserBundle version `dev-master / 2.0.x-dev` with Symfony 2.7.* and everything is fine.

**Comment by dannyalfonzo** [comment]
with steps which you installed it?

**Comment by stof** [comment]
@dannyalfonzo where does it say that ?

**Comment by XWB** [comment]
Both 1.3 and 2.0 work with Symfony 2.7

**Comment by stof** [comment]
this does not answer the question about where we say it is for 2.0.x, so that we can change it (2.0.x versions of Symfony are actually unsupported since years)

**Comment by XWB** [comment]
He probably meant this reference:

`For Symfony 2.0.x, you need to use the 1.2.0 release of the bundle (or lower)`
`:2.0.x, please use the 1.2.x releases of the bundle`

In README.markdown and Resources/doc/index.rst
