### ISSUE TITLE
from_email should not has default values

### ISSUE THREAD

**Issue by LouTerrailloune** [FriendsOfSymfony/FOSUserBundle#1905]
In the config reference we have:

```
    from_email:
        address:        webmaster@example.com
        sender_name:    Admin
```

I think the default values should not be set (at least address), because nobody want to send mail from 'webmaster@example.com' and forgetting to set it may lead to unexpected errors (like email not sending because of the fake from address).

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2417
