### ISSUE TITLE
Install doc, Step 3: Create your User class -- no example for Doctine.

### ISSUE THREAD

**Issue by toddkaufmann** [FriendsOfSymfony/FOSUserBundle#1912]
At this section:
https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Resources/doc/index.rst#a-doctrine-orm-user-class

"... then your User class should ... look like this to start:"

then nothing!

MongoDB and CouchDB have examples, where is this one ?

**Comment by toddkaufmann** [comment]
Thinking the example might have existed in the past, 
I look at the history and see something about making .rst work on symfony.com.

When I search for FOSUserBundle, top link is the github repo.  
It has a link to http://friendsofsymfony.github.io/, which is useless as far as FOSUserBundle is concerned.

This is probably the core problem or a separate issue:

How does a user know to go to 
http://symfony.com/doc/master/bundles/FOSUserBundle/index.html ?

**Comment by stof** [comment]
@toddkaufmann links to the documentation in the readme have been updated to point to symfony.com

**Comment by toddkaufmann** [comment]
Excellent.

Looking a little closer at the raw .rst file, this appears to be problematic:
    `.. configuration-block::`
Everything from that to the close is not visible on github.
Top level `code-block` is okay.

Did it ever work?  This recent issue implies `code-block` stopped working recently:
https://github.com/github/markup/issues/106

I don't have time to follow this issue, I'll just read at symfony.com.  
Feel free to close, and thanks for updating the link to docs.

**Comment by sstok** [comment]
` .. configuration-block::` is a Symfony specific block that is provided an extension.
https://github.com/fabpot/sphinx-php/blob/master/sensio/sphinx/configurationblock.py

**Comment by toddkaufmann** [comment]
Thanks.  
How the docs get built was a mystery to me.  Now I know where to go at least.
