### ISSUE TITLE
Adding a new column to fos_user and getting the data

### ISSUE THREAD

**Issue by stevedeveloper1** [FriendsOfSymfony/FOSUserBundle#1914]
I have added a new column in user.php 

```php
    /**
   * @var boolean
   * @ORM\Column(type="string")
   */
  protected $plant;

  public function getplant() {
    return $this->plant;
  }
```

and updated my database schema, I can see the column in the user object using {{ dump(app.user) }} but it displays null.

```
    ["plant":protected]=>
  NULL
```

I can't find out why or the documentation to help me

**Comment by stof** [comment]
Well, which value do you have in the database for this field ?

**Comment by stevedeveloper1** [comment]
CORP

**Comment by stof** [comment]
hmm, have you updated your database schema manually or through Doctrine tools ? I'm wondering whether Doctrine is seeing your mapping properly

**Comment by stevedeveloper1** [comment]
I think you may have got it i did it manually, ill re do it and report

**Comment by stof** [comment]
Which format are you using to define the mapping of your bundle ?

**Comment by stevedeveloper1** [comment]
orm:
            auto_generate_proxy_classes: "%kernel.debug%"
            auto_mapping: true

**Comment by stof** [comment]
this is not the answer to my question at all. I have not asked for the way you are configuring DoctrineBundle but for the format (XML, YAML, annotations, ...) that you are using to define the mapping in your bundle

**Comment by stevedeveloper1** [comment]
Sorry Its Annotations,

If I update the schema I get the following error

[Doctrine\DBAL\Driver\PDOException]                                                                                                      
  SQLSTATE[HY000]: General error: 4901 General SQL Server error: Check messages from the SQL Server [4901] (severity 16) [ALTER TABLE fos  
  _user ADD plant NVARCHAR(255) NOT NULL]

**Comment by stof** [comment]
I suggest you to open an issue in the Doctrine DBAL issue tracker

**Comment by stevedeveloper1** [comment]
/**
     * @var string
     *
     * @ORM\Column(name="plant", type="string", length=30, nullable=true)
   */
    protected $plant;

Ive changed it to this and the schema has been updated.

I have altered the User.orm.xml in Resources/config/doctrine to 

<?xml version="1.0" encoding="utf-8"?>

    <doctrine-mapping xmlns="http://doctrine-project.org/schemas/orm/doctrine-mapping"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://doctrine-project.org/schemas/orm/doctrine-mapping     http://doctrine-project.org/schemas/orm/doctrine-mapping.xsd">  
    <entity name="f8creates\ImslBundle\Entity\User" table="fos_user">
        <id name="id" type="integer" column="id">
            <generator strategy="AUTO"/>
        </id>
        <field name="plant" column="plant" type="string" length="50" />
    </entity>
</doctrine-mapping>

   /**
     * @var string
     *
     * @ORM\Column(name="plant", type="string", length=30, nullable=true)
   */
    protected $plant;

I was told that I don't need the user.orm.xml if I am using annotations. 

Again thank you alot for your help

**Comment by stof** [comment]
the point is, as soon as you have one ``*.orm.xml`` file in your bundle, you **are** using XML, not annotations (and you don't need the annotations in this case)

**Comment by stevedeveloper1** [comment]
Thank you for your help
