### ISSUE TITLE
Passing doctrine entity manager to registration form type

### ISSUE THREAD

**Issue by georgesamy** [FriendsOfSymfony/FOSUserBundle#1915]
This is my overridden registration form type of FOSUserBundle

```php
    class RegistrationFormType extends BaseType
    {
      protected $em;
      function __construct(EntityManager $em)
       {
          $this->em = $em;
      }
   }
```

The following is a section in my also overriden registration controller of FOSUserBundle registration controller

```php
    $em = $this->getDoctrine()->getManager();
    /** @var $formFactory \FOS\UserBundle\Form\Factory\FactoryInterface */
    $formFactory = $this->get('fos_user.registration.form.factory');
    /** @var $userManager \FOS\UserBundle\Model\UserManagerInterface */
    $userManager = $this->get('fos_user.user_manager');
    /** @var $dispatcher \Symfony\Component\EventDispatcher\EventDispatcherInterface */
    $dispatcher = $this->get('event_dispatcher');
    $user = $userManager->createUser();
    $user->setEnabled(true);

    $event = new GetResponseUserEvent($user, $request);
    $dispatcher->dispatch(FOSUserEvents::REGISTRATION_INITIALIZE, $event);

    if (null !== $event->getResponse()) {
        return $event->getResponse();
    }

    $form = $formFactory->createForm(new RegistrationFormType($em));
    $form->setData($user);
```

I am getting the following error

```
Catchable Fatal Error: Argument 1 passed to Disty\SystemBundle\Form\RegistrationFormType::__construct() must be an instance of Doctrine\ORM\EntityManager, string given
```

I'm guessing that I am not correctly passing the $em to the form type, so my question is: How do I pass doctrine's entity manager to FOSUserBundle's form type?

**Comment by stof** [comment]
Can you paste the stack trace of the exception ? Without it, we are missing a very important piece of information to help you: the location of the error and what called this piece of code

**Comment by stof** [comment]
btw, there is no reason to overwrite the controller to change the form type being used (actually, there is almost no reason to overwrite controllers directly in FOSUserBundle 2)

**Comment by georgesamy** [comment]
My apologies for not knowing how to copy/paste the stack trace in a readable format. And I've overridden the registration controller because in my case I did not want users to login after a registration, so I had the following line commented out from the registerAction
    // Commented out to prevent registration from signing in a user
    // $dispatcher->dispatch(FOSUserEvents::REGISTRATION_COMPLETED, new FilterUserResponseEvent($user, $request, $response));
Though it isn't currently working well, that's an issue of another day.

The Stack Trace:

in src/Disty/SystemBundle/Form/RegistrationFormType.php at line 17   -
{
    protected $em;
    function __construct(EntityManager $em)    // This is line 17
    {
        $this->em = $em;
    }
at ErrorHandler ->handleError ('4096', 'Argument 1 passed to Disty\SystemBundle\Form\RegistrationFormType::__construct() must be an instance of Doctrine\ORM\EntityManager, string given, called in /Applications/MAMP/htdocs/disty/app/cache/dev/appDevDebugProjectContainer.php on line 628 and defined', '/Applications/MAMP/htdocs/disty/src/Disty/SystemBundle/Form/RegistrationFormType.php', '17', array()) 
in src/Disty/SystemBundle/Form/RegistrationFormType.php at line 17   -
{
    protected $em;
    function __construct(EntityManager $em)
    {
        $this->em = $em;
    }
at RegistrationFormType ->__construct ('Disty\SystemBundle\Entity\User', object(EntityManager)) 
in app/cache/dev/appDevDebugProjectContainer.php at line 628   -
     */
    protected function getDistyUser_Registration_Form_TypeService()
    {
        return $this->services['disty_user.registration.form.type'] = new \Disty\SystemBundle\Form\RegistrationFormType('Disty\\SystemBundle\\Entity\\User', $this->get('doctrine.orm.default_entity_manager'));
    }
    /**
at appDevDebugProjectContainer ->getDistyUser_Registration_Form_TypeService () 
in app/bootstrap.php.cache at line 2155   -
}
$this->loading[$id] = true;
try {
$service = $this->$method();
} catch (\Exception $e) {
unset($this->loading[$id]);
if (array_key_exists($id, $this->services)) {
at Container ->get ('disty_user.registration.form.type') 
in vendor/symfony/symfony/src/Symfony/Component/Form/Extension/DependencyInjection/DependencyInjectionExtension.php at line 44   -
            throw new InvalidArgumentException(sprintf('The field type "%s" is not registered with the service container.', $name));
        }
        $type = $this->container->get($this->typeServiceIds[$name]);
        if ($type->getName() !== $name) {
            throw new InvalidArgumentException(
at DependencyInjectionExtension ->getType ('disty_user_registration') 
in vendor/symfony/symfony/src/Symfony/Component/Form/FormRegistry.php at line 81   -
            foreach ($this->extensions as $extension) {
                if ($extension->hasType($name)) {
                    $type = $extension->getType($name);
                    break;
                }
            }
at FormRegistry ->getType ('disty_user_registration') 
in vendor/symfony/symfony/src/Symfony/Component/Form/FormFactory.php at line 82   -
        if ($type instanceof FormTypeInterface) {
            $type = $this->resolveType($type);
        } elseif (is_string($type)) {
            $type = $this->registry->getType($type);
        } elseif (!$type instanceof ResolvedFormTypeInterface) {
            throw new UnexpectedTypeException($type, 'string, Symfony\Component\Form\ResolvedFormTypeInterface or Symfony\Component\Form\FormTypeInterface');
        }
at FormFactory ->createNamedBuilder ('fos_user_registration_form', 'disty_user_registration', null, array('validation_groups' => array('Registration', 'Default'))) 
in vendor/symfony/symfony/src/Symfony/Component/Form/FormFactory.php at line 47   -
     */
    public function createNamed($name, $type = 'form', $data = null, array $options = array())
    {
        return $this->createNamedBuilder($name, $type, $data, $options)->getForm();
    }
    /**
at FormFactory ->createNamed ('fos_user_registration_form', 'disty_user_registration', null, array('validation_groups' => array('Registration', 'Default'))) 
in vendor/friendsofsymfony/user-bundle/Form/Factory/FormFactory.php at line 33   -
    public function createForm()
    {
        return $this->formFactory->createNamed($this->name, $this->type, null, array('validation_groups' => $this->validationGroups));
    }
}
 
at FormFactory ->createForm (object(RegistrationFormType)) 
in src/Disty/SystemBundle/Controller/UsermanagementController.php at line 73   -
            return $event->getResponse();
        }
        $em = $this->getDoctrine()->getManager();
        $form = $formFactory->createForm(new RegistrationFormType($em));
        $form->setData($user);
        $form->handleRequest($request);
at UsermanagementController ->newuserAction (object(Request)) 
at call_user_func_array (array(object(UsermanagementController), 'newuserAction'), array(object(Request))) 
in app/bootstrap.php.cache at line 3109   -
$this->dispatcher->dispatch(KernelEvents::CONTROLLER, $event);
$controller = $event->getController();
$arguments = $this->resolver->getArguments($request, $controller);
$response = call_user_func_array($controller, $arguments);
if (!$response instanceof Response) {
$event = new GetResponseForControllerResultEvent($this, $request, $type, $response);
$this->dispatcher->dispatch(KernelEvents::VIEW, $event);
at HttpKernel ->handleRaw (object(Request), '1') 
in app/bootstrap.php.cache at line 3071   -
{
$request->headers->set('X-Php-Ob-Level', ob_get_level());
try {
return $this->handleRaw($request, $type);
} catch (\Exception $e) {
if (false === $catch) {
$this->finishRequest($request, $type);
at HttpKernel ->handle (object(Request), '1', true) 
in app/bootstrap.php.cache at line 3222   -
$this->container->enterScope('request');
$this->container->set('request', $request,'request');
try {
$response = parent::handle($request, $type, $catch);
} catch (\Exception $e) {
$this->container->set('request', null,'request');
$this->container->leaveScope('request');
at ContainerAwareHttpKernel ->handle (object(Request), '1', true) 
in app/bootstrap.php.cache at line 2444   -
if (false === $this->booted) {
$this->boot();
}
return $this->getHttpKernel()->handle($request, $type, $catch);
}
protected function getHttpKernel()
{
at Kernel ->handle (object(Request)) 
in web/app_dev.php at line 28   -
$kernel = new AppKernel('dev', true);
$kernel->loadClassCache();
$request = Request::createFromGlobals();
$response = $kernel->handle($request);
$response->send();
$kernel->terminate($request, $response);

**Comment by stof** [comment]
Symfony error pages should have a text representation of the stack trace at the bottom (without all code snippets for instance)

**Comment by stof** [comment]
however, it looks like your ``disty_user.registration.form.type`` service passes the class name as first constructor argument, which is why things don't work

**Comment by georgesamy** [comment]
disty_user.profile.form.type:
            class: Disty\SystemBundle\Form\ProfileFormType
            arguments: [%fos_user.model.user.class%]
            tags:
                - { name: form.type, alias: disty_user_profile }

This is my service, any suggestions to how i can fix it to work in my favor?

**Comment by stof** [comment]
Well, you are defining the service passing the class name parameter as argument, while your constructor expects an EntityManager. Just fix your service definition.

Closign this issue as it is not a bug in FOSUserBundle but in your own service definition

**Comment by georgesamy** [comment]
@stof Yeah that got it fixed, thanks for your time.
