### ISSUE TITLE
UserManager flush method

### ISSUE THREAD

**Issue by aivus** [FriendsOfSymfony/FOSUserBundle#1916]
In the current implementation `flush` method can be called inside `updateUser`, but this is not optimal usage, when I want to update many users.

I want to do something like this:

``` php
foreach ($users as $user) {
    // some user actions
    $userManager->updateUser($user, false);
}
$userManager->flush();
```

What do you think about add `flush` method to `UserManager`?

**Comment by JHGitty** [comment]
This would be a BC break, right?

**Comment by Blackskyliner** [comment]
You just have to inject/get doctrine in your service and then replace your `$userManager` with `$doctrine->flush()` as it will be the same.

I think the userManager should not make encapsulated properties accessible, just to use the underlying ObjectManager/Registry/Doctrine as it's not the concern of this manager.

It would be no BC break, as no `flush()` method exists, but it would clutter the public interface of this class with unnecessary functions.

**Comment by XWB** [comment]
See above.
