### ISSUE TITLE
Logging in redirects to the login page with no errors

### ISSUE THREAD

**Issue by syyyn** [FriendsOfSymfony/FOSUserBundle#1921]
I currently have the Symfony 2.7 and the master FOSUserBundle installed. Everything is working fine except when I login with the correct user and pass it redirects me to the login page and nothing is shown about being logged on in debug.  Trying to go to the profile page redirects me to the login page.  There are no errors being thrown.  Configuration was followed on the symfony site linked in this repos.

**Comment by xabbuh** [comment]
Do you see anything related to this in your log?

**Comment by syyyn** [comment]
security.INFO: User has been authenticated successfully. {"username":"syn"} []    Is in the log but still seems to just redirect back to login after going to /profile.   Havn't used FOS since Symfony 2.3 wondering if something changed?

**Comment by syyyn** [comment]
Found my issue.  Staying up late coding takes a toll on you ;) Cleared my cookies found out PHPSESSID was in the list twice.
