### ISSUE TITLE
FILTER_VALIDATE_EMAIL is not 100% RFC-conform

### ISSUE THREAD

**Issue by JHGitty** [FriendsOfSymfony/FOSUserBundle#1923]
Validation of email addresses is really really really complex.

In FOSUserBundle the email is validated by the PHP filter FILTER_VALIDATE_EMAIL.
This is not a good idea because not all valid email addresses are working with it.

We should not validate email adresses **or** we should use an external bundle which is 100% conform to all RFCs (think about the performance, you should be able to deactivate it!).

**Comment by JHGitty** [comment]
Email validation is not recommended:
http://stackoverflow.com/questions/201323/using-a-regular-expression-to-validate-an-email-address/201378#201378

A valid regex for only one RFC (RFC 822) is crazy. And there are a lot more RFCs for valid email addresses. http://stackoverflow.com/a/13719870

**Comment by JHGitty** [comment]
This validation filter is currently used here:
https://github.com/FriendsOfSymfony/FOSUserBundle/blob/92d5624f2a29e74d8fd9d2a94d7ed7998a8c2809/Model/UserManager.php#L104

**Comment by XWB** [comment]
I think we should do it similar like Symfony: http://symfony.com/doc/current/reference/constraints/Email.html#strict

**Comment by JHGitty** [comment]
@XWB Sounds like a good idea.

**Comment by OskarStark** [comment]
any news on this, as its on the Roadmap for the next 2.0 stable :(

**Comment by JHGitty** [comment]
I think we should add an interface for email validation so users are able to add their own integration of email validation. By default we even could use FILTER_VALIDATE_EMAIL and write to the documentation that it is not 100% RFC-conform.

**Comment by JHGitty** [comment]
Important topic: https://github.com/symfony/symfony/issues/18177

**Comment by XWB** [comment]
This has been fixed in master.
