### ISSUE TITLE
[Question]: Is there any plan for ~2.7 symfony support in stable branches?

### ISSUE THREAD

**Issue by hanovruslan** [FriendsOfSymfony/FOSUserBundle#1924]

**Comment by toinouu** [comment]
+1

**Comment by stof** [comment]
Symfony 2.7 is supported in both the 1.3.x branch (thanks to the Symfony BC layers) and the 2.x branch (where we use the new APIs to avoid deprecation warnings).

**Comment by XWB** [comment]
You can now use the latest alpha version.

https://github.com/FriendsOfSymfony/FOSUserBundle/releases/tag/v2.0.0-alpha2

**Comment by stof** [comment]
use alpha3 instead of alpha2 though
