### ISSUE TITLE
Attribute overrides for usernameCanonical

### ISSUE THREAD

**Issue by PouleR** [FriendsOfSymfony/FOSUserBundle#1925]
Hi,

Since we're using utf8mb4 for our database and tables we need to change the length of the following fields:

- usernameCanonical
- username
- emailCanonical
- email

So I've created these attribute overrides in our XML file:

        <?xml version="1.0" encoding="utf-8"?>
    <doctrine-mapping xmlns="http://doctrine-project.org/schemas/orm/doctrine-mapping" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"     xsi:schemaLocation="http://doctrine-project.org/schemas/orm/doctrine-mapping http://doctrine-project.org/schemas/orm/doctrine-mapping.xsd"     xmlns:gedmo="http://gediminasm.org/schemas/orm/doctrine-extensions-mapping">
      <entity repository-class="Pler\UserBundle\Entity\UserRepository" name="Pler\UserBundle\Entity\User" table="fos_user">
        <attribute-overrides>
            <attribute-override name="usernameCanonical">
                <field column="username_canonical" length="191" unique="true" name="usernameCanonical" type="string" />
            </attribute-override>
            <attribute-override name="username">
                <field column="username" length="191" />
            </attribute-override>
            <attribute-override name="emailCanonical">
                <field column="email_canonical" length="191" />
            </attribute-override>
            <attribute-override name="email">
                <field column="email" length="191" />
            </attribute-override>
        </attribute-overrides>
        <options>
          <option name="charset">utf8mb4</option>
          <option name="collate">utf8mb4_general_ci</option>
        </options>

But when I try to generate the entities (for other bundles for e.g.) I get this error:

      [Doctrine\ORM\Mapping\MappingException]                                              
      Invalid field override named 'username' for class 'Pler\UserBundle\Entity\User'.

My current work-around is to remove the attribute-overrides from the XML file and generate the entities, however I'm searching for a real solution. How can I fix this error?

**Comment by stof** [comment]
this looks like a bug in Doctrine when the entity generator is used (they use a special way to load mapping in this case to deal with the fact that classes may not exist yet, and this might impact this cases).
Please open an issue in the [issue tracker of the Doctrine ORM](http://www.doctrine-project.org/jira/projects/DDC) instead, as it is not an issue in FOSUserBundle

**Comment by xabbuh** [comment]
@PouleR By the way, you are missing the `type` attribute for `username`, `emailCanonical`, and `email`.

**Comment by PouleR** [comment]
@xabbuh Thank you, I also changed that later on but it didn't affect the error. I've created an issue in the Doctrine ORM Jira database.

**Comment by xabbuh** [comment]
@PouleR Do you mind linking the issue here?

**Comment by PouleR** [comment]
http://www.doctrine-project.org/jira/browse/DDC-3880

**Comment by manufourc** [comment]
It is not a bug in Doctrine :
Attribute Overriding "Could be used by an entity that extends a **mapped superclass** to override a field mapping defined by the **mapped superclass**."
But FOS\UserBundle\Model\User is NOT declared (annotations) as a doctrine mapped superclass : https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Model/User.php

**Comment by karasq** [comment]
@manufourc doctrine mapping is here in XML https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Resources/config/doctrine-mapping/User.orm.xml and this is supperclass mapping.

and this seems to be doctrine bug:
https://github.com/doctrine/doctrine2/issues/3885
