### ISSUE TITLE
[This is not an issue] Logical login diagram

### ISSUE THREAD

**Issue by BentCoder** [FriendsOfSymfony/FOSUserBundle#1926]
Hi,

Is there a kind of diagram ([something like these](https://www.google.co.uk/search?q=FOSUserBundle+login+diagram&espv=2&biw=1536&bih=948&source=lnms&tbm=isch&sa=X&ved=0CAYQ_AUoAWoVChMI-MqFuKjGxwIVZBbbCh2wsAM-#tbm=isch&q=login+diagram)) that represents/explains just login process cos I'll need to replicate/login without using the actual login form. If there is nothing that obviously I'll have to dig in to the code.

Thanks

**Comment by stof** [comment]
FOSUserBundle is not responsible for the login at all. It does not provide authentication features. It provides user management features. Authentication is handled by the Symfony Security component.

**Comment by BentCoder** [comment]
That you. I'll then study [The Security Component](http://symfony.com/doc/current/components/security/introduction.html)

**Comment by sstok** [comment]
@BentCoder maybe this what you are looking for :)
https://github.com/symfony/symfony/pull/14673

**Comment by BentCoder** [comment]
@sstok I've read it but just make it clear, will it give me a chance to login by making an API call to login?
