### ISSUE TITLE
Using  FOSUserBundle with SonataAdmin together and getting No entity manager defined for class ....

### ISSUE THREAD

**Issue by dsteplight** [FriendsOfSymfony/FOSUserBundle#1929]
When I connect FOSUserBundle with SonataAdmin bundle I'm seeing this error when I click on the link_add or link_list links for my content. These links were working properly before I added the FOSUserBundle. Is there a config change that I'm missing? I looked over the documentation over and over , but where should the entity manager mapping be set? I tried in the app/confg/config.yml file. Here is a link to the gist https://gist.github.com/dsteplight/104b58c39be61695d0e1 .

**Comment by xabbuh** [comment]
In your DoctrineBundle config, `auto_mapping` is disabled and you only have a configured entity manager for the ApplicationSonataUserBundle, SonataUserBundle and FOSUserBundle, but no config for your SympalTorneioBundle.

**Comment by dsteplight** [comment]
@xabbuh   I started from scratch in a new project but I had to get rid of the other Bundle mappings and just turn on auto_mapping as stated here.

https://github.com/sonata-project/SonataAdminBundle/issues/3204#issuecomment-136288775
