### ISSUE TITLE
Redirect to previous page after login

### ISSUE THREAD

**Issue by JHGitty** [FriendsOfSymfony/FOSUserBundle#1930]
I send somebody a link which is behind a login with FOSUserBundle.
After the login the user should not be redirected to the default target page. Instead the user should be redirected to the url which I sent him.

How can I do it?

**Comment by stof** [comment]
The login is not handled by FOSUserBundle at all, but by the Symfony security component. this bundle is about providing user management only.
Read the Symfony doc about the Security component for that
