### ISSUE TITLE
[question] There is any WIP or intention of remove the coupling o the FOS\UserBundle\Model\User from the Doctrine framework?

### ISSUE THREAD

**Issue by bitgandtter** [FriendsOfSymfony/FOSUserBundle#1942]
There is any WIP or intention of remove the coupling o the FOS\UserBundle\Model\User from the Doctrine framework? 

The class use the Collection and ArrayCollection classes. When we extends from it we couple the code to doctrine and that its not a good idea, even if decide to use doctrine at all cost; its better to have the less coupling we can.

My proposal is to drop that dependency and use simple array for the work. At this point i dont know for sure if that can be done since maybe the Collection and the ArrayCollection classes are needed at some point, but if that its the case, we can drop it from this class and instruct the developer to implement the getGroups method on his end class and then introduce the coupling, that will gave the developer the flexibility to design where to introduce the coupling and not to force it from the start.

If this idea its welcome by the team and there its no plan for making it, i can work on it and then create a PR.

Thanks

**Comment by stof** [comment]
doctrine/collections is a standalone package. So it is not worth the extra complexity IMO
