### ISSUE TITLE
Protect /admin with an extra password

### ISSUE THREAD

**Issue by Mondane** [FriendsOfSymfony/FOSUserBundle#1943]
I have users that are allowed to see the normal parts of the website, eg. /newsitems and those that are also allowed to see the admin, eg. /admin/newsitems .

When the latter goes to /newsitems and logs in, that will just log him in into the normal part. When he then goes to /admin/newsitems, I would like to have the system confirm his identity by providing his password again. 

Is this possible with FOSUserBundle? 

NB This kind of flow is also implemented in JIRA , https://www.atlassian.com/software/jira .

**Comment by stof** [comment]
FOSUserBundle has nothing to do with this. This bundle is about managing users, not about authentication and authorization. Look at the documentation of the Symfony security system instead
