### ISSUE TITLE
Undefined variable: test

### ISSUE THREAD

**Issue by chdez** [FriendsOfSymfony/FOSUserBundle#1945]
Route: /app_dev.php/register/
Error: An exception has been thrown during the compilation of a template ("Notice: Undefined variable: test") in "FOSUserBundle:Registration:register_content.html.twig"."

Symfony 2.7.4

Any Solution?

**Comment by stof** [comment]
This bug is not in FOSUserBundle but in Twig (look at the location of the notice) and it has already been fixed. Just update Twig to the latest version.

**Comment by chdez** [comment]
Thanks!
Update twig from v1.21.1 to v1.21.2.
