### ISSUE TITLE
FOSUserBundle 2.0 road map

### ISSUE THREAD

**Issue by XWB** [FriendsOfSymfony/FOSUserBundle#1951]
We should work towards a final 2.0 release.

**Alpha**
This bundle remains in alpha phase as long as we keep introducing BC breaks. Is there anything you want to see changed before we move on to a beta candidate?

**Beta**
No further BC breaks and focus on new features and testing. What kind of new features or improvements do you want to see?

Thoughts?

**Comment by stof** [comment]
@XWB there are a few things I want to do yes. Unfortunately I got no time on weekends since some time (and the few time I got was focused on symfony itself).

If you want to contribute actively on the bundle, I suggest we plan a time to chat about the bundle so that I can tell you things I have in mind.

**Comment by JHGitty** [comment]
Any updates?

**Comment by geekdevs** [comment]
@stof I am interested to contribute and push 2.0 release (which is in alpha 3 since September 15).
Could you please create general list priorities/general thoughts on the roadmap so that everyone would see? And then if needed, I would be happy to discuss on chat the details.

**Comment by JHGitty** [comment]
@stof You may use the milestone feature in GitHub to mark issues which should be done for a beta release.

**Comment by acrobat** [comment]
I would be great to have a todo list for a 2.0-beta release. So we can help and focus on those issues. As sonata is also waiting for a stable release to have symfony 2.8/3.0 support in their bundles
