### ISSUE TITLE
Security config Error

### ISSUE THREAD

**Issue by andresetevejob** [FriendsOfSymfony/FOSUserBundle#1953]
Hi All, I have this error with my security.yml
this my file : 
# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    # http://symfony.com/doc/current/book/security.html#hierarchical-roles
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle: 
            id: fos_user.user_provider.username_email
    
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        
        main_login:
            context: primary_auth
            pattern:            ^/survey$
            anonymous: false
            
        main:
            pattern:  ^/login$
            anonymous: true
            form_login:
                provider:       fos_userbundle
                login_path:     fos_user_security_login
                use_forward:    true
                use_referer:    true
                check_path:     fos_user_security_check
                #failure_path:   null
                default_target_path: fos_user_profile_show
            logout:
                path: fos_user_security_logout
                target: gensoft_survey_home
            anonymous:  true
            
    access_control:
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY  }
        - { path: ^/profile, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/inscription, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/members, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/survey$, roles: ROLE_ADMIN }

this the error : 
![erreursecurityyml](https://cloud.githubusercontent.com/assets/3342068/9884438/97f50274-5bd7-11e5-9cd3-3e62b2722e9f.jpg)

**Comment by stof** [comment]
What is the goal of ``main_login`` ?

**Comment by andresetevejob** [comment]
I want to use main_login to secure the pattern : ^/survey

**Comment by stof** [comment]
Well, the issue is not related to FOSUserBundle. You are creating a ``main_login`` firewall without enabling an authentication listener (there is no way to authenticate in your firewall), which is invalid in Symfony. There is nothing involving FOSUserBundle here

**Comment by andresetevejob** [comment]
thanks you for your help
