### ISSUE TITLE
fos_user_bundle error

### ISSUE THREAD

**Issue by andresetevejob** [FriendsOfSymfony/FOSUserBundle#1954]
Hi All,
I have this error when I want to authenticate a member of my application.
"Attempted to call method "getRoles" on class "Closure"

**Comment by stof** [comment]
Please provide the stack trace of the error

**Comment by andresetevejob** [comment]
Ok.my error is resolve but i don't how it's possible.But i can explain the context which have generate this error.I have two entity User and Groups that inherit of the entity of fosuserbundle.the relationship between my two entities is ManyToOne (One Group have Many Users.And One User is in One Group)
And i have create the user manually and the group i have created directly in phpmyadmin.when i have make an authentication for the user, symfony have generated this error.I have remove my cache folder in the app and it'works
