### ISSUE TITLE
Expired Credentials At: ability to set to NULL

### ISSUE THREAD

**Issue by bertoost** [FriendsOfSymfony/FOSUserBundle#1958]
Currently I am implementing Credentials Expired feature. Want to use this feature when someone has requested a new password via the administrator. There will be a password generated and send to the client by email.

When they login I catch the "CredentialsExpiredException" and redirect user to a controller method that will generate a reset token, and force them to change the password first.

After changing their password, the **Credentials Expired** is set back to false (0) but I cannot set **Credentials Expired At** back to NULL, because the set method requires me to pass a DateTime object.

```
/**
 * @param \DateTime $date
 *
 * @return User
 */
public function setCredentialsExpireAt(\DateTime $date)
{
    $this->credentialsExpireAt = $date;

    return $this;
}
```

For now I have added a workaround..
Override the method in my User entity and pass a DateTime in the future, check Timestamp() with time() and set to NULL if in the future.
But it should be possible to set NULL since the database field allows it too.

Thanks!

**Comment by XWB** [comment]
These fields have been removed.
