### ISSUE TITLE
TwigSwiftMailer templates don't have access to twig global vars ?

### ISSUE THREAD

**Issue by nicolaskern** [FriendsOfSymfony/FOSUserBundle#1960]
Hi,

I try to access a global Twig variable from a template called with this line : $this->get('fos_user.mailer')->sendResettingEmailMessage($user);

Is it normal? Twig is injected in this service, and the twig method loadTemplate is used, does this inject the global twig vars as well ?

Best,
Nicolas

**Comment by damienalexandre** [comment]
I can't reproduce this issue, can you provide more informations?

- `composer info` output
- email template used
- fos_user configuration

Thanks

**Comment by stof** [comment]
This is fixed in 2.0
