### ISSUE TITLE
Error: Cannot instantiate abstract class FOS\UserBundle\Model\User

### ISSUE THREAD

**Issue by castwayalldc** [FriendsOfSymfony/FOSUserBundle#1962]
Hello guys,

I'm gettin this error "Error: Cannot instantiate abstract class FOS\UserBundle\Model\User" when im trying to access the route "/register" or while trying to run the command "app/console fos:user:create testuser test@example.com p@ssword", i haven't touched anything but it just stopped working.

My configuration is the following:

config.yml:

``` yaml
fos_user:
    db_driver: orm 
    firewall_name: main
    user_class: AppBundle\Entity\User
```

My user entity:

``` php
namespace AppBundle\Entity;

use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity
 * @ORM\Table(name="mo_user")
 */
class User extends BaseUser
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $lastName;


    public function __construct() {
        parent::__construct();
    }
}
```

I actually haven't touched any other configuration for the bundle, only if i remove the abstract declaration it tries to work but then i get a new error:

```
"The given entity of type 'FOS\UserBundle\Model\User' (testuser) has no iden  
  tity/no id values set. It cannot be added to the identity map."
```

**Comment by stof** [comment]
Can you paste the stack trace of the exception to see which place is trying to instantiate the abstract class ? this does not make sense to me.

**Comment by castwayalldc** [comment]
![capture](https://cloud.githubusercontent.com/assets/9592208/9997851/fa22bad8-6053-11e5-8e0d-02f28c561c2b.PNG)

**Comment by damienalexandre** [comment]
Which version were you using? It looks like your `user_class` parameter is not taken into account.

Feel free to close if you fixed this issue.
