### ISSUE TITLE
Error when access to register form in FOSUserBundle

### ISSUE THREAD

**Issue by mmoalla** [FriendsOfSymfony/FOSUserBundle#1964]
Hello, I use FOSUserBundle for my project and I made the installation and the configuration as indicated in the documentation but when i try to access to the registration form this error return every time 

<b>An exception has been thrown during the compilation of a template ("Notice: Undefined variable: test") in "FOSUserBundle:Registration:register_content.html.twig".<b>

**Comment by mmoalla** [comment]
![error](https://cloud.githubusercontent.com/assets/6381809/10084603/461c958a-62fc-11e5-8a27-8d20c5fe90d0.PNG)
![st1](https://cloud.githubusercontent.com/assets/6381809/10084604/461e46fa-62fc-11e5-8a1e-39e367a77d92.PNG)
![st2](https://cloud.githubusercontent.com/assets/6381809/10084605/462a38fc-62fc-11e5-861a-9aa26e10f5e6.PNG)

**Comment by xabbuh** [comment]
This was a bug in Twig. Just update the Twig package in your project and the error should be gone.

**Comment by mmoalla** [comment]
thank you for your help
