### ISSUE TITLE
Override FOS user login form

### ISSUE THREAD

**Issue by qweluke** [FriendsOfSymfony/FOSUserBundle#1965]
Hi,

I have overridden registration form and add new field to it.
https://symfony.com/doc/master/bundles/FOSUserBundle/overriding_forms.html
Now I want to use that field in login form, so user need to provide 3 fields, `company name`, `username`, `password`.
How I can do this?

**Comment by stof** [comment]
You cannot, because the login form is handled by the Symfony form_login system, and it does not support a `company name` field. You would need to implement your own authentication provider for that

**Comment by maalicki** [comment]
OK, how to check if user entered correct password?
FOSUserBundle use salt for password encryption..
Can I use `fos_user.user_manager` to check that and login a user?

**Comment by maalicki** [comment]
Thank you
