### ISSUE TITLE
How to override orm storage-validation in FOS 2.x

### ISSUE THREAD

**Issue by qweluke** [FriendsOfSymfony/FOSUserBundle#1966]
OK, I want to override `storage-validation` and remove that key

```
        <constraint name="Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity">
            <option name="fields">usernameCanonical</option>
            <option name="errorPath">username</option>
            <option name="message">fos_user.username.already_used</option>
            <option name="groups">
                <value>Registration</value>
                <value>Profile</value>
            </option>
        </constraint>
```
Where should I put file from
`/vendor/friendsofsymfony/user-bundle/Resources/config/storage-validation/orm.xml`

**Comment by maalicki** [comment]
OK, I want to override `storage-validation` and remove that key

```
        <constraint name="Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity">
            <option name="fields">usernameCanonical, company</option>
            <option name="errorPath">username</option>
            <option name="message">fos_user.username.already_used</option>
            <option name="groups">
                <value>Registration</value>
                <value>Profile</value>
            </option>
        </constraint>
```
Where should I put file from
`/vendor/friendsofsymfony/user-bundle/Resources/config/storage-validation/orm.xml`

Location
`/app/Resources/FOSUserBundle/Resources/config/storage-validation/orm.xml` seems not working

**Comment by stof** [comment]
The username is the identifier used in the Security component of Symfony. Symfony requires that it is an identifier. This means it must be globally unique. Otherwise, you will break the security system

**Comment by maalicki** [comment]
@stof I want it to be unique but in that way:

```
 * @UniqueEntity(
 *     fields={"organization", "usernameCanonical"},
 *     errorPath="username",
 *     message="This username is already in use on that company."
 * )
```
I forgot to mention about this ;)

**Comment by stof** [comment]
@maalicki this would still break the requirement of the Security component. Uniqueness of ``(organization, usernameCanonical)`` does not guarantee uniqueness of the username, and so makes the username unusable as identifier, thus providing a broken implementation of UserInterface.

**Comment by maalicki** [comment]
@stof Even if for logon form user must provide correct `organization` to be successfully logged in?
How to provide then unique username only within organization?
I need to get something like this:
User creates accout and organization and becomes admin of that organization.
Then he can create new users of that organization (ex user with username `abcd`)

If another user create his own organization he should also create new user in that organization with username `abcd`.

**Comment by stof** [comment]
@maalicki the UserInterface of the component **requires** that the value returned by ``getUsername`` is an identifier.
If it is not the case, it will break things (the remember-me feature and the ACL system for sure, and maybe other parts too).

Your concept of username is different from the Symfony concept, so you need to find another name for it (at least in the code).

**Comment by maalicki** [comment]
OK, Thank you for your help.
