### ISSUE TITLE
Override Assertion for username

### ISSUE THREAD

**Issue by taqiofficial** [FriendsOfSymfony/FOSUserBundle#1975]
I need to user my people to login via NIC. So i am using username field as nic. it works for me. but the issue is i need to put custom assertion on username for now the default limit is 255. i have to set it to 15.

I have tried this, but not working...

```
* @ORM\HasLifecycleCallbacks()
 *  * @ORM\AttributeOverrides({
 *     @ORM\AttributeOverride(name="username",
 *          column=@ORM\Column(
 *              nullable = false,
 *              unique   = true,
 *              length   = 15
 *          )
 *      ),
 *     @ORM\AttributeOverride(name="usernameCanonical",
 *          column=@ORM\Column(
 *              name = "username_canonical",
 *              nullable = false,
 *              unique   = true,
 *              length   = 15
 *          )
 *      ),
 * })
```

**Comment by damienalexandre** [comment]
`AttributeOverride` only works for doctrine mapping, not validation rules. As there is no way to extend validation rules in a Symfony Bundle, you need to follow those steps: http://symfony.com/doc/current/bundles/override.html#validation-metadata
