### ISSUE TITLE
confirmAction() does not start session

### ISSUE THREAD

**Issue by tottt** [FriendsOfSymfony/FOSUserBundle#1976]
When a user registers and confirmation is enabled the registrationController returns a RedirectResponse. Problem is, that if there is no session cookie set already (eg. Optin-Link opens in a different client than the user used to register) that RedirectResponse does not set a cookie to start a session. Therefore user is not logged in when he reaches confirmedAction().
Fix could be to explicitly start the session after authenticateUser() in confirmAction() 

$session = $this->container->get('session');
$session->start();

**Comment by XWB** [comment]
In Symfony, a session starts on demand.
