### ISSUE TITLE
Login with "fosUser" and "prod.log" is temporary locked

### ISSUE THREAD

**Issue by Zamoud** [FriendsOfSymfony/FOSUserBundle#1981]
configuration
symfony 2.4

bundles
- fosUserBundle
- HWIOAuthBundle

In the beginning, all work fine
but, every 5 days, login with "fosUser" is locked for 1 day or less ... 
he return " login or password incorrect  ..."
( HWIOAuthBundle still work when "fosUser" is locked !!!! )

After clear cache the problem persists ...
the project create prod directory and his sub ( directory / files ) ...
but the logs directory is empty !!!

It's a weird problem  :)
Sorry for my bad english

**Comment by damienalexandre** [comment]
What do you mean by "locked"? We need more information to be able to help you out.

**Comment by XWB** [comment]
Closing this issue as there is no further information available.
