### ISSUE TITLE
`findBy` with object as parameter?

### ISSUE THREAD

**Issue by yellowmamba** [FriendsOfSymfony/FOSUserBundle#1982]
Hi folks,

We have a weird problem here when trying to grab an object with its many-to-one association. Code sample as follows:

``` php
class Order
{
    ...

    /**
     * @ORM\ManyToOne(
     *     targetEntity="Customer"
     * )
     * @ORM\JoinColumn(
     *     name="customer",
     *     referencedColumnName="id",
     *     nullable=true
     * )
     */
    protected $customer;

    ...
}
```

When I do `$em->getRepository('MyBundle:Order')->findByCustomer($customer)`, it throws `undefined offset: 12` error on some objects, but it works on other objects, which really confuses me. I tracked down the error was thrown from the `FOS\UserBundle\Model\User::unserialize()` method, but I can't figure out what exactly goes wrong.

Any advice would be greatly appreciated.

Michael

**Comment by damienalexandre** [comment]
That's strange; could you provide a more complete stack trace or code sample to allow contributors to reproduce your error?

**Comment by XWB** [comment]
Closing this issue as there is no further information available.
