### ISSUE TITLE
Redirect to register/login when trying to submit a form 

### ISSUE THREAD

**Issue by armilleiwilliam** [FriendsOfSymfony/FOSUserBundle#1984]
I realized an auctions website. Each user can submit the amount of money he is  willing to pay, but it must happen only if he is logged In. 
Put it simply, I'd like to redirect the user to the login page when he tries to insert the amount of money in the form when he is not  logged In already; then being able to register if he had not done it before, and after having logged In or registered to redirect him back to the auction page or even save the price he tried to insert before he was redirected to the login page. I think I may find out how to redirect him to the login page after trying to submit a price without being registered, but I don't know how to redirect him to the auction page he was trying to submit the price once he is logged In. I hope I could explain myself well.

**Comment by armilleiwilliam** [comment]
Ok, I've found a solution already, but I have a question. Is it possible to have a path like the following?
access_control:
         - { path: ^/bidsinfo/createbid/{id}, role: ROLE_USER }

Because I need to pass the  Id of the auction product in the path, I mean, I want symfony2 any time it parses an address format like the following 
"bidsinfo/createdid/se42343-s4sfsf-werre-2343"
where the middle value is the Id product, to redirect to login. And after login to redirect to that address again. It seems that fosuserbundle doesn't parse that kind of route format. I can redirect to login if the address is just "bidsinfo/createdid/", but it  doesn't if I add the Id#. Do you have any idea if it's possible somehow? Thanks.

**Comment by damienalexandre** [comment]
That's not related to FOSUserBundle but to Symfony security. The access_control rules are regexp: https://symfony.com/doc/2.7/security/access_control.html#main

So you should use something like:

```
access_control:
  - { path: '^/bidsinfo/createbid/[0-9]+', role: ROLE_USER }
```
