### ISSUE TITLE
Could not load type "Symfony\Component\Form\Extension\Core\Type\TextType"

### ISSUE THREAD

**Issue by greg-man** [FriendsOfSymfony/FOSUserBundle#1985]
Hi,

after composer update my app throws the above named execption when loading register route of FOS UserBundle. Issue is caused by class FOS\UserBundle\Form\Type\RegistrationFormType. Second  parameter of $builder->add(username, ... is null. If I change it to 'text' everything seems to be fine.

Is this a bug or a conflict in some of the packages? I'm using Symfony 2.6.11 and latest FOS UserBundle.

Kind regards
Greg

**Comment by xabbuh** [comment]
Can you paste the complete stack trace?

**Comment by greg-man** [comment]
Sure here it is:


Stack Trace

    in vendor/symfony/symfony/src/Symfony/Component/Form/FormRegistry.php at line 87  +
    at FormRegistry ->getType ('Symfony\Component\Form\Extension\Core\Type\TextType')
    in vendor/symfony/symfony/src/Symfony/Component/Form/FormFactory.php at line 82  +
    at FormFactory ->createNamedBuilder ('username', 'Symfony\Component\Form\Extension\Core\Type\TextType', null, array('required' => true, 'attr' => array('maxlength' => '255', 'pattern' => '.{2,}'), 'label' => 'form.username', 'translation_domain' => 'FOSUserBundle'))
    in vendor/symfony/symfony/src/Symfony/Component/Form/FormFactory.php at line 132  +
    at FormFactory ->createBuilderForProperty ('AppBundle\Entity\User', 'username', null, array('label' => 'form.username', 'translation_domain' => 'FOSUserBundle'))
    in vendor/symfony/symfony/src/Symfony/Component/Form/FormBuilder.php at line 109  +
    at FormBuilder ->create ('username', null, array('label' => 'form.username', 'translation_domain' => 'FOSUserBundle'))
    in vendor/symfony/symfony/src/Symfony/Component/Form/FormBuilder.php at line 267  +
    at FormBuilder ->resolveChildren ()
    in vendor/symfony/symfony/src/Symfony/Component/Form/FormBuilder.php at line 215  +
    at FormBuilder ->getForm ()
    in vendor/symfony/symfony/src/Symfony/Component/Form/FormFactory.php at line 47  +
    at FormFactory ->createNamed ('customer_registration_form', object(RegistrationCustomerFormType), null, array('validation_groups' => array('strong_password_registration')))
    in vendor/pugx/multi-user-bundle/PUGX/MultiUserBundle/Form/FormFactory.php at line 65  +
    at FormFactory ->createForm ()
    in vendor/friendsofsymfony/user-bundle/Controller/RegistrationController.php at line 52  +
    at RegistrationController ->registerAction (object(Request))
    at call_user_func_array (array(object(RegistrationController), 'registerAction'), array(object(Request)))
    in app/bootstrap.php.cache at line 3088  +
    at HttpKernel ->handleRaw (object(Request), '1')
    in app/bootstrap.php.cache at line 3050  +
    at HttpKernel ->handle (object(Request), '1', true)
    in app/bootstrap.php.cache at line 3199  +
    at ContainerAwareHttpKernel ->handle (object(Request), '1', true)
    in app/bootstrap.php.cache at line 2440  +
    at Kernel ->handle (object(Request))
    in web/app_dev.php at line 28  +

**Comment by kakoma** [comment]
I've run into this too. Using Symfony 2.6.11

**Comment by stof** [comment]
Can you show the output of ``composer show -i |grep symfony`` (if you are on windows, filter the list by hand instead of using ``grep``) ? this error is really weird as it looks like you are running the 2.8 version of some components, while running the 2.6 version of others

**Comment by kakoma** [comment]
Interestingly, it has worked after I switched to the 'normal' field names i.e. text, choice, etc. Here's the output:

```
$  composer show -i |grep symfony
friendsofsymfony/jsrouting-bundle          1.5.4   A pretty nice way to expose your Symfony2 routing to client app...
friendsofsymfony/rest-bundle               1.7.2   This Bundle provides various tools to rapidly develop RESTful A...
friendsofsymfony/user-bundle               v1.3.6  Symfony FOSUserBundle
symfony-cmf/block-bundle                   1.2.2   Symfony CMF Block Bundle
symfony-cmf/content-bundle                 1.2.0   Symfony CMF Content Bundle
symfony-cmf/core-bundle                    1.2.0   Symfony CMF Core Bundle
symfony-cmf/create-bundle                  1.2.2   Symfony Bundle for createphp and create.js. The easiest way to ...
symfony-cmf/media-bundle                   1.2.1   Symfony CMF Media Bundle
symfony-cmf/menu-bundle                    1.2.0   Symfony CMF Menu Bundle
symfony-cmf/routing                        1.3.0   Extends the Symfony2 routing component for dynamic routes and c...
symfony-cmf/routing-bundle                 1.3.5   Symfony RoutingBundle
symfony-cmf/simple-cms-bundle              1.2.0   A simple CMS bundle based on the Symfony CMF
symfony-cmf/symfony-cmf                    1.2.0   Symfony Content Management Framework
symfony-cmf/tree-browser-bundle            1.1.0   Symfony CMF Tree Browser Bundle
symfony/assetic-bundle                     v2.7.0  Integrates Assetic into Symfony2
symfony/monolog-bundle                     2.8.1   Symfony MonologBundle
symfony/swiftmailer-bundle                 v2.3.8  Symfony SwiftmailerBundle
symfony/symfony                            v2.6.11 The Symfony PHP framework
```

**Comment by xabbuh** [comment]
Well, the error is triggered when building the `customer_registration_form` form. Did you define this in your own application?

**Comment by kakoma** [comment]
Nope. Got it after defining a custom form with just one field. 
```
$this->createFormBuilder()
                   ->add('name', 'Symfony\Component\Form\Extension\Core\Type\ChoiceType', array(
                    'choices' => array(
                        'Maybe' => null,
                        'Yes' => true,
                        'No' => false,
                    ), 'choices_as_values' => true,))
                    ->getForm()->createView();
//(as per this tutorial http://symfony.com/doc/current/book/forms.html#building-the-form)
```
That's based on [this tutorial] (http://symfony.com/doc/current/book/forms.html#building-the-form)
Interestingly, merely using the 'normal' field types works. This works:
```
$this->createFormBuilder()
                   ->add('select_issue', 'choice', array(
                    'choices' => array(
                        'Maybe' => 'null',
                        'Yes' => 'true',
                        'No' => 'false',
                    )))
                    ->getForm()->createView();
```
I propose that the tutorial is updated to reflect this instead.

**Comment by xabbuh** [comment]
Well, when you use Symfony 2.6, you should read the documentation for that version. The new way to reference form types was introduced in 2.8 and the docs you refer to are for 3.0.

**Comment by kakoma** [comment]
Ah ok. Cool. Thanks

On Wed, Dec 2, 2015 at 9:58 AM, Christian Flothmann <
notifications@github.com> wrote:

> Well, when you use Symfony 2.6, you should read the documentation for that
> version. The new way to reference form types was introduced in 2.8 and the
> docs you refer to are for 3.0.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1985#issuecomment-161201861>
> .
>



-- 
http://kakoma.ug
http:somanystories.ug <http://somanystories.ug>

**Comment by xabbuh** [comment]
@kakoma Can you then close here please? :)

By the way, Symfony 2.6 does not receive bug fixes anymore and it will only receive security patches until January 2016.

**Comment by kakoma** [comment]
Thanks for that @xabbuh . I don't seem to have permission to close this; I didn't open it initially though

**Comment by xabbuh** [comment]
@kakoma Oh indeed, and the stack trace I was referring to actually wasn't yours too. :)

**Comment by stof** [comment]
@greg-man can you provide the info I asked previously ?

**Comment by greg-man** [comment]
@stof Sorry for my late reply. 
Seems that the error wasn't related to FOS Userbundle and I indeed managed to mix the FormTypeGuesser of Symfony 2.8 into Symfony 2.6 (don't know how ...). After deleting the symfony vendor folder, clearing composer cache and reinstalling symfony 2.6 today, everything is working now.

Thanx for your help
Greg
