### ISSUE TITLE
Will FOSUserBundle be updated to work with the new Guard component (new in Symfony 2.8)?

### ISSUE THREAD

**Issue by rparsi** [FriendsOfSymfony/FOSUserBundle#1988]
https://symfony.com/blog/new-in-symfony-2-8-guard-authentication-component
http://symfony.com/components/Guard

**Comment by stof** [comment]
FOSUserBundle only provides a user provider. so it has strictly nothing to change to be usable with the Guard component (which also relies on the user provider)
