### ISSUE TITLE
Authentication Token  Always Null - listener called BEFORE the security firewall

### ISSUE THREAD

**Issue by houssrad** [FriendsOfSymfony/FOSUserBundle#1989]
I want to customize my errors pages : 404, 403 & 500 Code Error . 

I want to show Menu in the page error according to connected user, But i cant get current user because the listener of exeption if called BEFORE the security firewall. 

There is any solution to resolve this problem ? 

Thanks.

**Comment by stof** [comment]
Error pages have nothing to do with FOSUserBundle, so I'm closing this issue
