### ISSUE TITLE
 non-existent service "security.token_storage"

### ISSUE THREAD

**Issue by kszyma** [FriendsOfSymfony/FOSUserBundle#1993]
Hi,

today i made a "composer update" on my (minutes before working :) symfony 2.3 application.

But then i get:

  [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
  The service "fos_user.security.login_manager" has a dependency on a non-existent service "security.token_storage".

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-upd

  [RuntimeException]
  An error occurred when executing the "'cache:clear --no-warmup'" command.

Also if i try

   $ php app/console

i get

  [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
  The service "fos_user.security.login_manager" has a dependency on a non-existent service "s
  ecurity.token_storage".

What happened ? :)

CU,
  Kai.

**Comment by stof** [comment]
which version of FOSUserBundle and Symfony are you using ?

**Comment by kszyma** [comment]
Hi stof,

Symfony 2.3.34
FOSUserbundle 2.0.0-alpha3

CU,
  Kai.

PS: A dump of versions for of all installed packages you will find here: https://gist.github.com/kszyma/d8a3a4376fc4d60b68e8

**Comment by kszyma** [comment]
Here the diff (buggy = not Working, new = old nbackuped version that works):

$ diff /tmp/buggy.txt /tmp/new.txt
7,8c7,8
< doctrine/doctrine-bundle             1.6.0              Symfony DoctrineBundle
< doctrine/doctrine-cache-bundle       1.2.1              Symfony Bundle for Doctrine Cache
---
> doctrine/doctrine-bundle             v1.5.2             Symfony DoctrineBundle
> doctrine/doctrine-cache-bundle       v1.0.1             Symfony2 Bundle for Doctrine Cache
10,11c10,11
< doctrine/doctrine-migrations-bundle  1.1.1              Symfony DoctrineMigrationsBundle
< doctrine/inflector                   v1.1.0             Common String Manipulations with regard to casing and singular/plural rules.
---
> doctrine/doctrine-migrations-bundle  v1.1.0             Symfony DoctrineMigrationsBundle
> doctrine/inflector                   v1.0.1             Common String Manipulations with regard to casing and singular/plural rules.
19c19
< incenteev/composer-parameter-handler v2.1.2             Composer script handling your ignored parameter file
---
> incenteev/composer-parameter-handler v2.1.1             Composer script handling your ignored parameter file
41c41
< phpunit/phpunit                      4.8.18             The PHP Unit Testing framework.
---
> phpunit/phpunit                      4.8.16             The PHP Unit Testing framework.
53c53
< sensio/framework-extra-bundle        v3.0.11            This bundle provides a way to configure your controllers with annotations
---
> sensio/framework-extra-bundle        v3.0.10            This bundle provides a way to configure your controllers with annotations
59,60d58
< symfony/security-acl                 v2.7.6             Symfony Security Component - ACL (Access Control List)
< symfony/security-core                v2.7.6             Symfony Security Component - Core Library
64c62
< twig/twig                            v1.23.1            Twig, the flexible, fast, and secure template language for PHP
---
> twig/twig                            v1.23.0            Twig, the flexible, fast, and secure template language for PHP

**Comment by kszyma** [comment]
jhere a diff between buggy version and old working verion: https://gist.github.com/kszyma/72de378657be6559f6be

**Comment by fredpo** [comment]
This is a problem with Symfony 2.3.34 release, this can be resolved by removing symfony/security-core and security-acl as they are version v2.7.6 and should not have been included with 2.3.*

(https://github.com/symfony/symfony/issues/16500)

**Comment by XWB** [comment]
See above.
