### ISSUE TITLE
Symfony 3.0 compatibility?

### ISSUE THREAD

**Issue by greg606** [FriendsOfSymfony/FOSUserBundle#1996]
What are the plans for 3.0 compatibility?

**Comment by xabbuh** [comment]
see for example #1990

**Comment by 1ed** [comment]
FYI the **master** branch is now compatible with Symfony 3.

**Comment by rande** [comment]
@stof do you plan to have 1.x branch compatible with Symfony3 ?

**Comment by gsdevme** [comment]
+1

**Comment by kilhage** [comment]
+1

**Comment by smedbergsimon** [comment]
+1

**Comment by redactuk** [comment]
+1
Please please please can we have a 2.x release

**Comment by stof** [comment]
@rande no I don't. But I plan to release 2.x as stable before the end of the month (I will work on making releases this weekend, but FOSUserBundle may not fit in this weekend yet)

**Comment by rande** [comment]
@stof ok, thanks for the response.

**Comment by toinouu** [comment]
@stof +1

**Comment by Ener-Getick** [comment]
@stof are you open to a PR which would add symfony 3.0 support on the ``1.x`` branch?

**Comment by OskarStark** [comment]
> @rande no I don't. But I plan to release 2.x as stable before the end of the month (I will work on making releases this weekend, but FOSUserBundle may not fit in this weekend yet)

:+1:

**Comment by geekdevs** [comment]
@stof so will v2 be compatible with symfony3? Looking at current alpha seems like it's not (?)

**Comment by Ener-Getick** [comment]
@geekdevs the v2 is already compatible with symfony 3 (see its [``composer.json``](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/composer.json))

**Comment by geekdevs** [comment]
@Ener-Getick ok thanks. looking forward for release

**Comment by redactuk** [comment]
Any news on 2.0 release? You said end of the month in December :(

**Comment by alanchavez88** [comment]
@redactuk I don't know if there is an official release yet -- but I have been using the `master` branch with symfony 3 without a problem at all. Though, I understand this might not be the ideal situation for everyone

**Comment by happynessTony** [comment]
why symfony 3 use fosuserbundle cannot rewrite the login.html.twig ? I use the symfony 3 and rewrite the login.html.twig and the layout.html.twig was success to be rewrite but the login.html.twig was useless。。。

**Comment by XWB** [comment]
Closing this in favor of https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2206

**Comment by AmaliDeveloper** [comment]
you can get th solution in this tutorial [link](https://youtu.be/KT2JHTKziPo)
