### ISSUE TITLE
suggest username

### ISSUE THREAD

**Issue by wajaja** [FriendsOfSymfony/FOSUserBundle#1997]
I use Doctrine MongoDB; I want that when a user enters an existing username; it has a username list available

**Comment by SakyaStelios** [comment]
I thinf you can implement it in the frontend, i.e, with jQuery Cool Auto-Suggest

**Comment by wajaja** [comment]
thanks

**Comment by stof** [comment]
Closing as this is indeed something which is outside the scope of FOSUserBundle itself.
