### ISSUE TITLE
Repository cannot see FOSUser field on my extended entity?

### ISSUE THREAD

**Issue by MartinLyne** [FriendsOfSymfony/FOSUserBundle#1998]
Hi, 
Hopefully I've missed something silly and it's an easy fix.

The error `[Semantical Error] line 0, col 60 near 'username_canonical': Error: Class Bay12\CoreBundle\Entity\SiteUser has no field or association named username_canonical`

### Composer version
    "friendsofsymfony/user-bundle": "~2.0@dev"

### FOS + Doctrine Config
    doctrine:
        dbal:
            driver:   pdo_mysql
            host:     "%database_host%"
            port:     "%database_port%"
            dbname:   "%database_name%"
            user:     "%database_user%"
            password: "%database_password%"
            charset:  UTF8

        orm:
            auto_generate_proxy_classes: "%kernel.debug%"
            naming_strategy: doctrine.orm.naming_strategy.underscore
            auto_mapping: true

    fos_user:
        db_driver: orm
        firewall_name: main
        user_class: Bay12\CoreBundle\Entity\SiteUser

        [...]

### Entity:
Bog-standard extension of BaseUser
[Entity/SiteUser.php](http://pastebin.com/ipTFedA3)

### Repo
Very simple Repo to search by partial usernames
[Repository/SiteUserRepository.php](http://pastebin.com/PycckP0B)

### How DB Looks
    mysql> desc siteuser;
    +-----------------------+--------------+------+-----+---------+----------------+
    | Field                 | Type         | Null | Key | Default | Extra          |
    +-----------------------+--------------+------+-----+---------+----------------+
    | id                    | int(11)      | NO   | PRI | NULL    | auto_increment |
    | username              | varchar(255) | NO   |     | NULL    |                |
    | username_canonical    | varchar(255) | NO   | UNI | NULL    |                |
    | email                 | varchar(255) | NO   |     | NULL    |                |
    | email_canonical       | varchar(255) | NO   | UNI | NULL    |                |
    | enabled               | tinyint(1)   | NO   |     | NULL    |                |
    | salt                  | varchar(255) | NO   |     | NULL    |                |
    | password              | varchar(255) | NO   |     | NULL    |                |
    | last_login            | datetime     | YES  |     | NULL    |                |
    | locked                | tinyint(1)   | NO   |     | NULL    |                |
    | expired               | tinyint(1)   | NO   |     | NULL    |                |
    | expires_at            | datetime     | YES  |     | NULL    |                |
    | confirmation_token    | varchar(255) | YES  |     | NULL    |                |
    | password_requested_at | datetime     | YES  |     | NULL    |                |
    | roles                 | longtext     | NO   |     | NULL    |                |
    | credentials_expired   | tinyint(1)   | NO   |     | NULL    |                |
    | credentials_expire_at | datetime     | YES  |     | NULL    |                |
    | first_name            | varchar(255) | NO   |     | NULL    |                |
    | last_name             | varchar(255) | NO   |     | NULL    |                |
    | profileImage          | int(11)      | YES  | MUL | NULL    |                |
    +-----------------------+--------------+------+-----+---------+----------------+

### Attempted
- Tried a composer update but seems to be up to date
- Tried adding a `protected $username_canonical;` to my SiteUser Entity (without generating entities), but it made no difference.

Really appreciate any help!
Thanks,
Martin

**Comment by 1ed** [comment]
In the query you should write `su.usernameCanonical` (you can find it in the base [User class](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Model/User.php#L35)) not `su.username_canonical`. In a DQL query you have to user property names of a class and not field names of a database.

**Comment by MartinLyne** [comment]
*sigh* Thank you. I swear whatever I try first is wrong first time around!

**Comment by 1ed** [comment]
Could you please close the issue if it's resolved? Thanks!

**Comment by MartinLyne** [comment]
I don't see a way? Maybe don't have permission?
