### ISSUE TITLE
Access response on SECURITY_IMPLICIT_LOGIN

### ISSUE THREAD

**Issue by ghost** [FriendsOfSymfony/FOSUserBundle#2000]
How can I access the response on the `SECURITY_IMPLICIT_LOGIN` event?

Documentation:
https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/FOSUserEvents.php#L190

The `FOS\UserBundle\Event\UserEvent` event only has the `request` and the `user`
but not any `response`. I like to do a redirect after the login on special cases.

For example I like to redirect the user on his first login to visit a "tutorial page".

**Comment by stof** [comment]
well, the code triggering the event has no way to set a response for the controller anyway. This is why the event class does not let you set a Response object: it cannot be used if you set it. I think that you are trying to use the wrong event for your use case.

**Comment by JHGitty** [comment]
Then the text is wrong? (See link above)
```
This event allows you to access the response which will be sent.
```
