### ISSUE TITLE
Testing FOSUserBundle in Symfony 3 - Unknown "form_enctype"

### ISSUE THREAD

**Issue by itrascastro** [FriendsOfSymfony/FOSUserBundle#2001]
Testing /profile/edit i get this error:

Unknown "form_enctype" function in FOSUserBundle:Profile:edit_content.html.twig at line 3

**Comment by 1ed** [comment]
Which version of the bundle are you using? Only the **master** branch is compatible with Symfony 3 yet.

**Comment by itrascastro** [comment]
"friendsofsymfony/user-bundle": "dev-master"

**Comment by 1ed** [comment]
As you can see [here](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Resources/views/Profile/edit_content.html.twig) there is not `form_enctype` in that file. It was removed by https://github.com/FriendsOfSymfony/FOSUserBundle/commit/4a6660f04a731a07c545e02d90634dbb723d0956. Could you please check on which commit the package is installed?  `composer show -i` It should show `friendsofsymfony/user-bundle dev-master e39b040`, if not you should update the package `composer update friendsofsymfony/user-bundle`

**Comment by itrascastro** [comment]
That was the problem, overriding files. Thank you
