### ISSUE TITLE
User logs in without confirming email address.

### ISSUE THREAD

**Issue by redjanym** [FriendsOfSymfony/FOSUserBundle#2002]
Is the default behaivor of the FosUserBundle to not login the user without confirming the email address? Because i am having this problem, even after following all the configuration steps for the Registration Confirmation Email. Any help? Thanks in advance.

**Comment by stof** [comment]
I don't understand what you mean

**Comment by Green-Cat** [comment]
I think he means that the bundle is not checking if a user confirmed his account before logging them in.

**Comment by stof** [comment]
When enabling the email confirmation feature, the ``enabled`` flag of the user is set to ``false`` until the confirmation link is used. And SecurityBundle forbids the login in such case

**Comment by redjanym** [comment]
Yes Green-Cat. I register as a new User, the Confirmation Emnail arrives but even without confirming the Email Address, i can still Login.

**Comment by redjanym** [comment]
This is my Configuration:
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Custom\Class
    registration:
      form:
        type: custom_user_registration
      confirmation:
        enabled:    true
        from_email:
          address:        info@email.com
          sender_name:   Sender
    resetting:
      form:
        type: custom_user_resetting
      email:
        from_email: # Use this node only if you don't want the global email address for the resetting email
          address: info@email.com
          sender_name: Sender

**Comment by redjanym** [comment]
An event Listener onRegistrationCompletedSuccess was setting Enabled to TRUE since the begining. Thanks for your replies.

**Comment by aanchalgera** [comment]
@redjanym How did you fix this?
