### ISSUE TITLE
ProfileEditType impossible to rewrite

### ISSUE THREAD

**Issue by MatthAddax** [FriendsOfSymfony/FOSUserBundle#2003]
Hi,

I'm triyng to rewrite the profile edit type just like I did for the RegistrationType but it doesn't work

Here's the part in my Type where I get the parent and change the name and the part in the config.yml where I tell FOS to use my  form type :

    public function getParent()
    {
        return 'fos_user_profile';
    }

    public function getName()
    {
        return 'app_user_profile';
    }

YAML :

        group_class: Patro\UserBundle\Entity\Fos_Group
    registration:
            form:
                type: app_user_registration
    profile:
            form:
                type: app_user_profile

Can anyone help me?? Thanks :)

**Comment by xabbuh** [comment]
Please provide more information. Which version of the bundle do you use? What does not work? Which error message(s) do you get?

**Comment by MatthAddax** [comment]
Yes sorry,

I use Symfony 2.7.7 and the dev-master version of FOSUserBundle (according to my composer settings)

The error I get is this one : 
![could_not_load_type_app_user_profile](https://cloud.githubusercontent.com/assets/12526135/11636438/6bef4258-9d1c-11e5-8d75-550290eff476.PNG)


I did the same for the RegisterType and it worked fine.

**Comment by xabbuh** [comment]
Did you think of registering your form type as a service?

**Comment by MatthAddax** [comment]
No I didn't but I just saw that I did for my registration type so I'll do it for the profile edit type
