### ISSUE TITLE
Use dynamic template path

### ISSUE THREAD

**Issue by JHGitty** [FriendsOfSymfony/FOSUserBundle#2005]
Currently the template paths are hardcoded:
https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Controller/GroupController.php#L39

It would be nice if they would be passed through an extra `protected function`. Then we could extend an own controller from these controllers to change the path of the templates.

Sure: I could override the templates itself. But I think it is much more clean to use an own structure.

**Comment by stof** [comment]
IMO, using the Symfony overwriting feature is enough. Creating extra extension point to provide a second way to do the same is only adding confusion IMO

**Comment by XWB** [comment]
See comment above.
