### ISSUE TITLE
Tag for 1.3.x

### ISSUE THREAD

**Issue by Soullivaneuh** [FriendsOfSymfony/FOSUserBundle#2008]
Lot of deprecated stuff was fixed on 1.3.x branch AFAIK but no stable tags since Jun 2015.

Could be possible to have a new one?

Thanks.

**Comment by stof** [comment]
I will do a bunch of releases this weekend in many packages I maintain

**Comment by Soullivaneuh** [comment]
Thanks! :+1:

**Comment by lolautruche** [comment]
Hi

Any news on a `v1.3.7` tag?
Thanks

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSUserBundle/releases/tag/v1.3.7

**Comment by stof** [comment]
@XWB next time you do releases, please don't forget to update the changelog file first

**Comment by XWB** [comment]
@stof https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2312
