### ISSUE TITLE
Resetting password mailer fail message

### ISSUE THREAD

**Issue by Stanislavsky34200** [FriendsOfSymfony/FOSUserBundle#2011]
Please add a message that indicates mailer failure on sending resetting email, because for example mailer server can be unreachable for some reason but user still will receive success message.

**Comment by xabbuh** [comment]
I don't think that this issue can be solved in such a generic way. The thing is that you do not necessarily know at this stage if the e-mail really was sent successfully (for example, your application uses a queue to store mails which are then processed later by another process, there can be temporary issues with a mail server which only lead to a complete failure later, and so on).
