### ISSUE TITLE
Unknown "form_enctype" function in FOSUserBundle:Registration:register_content.html.twig at line 5

### ISSUE THREAD

**Issue by gabryxx89** [FriendsOfSymfony/FOSUserBundle#2012]
I get this error when trying to reach /register.
my version is ~2.0@dev (dev-master e39b040) and symfony is 3.0.

There was a similar issue opened but it has been closed as it was on overriding the registration template, while for me it's still the original template, I haven't overridden it yet.

**Comment by stof** [comment]
Are you sure you don't overwrite any template ? The template in the bundle does not contain ``form_enctype``: https://github.com/FriendsOfSymfony/FOSUserBundle/blob/e39b040e272c72f0a090c67d802e1d3b2d0b0313/Resources/views/Registration/register_content.html.twig

**Comment by gabryxx89** [comment]
Oops i'm sorry I was looking into the wrong folder, I did actually copy my overridden templates over to the new version, I'm sorry!

I thought I was going crazy, I couldn't see any function in the skeletons!

Thanks
