### ISSUE TITLE
login_check is not calling doctrine to ensure values when called

### ISSUE THREAD

**Issue by huitiemesens** [FriendsOfSymfony/FOSUserBundle#2013]
i m facing a very weird situation, 

i m using this bundle for 2 years now without problems until now, we are facing an issue we don t understand : 

We can t authenticate user on our test server while we can successfully authenticate on our local dev server and prod server because the login_check , according to profiler, is not calling doctrine to validate the credentials.

i don t know what s going since the bundle and symfony2 ( fosuser dev-master and sf2.7.8 ) are absolutely the same ( we are using a versionning system )  on the 3 servers ( which are giving a success setup with check.php and web/config.php )

here is screenshot from the 2 servers, one is doing the correct doctrine queries to check for credentials, the other is performing no queries . ( i can provide full profiler for each server if needed).
![test_server_no_queries_perform](https://cloud.githubusercontent.com/assets/6419077/11953661/388a43b8-a8a2-11e5-9ada-de8b70bbfd87.png)
![prod_server_sucess_authentication](https://cloud.githubusercontent.com/assets/6419077/11953662/388afbfa-a8a2-11e5-8f3d-acb4063fd1a5.png)

**Comment by dmaicher** [comment]
Did you check the logs of your symfony application? Sometimes exceptions that are not related to the authentication are caught during authentication and they will be logged.

**Comment by dmaicher** [comment]
Or can you close this issue if the problem is solved?

**Comment by huitiemesens** [comment]
@dmaicher i forgot i openned that issue, i found the issue which is very weird : It seems that server was misconfigured with session which result in a conflict with php settings ( in session entropy specifically ) so i guess this is not code related but more server side. Sorry for that late answer
