### ISSUE TITLE
[Symfony 3] After reset password and user connected or not ?

### ISSUE THREAD

**Issue by gazouweb** [FriendsOfSymfony/FOSUserBundle#2015]
Hello,
At the launch of the homepage, if the user is anonymous, I return to the login form, if the user is connected so I displays the home page.

```
if ($this->getUser() && $this->get('security.authorization_checker')->isGranted('IS_AUTHENTICATED_REMEMBERED')) {
            return $this->redirect($this->generateUrl('homepage'));
}
```

After resetting the password, logically I redirect to the home page, but there is a redirect loop because isGranted('IS_AUTHENTICATED_REMEMBERED') is true and when I do the test
isGranted('IS_AUTHENTICATED_ANONYMOUSLY') is also true, which is totally impossible.

How to prevent the controller to authenticate the user?

Thanks

**Comment by gazouweb** [comment]
Help please ??

**Comment by stof** [comment]
IS_AUTHENTICATED_ANONYMOUSLY does not mean "I am anonymous" but "I am at least anonymous". There is a hierarchy between ANONYMOUSLY, REMEMBERED and FULLY. So if you have REMEMBERED, you always have ANONYMOUSLY too

**Comment by gazouweb** [comment]
my file security.yml
```
security:

    encoders:
        UsersBundle\Entity\User:
            algorithm:            sha512
            encode_as_base64:     true
            iterations:           9542

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        admin:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:    ^/(_(profiler|wdt)|css|images|js)/
            security:   false
        admin_login:
            pattern:    ^/(login$|register|resetting)
            anonymous:  true
        admin:
            pattern:    ^/
            anonymous:  false
            provider:   admin
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: /
                always_use_default_target_path: true
            logout:
                path:   fos_user_security_logout
                target: /
            remember_me:
                secret:   %secret%
                lifetime: 604800 # 7 jours en secondes
                path:     /
                domain:   ~
```
So it always sees anonymous that's why I have a loop.

**Comment by gazouweb** [comment]
After the reset : 
isGranted('IS_AUTHENTICATED_REMEMBERED') = true
isGranted('IS_AUTHENTICATED_FULLY') = true
isGranted('IS_AUTHENTICATED_ANONYMOUSLY') = true
and 
$this->getUser() is not null
Why ?

**Comment by gazouweb** [comment]
Manually when nobody is logged:
isGranted('IS_AUTHENTICATED_REMEMBERED') = false
isGranted('IS_AUTHENTICATED_FULLY') = false
isGranted('IS_AUTHENTICATED_ANONYMOUSLY') = true
$this->getUser() is null

I don't understand is why when the password is changed then:
isGranted('IS_AUTHENTICATED_REMEMBERED') = true
isGranted('IS_AUTHENTICATED_FULLY') = true
isGranted('IS_AUTHENTICATED_ANONYMOUSLY') = true
$this->getUser() is not null

if I try to overload the resetAction method according to the documentation, my controller is not recognized.

anyone can help me?

**Comment by xabbuh** [comment]
On which action? Maybe the user is authenticated by their remember me cookie as you have different firewalls then.

**Comment by gazouweb** [comment]
no user is logged in at the time. I do a password reset, and when the password is changed I redirect to the home page that checks if a user is connected via a cookie.
I solved the problem by:
```
if ($this->getUser() && $authCheck->isGranted('IS_AUTHENTICATED_REMEMBERED') && !$authCheck->isGranted('IS_AUTHENTICATED_ANONYMOUSLY')) {
     return $this->redirect($this->generateUrl('evol_homepage'));
}
```
but, i don't understand why all possibilities are true ...

**Comment by xabbuh** [comment]
I don't understand your problem. If they are logged in, why shouldn't all these method calls return `true`  for the user?

**Comment by gazouweb** [comment]
I'll try to explain, step by step ...

1) initially, no user logged on, so:
isGranted('IS_AUTHENTICATED_REMEMBERED') = false
isGranted('IS_AUTHENTICATED_FULLY') = false
isGranted('IS_AUTHENTICATED_ANONYMOUSLY') = true

2) I reset the password
3) When the password is reset, the form redirect to the home page, and there :
isGranted('IS_AUTHENTICATED_REMEMBERED') = true
isGranted('IS_AUTHENTICATED_FULLY') = true
isGranted('IS_AUTHENTICATED_ANONYMOUSLY') = true

the problem is here, why this 3 verifications are TRUE ?

I just want to be on the home page as anonymous, the controller that resets the password identifies the user, and symfony sees an anonymous user at the same time the user, it's inconsistent ...

**Comment by xabbuh** [comment]
In your last comment you said that the user is logged in at the time. So why shouldn't they be shown as authenticated?

**Comment by gazouweb** [comment]
Sorry, I don't speak english very well, I'm French.
Initially, there is no user logged.

**Comment by xabbuh** [comment]
How did you check that? Debugging the information on the password reset route isn't enough as you have different firewalls (and by the way, what is the reason for that?).

**Comment by gazouweb** [comment]
Simply, what I would like, when the password is reset, do not automatically authenticated user. Staying in anonymous access.
I don't know if I explain myself properly.

**Comment by xabbuh** [comment]
Well, I don't see any code that would trigger the authentication after resetting the password (doing so wouldn't make much sense). That's why I am trying to figure out why this happens to you (or why you think it does).

**Comment by gazouweb** [comment]
When the password reset, the trace : 

1) changePasswordAction > FOS\UserBundle\Controller\ChangePasswordController
2) Event "CHANGE_PASSWORD_COMPLETED" execute "FilterUserResponseEvent"
3) __construct > FOS\UserBundle\Event\UserEvent 
and in this constructor there is : $this->user = $user;

**Comment by xabbuh** [comment]
Changing the password is something different than resetting the password. What are you actually trying to do?

**Comment by gazouweb** [comment]
Sorry, I was wrong trace : 

1) resetAction> FOS\UserBundle\Controller\ResettingController
2) Event "RESETTING_RESET_COMPLETED" execute "FilterUserResponseEvent"
3) __construct > FOS\UserBundle\Event\UserEvent 
and in this constructor there is : $this->user = $user;

**Comment by xabbuh** [comment]
Nothing of that is related to authentication.

Once again: Where did you check before that the user is not authenticated? Doing so in a different firewall is meaningless if they don't share the same context.

Why don't you start with using just one firewall (except for the `dev` one).

**Comment by gazouweb** [comment]
All website is accessible only if the user is authenticated.

As defined in my security.yml, firewall "admin" : 
```
firewalls:
        dev:
            pattern:    ^/(_(profiler|wdt)|css|images|js)/
            security:   false
        admin_login:
            pattern:    ^/(login$|register|resetting)
            anonymous:  true
        admin:
            pattern:    ^/
            anonymous:  false
            provider:   admin
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: /
                always_use_default_target_path: true
            logout:
                path:   fos_user_security_logout
                target: /
            remember_me:
                secret:   %secret%
                lifetime: 604800
                path:     /
                domain:   ~
```

So, if the user is anonymous, it's redirect to "/login", ans here, in my controller of login, I check the state of the user : 
```php
if ($this->getUser() && $authCheck->isGranted('IS_AUTHENTICATED_REMEMBERED')) {
            return $this->redirect($this->generateUrl('homepage'));
        }
```

This, it's the correct process and run.
But if there is no user authenticated, or remembered, and wants to reset his password, it happens that I describe above.

Currently, I "get around" the problem by checking the user as well: 
```php
if ($this->getUser() && $authCheck->isGranted('IS_AUTHENTICATED_REMEMBERED') && !$authCheck->isGranted('IS_AUTHENTICATED_ANONYMOUSLY')) {
            return $this->redirect($this->generateUrl('homepage'));
        }
```

**Comment by xabbuh** [comment]
Can you please visit the home page and after that reset the password and then please show the complete log for these requests (you need to be in the `dev` environment)?

**Comment by gazouweb** [comment]
You want me to go on the homepage as anonymous, then I reset the password, and I send you the logs, right?

**Comment by xabbuh** [comment]
Yeah, maybe they provide more information about what is going wrong in your application.

**Comment by gazouweb** [comment]
here is the log
[dev.txt](https://github.com/FriendsOfSymfony/FOSUserBundle/files/74027/dev.txt)

**Comment by xabbuh** [comment]
And what is the issue now? Even after resetting the password access to the homepage is denied because the Security component doesn't find a token.

**Comment by xabbuh** [comment]
What's happening is this (unnecessary log entries removed):

```
[2015-12-29 15:56:46] request.INFO: Matched route "fos_user_resetting_reset". {"route_parameters":{"_controller":"FOS\\UserBundle\\Controller\\ResettingController::resetAction","token":"fTOSIvFAPRouoGOw4uLfJt67zRP2tAw9BURkIsgdMHk","_route":"fos_user_resetting_reset"},"request_uri":"http://proevol.vm/web/app_dev.php/resetting/reset/fTOSIvFAPRouoGOw4uLfJt67zRP2tAw9BURkIsgdMHk"} []
[2015-12-29 15:56:46] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2015-12-29 15:56:46] request.INFO: Matched route "evol_homepage". {"route_parameters":{"_controller":"EvolBundle\\Controller\\HomeController::indexAction","_route":"evol_homepage"},"request_uri":"http://proevol.vm/web/app_dev.php/"} []
[2015-12-29 15:56:46] security.INFO: An AuthenticationException was thrown; redirecting to authentication entry point. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationCredentialsNotFoundException(code: 0): A Token was not found in the TokenStorage. at /var/www/evolupharm-pro/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/AccessListener.php:53)"} []
[2015-12-29 15:56:46] request.INFO: Matched route "fos_user_security_login". {"route_parameters":{"_controller":"UsersBundle\\Controller\\SecurityController::loginAction","_route":"fos_user_security_login"},"request_uri":"http://proevol.vm/web/app_dev.php/login"} []
```

and so on

**Comment by gazouweb** [comment]
Exactly, the Security component doesn't find a token so redirect to login, but on login, isGranted ('IS_AUTHENTICATED_REMEMBERED') returns TRUE when it should not, and so redirect to the home page, and so on.

My question was, why isGranted ('IS_AUTHENTICATED_REMEMBERED') is TRUE after the reset ?

As mentioned before, I bypassed by checking whether the user is anonymous and if it is stored.

**Comment by gazouweb** [comment]
isGranted ('IS_AUTHENTICATED_REMEMBERED') is FALSE before the reset, and after the reset, it's TRUE ... and I don't know why.

**Comment by xabbuh** [comment]
What does your `UsersBundle\EventListener\PasswordResettingListener` class do in its `onPasswordResettingSuccess()` method when the `fos_user.resetting.reset.success` event is dispatched?

**Comment by gazouweb** [comment]
```php
class PasswordResettingListener implements EventSubscriberInterface {

    private $router;

    public function __construct(UrlGeneratorInterface $router) {
        $this->router = $router;
    }

    public static function getSubscribedEvents() {
        return [
            FOSUserEvents::RESETTING_RESET_SUCCESS => 'onPasswordResettingSuccess',
        ];
    }

    public function onPasswordResettingSuccess(FormEvent $event) {
        $url = $this->router->generate('homepage');
        $event->setResponse(new RedirectResponse($url));
    }
}
```

**Comment by xabbuh** [comment]
Ah, the implicit login is taking place in the `AuthenticationListener` which listens to the `fos_user.security.implicit_login` event.

**Comment by gazouweb** [comment]
And what can I do?

**Comment by xabbuh** [comment]
If you really don't want the user to be logged in after they successfully reset their password (I understood they were logged in after they requested a new password), you can replace the listener with a custom one that only listens to the other two events.

**Comment by gazouweb** [comment]
Hum ... how do I do that?

**Comment by xabbuh** [comment]
Do you really want to do that? Or isn't your real issue that after resetting the password the redirect to your homepage doesn't work?

**Comment by gazouweb** [comment]
it works with my workaround, but I thought to do things properly, I'll see what I can do in this case.

**Comment by xabbuh** [comment]
Your main issue imo still is that you have more than one firewall which means that they don't share the same context.

**Comment by XWB** [comment]
Closing this issue as it does not seem related to FOSUserBundle.
