### ISSUE TITLE
Canonical Email field not populated after creating user from command line

### ISSUE THREAD

**Issue by JacerOmri** [FriendsOfSymfony/FOSUserBundle#2017]
Hello,

I'm using FOSUserBundle in a project.
After deploying the project (dev or prod) I manually add an admin user through the command line. It runs successfully and adds a user with no canonical email.
When a user registers fron the web interface, A SQL constraint violation exceptions is raised because of duplicate enty for the index

After manually setting a value for the canonical email, everything works as expected. Am I missing something?

**Comment by xabbuh** [comment]
Which version of the bundle do you use? Did you customise the controllers or templates?

**Comment by JacerOmri** [comment]
I'm using FOSUserBundle version 2.0.x-dev (dev-master) and yes, i did override the registration and profile edit actions. I overrode the templates to set layouts mainly.

**Comment by xabbuh** [comment]
Did you change the command to create new users?

**Comment by JacerOmri** [comment]
no, I didn't, i only overrode what i mentionned above

**Comment by damienalexandre** [comment]
I can't reproduce with beta1, can you provide more informations or maybe retry?

**Comment by XWB** [comment]
Closing this issue as no further information was provided.
