### ISSUE TITLE
Use Yaml doctrine mapping instead of XML due to issue with XML driver and libxml_disable_entity_loader

### ISSUE THREAD

**Issue by layanto** [FriendsOfSymfony/FOSUserBundle#2018]
There is a bug with PHP/libxml where simplexml_load_file (used by doctrine mapping XML driver) will fail even when loading xml with no external entities if libxml_disable_entity_loader is set to true. This bug still exists with latest PHP5.6 and latestt PHP7 (didn't check PHP5.5 but expect to be affected too). See https://bugs.php.net/bug.php?id=62577&edit=1 and http://www.serverphorums.com/read.php?7,1262794 (discussion on making libxml_disable_entity_loader setting default to true for PHP7 or 7.1).

This bug causes error in reading FosUser's orm mapping in XML. See https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1062

I have raised this with doctrine project too. See https://github.com/doctrine/doctrine2/issues/3788 and https://groups.google.com/forum/m/#!topic/doctrine-user/vAb_3zcz6vU

The PHP bug was reported back in 2012 and is still not fixed. My suggestions (in order of preference):
1. PHP/libxml fixing this bug but as bug unresolved for many years probably won't happen
2. Change XML driver of doctrine to be able to load XML mapping when libxml_disable_entity_loader is set to true (similar to what OwnCloud did, see https://github.com/owncloud/core/pull/7498/files)
3. Change FosUser doctrine mapping to use YML instead of XML hence avoiding this bug

**Comment by stof** [comment]
Given that the Doctrine team wants to remove the YAML driver in Doctrine 3, this won't happen
