### ISSUE TITLE
Registration and login form at same page

### ISSUE THREAD

**Issue by bodnar1212** [FriendsOfSymfony/FOSUserBundle#2019]
How resolve it? Help me please.

**Comment by xabbuh** [comment]
What exactly is the problem that you have?

**Comment by bodnar1212** [comment]
1. create welcome.html twig with http://joxi.ru/GrqLQvWsN4vQKA
{{ render(controller('UserBundle:Security:login')) }}
{{ render(controller('UserBundle:Registration:register')) }}
2. In login.html.twig http://joxi.ru/52akGvxhGEp44r
3. In register.html.twig http://joxi.ru/8An64pQuqz6joA
4. Register http://joxi.ru/eAO7ZRbF49O9bA If errors in register fields render in a new page http://joxi.ru/823kNzqh6919D2

**Comment by bodnar1212** [comment]
And second question.
1. I render 2 controllers(register) in my controller welcomeAction. How disable access to /login http://joxi.ru/4AkpV8MIMoZX8r http://joxi.ru/KAg8bPNIgEMXWr

**Comment by bodnar1212** [comment]
[the same question](http://stackoverflow.com/questions/28541496/merge-2-actions-from-2-different-controllers-in-one-view-symfony2)
[the same question2](https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1359)

**Comment by JHGitty** [comment]
My suggestion: Create an own page for each function (login and registration). Then render the form fields on another page ("same page"). If there will be an issue while using the form the user will be redirected to the single page (login page or registration page) because these are the main pages for these features.

So you just need to find out how to render form fields - and this is not that hard - just look into the Twig templates how FOSUserBundle does it.

**Comment by HarounOujihi** [comment]
I tried to make login and register in same page (at root /login) using symfony 2.8 and This is how it works for me:

First simple edit in friendsofsymfony/user-bundle/Controller/SecurityController.php

at the buttom of function loginAction and befor return add this :

```
$formFactory = $this->get('fos_user.registration.form.factory');
$form = $formFactory->createForm();
```
and then add the registration form view to the return to be like this:

```
return $this->renderLogin(array(
            'last_username' => $lastUsername,
            'error' => $error,
            'csrf_token' => $csrfToken,
            'register_form' => $form->createView()
        ));
```
Then in your login.html.twig put where ever you want:

`{{ form_rest(register_form) }}`

* Important: this is will works fine for login, but in case of registration verification error it will redirect to /register !
