### ISSUE TITLE
Circular reference detected for service "fos_user.user_provider.username_email"

### ISSUE THREAD

**Issue by dialogik** [FriendsOfSymfony/FOSUserBundle#2022]
I upgraded my Symfony2 app to Symfony 3.0 with FOSUserBundle ([current `dev-master`](https://github.com/FriendsOfSymfony/FOSUserBundle/commit/e39b040e272c72f0a090c67d802e1d3b2d0b0313)) and use a workaround to cover `username` with the `email` field.

Activating APC on productive environment I get a `Circular reference detected` error:

```
Fatal error: Call to undefined function Doctrine/Common/Cache/apc_fetch() in
/var/html/app/vendor/doctrine/cache/lib/Doctrine/Common/Cache/ApcCache.php on line 40

Fatal error: Uncaught exception 'Symfony\Component\Debug\Exception\UndefinedFunctionException'
with message 'Attempted to call function "apc_fetch" from namespace "Doctrine/Common/Cache".'
in /var/html/app/vendor/doctrine/cache/lib/Doctrine/Common/Cache/ApcCache.php:40
Stack trace: #0 {main} Next exception
'Symfony/Component/DependencyInjection/Exception/ServiceCircularReferenceException'
with message 'Circular reference detected for service "fos_user.user_provider.username_email",
path: "security.firewall.map.context.main -> fos_user.user_provider.username_email ->
fos_user.user_manager -> security.authorization_checker -> security.authentication.manager".'
in /var/html/app//var/bootstrap.php.cache:2064 Stack trace: #0
/var/html/app//var/cache/prod/appProdProjectContainer.php(1531):
Symfony/Component/DependencyInjection/Container->get('fos_user.user_p...') #1
/var/html/app//var/bootstrap.php.cache(2090):
appProdProjectContainer->getSecurity_Authentication_ManagerService() #2 in
/var/html/app//var/bootstrap.php.cache on line 2064
```

which sounds like it's related to the [deprecation of the `SecurityContextInterface`](https://github.com/symfony/symfony/blob/2.8/UPGRADE-2.6.md#security) in Symfony 2.6.

As this doesn't seem to have raised any issues yet, I assume that this is due to my workaround. Or has anyone else had this issue yet?

**Comment by stof** [comment]
This fatal error is related to using the ApcCache without having the APC extension instead.
And the circular reference should be fixed in the meantime due to other refactorings.
