### ISSUE TITLE
Warning: array_merge(): Argument #2 is not an array 

### ISSUE THREAD

**Issue by mkalisz77** [FriendsOfSymfony/FOSUserBundle#2023]
I have this kind of error in my Symfony application when I try to add Group to user using custom form. Group doesn't have any roles. If group have some roles errror doesn't apper.

 in vendor/friendsofsymfony/user-bundle/Model/User.php at line 286  +
at ErrorHandler ->handleError ('2', 'array_merge(): Argument #2 is not an array', '/home/michal/www/my-admin-dev/vendor/friendsofsymfony/user-bundle/Model/User.php', '286', array('roles' => array('ROLE_ADMIN'), 'group' => object(Group)))
at array_merge (array('ROLE_ADMIN'), null)
in vendor/friendsofsymfony/user-bundle/Model/User.php at line 286  +
at User ->getRoles ()
in vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php at line 416  +
at PropertyAccessor ->readProperty (object(User), 'roles')
in vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php at line 330  +
at PropertyAccessor ->readPropertiesUntil (object(User), object(PropertyPath), '1', true)
in vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php at line 139  +
at PropertyAccessor ->getValue (object(User), object(PropertyPath))
in vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php at line 92  +
at PropertyPathMapper ->mapFormsToData (object(RecursiveIteratorIterator), object(User))
in vendor/symfony/symfony/src/Symfony/Component/Form/Form.php at line 623  +
at Form ->submit (array('username' =

**Comment by xabbuh** [comment]
For some reason, the `getRoles()` method of your `Group` class does not return an array. How does your `Group` class look like?

**Comment by mkalisz77** [comment]
<?php
namespace AppBundle\Entity;

use AppBundle\Doctrine\Timestampable\Traits\TimestampableEntity;
use AppBundle\Doctrine\Blameable\Traits\BlameableEntity;
use FOS\UserBundle\Model\Group as BaseGroup;
use Doctrine\ORM\Mapping as ORM;
use AppBundle\Entity\Traits\BaseEntity;
use AppBundle\Entity\Interfaces\BaseEntityInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity
 * @ORM\Table(name="zu_group")
 * @UniqueEntity("name")
 */
class Group extends BaseGroup implements BaseEntityInterface
{
    use BaseEntity;
   /**
     * Hook timestampable behavior
     * updates createdAt, updatedAt fields
     */
    use TimestampableEntity;

    /**
     * Hook blameable behavior
     * updates createdBy, updatedBy fields
     */
    use BlameableEntity;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\ManyToMany(targetEntity="AppBundle\Entity\User", mappedBy="groups")
     *
     */
    protected $users;


    public function getUsers()
    {
        return $this->users;
    }

    public function addUser(User $user)
    {
        $this->users[] = $user;
        $user->addGroup($this);
        return $this;
    }

    public function removeUser(user $user)
    {
        $this->users->removeElement($user);
        $user->removeGroup($this);
    }

    public function __toString()
    {
       return (string) $this->getName();
    }
}

**Comment by xabbuh** [comment]
What's in `AppBundle\Entity\Traits\BaseEntity`?

**Comment by mkalisz77** [comment]
Oh..
I have used 

    public function __construct()
    {
....
    }    

without parent call. Thank you for your help. Now error disappear.

BTW. 
When I delete Group it automatically remove it from all Users. Do you know if there is possibility to show Constraint Error in such situation if there is any User who has Group which we try to delete.

**Comment by xabbuh** [comment]
There is a [Count](http://symfony.com/doc/current/reference/constraints/Count.html) constraint which you might want to take a look at.

**Comment by XWB** [comment]
Sounds like resolved.
