### ISSUE TITLE
Mail not sent in fosuserbundle with symfony 2.8

### ISSUE THREAD

**Issue by ghost** [FriendsOfSymfony/FOSUserBundle#2024]
Please visit http://stackoverflow.com/questions/34596190/symfony-swiftmailer-mail-not-sent-in-prod-environment

**Comment by xabbuh** [comment]
duplicate of symfony/swiftmailer-bundle#128

**Comment by antondachauer** [comment]
Right, but that is another bundle and maybe another developer team.

**Comment by ybensacq** [comment]
I have a project on symfony 2.8 with fos user bundle, and mail in prod are well sent.

**Comment by XWB** [comment]
This is not the right place.
