### ISSUE TITLE
utf8mb4 isn't compatible with string fields length 255

### ISSUE THREAD

**Issue by hmartin** [FriendsOfSymfony/FOSUserBundle#2036]
As they said in https://dev.mysql.com/doc/refman/5.5/en/charset-unicode-upgrading.html
Max length for a string in utf8mb4 (that symfony recommends http://symfony.com/doc/current/book/doctrine.html) is 191.
Can i do a PR with:

```
<field ... type="string" length="191" unique="true" />
```

?

**Comment by joksnet** [comment]
In the link you provide one solution is to index only 191 chars, but store all up to 255. Is this possible in Doctrine?

**Comment by hmartin** [comment]
No it isn't... ;(

**Comment by Chuvisco88** [comment]
Who needs usernames or mail addresses with 255 length anyway? ;D

**Comment by hmartin** [comment]
Nobody, but if database have some biiiig username, some persons will have big problems!

**Comment by damienalexandre** [comment]
Fixed in https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2187 & https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2182
