### ISSUE TITLE
Q: How to create two secured areas with FOSUserBundle: chat and admin?

### ISSUE THREAD

**Issue by reypm** [FriendsOfSymfony/FOSUserBundle#2037]
I'm working in a Symfony 2.8.x app and I need to setup two secured areas: `frontend` and `admin`. This means that `frontend` and `admin` will use the same login template (if this is possible and I don't need to setup different one for this purpose). I have Google before ask here and there is a few things related and I read a lot of post about this topic: [1], [2], [3], [4] for example but I am doing something wrong since I can't get this working properly. This is how `/app/config/security.yml` looks like (just the firewalls and access_control piece of code):

	security:
		....
		firewalls:
		    admin:
		        pattern: /admin/(.*)
		        anonymous: ~
		        form_login:
		            provider: fos_userbundle
		            csrf_provider: security.csrf.token_manager
		            login_path: fos_user_security_login
		            check_path: fos_user_security_check  
		            use_forward: true                                           
		            always_use_default_target_path: true
		            default_target_path: /admin
		            target_path_parameter: _target_path
		            use_referer: true
		            remember_me: true
		        logout:
		          target: /admin
		        remember_me:
		            secret:   '%secret%'
		            lifetime: 604800 # 1 week in seconds
		            path:     /
		    chat:
		        pattern: ^/chat/(.*)
		        anonymous: ~
		        form_login:
		            provider: fos_userbundle
		            csrf_provider: security.csrf.token_manager
		            login_path: fos_user_security_login
		            check_path: fos_user_security_check
		            use_forward: true
		            always_use_default_target_path: true
		            default_target_path: /chat
		            target_path_parameter: _target_path
		            use_referer: true    
		            remember_me: true
		        logout: ~
		        remember_me:
		            secret:   '%secret%'
		            lifetime: 604800 # 1 week in seconds
		            path:     /

		access_control:
		    - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
		    - { path: ^/admin/resetting$, role: IS_AUTHENTICATED_ANONYMOUSLY }
		    - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }

		    - { path: ^/chat/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
		    - { path: ^/chat/resetting$, role: IS_AUTHENTICATED_ANONYMOUSLY }
		    - { path: ^/chat/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }

		    - { path: ^/chat/, role: ROLE_CHATTER }
		    - { path: ^/admin/, role: ROLE_ADMIN }

Now this is the config for my bundles at `app/config/routing.yml`:

	platform_chat:
	    resource: "@PlatformChatBundle/Controller/"
	    type:     annotation
	    prefix:   /chat/
	    options:
	            expose: true

	platform_admin:
	    resource: "@PlatformAdminBundle/Controller/"
	    type:     annotation
	    prefix:   /admin/
	    options:
	        expose: true

And for `FOSUserBundle` I have tried this two (both without success and each at a time):

	#FOSUser
	fos_user:
		resource: "@FOSUserBundle/Resources/config/routing/all.xml"

	#FOSUser	
	# this second causes doubts to me since I think I will need 
	# to repeat the same routes for chat prefix but I'm not sure at all
	fos_user_security:
	    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
	    prefix: /admin

	fos_user_profile:
	    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
	    prefix: /admin/profile

	fos_user_register:
	    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
	    prefix: /admin/register

	fos_user_resetting:
	    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
	    prefix: /admin/resetting

	fos_user_change_password:
	    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
	    prefix: /admin/profile

I have overwrite the login template at `app/Resources/FOSUserBundle/views/Security/login.html.twig`. (if source is needed I can provide just ommit for not make the post longer than it's already). 

When I call the URL: `http://domain.tld/app_dev.php/admin` and try to login I got this error:

> Translation not found.
> Context: { "id":
> "Symfony\\Component\\Security\\Core\\Exception\\BadCredentialsException:
> Bad credentials. in
> /var/www/html/platform-cm/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/UserAuthenticationProvider.php:90\nStack
> trace:\n#0

(I can provide the full stacktrace if needed)

this is weird to me but perhaps it's caused for a bad configuration since I have double checked credentials.

When I call the URL: `http://domain.tld/app_dev.php/chat` and try to login I got `Access Denied` but it's right because I am redirected to `http://domain.tld/app_dev.php/admin/`. Can any give me some help on this configuration? I am stuck and can't move forward because of this

 [1]: http://stackoverflow.com/questions/21390276/fosuserbundle-different-login-pages
 [2]: http://stackoverflow.com/questions/9826370/symfony2-fosuserbundle-multiple-login-locations
 [3]: https://github.com/FriendsOfSymfony/FOSUserBundle/issues/849
 [4]: http://stackoverflow.com/questions/17240827/how-to-set-a-login-form-for-admins-and-another-for-other-users-using-fosuserbund/17240828

**Comment by stof** [comment]
Well, the login check path must be under the pattern of the firewall. So you cannot use the same route for both.

I'm closing this issue as it is not related to FOSUserBundle but to a misconfiguration of SecurityBundle (authentication is not a feature handed by FOSUserBundle)
