### ISSUE TITLE
Multi type query

### ISSUE THREAD

**Issue by portey** [FriendsOfSymfony/FOSUserBundle#2045]
Hello,
I want to query over two types in my mapping. I can't find realization of needed SearchableInterface, there are DinamicIndex, but it's deprecated.

Have somebody any idea how can I do this?

**Comment by portey** [comment]
Sorry for new issue, I decided to use FOS\ElasticaBundle\Elastica\Index, where i can past my type name.

**Comment by xabbuh** [comment]
I guess you are confusing repositories. :) This is the FOSUserBundle repository. Can you please close your issue here?

**Comment by portey** [comment]
Oh, my mistake, I confuse with FOSElasticaBundle. Yes, I close this one.
