### ISSUE TITLE
2 user class in fosuserbundle

### ISSUE THREAD

**Issue by fabirus** [FriendsOfSymfony/FOSUserBundle#2046]
Hello, please i have some problem, what is the solution to use 2 differents classes with fosuserbundle...
one class for support party of my website, another to adminstration...
thanks you

**Comment by xabbuh** [comment]
Why do you need two different classes for this use case and don't simply use different roles for the two sections of your application?

**Comment by fabirus** [comment]
hello because i override the template of fosuserbundle in admin party... and i want different render for the profile template in support party

**Comment by xabbuh** [comment]
Not sure I understand what you mean with party and how that is related to your user class.

**Comment by fcpauldiaz** [comment]
I also want to have two user classes but I'm not sure if this is even possible, I don't want to use roles because that will mean that a lot of fields will be set to null in the database and I don't want that. 
Do you know if it is possible to use 2 user class? @xabbuh

**Comment by fcpauldiaz** [comment]
This is how you can use two user classes. [Multiple user providers](http://symfony.com/doc/current/cookbook/security/multiple_user_providers.html) @fabirus

**Comment by JHGitty** [comment]
https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2094
