### ISSUE TITLE
Attempted to call an undefined method named "getUnifOfWork"

### ISSUE THREAD

**Issue by kevinvergauwen** [FriendsOfSymfony/FOSUserBundle#2051]
Attempted to call an undefined method named "getUnifOfWork" of class "Doctrine\ORM\EntityManager".
Did you mean to call "getUnitOfWork"?

This is clearly a typo.

Stack trace:

in vendor/friendsofsymfony/user-bundle/Doctrine/UserListener.php at line 111 

        $meta = $om->getClassMetadata(get_class($user));
        if ($om instanceof EntityManager) {
            $om->getUnifOfWork()->recomputeSingleEntityChangeSet($meta, $user);
            return;
        }

**Comment by stloyd** [comment]
This was fixed few minutes ago by #2049.

**Comment by kevinvergauwen** [comment]
Super!
