### ISSUE TITLE
Non-existent service "fos_user.entity_manager"

### ISSUE THREAD

**Issue by adrx** [FriendsOfSymfony/FOSUserBundle#2055]
Since upgrading from user-bundle dev-master e5e7a2b to dev-master 8f1fc22 I am getting these messages:

>  [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
> 
>   The service "adrx_common.user_manager" has a dependency on a non-existent service 
> "fos_user.entity_manager".

adrx_common.user_manager is a service that extends fos_user.user_manager but uses the same dependencies:

adrx_common.user_manager:
        class: Adrx\Bundle\CommonBundle\Util\UserManager
        arguments:
             - @security.encoder_factory
             - @fos_user.util.username_canonicalizer
             - @fos_user.util.email_canonicalizer
             - @fos_user.entity_manager
             - %fos_user.model.user.class%

if I roll back to dev-master e5e7a2b the "non-existent service" messages disappear.

My symfony2 version is v.2.7.9

**Comment by adrx** [comment]
Answering my own question:
A commit on Jan 26th removed fos_user.entity_manager and substituted fos_user.object_manager

**Comment by greg0ire** [comment]
Providing the commit hash would have been great :P

**Comment by stof** [comment]
This service is clearly internal (and it may be removed again before 2.0 stable as I want to avoid early loading of Doctrine metadata and be compatible with entity manager resetting, and this might imply changing how I inject Doctrine). You should avoid depending on it directly. It is not part of the FOSUserBundle supported services.
