### ISSUE TITLE
UserListener::preUpdate() must be an instance of LifecycleEventArgs.

### ISSUE THREAD

**Issue by jeffersonM** [FriendsOfSymfony/FOSUserBundle#2059]
When you enter the login method, then, is the direction of the route login_check , I get the following error.

`ContextErrorException: Catchable Fatal Error: Argument 1 passed to FOS\UserBundle\Doctrine\UserListener::preUpdate() must be an instance of Doctrine\Common\Persistence\Event\LifecycleEventArgs, instance of Doctrine\ORM\Event\PreUpdateEventArgs given, called in /var/www/solicitud_cupos/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php on line 63 and defined in /var/www/solicitud_cupos/vendor/friendsofsymfony/user-bundle/Doctrine/UserListener.php line 76`

Version: Symfony 2.3.37

Thank you for your help

**Comment by xabbuh** [comment]
Which Doctrine version do you use?

**Comment by jeffersonM** [comment]
Version Doctrine  from composer >=2.2.3,<2.4-dev

**Comment by Tanariel** [comment]
Hello,
I'm having somehow the same problem, so i put it here in case it's related.

I updated my version of Symfony from 2.7.x to 2.8.2 and i now get this error.
I'm using "friendsofsymfony/user-bundle": "~2.0@dev".

Catchable Fatal Error: Argument 1 passed to FOS\UserBundle\Doctrine\UserListener::prePersist() must be an instance of Doctrine\Common\Persistence\Event\LifecycleEventArgs, instance of Doctrine\ORM\Event\LifecycleEventArgs given, called in /home/snack.bg/dev/Symfony/vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/ContainerAwareEventManager.php on line 63 and defined

**Comment by Tanariel** [comment]
Problem solved by updating composer.json to : 

"doctrine/orm": "2.4.*"

**Comment by stof** [comment]
doctrine ORM 2.3 is unmaintained since several years. FOSUserBundle 2.0-dev dropped support for it. So I'm closing the issue.
