### ISSUE TITLE
APC doesnt save properties in fosuserbundle extended class

### ISSUE THREAD

**Issue by andrzejdziekonski** [FriendsOfSymfony/FOSUserBundle#2061]
I have a problem with joining my Article entity with User (which extends FosUserBundle class). It works nice when i query database for it, but when i use APC: 
$driver = \Doctrine\Common\Cache\ApcCache();
$driver->save($key, $queryResult), and then ask for $driver->fetch($key) I receive data only for core FosUserBundle columns (id, email etc), but NULLS for my extra columns.

I have:
```
mappings:
   FOSUserBundle: ~
```
in my orm default entity manager configuration. Any idea what might happen?

**Comment by stof** [comment]
Well, this is because we implement Serializable (as it is the only way to make serialization works reliably for an entity due to the usage of proxies). If you want to include your own fields in the serialization data, overwrite the Serializable implementation to include them
