### ISSUE TITLE
redirect change password

### ISSUE THREAD

**Issue by naeem90** [FriendsOfSymfony/FOSUserBundle#2062]
what will be the option in security.firewalls.main for change password to redirect it to specified service

**Comment by stof** [comment]
I don't understand what you mean. Changing the password is not handled by the firewall of the security component.

**Comment by naeem90** [comment]
i want to route change_password to the route specified by me

**Comment by rparsi** [comment]
@naeem90 Easiest way is to listen for specific form event and implement your response/redirect.  Refer to http://symfony.com/doc/current/bundles/FOSUserBundle/overriding_forms.html.

**Comment by metalmini** [comment]
Posting passwords should always respond with a redirect. Which it does, when you don't get errors on the form. But if the passwords don't match you get a 200 response, this will be cached by the browser. This could be seen as a vulnerability. This was a minor problem after a PEN test in our application. https://www.owasp.org/index.php/Testing_for_logout_functionality_%28OTG-SESS-006%29

**Comment by stof** [comment]
> this will be cached by the browser

Only if you add cache headers. By default, pages are not cachable in responses sent by Symfony
