### ISSUE TITLE
Support propel/propel-bundle >=1.5: propel UniqueObject validator constraint for propel bundle

### ISSUE THREAD

**Issue by uddhab** [FriendsOfSymfony/FOSUserBundle#2068]
The source `FOSUserBundle/Resources/config/storage-validation/propel.xml` uses `Propel\PropelBundle\Validator\Constraints\UniqueObject`.

This should be updated to `Propel\Bundle\PropelBundle\Validator\Constraints\UniqueObject` from propel/propel-bundle 1.5 or above.

**Comment by Lionel09** [comment]
:+1:

**Comment by xabbuh** [comment]
Imo the PropelBundle should maintain the old constraint namespace as long as they are not bumping the major version. Everything else is a BC break and hard to deal with in other bundles.

**Comment by stof** [comment]
totally agree. Not following semver is a shame at the time of composer

**Comment by xabbuh** [comment]
PropelBundle 1.5.1 should fix this.

**Comment by uddhab** [comment]
@xabbuh Yes. Great. :+1:
