### ISSUE TITLE
password (plainPassword first and second fields) in form are not encrypted/encoded [POST request]

### ISSUE THREAD

**Issue by ValleJulien** [FriendsOfSymfony/FOSUserBundle#2069]
In my secutity.yml I have this in order to use bcrypt encoder:

```
security:
    # FOS UserBundle needles
    encoders:
        Symfony\Component\Security\Core\User\User: bcrypt
        MyNamespace\MyBundle\Entity\User: bcrypt
        FOS\UserBundle\Model\UserInterface: bcrypt
```

I call the fos user registration form in an embeded form like this:
```
$builder
  ->add('contactPhone')
  ->add('contactMobilePhone')
  ->add('user', 'fos_user_registration', array(
                                               'label' => false,
      ))
```

It renders me [this ](http://stackoverflow.com/questions/35413190/fosuserbundle-password-plainpassword-are-not-encrypted-on-submit-post-form)for example (follow the link and see the image in the stack question, thank you)

But when I submit the form, I could see in the network console browser that my password are in plain text and everybody could use them.

So I can recover all datas of my POST request in the console browser like this for example:
    

>     my_form[user][email]=test@test.com
> 
>     my_form[contactPhone]=0404040404
> 
>     my_form[contactMobilePhone]=0606060606
> 
>     my_form[user][username]=test
> 
>     my_form[user][plainPassword][first]=test // first password entry
> 
>     my_form[user][plainPassword][second]=test // verification
> 
>     my_form[save] // submit my_form[_token_consumer]=// no need to see him

How I need to proceed in order to encode my password(s) when submit ?

You could understand that iit's not secured. I need to encode the password when I submit the form in order to not allow everybody to see them.

**Note that the same thing occured when I log myself with the FOSUserBundle user login form.**

**Comment by stof** [comment]
When, the solution to encrypt passwords during form submissions is to use HTTPS for the transmission. HTML forms don't have any feature to encode their data before submission (this is what HTTPS is for).

**Comment by ValleJulien** [comment]
My application will be on a HTTPS server, but that I reaaly wanted to know if if my code is safe and if this behavior is "normal".

**Comment by stof** [comment]
Yes, it is normal. The browser console shows you the content of the request. It can read it as it stands before (or after depending of the PoV) the HTTPS encryption.
If you want to know what goes over the network, use a network inspector (for instance wireshark), not the browser console (which does not show you what goes over the network exactly, for instance in the case of HTTPS where it is able to show the content, which is much better for its use case).

Anyway, I'm closing this issue as it is not related to FOSUserBundle at all (it is about how HTTPS works)

**Comment by ValleJulien** [comment]
Sorry for the issue, like I told you, I wanted to know if  my code is safe or If there is a way to secure this better.
Thank you by the way.
