### ISSUE TITLE
step in register

### ISSUE THREAD

**Issue by jomalix** [FriendsOfSymfony/FOSUserBundle#2077]
Hi!
First sorry for bad English...!

I search how I can include one step in my inscription.
I have the fosuserbundle form, after I want in an other template an other form (it's already OK), And I want the over form before sending the mail.

I haven't good idea for do it, try to override RegistrationController.php but I don't thinks is the good plan.

I want your idea

thinks and sorry again for bad English!

**Comment by stof** [comment]
Well, what you could do is disable the FOSUserBundle confirmation email, and then handle the email on your own after your own form.

**Comment by jomalix** [comment]
it's a good idea, thinks!
