### ISSUE TITLE
[doc] Error in overriding_controllers.rst

### ISSUE THREAD

**Issue by javiereguiluz** [FriendsOfSymfony/FOSUserBundle#2080]
As reported in http://symfony.com/doc/build_errors:

```
Errors for "friendsofsymfony-fosuser-bundle/master"

overriding_controllers.rst:11: WARNING: unknown document: events </controller_events>`
```

**Comment by stof** [comment]
@javiereguiluz what is the frequency of updates of the doc on symfony.com (to know when I can check that my fix was indeed enough) ?

**Comment by javiereguiluz** [comment]
Docs are built hourly, but the full error logs are generated daily (at 3 AM CET).

**Comment by stof** [comment]
Then, I will look at it again in 1 week, after my vacations (unless I forget it, in which case feel free to open an issue if there are other warnings)
