### ISSUE TITLE
Deprecated setFactory...

### ISSUE THREAD

**Issue by infinitely-young** [FriendsOfSymfony/FOSUserBundle#2082]
Please, can you fix this deprecation's:
setFactoryService, setFactoryMethod, setFactoryClass, etc.

Thanks!

**Comment by JHGitty** [comment]
It would be nice if you may send use links to the lines in the code where deprecated code has been found.

**Comment by stof** [comment]
The master branch of FOSUserBundle is already updated (or at least it should be)

**Comment by XWB** [comment]
This has been fixed in master.
