### ISSUE TITLE
Fatal error when login route is accessed from app_dev.php

### ISSUE THREAD

**Issue by starx** [FriendsOfSymfony/FOSUserBundle#2083]
On Symfony 3:

When the login is accessed from `app_dev.php`, you get a `500 Server Error`

> Key "request" for array with keys "name" does not exist in FOSUserBundle::layout.html.twig

**Comment by damienalexandre** [comment]
Can you provide more informations? Which version of FOSUserBundle are you using? Did you extends the controllers? What is your fos_user configuration?

**Comment by stof** [comment]
This looks like you are overriding the Twig ``app`` global variable with something else than the variable shipped in TwigBundle. This is not something we want to support.
