### ISSUE TITLE
PHPCR support

### ISSUE THREAD

**Issue by ranchmed** [FriendsOfSymfony/FOSUserBundle#2087]
I am working on a fork of the FOSUserBundle to add support for the PHPCR physical layer. I am almost done, but have come up against an issue concerning the uniqueness constraints for the canonical usernames and emails. The uniqueness constraints for the phpcr are not available from what I can tell, so we are forced to do something else, or implement a custom constraint within this bundle.

My question concerns approach (I am moving from Drupal to Symfony so I am climbing a learning curve). Should I do a Pull Request and submit what I have to start a dialog about best approach, or do we discuss this issue as an enhancement here?

**Comment by XWB** [comment]
You may send a PR, we can discuss the implementation.

**Comment by stof** [comment]
I suggest you to submit an implementation of uniqueness constraint to the PHPCR bundle, or at least a feature request there. I'd rather not ship such an implementation in FOSUserBundle itself, as it is more the job of the PHPCR bundle.
