### ISSUE TITLE
password recovry: route path issue in Mailer 1.3.6 with symfony 2.8

### ISSUE THREAD

**Issue by NicoD** [FriendsOfSymfony/FOSUserBundle#2088]
in the 1.3.6 Mailer, UrlGeneratorInterface::generate method calls are not compatible with symfony 2.8 because they've change URL type constant value.

`$this->router->generate('fos_user_registration_confirm', array('token' => $user->getConfirmationToken()), true);`
should be
`$this->router->generate('fos_user_registration_confirm', array('token' => $user->getConfirmationToken()), UrlGeneratorInterface::ABSOLUTE_URL);`

**Comment by 1ed** [comment]
Please see https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2070#issuecomment-185117000

**Comment by XWB** [comment]
See above.
