### ISSUE TITLE
After composer update parent entity fields are dropped

### ISSUE THREAD

**Issue by StefanGlaesser** [FriendsOfSymfony/FOSUserBundle#2089]
Hello,

after upgrading an existing symfony 2.7.10 application the fos user bundle fields have been dropped from the user table:

    php app/console doctrine:schema:update --dump-sql
    DROP INDEX UNIQ_4690EDA392FC23A8 ON my_user;
    DROP INDEX UNIQ_4690EDA3A0D96FBF ON my_user;    
    ALTER TABLE my_user DROP username, DROP username_canonical, DROP email, DROP email_canonical, DROP enabled, DROP salt, DROP password, DROP last_login, DROP locked, DROP expired, DROP expires_at, DROP confirmation_token, DROP password_requested_at, DROP roles, DROP credentials_expired, DROP credentials_expire_at;

Restoring the entity from a backup results in same affect when repeating the command. What's the problem with it?

This is my configuration:
composer.json

> {
    "name": "symfony/framework-standard-edition",
    "license": "MIT",
    "type": "project",
    "description": "The \"Symfony Standard Edition\" distribution",
    "autoload": {
        "psr-0": { "": "src/" }
    },
    "require": {
        "php": ">=5.3.3",
        "symfony/symfony": "2.7.*",
        "doctrine/orm": "~2.2,>=2.2.3",
        "doctrine/doctrine-bundle": "1.2.*",
        "twig/extensions": "1.0.*",
        "symfony/assetic-bundle": "dev-master",
        "symfony/swiftmailer-bundle": "2.3.*",
        "symfony/monolog-bundle": "2.3.*",
        "sensio/distribution-bundle": "2.3.*",
        "sensio/framework-extra-bundle": "2.3.*",
        "sensio/generator-bundle": "2.3.*",
        "incenteev/composer-parameter-handler": "~2.0",
	    "mopa/bootstrap-bundle": "~3.0",
        "twbs/bootstrap": "dev-master",
	    "white-october/pagerfanta-bundle": "@stable",
	    "friendsofsymfony/jsrouting-bundle": "@stable",
        "friendsofsymfony/user-bundle": "~2.0@dev",
        "jms/i18n-routing-bundle": "@stable",
	    "knplabs/knp-menu-bundle": "~2.0",
        "beberlei/DoctrineExtensions": "*",
	    "whiteoctober/tcpdf-bundle": "dev-master",
        "willdurand/js-translation-bundle": "^2.5"
    },
    "scripts": {
        "post-install-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile"
        ],
        "post-update-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile"
        ]
    },
    "config": {
        "bin-dir": "bin"
    },
    "minimum-stability": "stable",
    "extra": {
        "symfony-app-dir": "app",
        "symfony-web-dir": "web",
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        },
        "branch-alias": {
            "dev-master": "2.3-dev"
        }
    },
    "require-dev": {
        "tchwork/debug-bundle": "^1.4"
    }
}

**Comment by StefanGlaesser** [comment]
Got it - ppdating Doctrine fixes the problem for me:

        "doctrine/orm": "^2.5.4",
        "doctrine/doctrine-bundle": "~1.4",

**Comment by guldil** [comment]
Hi

I have same problem with Symphony 2.3.39 ...

`"require": {
        "php": ">=5.3.3",
        "symfony/symfony": "2.3.*",
        "doctrine/orm": "~2.2,>=2.2.3",
        "doctrine/doctrine-bundle": "1.2.*",
        "doctrine/doctrine-fixtures-bundle": "dev-master",
        "doctrine/data-fixtures": "@dev",
        "twig/extensions": "1.0.*",
        "symfony/assetic-bundle": "2.3.*",
        "symfony/swiftmailer-bundle": "2.3.*",
        "symfony/monolog-bundle": "2.3.*",
        "sensio/distribution-bundle": "2.3.*",
        "sensio/framework-extra-bundle": "2.3.*",
        "sensio/generator-bundle": "2.3.*",
        "incenteev/composer-parameter-handler": "~2.0",
        "friendsofsymfony/user-bundle": "~2.0@dev",
        "kitpages/data-grid-bundle": "~2.0",
        "phpoffice/phpexcel" : "1.8.0",
        "oneup/uploader-bundle": "~1.3",
        "whiteoctober/tcpdf-bundle": "^1.0",
        "knplabs/knp-snappy-bundle": "^1.4"
    },`

**Comment by guldil** [comment]
fixed with "doctrine/doctrine-bundle": "1.3.*"
