### ISSUE TITLE
Add  field company in table fos_user table

### ISSUE THREAD

**Issue by ajcostaltda** [FriendsOfSymfony/FOSUserBundle#2090]
I have a company ManyToMany field in fos_user table ,
I need to authenticate by User , company and password. A user can access a more business . After logging in, I need to know which company the user has selected to filter products, sales , company purchases selected for the user. Can anyone help me , have created the field, just do not know how to implement the login form and authenticate .

**Comment by fcpauldiaz** [comment]
I think you should not login by company. If you do, you would have to search a user by company and a company may have multiple users, so it might be a problem modifying the user provider. I think it would be easier to make a form after logging in and there ask the user what company wants to show.

If you still want to do this, you can make a form to search the company and show the two forms in the login view, so the user won't notice the difference but you wouldn't be logging in by company just making a custom query to show only the data of that selected company.

**Comment by stof** [comment]
This looks like you need your own authentication system, which is outside the scope of this bundle (as it does not implement authentication at all but user management).
You may use the Guard system of Symfony 2.8+ to achieve it.

anyway, closing this as it is not related to FOSUserBundle.
