### ISSUE TITLE
Unique email constraint for multiple User extending classes throws error.

### ISSUE THREAD

**Issue by dutchiexl** [FriendsOfSymfony/FOSUserBundle#2091]
I have a User class that extends the baseuser, and 2 classes that extend the user class (Mentor and Mentee).

When I try to create a Mentee with an email address that already exists, the validation works fine. But when I try to register a Mentor with an email address that is already used by a Mentee, the entity is treated as valid, but the DB throws an error  (as it should) because of the unique id constraint on DB level.

How can I make sure the unique email validation is checked for all Users and not one subgroup ?

```
class User extends BaseUser{}

class Mentor extends User{}

class Mentee extends User{}
```

```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'myemail@gmail.com' for key 'UNIQ_8D93D64992FC23A8'
```

**Comment by stof** [comment]
The Symfony UniqueEntity validator is known to have a hard time with the entity inheritance feature of Doctrine.
As entity inheritance has many gotchas in Doctrine as well (and it cannot be otherwise by definition of the feature), my best advice is to avoid using it.

**Comment by stof** [comment]
The Symfony UniqueEntity validator is known to have a hard time with the entity inheritance feature of Doctrine.
As entity inheritance has many gotchas in Doctrine as well (and it cannot be otherwise by definition of the feature), my best advice is to avoid using it.
