### ISSUE TITLE
Multi User application 

### ISSUE THREAD

**Issue by napestershine** [FriendsOfSymfony/FOSUserBundle#2094]
Hi

I am using FOSUserBundle for user management, How can i provide two user based application?

**Comment by stof** [comment]
Well, if you want to use 2 different user classes, FOSUserBundle alone won't be suited for that. This is out of the scope of this bundle.

**Comment by napestershine** [comment]
So i have to do it manually for sf2 application?

**Comment by stof** [comment]
Well, if your goal is to have multiple user classes, there are some bundles providing this on top of FOSUserBundle AFAIK. But I never tried them.

**Comment by JHGitty** [comment]
https://github.com/PUGX/PUGXMultiUserBundle

**Comment by XWB** [comment]
See above.
