### ISSUE TITLE
Extract business logic from controllers

### ISSUE THREAD

**Issue by bblue** [FriendsOfSymfony/FOSUserBundle#2097]
From my very limited experience with this bundle it appears to me that the controllers could do well with a refactoring to extract the business logic into services. This will increase the possible use-cases for the bundle.

For instance, I would like to auto-register users when logging in via a third party (i.e facebook, google etc.). Currently a lot of the business logic for registering a user is found within the controllers, so I need to duplicate a lot of the same code.

**Comment by stof** [comment]
the logic being inside the controller is almost always limited to a few things:

- handling forms, which totally belongs to the controller, not to services deeper (unless you want to make the controller a one-liner calling a service doing everything, which is pointless as it just moves the logic as a whole)
- calling the UserManager service to save changes in the DB
- dispatching events at different points (before handling the form, before saving and after saving) to allow business logic to hook into this process.
- generating a final response (either a redirect or rendering a template), unless a response was provided through the events being dispatched

I don't really see what you would want to extract from there.

**Comment by SakyaStelios** [comment]
[A way to integrate FosUserBundle and HWIOAuthBundle](https://gist.github.com/danvbe/4476697)

**Comment by stof** [comment]
Well, there is nothing in your gist duplicating code of FOSUserBundle (note that I haven't read the whole bunch of comments, I only considered the implementation provided in the gist)

**Comment by bblue** [comment]
I quite possibly made an error here then, what you say makes sense. I had been at it for 15+ hours when I wrote the post, so my brain was hurting.

I was hoping for a single registerNewUser() type of method that would trigger all magic for me, but looking at my code it is not too much excess.

**Comment by stof** [comment]
Well, would you pass many arguments to this method to set each field of the User ? The Form system is what does it in FOSUserBundle.
