### ISSUE TITLE
how to overriding fosuserbundle change password form style ?

### ISSUE THREAD

**Issue by suhasini1212** [FriendsOfSymfony/FOSUserBundle#2098]

**Comment by JHGitty** [comment]
http://symfony.com/doc/current/book/templating.html#overriding-bundle-templates
This is a main question how to override Twig templates in Symfony, right? So there is no issue on this bundle. Please close this issue here.

**Comment by Naskalin** [comment]
Same problem. I have when overriding the templates folder "ChangePassword" also does not work. It is this folder, with all the other all ok

**Comment by ThomasTr** [comment]
Same here: can not overwrite FOSUserBundle:ChangePassword:change_password_content.html.twig

**Comment by mysiar** [comment]
hi guys, no problem to over write change password twig template,

check this out
https://github.com/mysiar/Invoice/blob/master/app/Resources/FOSUserBundle/views/ChangePassword/changePassword_content.html.twig

and how it looks like
https://github.com/mysiar/Invoice/blob/master/web/img/password.change.png

hope this helps

**Comment by XWB** [comment]
Not related to this bundle => closing.
