### ISSUE TITLE
Bad credentials only on remote server

### ISSUE THREAD

**Issue by Zamoud** [FriendsOfSymfony/FOSUserBundle#2099]
I use FOSUserBundle to provide user authorization and registration.
Everything works fine, on loacl and remote server.
But sometimes on remote server I cain't login!

Error in log file is
 
`exception 'Symfony\Component\Security\Core\Exception\BadCredentialsException' with message 'Bad credentials' in /var/www/monsite/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/UserAuthenticationProvider.php:73 Stack trace: #0 /var/www/monsite/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php(147): session_start() #1 /var/www/monsite/vendor/symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php(281) ...`

configartion: 
Symfony 2.4.10
Host : shared host (OVH)

**Comment by JHGitty** [comment]
1. Symfony 2.4 is out of support / EOL. 
http://symfony.com/doc/current/contributing/community/releases.html#schedule

2. Please provide us more information when this happens and provide us some code examples.

**Comment by stof** [comment]
> I use FOSUserBundle to provide user authorization

FOSUserBundle does not provide such feature. This is provided by Symfony itself
