### ISSUE TITLE
Results do not response back to Modal Window

### ISSUE THREAD

**Issue by napestershine** [FriendsOfSymfony/FOSUserBundle#2100]
HI

I am not understanding when ajax call is working then what it will return back?

Please take a look at: https://github.com/napestershine/tesstone

Thanks

**Comment by xabbuh** [comment]
The controllers in this bundle do not have any special handling in case they are called via AJAX requests.

**Comment by stof** [comment]
If you want such special handling, write your own controllers IMO (or maybe just your own templates if it can be enough).
Forcing it to return a modal layout when called through AJAX will not be done directly in the bundle:
- it would couple the bundle to a particular CSS framework (as they all have a different markup for modals)
- it would force using modals when doing AJAX, while AJAX could be used for other reasons (AJAX-based page loading with pjax or similar tools for instance).
