### ISSUE TITLE
Controller results fail always

### ISSUE THREAD

**Issue by napestershine** [FriendsOfSymfony/FOSUserBundle#2101]
HI

Here is my registration controller overrides from FOS

`  public function registerAction(Request $request)
    {

        if ($request->isXmlHttpRequest()) {
            /** @var $formFactory \FOS\UserBundle\Form\Factory\FactoryInterface */
            $formFactory = $this->get('fos_user.registration.form.factory');
            /** @var $userManager \FOS\UserBundle\Model\UserManagerInterface */
            $userManager = $this->get('fos_user.user_manager');
            /** @var $dispatcher \Symfony\Component\EventDispatcher\EventDispatcherInterface */
            $dispatcher = $this->get('event_dispatcher');
            $user = $userManager->createUser();
            $user->setEnabled(true);
            $event = new GetResponseUserEvent($user, $request);
            $dispatcher->dispatch(FOSUserEvents::REGISTRATION_INITIALIZE, $event);
            if (null !== $event->getResponse()) {
                return $event->getResponse();
            }
            $form = $formFactory->createForm();
            $form->setData($user);
            $form->handleRequest($request);
            if ($form->isValid()) {
                $event = new FormEvent($form, $request);
                $dispatcher->dispatch(FOSUserEvents::REGISTRATION_SUCCESS, $event);
                $userManager->updateUser($user);
                if (null === $response = $event->getResponse()) {
                    $url = $this->generateUrl('fos_user_registration_confirmed');
                    $response = new RedirectResponse($url);
                }
                $dispatcher->dispatch(FOSUserEvents::REGISTRATION_COMPLETED,
                    new FilterUserResponseEvent($user, $request, $response));
                return $response;
            }
        } else {
            /** @var $formFactory \FOS\UserBundle\Form\Factory\FactoryInterface */
            $formFactory = $this->get('fos_user.registration.form.factory');
            /** @var $userManager \FOS\UserBundle\Model\UserManagerInterface */
            $userManager = $this->get('fos_user.user_manager');
            /** @var $dispatcher \Symfony\Component\EventDispatcher\EventDispatcherInterface */
            $dispatcher = $this->get('event_dispatcher');
            $user = $userManager->createUser();
            $user->setEnabled(true);
            $event = new GetResponseUserEvent($user, $request);
            $dispatcher->dispatch(FOSUserEvents::REGISTRATION_INITIALIZE, $event);
            if (null !== $event->getResponse()) {
                return $event->getResponse();
            }
            $form = $formFactory->createForm();
            $form->setData($user);
            $form->handleRequest($request);
            if ($form->isValid()) {
                $event = new FormEvent($form, $request);
                $dispatcher->dispatch(FOSUserEvents::REGISTRATION_SUCCESS, $event);
                $userManager->updateUser($user);
                if (null === $response = $event->getResponse()) {
                    $url = $this->generateUrl('fos_user_registration_confirmed');
                    $response = new RedirectResponse($url);
                }
                $dispatcher->dispatch(FOSUserEvents::REGISTRATION_COMPLETED,
                    new FilterUserResponseEvent($user, $request, $response));
                return $response;
            }
            return $this->render('FOSUserBundle:Registration:register.html.twig', array(
                'form' => $form->createView(),
            ));
        }
    }`

**Comment by xabbuh** [comment]
What issue exactly do you have with your controller?

**Comment by napestershine** [comment]
@xabbuh  Thanks so much.
1. It's not returning something while ajax call expects that this controller return something.
2. I tried to return some text or Json or twig but in all cases it either returns true or false in all cases.

Is there any particular steps that need to follow to make FOS controllers working with ajax calls?

Thanks

**Comment by xabbuh** [comment]
In case of AJAX requests your controller does not return anything at all when the form is not valid. And what do you mean with "it either returns true or false in all cases"? How did you check that? Does Symfony complain that your controller does not return a `Response` instance?

**Comment by napestershine** [comment]
@xabbuh  thanks so much but I got solution of problem, and I guess it's problem of most of people i searched on Internet. Also I made a git repo for that. 


You can check this here:
https://github.com/napestershine/tesstone

Thanks
