### ISSUE TITLE
Problem with reset password

### ISSUE THREAD

**Issue by Clowning** [FriendsOfSymfony/FOSUserBundle#2104]
Hey everybody,

i implemented FOSUserBundle and everything work correctly but i have a problem with Resetting / password forgotten... The email isn't send... but when a user is register he receive a mail... i don't understand ! So if you have some idea to help me.. :) ! 

Thanks

**Comment by dmaicher** [comment]
Well without any further info its quite impossible to help you with that issue ;)

Did you try to debug it yourself?

**Comment by XWB** [comment]
We cannot help you without any debug info.
