### ISSUE TITLE
Fatal error on clearing cache after uninstalling bundle

### ISSUE THREAD

**Issue by martixy** [FriendsOfSymfony/FOSUserBundle#2105]
What the title says.

```
[RuntimeException]
An error occurred when executing the ""cache:clear --no-warmup"" command:
Fatal error: Class 'FOS\UserBundle\FOSUserBundle' not found in D:\WebDev\Projects\[...]\app\AppKernel.php on line 20
PHP Fatal error:  Class 'FOS\UserBundle\FOSUserBundle' not found in D:\WebDev\Projects\
[...]\app\AppKernel.php on line 20
```

It resulted when I reverted to a previous version of the project and ran `composer install`.
Version is `~2.0@dev`, whatever that means, with Symfony 3.0.4.
Let me know if you need more information or if this is the wrong place to take this problem.

**Comment by XWB** [comment]
Please us the latest master version.
