### ISSUE TITLE
SwiftmailerBundle dependency

### ISSUE THREAD

**Issue by mmoreram** [FriendsOfSymfony/FOSUserBundle#2113]
I would like to discuss the dependency between FOSUserBundle and SwiftMailer.

I added in my project the dependency with FOSUserBundle but I don't really need the mailing feature, so in my composer.json file I don't have this dependency.
The result of this is that FOSUserBundle expects a service called mailer, and by default this service is defined in SwiftMailer, but of course I don't have this package.

So, looking for clues in the package, I see that the service mailer can  be overwritten by configuration, but this means that I need a mailer service anyway... so...

Some extra hints here?

In the case you don't want to make a strong dependency between both bundles because you propose a way of overwritting (that would a reason **any** bundle could follow because you can overwrite whatever you want in the DIC), then you should be dependency with an interface package, right? Composer Virtual packages.

Thanks.

**Comment by mmoreram** [comment]
BTW, maybe you have this *issue* with other dependencies?

**Comment by stof** [comment]
configure the bundle to use its noop mailer service, and it won't depend on SwiftmailerBundle

**Comment by mmoreram** [comment]
OK, true.

Thanks.
