### ISSUE TITLE
This user instance is not supported by the Propel UserManager implementation

### ISSUE THREAD

**Issue by exchentrix** [FriendsOfSymfony/FOSUserBundle#2114]
Hey,

I'm trying to add some users to my database. I'm using symfony3, propel2 and the FOSUserBundle:

    fos_user:
        db_driver: propel
        user_class: ApiBundle\Model\Acl\Customer\Customer
        firewall_name: api

My model (which is generated by Propel):

    <?php

    namespace ApiBundle\Model\Acl\Customer;

    use ApiBundle\Model\Acl\Customer\Base\Customer as BaseCustomer;
    use FOS\UserBundle\Model\UserInterface;

    class Customer extends BaseCustomer implements UserInterface
    {
        ...
    }

Controller

    public function putCustomersAction(Request $request)
    {
        $customer = new Customer();
        $form = $this->formService->createForm(CustomerType::class, $customer, $request);

        if ($form->isValid()) {

            $this->userManager->updateUser($customer);
            return $customer;
        }

        return $form;
    }

However, if I try to use the Propel Usermanager to update an user it comes up with an error. The action from above results in a

    {
        "code": 500,
        "message": "This user instance is not supported by the Propel UserManager implementation",
        "errors": null
    }

Is there something, I do wrong?

From the Propel UserManager (FOS\UserBundle\Propel\UserManager)

    public function updateUser(UserInterface $user)
    {
        if (!$user instanceof \Persistent) { // There is no \Persistent class in my Vendor directory
            throw new \InvalidArgumentException('This user instance is not supported by the Propel UserManager implementation');
        }

        $this->updateCanonicalFields($user);
        $this->updatePassword($user);
        $user->save();
    }

**Comment by xabbuh** [comment]
You need to use the base class provided by FOSUserBundle or extend that class: https://symfony.com/doc/master/bundles/FOSUserBundle/index.html#d-propel-1-x-user-class

**Comment by XWB** [comment]
See above.
