### ISSUE TITLE
Attempted to load class \"PropelQuery\" from the global namespace

### ISSUE THREAD

**Issue by exchentrix** [FriendsOfSymfony/FOSUserBundle#2115]
Hey,

I'm using FOS_UserBundle and I'm trying to load some users from my database. I'm also using fos_oauth. Hower, sending an POST to my oauth token endpoint results in an error:

POST /oauth/token

```
{
    "grant_type":"password",
    "client_id":CLIENT_ID,
    "client_secret":SECRET,
    "username":"foo@bar.de",
    "password":"foobar"
}
```

results in the following error:

```
{
    "code": 500,
    "message": "Attempted to load class \"PropelQuery\" from the global namespace.\nDid you forget a \"use\" statement for \"Propel\\Runtime\\ActiveQuery\\PropelQuery\"?",
    "errors": null
}
```

in friendsofsymfony/user-bundle/Propel/UserManager.php line 114

My fos user config:

```
fos_user:
    db_driver: propel
    user_class: ApiBundle\Model\Acl\Customer\Customer
    firewall_name: api
```

From the propel UserManager (FOS\UserBundle\Propel\UserManager)

```
protected function createQuery()
{
    return \PropelQuery::from($this->class); // There is no \PropelQuery in the global namespace
}
```

If I use the correct use statement in the header of the file, everything is working as expected:

```
use Propel\Runtime\ActiveQuery\PropelQuery;
```

**Comment by XWB** [comment]
Closing as Propel integration was moved to another bundle.
