### ISSUE TITLE
Mapping of User Entity not being done correctly

### ISSUE THREAD

**Issue by narru19** [FriendsOfSymfony/FOSUserBundle#2119]
Hi!

I currently am trying to implement user authentication using FOSUserBundle (+FR3DLdapBundle once the first is working). Everything seems to work fine until I try to login / register, which produces the following error in my dev.log: Authentication request failed: Unrecognized field: usernameCanonical.

I have followed every step of the documentation (the master one, 2.0) until the User class part, where it tells me to create  a User class. I already had the whole project created without authentication (I already have a class called Person, which works as the User class). I have made the Person class extend BaseUser and made the id field protected. 

Should this work? Is it possible to adapt an existing "User" class to the User class FOSUserBundle asks for? (I guess this is what isn't working since it cannot find field that should be there if the mapping is being done correctly).

Thanks!

**Comment by stof** [comment]
Which version of the bundle are you using exactly ? Use ``composer show -i friendsofsymfony/user-bundle`` for that

and please show paste your entity

**Comment by narru19** [comment]
I am using the master version (2.0) of the bundle. As for the User Entity, I'll not be able to post it until tomorrow, sorry for the late response, will update it here!

**Comment by narru19** [comment]
I am using Navicat in order to create my Schema, and the table generated is the following: (using pastebin due to length)
http://pastebin.com/bE1Beb14
I've changed the $id attribute from private to protected (otherwise errors appeared) and I've also added the construct.

**Comment by narru19** [comment]
I've tried the update-database commands shown in the documentation https://symfony.com/doc/master/bundles/FOSUserBundle/index.html and the result is "Nothing to update - your database is already in sync with the current entity metadata." Maybe the database still doesn't have the inherited fields from the FOSUserBundle User model and hence why it gives this error (my guess :/). Even with this, I still have no clue why the database doesn't detect any changes as I clearly modified the Persona entity...

**Comment by narru19** [comment]
My guess was right, somehow my DB properties wouldn't allow me to work with FOSUserBundle, I instead took the approach of using a plain LDAP extension in order to authenticate, I'm closing the issue since it was not an issue, more like a not compatible feature towards me, thanks for your help!

**Comment by nadne** [comment]
Noooooo :(((((
