### ISSUE TITLE
In need of a renderRegister for multiple registration templates/routes

### ISSUE THREAD

**Issue by clytemnestra** [FriendsOfSymfony/FOSUserBundle#2121]
Why doesn't `RegistrationController` have a `renderRegister` function, too, like login has?

I want to make multiple login/register pages for different users. This is easy done for login by overriding the renderLogin method:

``` php
 public function renderLogin(array $data)
    {
        $requestAttributes = $this->container->get('request')->attributes;

        if ('admin_login' === $requestAttributes->get('_route')) {
            return $this->container->get('templating')->renderResponse('@ApplicationFOSUser/Security/adminLogin.html.twig', $data);
        } else {
            return parent::renderLogin($data);
        }

    }
```

but for another registration route, I need to copy all the code from FOSUB's registerAction into the new one.

**Comment by XWB** [comment]
Feel free to open a PR.
