### ISSUE TITLE
updateUser in userManager

### ISSUE THREAD

**Issue by matudelatower** [FriendsOfSymfony/FOSUserBundle#2126]
Im using:

```
"name": "friendsofsymfony/user-bundle",
"version": "v1.3.6",
```

when i try to update myself user y get this error:

![captura de pantalla de 2016-04-27 07-53-10](https://cloud.githubusercontent.com/assets/5694115/14850370/f2bf920a-0c4e-11e6-9ab9-151758840983.png)

I try to deactivate Xdebug and the screen goes blank

**Comment by stof** [comment]
well, without the stack trace, it is impossible to debug this. Please provide the screenshot without truncating it

**Comment by matudelatower** [comment]
@stof 
![updateuser](https://cloud.githubusercontent.com/assets/5694115/14855069/9fcab128-0c68-11e6-85cd-f64896bddcab.png)

**Comment by dmaicher** [comment]
Can you provide even more of the stack? We cannot see any recursion yet :)

**Comment by matudelatower** [comment]
@dmaicher the error repeat 5 more times, this happens when I try to update my user to update other users have no problem

**Comment by stof** [comment]
The issue looks like an infinite loop due to the blameable extension (making the User entity blameable based on the User extension is likely to cause such bugs).
In any case, it is not related to FOSUserBundle

**Comment by matudelatower** [comment]
yes @stof we upgrade to symfony 2.8 and the problem has been solved
