### ISSUE TITLE
Push a new 2.0-alpha tag (Symfony 3.0 compatibility)

### ISSUE THREAD

**Issue by Soullivaneuh** [FriendsOfSymfony/FOSUserBundle#2128]
Hi there,

I know that user-bundle 2.0 is not ready yet for a stable release but you already have 3 alpha tags, all not compatible with Symfony 3.0.

The `master` branch is compatible. Could be possible to push a new alpha, beta or RC tag for that?

This will reduce issue opening like #1996, #2070 or #2127.

Thanks.

**Comment by mirbahar** [comment]
thank you  stof

**Comment by Pierstoval** [comment]
:+1:

**Comment by XWB** [comment]
Closing this in favor of https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2206
