### ISSUE TITLE
I can't log with the created user 

### ISSUE THREAD

**Issue by ivanove** [FriendsOfSymfony/FOSUserBundle#2133]
Hi all,

I create a new user using the form from 127.0.0.1:8000/register,  I found the user in a database, I give him role_admin, but when I come back to login form, I can't login with it, the only users that I can use are those in Security.yml:

>    providers:
>         in_memory:
>             memory:
>                 users:
>                     user:  { password: user, roles: [ 'ROLE_USER' ] }
>                     admin: { password: admin, roles: [ 'ROLE_ADMIN' ] }    

So my question how I can, login with the user that I created ?

**Comment by xabbuh** [comment]
Can you please show your full security configuration?

**Comment by ivanove** [comment]
security config is :

> 
> security:
>     # http://symfony.com/doc/current/book/security.html#encoding-the-user-s-password
>     encoders:
>         Symfony\Component\Security\Core\User\User: plaintext
>         #Screenfony\DemoBundle\Entity\User: sha512
>         FOS\UserBundle\Model\UserInterface: sha512
>     # http://symfony.com/doc/current/book/security.html#hierarchical-roles
>     role_hierarchy:
>         ROLE_ADMIN:       ROLE_USER
>         ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
> 
>     # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
>     providers:
>         in_memory:
>             memory:
>                 users:
>                     user:  { password: user, roles: [ 'ROLE_USER' ] }
>                     admin: { password: admin, roles: [ 'ROLE_ADMIN' ] }
> 
>     # the main part of the security, where you can set up firewalls
>     # for specific sections of your app
>     firewalls:
>         # disables authentication for assets and the profiler, adapt it according to your needs
>         dev:
>             pattern:  ^/(_(profiler|wdt)|css|images|js)/
>             security: false
>         # the login page has to be accessible for everybody
>         demo_login:
>             pattern:  ^/demo/secured/login$
>             security: false
> 
>         # secures part of the application
>         demo_secured_area:
>             pattern:    ^/demo/secured/
>             # it's important to notice that in this case _demo_security_check and _demo_login
>             # are route names and that they are specified in the AcmeDemoBundle
>             form_login:
>                 check_path: _demo_security_check
>                 login_path: _demo_login
>             logout:
>                 path:   _demo_logout
>                 target: _demo
>             #anonymous: ~
>             #http_basic:
>             #    realm: "Secured Demo Area"
>         main:
>             pattern: ^/
>             form_login:
>                 #provider: fos_userbundle
>                 #csrf_token_generator: security.csrf.token_manager
>                       # if you are using Symfony < 2.8, use the following config instead:
>                 csrf_provider: form.csrf_provider
>                 default_target_path: /redirect
>             logout: true
>             anonymous: true
> 
>     # with these settings you can restrict or allow access for different parts
>     # of your application based on roles, ip, host or methods
>     # http://symfony.com/doc/current/book/security.html#security-book-access-control-matching-options
>    # access_control:
>         #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
>     access_control:
>         - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
>         - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
>         - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
>         - { path: ^/admin, role: ROLE_ADMIN }
>

**Comment by xabbuh** [comment]
You need to configure the user provider: http://symfony.com/doc/master/bundles/FOSUserBundle/index.html#step-4-configure-your-application-s-security-yml

**Comment by XWB** [comment]
See above.
