### ISSUE TITLE
Default role in Model/User

### ISSUE THREAD

**Issue by lk77** [FriendsOfSymfony/FOSUserBundle#2135]
Hello,
there is a default role in the Abstract User class, in function getRoles():

```
// we need to make sure to have at least one role
$roles[] = static::ROLE_DEFAULT;
```

i think is better to do:

```
if (empty($roles)) {
            // we need to make sure to have at least one role
            $roles[] = static::ROLE_DEFAULT;
}
```

the purpose is to avoid to have an extra role.

**Comment by stof** [comment]
This was already suggested in the past, and rejected.
Adding the default role only when the user does not have any other role would lead to WTF from the user, where adding a role to a user could magically remove access to another section which relied on the default role for that. It is much easier to understand that this role is always there

**Comment by lk77** [comment]
Ok
