### ISSUE TITLE
JMS Serializer definition of ExclusionPolicy ignored on class extending Model\User

### ISSUE THREAD

**Issue by xDaizu** [FriendsOfSymfony/FOSUserBundle#2138]
I have a "FOSUser" class that extends FOS\UserBundle\Model\User and it consistently ignores my ExclusionPolicy and/or @Serializer\Exclude annotations on any overriden field and I wondered if it's a FOSUser oddity (maybe it has some other definition of serialization visibility overriding my own?) and how can I deal with it.

My desire would be to hide every parameter of my FOSUser entity except those with the explicit @Serializer\Exclude annotation, be it a new parameter (like $fullname) or an overriden one (like $password).

For more info on the use case, I leave a link to my StackOverflow's question:
http://stackoverflow.com/questions/37388557/jms-serializer-exclusion-policy-of-associated-entity-ignored

Thank you for your time!

**Comment by rparsi** [comment]
@xDaizu I've run into similar oddities when my target class has properties inherited by base class and/or traits that are more than 1 level down.  Only workaround I've found is to use `@AccessType` or `@Accessor` annotations on the target class and/or traits.  It's known issue with how jms parses the class reflection data.

**Comment by stof** [comment]
Closing this as it is about JMS Serializer, not about this bundle
