### ISSUE TITLE
You have requested a non-existent service "doctrine". 

### ISSUE THREAD

**Issue by xOwl420** [FriendsOfSymfony/FOSUserBundle#2143]
Hello Guys,

while i am use my first time Symfony3 and Symfony FOSUserBundle i need help.

I got the Issue "You have requested a non-existent service "doctrine".".

I use MongoDB.. can anyone help me out?

Thanks

**Comment by xabbuh** [comment]
Please show your FOSUserBundle configuration and the full stack trace of the exception you get.

**Comment by stof** [comment]
I strongly suspect that you configured FOSUserBundle to use the ORM rather than the ODM.

**Comment by XWB** [comment]
See above.

**Comment by zhasan0** [comment]
Change the following line in your services.yml
services:
**public: false** 
by
**public: true**
