### ISSUE TITLE
The user with email "" does not exist

### ISSUE THREAD

**Issue by SDPrio** [FriendsOfSymfony/FOSUserBundle#2145]
Hi,

I am using the latest version of FOSUserBundle in my Symfony 2.7 web app. It seems to work without any problem. However I can see the following errors in my log files quite often:

```
URL: /user/register/check-email
REF: https://www.example.com/user/register/
USER_AGENT: Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13F69 Safari/601.1

MESSAGE:
Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException:
"The user with email "" does not exist" at /path/to/webpage/vendor/friendsofsymfony/user-bundle/Controller/RegistrationController.php line 88

CONTEXT: {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): The user with email \"\" does not exist at /path/to/webpage/vendor/friendsofsymfony/user-bundle/Controller/RegistrationController.php:88)\n[stacktrace]\n#0 [internal function]: FOS\\UserBundle\\Controller\\RegistrationController->checkEmailAction()\n#1 /path/to/webpage/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(139): call_user_func_array(Array, Array)\n#2 /path/to/webpage/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(62): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#3 /path/to/webpage/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php(69): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#4 /path/to/webpage/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(184): Symfony\\Component\\HttpKernel\\DependencyInjection\\ContainerAwareHttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#5 /path/to/webpage/web/app.php(24): Symfony\\Component\\HttpKernel\\Kernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request))\n#6 {main}"}
```

A lot of users register each day without any problems. Additionally in all my test the user registration never showed any problems as well.  No users contacted me to report any registration problems.

Thus I have no idea what or who causes this problem. 

The exception  `"The user with email "" does not exist"` is thrown by the `RegistrationController.php` when handling `checkEmailAction`. As far as I can tell, this action is called by the `EmailConfirmationListener` by routing to `fos_user_registration_check_email`. 

This is done after a user has been created successfully. But there are no users without an e-mail address...

The only way to reproduce the issue is to call `/user/register/check-email`. While this will produce the same error, the log will show ` REF: NULL` instead of `REF: https://www.example.com/user/register/`as in the real error messages...

So, the exception seems to be thrown during a real registration process. However no user ever reported any registration problem and there are no unconfirmend users in the DB. 

What might cause this problem?

**Comment by clytemnestra** [comment]
Probably registered users refresh the checkEmail page.

The email is kept in session only for one request 

``php
    /**
     * Tell the user to check his email provider
     */
    public function checkEmailAction()
    {
        $email = $this->get('session')->get('fos_user_send_confirmation_email/email');
        $this->get('session')->remove('fos_user_send_confirmation_email/email');
        $user = $this->get('fos_user.user_manager')->findUserByEmail($email);

        if (null === $user) {
            throw new NotFoundHttpException(sprintf('The user with email "%s" does not exist', $email));
        }

        return $this->render('FOSUserBundle:Registration:checkEmail.html.twig', array(
            'user' => $user,
        ));
    }
``

And when the page is refreshed, the exception is being thrown.

**Comment by XWB** [comment]
See above.
