### ISSUE TITLE
Rename templates before major release

### ISSUE THREAD

**Issue by mvar** [FriendsOfSymfony/FOSUserBundle#2149]
You should rename your templates to use underscored names instead of camelCase. Your naming is against Symfony standards and every project starts to look ugly when you need to overwrite templates of UB.

**Comment by dborsatto** [comment]
Partially done in https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2200

**Comment by XWB** [comment]
This has been addressed in master.

**Comment by mvar** [comment]
Perfect. Thanks.
