### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by ivanbarlog** [FriendsOfSymfony/FOSUserBundle#2153]
You are helping the attacker to guess existing users by providing too much information in [request forgotten password label](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Resources/translations/FOSUserBundle.en.yml#L55)

**Comment by clytemnestra** [comment]
You can override that controller and allow a maximum of x tries.

**Comment by ivanbarlog** [comment]
Shouldn't be the library as secure as possible by default?

**Comment by clytemnestra** [comment]
You can write an entire book debating that question.

**Comment by thecomputermanonline** [comment]
true

**Comment by XWB** [comment]
This has been addressed in master.
