### ISSUE TITLE
Add verifications on checkAction

### ISSUE THREAD

**Issue by bastos71** [FriendsOfSymfony/FOSUserBundle#2155]
hello !

I would like to override the checkAction in my application to check additionnal conditions when users try to login.
Unfortunately I do not find anything that helps me :/

Could someone give me a solution ?

Thanks !

**Comment by clytemnestra** [comment]
You need to create a [user checker](http://symfony.com/doc/current/cookbook/security/user_checkers.html)

**Comment by bastos71** [comment]
Thanks a lot !!
