### ISSUE TITLE
Multiple ORM?

### ISSUE THREAD

**Issue by bourdeau** [FriendsOfSymfony/FOSUserBundle#2157]
Hi all,

I just arrived in a new company which use Propel and I'm building their REST API but I would like to use Doctrine. Is there any way I could configure FOSUserBundle to use both ??

**Comment by stof** [comment]
No, you cannot use both Propel and Doctrine in the same project (thus, Propel and Doctrine don't expect the same format in the DB for some cases, so they cannot be used on the same DB in 2 projects)
