### ISSUE TITLE
how to use ajax login instead of traditional login submit.

### ISSUE THREAD

**Issue by sudhir600** [FriendsOfSymfony/FOSUserBundle#2160]
Hi team, 
In FOSUserbundle, i want that my user can login using ajax. i put a javascript code with e.preventDefault and then i put ajax request. when i am clicking on login... either i am providing right credentials or wrong, its always getting successfull login. and in return i am getting admin page 's html code.

how to validate that, either credential was true or false. so that i can handle the redirection using jquery. 

Here is my js  code-: 

<pre>
<code>
$(document).ready(function(){
    $('#_submit').click(function(e){

        e.preventDefault();
        resp = ajaxLogin($(this).attr('path'));
        /* add ajax code here to check validation */
        if(resp==1) {
            setTimeout(function () {
                $(that).addClass("success");
                setTimeout(function () {
                    $app.show();
                    $app.css("top");
                    $app.addClass("active");
                }, submitPhase2 - 70);
                setTimeout(function () {
                    $login.hide();
                    $login.addClass("inactive");
                    animating = false;
                    $(that).removeClass("success processing");
                }, submitPhase2);
            }, submitPhase1);
        }
        else{
            alert(resp);
            console.log(resp);
        }
    });
});
</code>
</pre>

All others setting are perfect as i am successfully able to login via traditional submit way.

**Comment by dmaicher** [comment]
100% unrelated to this bundle and should be asked on StackOverflow instead.
