### ISSUE TITLE
Generate CRUD

### ISSUE THREAD

**Issue by yzaouga** [FriendsOfSymfony/FOSUserBundle#2165]
Hi, I use FOSUserBundle for a while without problems in installation, configuration and even overriding. On trying to add more routes to allow an administrator to create, read, update and delete users; I generated the CRUD using the command doctrine : generate : crud for user entity inherits BaseUser. But I encounter a problem in the FormType .

On the FormType , the added fields are those of the User entity and I do not know how I can add those of BaseUser too.

I hope I was clear enough. 

Any Help? Thank you

**Comment by Pierstoval** [comment]
It's an issue from the `doctrine:generate` command, IIUC

**Comment by stof** [comment]
Closing this as this indeed has nothing to do with FOSUserBundle. We are not maintaining the crud generator.

I suspect that the crud generator does not work well for entities inheriting from a mapped superclass. You should report it to SensioGeneratorBundle instead.
