### ISSUE TITLE
Mapping error

### ISSUE THREAD

**Issue by PeterFour** [FriendsOfSymfony/FOSUserBundle#2166]
When trying to update the schema or use the migration I get :

> [Doctrine\ORM\Mapping\MappingException]  
>   Duplicate definition of column 'roles' on entity 'FOS\UserBundle\Model\Group' in a field or discriminator column mapping.

But I'm not using any of the group feature, I tried looking for roles in my whole Entity folder but no result

**Comment by Omar1123** [comment]
Maybe in your model has a column with a name called "Group" that has conflict with some reference of fos user tries to rename this property and execute.

>  php bin\console doctrine:schema:update --force

**Comment by PeterFour** [comment]
Completely forgot about this issue, but I no longer have this problem, probably have changed something, closing the issue as this is no longer causing me any exception
