### ISSUE TITLE
The EntityManager is closed. 

### ISSUE THREAD

**Issue by sinner** [FriendsOfSymfony/FOSUserBundle#2170]
Symfony > fos:user:create admin --super-admin
Please choose an email:blackduck@gmail.com
Please choose a password:

                                
  [Doctrine\ORM\ORMException]   
  The EntityManager is closed.  
                                

fos:user:create [--super-admin] [--inactive] [--] <username> <email> <password>

The command terminated with an error status (1)
Symfony >

**Comment by dmaicher** [comment]
And what exactly is the Exception? Stacktrace?

**Comment by stof** [comment]
It looks like you are using the console shell. Please don't do it. This make all commands run in the same PHP process, meaning they are impacted by previous commands (this is the reason why the shell has been removed in Symfony 3)

**Comment by XWB** [comment]
See above.
