### ISSUE TITLE
Missing "Bad credentials" error when overriding the SecurityController (login):

### ISSUE THREAD

**Issue by Ziiweb** [FriendsOfSymfony/FOSUserBundle#2175]
Hi,

I have just followed the instructions to override a controller in `FOSUserBundle` [here](http://symfony.com/doc/current/bundles/FOSUserBundle/overriding_controllers.html). 

In my case I want to override the login controller so I have created a new bundle called `UserBundle` and the `SecurityController` like this below (as you can check I have just copied the original `SecurityController` methods).

    namespace UserBundle\Controller;
    
    use Symfony\Component\HttpFoundation\JsonResponse;
    use Symfony\Bundle\FrameworkBundle\Controller\Controller;
    use Symfony\Component\HttpFoundation\Request;
    use Symfony\Component\Security\Core\Security;
    
    class SecurityController extends Controller
    {
        public function loginAction(Request $request)
        {
    die("Here is entering when showing the login form and when submitting it");
            /** @var $session \Symfony\Component\HttpFoundation\Session\Session */
            $session = $request->getSession();
            if (class_exists('\Symfony\Component\Security\Core\Security')) {
                $authErrorKey = Security::AUTHENTICATION_ERROR;
                $lastUsernameKey = Security::LAST_USERNAME;
            } else {
                // BC for SF < 2.6
                $authErrorKey = SecurityContextInterface::AUTHENTICATION_ERROR;
                $lastUsernameKey = SecurityContextInterface::LAST_USERNAME;
            }
            // get the error if any (works with forward and redirect -- see below)
            if ($request->attributes->has($authErrorKey)) {
                $error = $request->attributes->get($authErrorKey);
            } elseif (null !== $session && $session->has($authErrorKey)) {
                $error = $session->get($authErrorKey);
                $session->remove($authErrorKey);
            } else {
                $error = null;
            }
            if (!$error instanceof AuthenticationException) {
                $error = null; // The value does not come from the security component.
            }
            // last username entered by the user
            $lastUsername = (null === $session) ? '' : $session->get($lastUsernameKey);
            if ($this->has('security.csrf.token_manager')) {
                $csrfToken = $this->get('security.csrf.token_manager')->getToken('authenticate')->getValue();
            } else {
                // BC for SF < 2.4
                $csrfToken = $this->has('form.csrf_provider')
                    ? $this->get('form.csrf_provider')->generateCsrfToken('authenticate')
                    : null;
            }
            return $this->renderLogin(array(
                'last_username' => $lastUsername,
                'error' => $error,
                'csrf_token' => $csrfToken,
            ));
        }
        /**
         * Renders the login template with the given parameters. Overwrite this function in
         * an extended controller to provide additional data for the login template.
         *
         * @param array $data
         *
         * @return \Symfony\Component\HttpFoundation\Response
         */
        protected function renderLogin(array $data)
        {
            return $this->render('FOSUserBundle:Security:login.html.twig', $data);
        }
        public function checkAction()
        {
            throw new \RuntimeException('You must configure the check path to be handled by the firewall using form_login in your security firewall configuration.');
        }
        public function logoutAction()
        {
            throw new \RuntimeException('You must activate the logout in your security firewall configuration.');
        }
    }

UserBundle.php

    namespace UserBundle;
  
    use Symfony\Component\HttpKernel\Bundle\Bundle;
    
    class UserBundle extends Bundle
    {
        public function getParent()
        {
            return 'FOSUserBundle';
        }
    }

The problem: after submittting the login form shown at `/login`, I don't get the error `Bad credentials` when they the credentials are bad.

Here is my `security.yml` file:

    security:
        encoders:
            FOS\UserBundle\Model\UserInterface: bcrypt
    
        role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: ROLE_ADMIN
    
        providers:
            fos_userbundle:
                id: fos_user.user_provider.username
    
        firewalls:
            main:
                pattern: ^/
                form_login:
                    provider: fos_userbundle
                    csrf_token_generator: security.csrf.token_manager
                    # if you are using Symfony < 2.8, use the following config instead:
                    # csrf_provider: form.csrf_provider
    
                logout:       true
                anonymous:    true
    
        access_control:
            - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin/, role: ROLE_ADMIN }

Note 1: debugging inside `loginAction` at the line where the comment `        // last username entered by the user` is, the value of `$error` is `null`.
Note 2: I didn't override the login template at any part, of course.

**Comment by Ziiweb** [comment]
No idea about this?

**Comment by andrepintado** [comment]
Hi,

Just had the exact same problem. I fixed it first by following this:

http://symfony.com/doc/current/security/form_login_setup.html

Cheers,
André
