### ISSUE TITLE
Delete some attributes from user and log in via email only

### ISSUE THREAD

**Issue by TarAll** [FriendsOfSymfony/FOSUserBundle#2178]
i'm trying to delete some attributes but failed to do that.I want also to log in via email only and delete username attribute

**Comment by Athov** [comment]
As far as i have read you can't remove username.
I don't know if this is good or bad but after hours of reading and searching i found that you can do 
`<?php

namespace AppBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\Form\FormEvent;

class RegistrationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->remove('username');
        $builder->get('email')->addEventListener(
            FormEvents::POST_SUBMIT,
            function (FormEvent $event) {
                $form = $event->getForm();
                $parent = $form->getParent();
                
                $username = substr(md5(uniqid()),rand(0,26),10);
                $parent->add('username', null, ['data'=> $username,'compound' => true]);
            }
        );
    }

    public function getParent()
    {
        return 'FOS\UserBundle\Form\Type\RegistrationFormType';
    }

    public function getBlockPrefix()
    {
        return 'app_user_registration';
    }

    public function getName()
    {
        return $this->getBlockPrefix();
    }
}
`
this is from [http://symfony.com/doc/current/bundles/FOSUserBundle/overriding_forms.html](url)
also in security.yml you must do `
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email`
you maybe have `
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username`

**Comment by XWB** [comment]
See example above.
