### ISSUE TITLE
FOSUserBundle is not Installing on symfony 3.1

### ISSUE THREAD

**Issue by shahroznawaz** [FriendsOfSymfony/FOSUserBundle#2179]
FOSUserBundle is not installing on Symfony 3.1. Is there any compatibility issues?

**Comment by stof** [comment]
You have to use the master branch for that for now. 1.3.x is not compatible with Symfony 3

**Comment by shahroznawaz** [comment]
Hey @stof  I am using 2.0 master branch but every time it's given me proc_open() error and i have a fresh server in use.

**Comment by xabbuh** [comment]
@shahroznawaz Please show the exact error message you get.

**Comment by shahroznawaz** [comment]
I have installed symfony 3.1 on cloud server and tried again to install FOSUserBundle but it's giving me an error plz see below.
Composer command:
![image](https://cloud.githubusercontent.com/assets/14107436/17172444/99fe3af6-540e-11e6-907f-8ee324eb4e15.png)

Error:
![image](https://cloud.githubusercontent.com/assets/14107436/17172498/d317f71e-540e-11e6-8c1e-f63e8f9aeb94.png)

**Comment by 1ed** [comment]
This nothing to do with this bundle. As the error message says composer runs out of memory and a solution is provided in the message as well https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors

**Comment by shahroznawaz** [comment]
Yes I know it but I have a fresh server. I tried twice to install it but no luck.

**Comment by stof** [comment]
Still, this is not something related to FOSUserBundle at all. It is an issue when running Composer. So asking for support here won't give you any more help (and the solution is clear anyway: give more memory to your server)

**Comment by shahroznawaz** [comment]
Issue solved thanks for the assistance

**Comment by iamthestreets** [comment]
@shahroznawaz can you share how you solved this?

**Comment by shahroznawaz** [comment]
That was the issue of memory I increased it and all done
