### ISSUE TITLE
TwigSwiftMailer class ambiguous phpdocs

### ISSUE THREAD

**Issue by larzuk91** [FriendsOfSymfony/FOSUserBundle#2181]
In the method "sendMessage" from TwigSwiftMailer class, the parameter $fromEmail has a wrong phpdoc, it's documented as an string, but actually it is an associative array

I know this is a minor issue but I hope it can help anyone who is figuring out how the "fromName" is been set

**Comment by XWB** [comment]
Thanks https://github.com/FriendsOfSymfony/FOSUserBundle/commit/12db0ce31769b19597be741a568fe9352fc1baba
