### ISSUE TITLE
Username size not suitable for default setting

### ISSUE THREAD

**Issue by roberteikermann** [FriendsOfSymfony/FOSUserBundle#2182]
Symfony recommends utf8mb4 for mysql, the default max length of username and email exceeds the allowed size (in bytes) for keys and indexes in innodb. On `bin/console doctrine:schema:update --force` the errors: `General error: 1709 Index column size too large. The maximum column size is 767 bytes`. and 
`General error: 1709 Index column size too large. The maximum column size is 767 bytes.` are thrown.

Restrict username and email to length 180 does the trick.

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2187

**Comment by MvanRietschoten** [comment]
Say I have a user database with loads of users and use doctrine migrations. I would run bin/console doctrine:migrations:diff and suddenly my user entity is in the migration file. I run the migration and all the huge ass long email addresses are missing a part... Does this count as a BC break? Or how should I see this?

I know I can override it and should always check what happens in your migrations to check if it would trim some email adresses, but still... Shouldn't this be decided by the Application using this bundle? I know many people don't use the recommended utf8mb4 and they don't have that problem as it says more than 255: 
http://dev.mysql.com/doc/refman/5.7/en/innodb-restrictions.html
> By default, an index key for a single-column index can be up to 767 bytes. The same length limit applies to any index key prefix. See Section 14.1.14, “CREATE INDEX Syntax”. For example, you might hit this limit with a column prefix index of more than 255 characters on a TEXT or VARCHAR column, assuming a UTF-8 character set and the maximum of 3 bytes for each character. When the innodb_large_prefix configuration option is enabled, this length limit is raised to 3072 bytes, for InnoDB tables that use the DYNAMIC and COMPRESSED row formats.
