### ISSUE TITLE
1.3x: routing/all.xml missing

### ISSUE THREAD

**Issue by mkumr** [FriendsOfSymfony/FOSUserBundle#2184]
There is no routing/all.xml file in there

**Comment by Koalabaerchen** [comment]
It was added in 2.0/dev-master

You might have followed the wrong documentation. See https://symfony.com/doc/1.3.x/bundles/FOSUserBundle/index.html

**Comment by c0demonk** [comment]
Realized! http://symfony.com/doc/current/bundles/FOSUserBundle/index.html points to 2.0/master I suppose. Is 2.0 current or still master?

**Comment by Koalabaerchen** [comment]
2.0 is officially in alpha (https://github.com/FriendsOfSymfony/FOSUserBundle/releases/tag/v2.0.0-alpha3) but personally I'd recommend using that because of the new features. Didn't have any problem with it and feel confident enough to use it in production.

**Comment by c0demonk** [comment]
Thanks! I also recommend to fix the issue with the docs as it's saying 1.3 in current path but the doc is for 2.0. I've found lot of q/a using wrong/misleading doc. Ex. in 2.0 for ORM, entity should extend FOS\UserBundle\Model\User but in 1.3 should extend FOS\UserBundle\Entity\User.

**Comment by xabbuh** [comment]
@c0demonk Can you point out where you found documentation for 2.0/dev-master served under the 1.3 version label?

**Comment by c0demonk** [comment]
@xabbuh 

![screenshot-symfony com 2016-08-04 16-14-22](https://cloud.githubusercontent.com/assets/7008027/17399467/c854c80a-5a5f-11e6-91ed-6649b0e06912.png)

![screenshot-symfony com 2016-08-04 16-16-12](https://cloud.githubusercontent.com/assets/7008027/17399475/d2b476ec-5a5f-11e6-9b97-ab87ee78d93e.png)

![screenshot-symfony com 2016-08-04 16-17-12](https://cloud.githubusercontent.com/assets/7008027/17399479/d83f0096-5a5f-11e6-9e1e-503c1adc542f.png)

You should find all the above contents here: http://symfony.com/doc/current/bundles/FOSUserBundle/index.html

**Comment by XWB** [comment]
Must be a bug on the Symfony website, the 1.3 branch does not contains this reference.

**Comment by stof** [comment]
@javiereguiluz can you check this ? Having the switcher displaying the wrong version compared to the content on the website is not nice.

**Comment by XWB** [comment]
Closing this and keeping https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2288 as reminder.
