### ISSUE TITLE
Question: does FOSUserBundle rely on the application's `secret` for hashing?

### ISSUE THREAD

**Issue by colinodell** [FriendsOfSymfony/FOSUserBundle#2190]
I need to change the `secret` parameter in my Symfony application.  I'm unsure whether doing so will prevent users from logging into their account with existing passwords.  For example, perhaps this bundle or a dependency uses the `secret` for hashing? ¯\\\_(ツ)\_/¯ 

Can you confirm whether changing the `secret` will impact logins?

**Comment by ahundiak** [comment]
No.  Changing the secret will have no impact on passwords.  Try it.  I hardly ever change the secret on my development machines.

**Comment by colinodell** [comment]
Thanks!
