### ISSUE TITLE
Possibility to override form factory

### ISSUE THREAD

**Issue by mcbuckets** [FriendsOfSymfony/FOSUserBundle#2192]
Is it possible to override form factory to pass some extra parameters. I'm using this approach to add dynamic fields to registration form based on route parameter. It sounds messy but, as far as i understand it's not possible through form events or some other way.

I have this:

```
          <service id="my.user_form.factory" class="My\UserBundle\Form\Factory\FormFactory">
            <argument type="service" id="form.factory" />
            <argument type="string">my_a_registration</argument>
            <argument type="string">My\UserBundle\Form\Type\ARegistrationType</argument>
            <argument type="constant">null</argument>
         </service>
```
and it produces this error:

> Warning: Missing argument 1 for FOS\UserBundle\Form\Type\RegistrationFormType::__construct()

**Comment by dmaicher** [comment]
Yes you can override the form factory by simply defining a service for it with the id `fos_user.registration.form.factory` :wink: 

Anyway this is not an issue of this bundle but more a question that should be posted on stackoverflow or similar sites.

Can you please close this issue? Thanks :+1:
