### ISSUE TITLE
[2.x] Support of old Symfony versions?

### ISSUE THREAD

**Issue by chalasr** [FriendsOfSymfony/FOSUserBundle#2197]
Hi there,

First, thanks for this useful bundle, I would like to help on the 2.x releases.
Do we stop to ensure BC with Symfony versions that are not maintained anymore (< 2.7)?
So we could start to remove BC related hacks in the master branch.

Thanks

**Comment by XWB** [comment]
We should drop BC in 3.x releases.

**Comment by chalasr** [comment]
Thank you @XWB

**Comment by stloyd** [comment]
@XWB as this is still in phase of alpha, maybe it's good idea to drop the support anyway?
