### ISSUE TITLE
Not yet implemented error "search message"

### ISSUE THREAD

**Issue by HabibMami** [FriendsOfSymfony/FOSUserBundle#2198]
Hello im a beginner in Symfony 2.8
i installed the FOSMessagebundle i followed the basics all goes great only when i go to search twig
i got a message "not yet implemented "
im i missing anything ?
image
![image](https://cloud.githubusercontent.com/assets/21245088/17977291/06bed8d0-6ae9-11e6-85e8-93c53bd8c722.png)

thank you ! :)

**Comment by stof** [comment]
This error has nothing to do with FOSUserBundle
