### ISSUE TITLE
Remove password when profile editing

### ISSUE THREAD

**Issue by mcbuckets** [FriendsOfSymfony/FOSUserBundle#2199]
Is it possible to remove password prompt when editing profile. I'm aware that it's for security purposes since email can be changed too. But what if i want email field out. 

I tried overriding Profile form but with no luck, password field is no longer there but on submit i get `Please enter a password`. Would overriding validation help me with this?

**Comment by damienalexandre** [comment]
You should just have to extend `ProfileFormType` to remove the `current_password` field. There is no constraints on this field if you remove it. What version are you using? Did you configure your new form type in config.yml?

**Comment by XWB** [comment]
Closing this as no further information was provided.
