### ISSUE TITLE
Conflict with HWIOauth bundle on Symfony 3

### ISSUE THREAD

**Issue by odecharette** [FriendsOfSymfony/FOSUserBundle#2201]
Hi,

I installed hwi/oauth-bundle with FOSUser bundle in my Symfony 3 application and it's working !!!

But I had to make a change in a FOSUserBunde file 
-> vendor\friendsofsymfony\user-bundle\Propel\user.php
Before `use FOS\UserBundle\Propel\om\BaseUser;`
After `use FOS\UserBundle\Model\User as BaseUser;`

the folder om doesn't exists in Propel folder

Did I make a mistake or if not, could you correct this in the source code so I can still update FOSuserbundle ?

Many thanks

**Comment by XWB** [comment]
What version of FOSUserBunde are you currently using?

**Comment by odecharette** [comment]
Hi

I use 
"friendsofsymfony/user-bundle": "dev-master",
"hwi/oauth-bundle": "0.5.x-dev"

with SF 3.1.0

Olivia

**Comment by XWB** [comment]
Same issue as https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2224
