### ISSUE TITLE
ORA-00903: invalid table name (Oracle 11g)

### ISSUE THREAD

**Issue by helmidridi** [FriendsOfSymfony/FOSUserBundle#2209]
I started a projet with oracle 11g, the connection work well, i installed FOSUserBundle and updated the datatbase, everithing is ok, the able user is created but when i tried to create user 

`C:\>php bin/console fos:user:create admin
Please choose an email:helmis@gmail.de
Please choose a password:
  [Doctrine\DBAL\Exception\DriverException]
  An exception occurred while executing 'INSERT INTO user (username, username
  _canonical, email, email_canonical, enabled, salt, password, last_login, lo
  cked, expired, expires_at, confirmation_token, password_requested_at, roles
  , credentials_expired, credentials_expire_at, id) VALUES (?, ?, ?, ?, ?, ?,
   ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["admin", "admin", "helmis@gmail.de", "helmis@gmail.de", 1, "msnp3rel3m880oggggkccg8wkwk4ks
  c", "6s1k9SkufVf0AO0h+L4JKUtuKkaASIiQLMpuiD4qdZsX2WR9xm53DXVN6YnAuv8ui6PPSa
  B0FwPpBwDzvI53GA==", null, 0, 0, null, null, null, "a:0:{}", 0, null, 2]:
  ORA-00903: invalid table name

  [Doctrine\DBAL\Driver\OCI8\OCI8Exception]
  ORA-00903: invalid table name

fos:user:create [--super-admin] [--inactive] [-h|--help] [-q|--quiet] [-v|vv|vvv
|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env
ENV] [--no-debug] [--] <command> <username> <email> <password>

C:\>php bin/console doctrine:schema:update
Nothing to update - your database is already in sync with the current entity met
adata.

`

**Comment by VincentChataignier** [comment]
'User' is a [reserved word](http://docs.oracle.com/cd/E18283_01/appdev.112/e10830/appb.htm) in Oracle. It can't be used as a table name

**Comment by XWB** [comment]
See above.
