### ISSUE TITLE
Having trouble for mails send to hotmail and live accounts

### ISSUE THREAD

**Issue by Laurent3170** [FriendsOfSymfony/FOSUserBundle#2215]
When a user register with a Microsoft (hotmail, live) address, he/she never receives the email of confirmation. My server doesn't send a lot of email so I don't think it's blacklisted...
If anyone can help it would be welcomed

**Comment by snebes** [comment]
Have you tried this yourself?  Are emails being sent out from your server, just not received?  Or spamboxed?

**Comment by Laurent3170** [comment]
Yes I did, all the mails sent to live.fr and hotmail.fr when registering from my websites are spamboxed. I use my own server.

**Comment by XWB** [comment]
I'm sorry, this isn't FOSUserBundle related. Please check the spam box of your email account.

**Comment by Laurent3170** [comment]
Yes, I know it's not related to FOSUserBundle. The problem is not with my mailbox, but as FOSUserBundle sends emails for validating the account, as webmaster, it's my concern if the emails delivered to validate the account are not delivered (in the non-spam).
The goal of the bundle is to create account, if it fails somewhere the goal is not reached...
So, I was wondering if there's a way to add header's extra-data or something else to avoid emails put in the spam folder.
For my personal case, I did some DKIM validation on my server and reached Microsoft's program to register my server and used HWIOauthBundle to give acces directly with Microsoft's accounts but if we can improve the "viability" of the emails sent, I think it's not useless.

**Comment by stof** [comment]
Emails are sent using SwiftmailerBundle (unless you replace the mailer service). FOSUserBundle is not responsible for implementing the email sending.

**Comment by Laurent3170** [comment]
Ok, so should be done on SwiftmailerBundle side.
Thanks
