### ISSUE TITLE
Translation doesn't work on login form only

### ISSUE THREAD

**Issue by NonlyNerd** [FriendsOfSymfony/FOSUserBundle#2221]
On dev-master (528f0a93aebb641a0bc6471cc24562fbd01432cb), there is an issue when including the login form.

In **login.html.twig**, there is ```{% trans_default_domain 'FOSUserBundle' %}``` but Symfony doesn't cascade this variable for included files (see [Translations documentation](http://symfony.com/doc/current/translation.html#twig-templates)).

So I've cut-paste the above twig variable in the head of **login_content.html.twig**, and that solve the problem.

EDIT : Adding #2222 pull request

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2222
