### ISSUE TITLE
PHP Fatal error:  Class 'FOS\UserBundle\Propel\om\BaseUser' not found

### ISSUE THREAD

**Issue by dkorsak** [FriendsOfSymfony/FOSUserBundle#2224]
After symfony command cache:warmup there is error:

PHP Fatal error:  Class 'FOS\UserBundle\Propel\om\BaseUser' not found in ..../vendor/friendsofsymfony/user-bundle/Propel/User.php on line 18
 *\* [out :: 138.201.93.46] [2016-09-15 16:52:02] php.CRITICAL: Fatal Error: Class 'FOS\UserBundle\Propel\om\BaseUser' not found {"exception":"[object](Symfony\Component\Debug\Exception\FatalErrorException%28code: 0%29: Error: Class 'FOS\UserBundle\Propel\om\BaseUser' not found at .../vendor/friendsofsymfony/user-bundle/Propel/User.php:18)"}

Symfony version 3.2.x-dev.

**Comment by core23** [comment]
Can you please leave a little more information...

Which bundle versions are you using?

**Comment by dkorsak** [comment]
dev-master, latest release of FOSUserBundle.
If you will look at file https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Propel/User.php, there is no namespace FOS\UserBundle\Propel\om in the bundle code

**Comment by core23** [comment]
Can you supply a PR which fixes https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Propel/User.php#L16 @dkorsak ?

**Comment by BowlingX** [comment]
that's weird that this file has never been in this bundle (at least till last year). Is there another bundle that provides this file in the same namespace?

**Comment by BowlingX** [comment]
The full Propel folder seems to be broken, the whole folder/namespace `FOS\UserBundle\Propel\om` is not available.

**Comment by BowlingX** [comment]
Ok, I think this seems to be an issue with the auto_mapping, this looks familiar: https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1646.

The classes in this namespace will be generated if I'm correct?

**Comment by BowlingX** [comment]
Looks like a symfony problem to me, after I downgraded to symfony commit #1f9f87b177126fa67739ab109f8f59659f0dab9a (master, 3.2-dev) it's working again. Something broke/changed after this commit

**Comment by dkorsak** [comment]
Event if I remove propel files from autoloader by adding "exclude-from-classmap" option into composer.json, symfony still is trying to autoload propel files.
Yes, seems to be symfony problem on dev-master branch.

**Comment by ryzhov** [comment]
Hello, have exactly same issue as BowlingX has

**Comment by stof** [comment]
The question is what is trying to access these classes. If you don't use Propel, the bundle should never access these classes. And if you use Propel, the base classes will be generated by Propel.

**Comment by ryzhov** [comment]
I do not use Propel, my FOSUserBundle config is:
fos_user:
    db_driver: orm 
    firewall_name: main
    user_class: UserBundle\Entity\BaseUser
    service:
        mailer: fos_user.mailer.noop

**Comment by ryzhov** [comment]
```
cache:clear --env=prod -vvv

 // Clearing the cache for the prod environment with debug false                                                        

 // Warming up cache...                                                                                                 

PHP Fatal error:  Class 'FOS\UserBundle\Propel\om\BaseUser' not found in /var/www/autodial/vendor/friendsofsymfony/user-bundle/Propel/User.php on line 18

                                                                                 
  [Symfony\Component\Debug\Exception\ClassNotFoundException]                     
  Attempted to load class "BaseUser" from namespace "FOS\UserBundle\Propel\om".  
  Did you forget a "use" statement for another namespace?                        
                                                                                 

Exception trace:
 () at /var/www/autodial/vendor/friendsofsymfony/user-bundle/Propel/User.php:18

```

**Comment by stof** [comment]
Please provide the full stack trace, allowing to know what required the Propel user class

**Comment by ryzhov** [comment]
this is full stack but I not found the source what use this class
[out.txt](https://github.com/FriendsOfSymfony/FOSUserBundle/files/496295/out.txt)

**Comment by cedricziel** [comment]
I just encountered the problem and I think the modifications on the composer autoload definition (specifically the `autoload-dev` section) is to blame. - Maybe in combination with changes in the class scanning in sf.

Here's the comparison between the current the working and the failing commit: https://github.com/FriendsOfSymfony/FOSUserBundle/compare/662463f...FriendsOfSymfony:7abb0ff#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R54

**Comment by stof** [comment]
what you gave me is an extract of your logs, not the stack trace. Run the cache warmup command in verbose mode to get a stack trace.

Btw, autoload-dev of FOSUserBundle has strictly no impact in your own project (composer will NEVER read this setting for packages installed as a dependency)

**Comment by cedricziel** [comment]
That's exactly my thought - still: rolling back just these changes fixes the error.

**Comment by ryzhov** [comment]
@stof, Did you mean this ?:
```
bin/console cache:warmup --verbose

 // Warming up the cache for the dev environment with debug true                                                        

PHP Fatal error:  Class 'FOS\UserBundle\Propel\om\BaseUser' not found in /var/www/autodial/vendor/friendsofsymfony/user-bundle/Propel/User.php on line 18
[2016-09-27 09:46:04] php.CRITICAL: Fatal Error: Class 'FOS\UserBundle\Propel\om\BaseUser' not found {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Error: Class 'FOS\\UserBundle\\Propel\\om\\BaseUser' not found at /var/www/autodial/vendor/friendsofsymfony/user-bundle/Propel/User.php:18)"} 

                                                                                 
  [Symfony\Component\Debug\Exception\ClassNotFoundException]                     
  Attempted to load class "BaseUser" from namespace "FOS\UserBundle\Propel\om".  
  Did you forget a "use" statement for another namespace?                        
                                                                                 

Exception trace:
 () at /var/www/autodial/vendor/friendsofsymfony/user-bundle/Propel/User.php:18

cache:warmup [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
```

**Comment by CaredduMattia** [comment]
I'm having the same problem.

**Comment by cedricziel** [comment]
I've attached a stack-trace.

Looks like the `ValidatorCacheWarmer` uses the available class-loaders to read metadata from all suitable loaders and that's where the error originates.

I am still convinced that it has something to do with the classmap-especially since the ValidatorBuilder uses it to build its metadata.

<details>
<summary>The stack trace</summary>
```
$ sf --env=prod cache:clear -vvv

 // Clearing the cache for the prod environment with debug false

 // Clearing outdated warmup directory...

 // Warming up cache...

PHP Fatal error:  Class 'FOS\UserBundle\Propel\om\BaseUser' not found in /home/cziel/projects/my-project/vendor/friendsofsymfony/user-bundle/Propel/User.php on line 18
PHP Stack trace:
PHP   1. {main}() /home/cziel/projects/my-project/bin/console:0
PHP   2. Symfony\Component\Console\Application->run() /home/cziel/projects/my-project/bin/console:29
PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:122
PHP   4. Symfony\Component\Console\Application->doRun() /home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:80
PHP   5. Symfony\Component\Console\Application->doRunCommand() /home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:191
PHP   6. Symfony\Component\Console\Command\Command->run() /home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:846
PHP   7. Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->execute() /home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:257
PHP   8. Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->warmup() /home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php:96
PHP   9. Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp() /home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php:144
PHP  10. Symfony\Bundle\FrameworkBundle\CacheWarmer\ValidatorCacheWarmer->warmUp() /home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/CacheWarmer/CacheWarmerAggregate.php:48
PHP  11. Symfony\Component\Validator\Mapping\Factory\LazyLoadingMetadataFactory->getMetadataFor() /home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/CacheWarmer/ValidatorCacheWarmer.php:71
PHP  12. class_exists() /home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Component/Validator/Mapping/Factory/LazyLoadingMetadataFactory.php:106
PHP  13. spl_autoload_call() /home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Component/Validator/Mapping/Factory/LazyLoadingMetadataFactory.php:106
PHP  14. Composer\Autoload\ClassLoader->loadClass() /home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Component/Validator/Mapping/Factory/LazyLoadingMetadataFactory.php:106
PHP  15. Composer\Autoload\includeFile() /home/cziel/projects/my-project/vendor/composer/ClassLoader.php:301
PHP  16. include() /home/cziel/projects/my-project/vendor/composer/ClassLoader.php:412


  [Symfony\Component\Debug\Exception\ClassNotFoundException]
  Attempted to load class "BaseUser" from namespace "FOS\UserBundle\Propel\om".
  Did you forget a "use" statement for another namespace?


Exception trace:
 () at /home/cziel/projects/my-project/vendor/friendsofsymfony/user-bundle/Propel/User.php:18
PHP Notice:  Undefined index: function in /home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php on line 677
PHP Stack trace:
PHP   1. {main}() /home/cziel/projects/my-project/bin/console:0
PHP   2. Symfony\Component\Console\Application->run() /home/cziel/projects/my-project/bin/console:29
PHP   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() /home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:122
PHP   4. Symfony\Component\Console\Application->doRun() /home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:80
PHP   5. Symfony\Component\Console\Application->doRunCommand() /home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:191
PHP   6. Symfony\Component\Console\Command\Command->run() /home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:846
PHP   7. Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->execute() /home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:257
PHP   8. Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->warmup() /home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php:96
PHP   9. Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp() /home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php:144
PHP  10. Symfony\Bundle\FrameworkBundle\CacheWarmer\ValidatorCacheWarmer->warmUp() /home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/CacheWarmer/CacheWarmerAggregate.php:48
PHP  11. Symfony\Component\Validator\Mapping\Factory\LazyLoadingMetadataFactory->getMetadataFor() /home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/CacheWarmer/ValidatorCacheWarmer.php:71
PHP  12. class_exists() /home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Component/Validator/Mapping/Factory/LazyLoadingMetadataFactory.php:106
PHP  13. spl_autoload_call() /home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Component/Validator/Mapping/Factory/LazyLoadingMetadataFactory.php:106
PHP  14. Composer\Autoload\ClassLoader->loadClass() /home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Component/Validator/Mapping/Factory/LazyLoadingMetadataFactory.php:106
PHP  15. Composer\Autoload\includeFile() /home/cziel/projects/my-project/vendor/composer/ClassLoader.php:301
PHP  16. include() /home/cziel/projects/my-project/vendor/composer/ClassLoader.php:412
PHP  17. Symfony\Component\Debug\ErrorHandler::handleFatalError() /home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php:0
PHP  18. Symfony\Component\Debug\ErrorHandler->handleException() /home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php:604
PHP  19. call_user_func:{/home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php:542}() /home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php:542
PHP  20. Symfony\Component\HttpKernel\EventListener\DebugHandlersListener->Symfony\Component\HttpKernel\EventListener\{closure}() /home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php:542
PHP  21. Symfony\Component\Console\Application->renderException() /home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/DebugHandlersListener.php:113
 () at /home/cziel/projects/my-project/vendor/composer/ClassLoader.php:412
 Composer\Autoload\includeFile() at /home/cziel/projects/my-project/vendor/composer/ClassLoader.php:301
 Composer\Autoload\ClassLoader->loadClass() at /home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Component/Validator/Mapping/Factory/LazyLoadingMetadataFactory.php:106
 spl_autoload_call() at /home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Component/Validator/Mapping/Factory/LazyLoadingMetadataFactory.php:106
 class_exists() at /home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Component/Validator/Mapping/Factory/LazyLoadingMetadataFactory.php:106
 Symfony\Component\Validator\Mapping\Factory\LazyLoadingMetadataFactory->getMetadataFor() at /home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/CacheWarmer/ValidatorCacheWarmer.php:71
 Symfony\Bundle\FrameworkBundle\CacheWarmer\ValidatorCacheWarmer->warmUp() at /home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/CacheWarmer/CacheWarmerAggregate.php:48
 Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->warmUp() at /home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php:144
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->warmup() at /home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php:96
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->execute() at /home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at /home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:846
 Symfony\Component\Console\Application->doRunCommand() at /home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:191
 Symfony\Component\Console\Application->doRun() at /home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:80
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /home/cziel/projects/my-project/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:122
 Symfony\Component\Console\Application->run() at /home/cziel/projects/my-project/bin/console:29
 {main}() at /home/cziel/projects/my-project/bin/console:0
```
</details>

**Comment by stof** [comment]
OK, I think I will move the propel integration into a separate bundle for v2 (and look for a maintainer for it, as I'm not using Propel myself), to avoid such issue.

**Comment by tacman** [comment]
How about just gutting Propel?  Version 2 will never be finished (it's been
in alpha for years, Version 1 is deprecated.  There's no good reason for
using Propel.

Alternatively, you could create the \Propel\om\BaseUser class and check it
into the repo.

**Comment by OskarStark** [comment]
> Alternatively, you could create the \Propel\om\BaseUser class and check it
into the repo

That is not how propel should work

**Comment by stof** [comment]
> Alternatively, you could create the \Propel\om\BaseUser class and check it into the repo.

As this class would extend from a Propel class, you would still have the same issue about the missing base class. It would just be the next one.

**Comment by stephanvierkant** [comment]
Any update on this? This issue prevents me from updating to Symfony 3.2 right now.

**Comment by cedricziel** [comment]
@stephanvierkant you can "pin" a healthy commit in the `require` section in your `composer.json`.

The last healthy commit is a24e799c8febbae675d41a42b552574887fa1784, so I use this right now and postpones the need to deal with the broken dependency for now:

```
  "friendsofsymfony/user-bundle": "2.0.x-dev#a24e799c8febbae675d41a42b552574887fa1784",
```

**Comment by ryzhov** [comment]
this commit [a24e799](https://github.com/FriendsOfSymfony/FOSUserBundle/commit/a24e799c8febbae675d41a42b552574887fa1784l) does not resolve issue for me

**Comment by cedricziel** [comment]
I just double checked it. Works fine for me, but I recall having trouble until i manually removed the cache dir.

**Comment by kbsali** [comment]
same issue here and downgrading to a24e799 won't help either! :(

**Comment by tacman** [comment]
Friends don't let friends use Propel.

How about dropping Propel support until Propel2 is at least in beta?  For
Propel1 support, use an older version of FOSUserBundle.

If you're upgrading to Symfony 3, you probably should be using an ORM
that's not obsolete or in alpha.

**Comment by core23** [comment]
👍 for dropping propel. We can (re)add support later, if someone needs this.

**Comment by codereviewvideos** [comment]
I've done a little further digging into this, and have a temporary workaround, but not a solution.

`vendor/friendsofsymfony/user-bundle/Resources/config/validation.xml`

https://github.com/FriendsOfSymfony/FOSUserBundle/blob/v2.0.0-alpha3/Resources/config/validation.xml#L97

comment out lines 97 > 183

Cache should now clear.

The issue appears to have been triggered by the inclusion of [the `ValidatorCacheWarmer`][1] in Symfony 3.2.

My theory goes that extracting the propel part of the `validation.xml` file to e.g. `validation_propel.xml`, and selectively loading that if using propel would solve the problem. Unfortunately, my current attempt to fix this problem is hitting this issue - something to do with the way I'm loading the config, but not sure exactly what yet:

```
 [InvalidArgumentException]                                                                                        
  [ERROR 1845] Element '{http://symfony.com/schema/dic/constraint-mapping}constraint-mapping': No matching global   
  declaration available for the validation root. (in /var/www/api.tribecount.dev/ - line 5, column 0)     
```

[1]: https://github.com/symfony/framework-bundle/commit/b87eddeadb0ff10c39789518b8eef9aa48281a65

**Comment by XWB** [comment]
Can you guys try the latest Symfony 3.2 branch? https://github.com/symfony/symfony/commit/59f99493f8395e85cf175a8f888a22e5a3517ed1

**Comment by ryzhov** [comment]
I have same issue on [symfony/symfony@a4edafbd](https://github.com/symfony/symfony/commit/a4edafbd7d82ccea983f04ade3dc220e72f340e2)

**Comment by codereviewvideos** [comment]
@XWB - just checked #59f9949 of Symfony, and #4ea37a5 of FOSUserBundle, and the cache clears fine for me :thumbsup:

**Comment by XWB** [comment]
@ryzhov You need to use the 3.2 branch, Symfony master branch has not been updated yet.

**Comment by ryzhov** [comment]
still not work in this environment

symfony/symfony                      3.2.x-dev 59f9949  The Symfony PHP framework
friendsofsymfony/user-bundle   dev-master dd966ca Symfony FOSUserBundle

**Comment by dkorsak** [comment]
Does not work.
After add to te composer.json

```
        "exclude-from-classmap": [
            "vendor/friendsofsymfony/user-bundle/Propel/"
        ]
```
composer still creating autoload class map with Propel files (composer bug?)
Event if I remove manually Propel files from composer autload class, still does not work.

Composer\Autoload\ClassLoader->loadClass function if will not find class in the class map, will find 
file friendsofsymfony/user-bundle/Propel/User.php by path.

ValidatorCacheWarmer class (XmlFileLoader) is trying to load Propel classes because in the file 
```
/friendsofsymfony/user-bundle/Resources/config/validation.xml 
```
there is

```
<class name="FOS\UserBundle\Propel\User">
```

and Symfony parsing this file is trying to load class FOS\UserBundle\Propel\User.

The solution is to split file
```
/friendsofsymfony/user-bundle/Resources/config/validation.xml 
```

into Doctrine and Propel validation_{orm}.xml files and load files manually by compiler pass:

see for example
http://stackoverflow.com/questions/24064813/how-to-split-validation-yaml-files-in-symfony-2-5/24210501#24210501

Exactly to fix it you can update file https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/DependencyInjection/Compiler/ValidationPass.php

by add something like

```
$validationFile = __DIR__.'/../../Resources/config/validation/orm.xml';
 if ($storage == 'propel') {
     $validationFile = __DIR__ . '/../../Resources/config/validation/propel.xml';
 }
 $container->getDefinition('validator.builder')
      ->addMethodCall('addXmlMapping', array($validationFile));
```

and split /friendsofsymfony/user-bundle/Resources/config/validation.xml  into orm.xml and propel.xml
and update documentaion

**Comment by stof** [comment]
@dkorsak not a composer bug. As these files are in the FOSUserBundle package, the exclude rule would have to be added in the FOSUserBundle metadata

**Comment by XWB** [comment]
Propel support has been removed.

https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2309

**Comment by ryzhov** [comment]
now cache:clear works as expected, thanks !
