### ISSUE TITLE
Profile edit form doesn't verify on correct "current_password"

### ISSUE THREAD

**Issue by djardine** [FriendsOfSymfony/FOSUserBundle#2246]
Maybe this is my misunderstanding of how the profile edit form is meant to work, but my expectation is that the "Current password" field is meant verify that the correct person if making changes to the user's profile by validating their current password. If this is the case, then the password verification doesn't seem to be happening. I can enter any string for "current_password" and the profile changes will be saved.

In file: FOSUserBundle/Form/Type/ProfileFormType.php, shouldn't:

```
$builder->add('current_password', LegacyFormHelper::getType('Symfony\Component\Form\Extension\Core\Type\PasswordType'), array(
            'label' => 'form.current_password',
            'translation_domain' => 'FOSUserBundle',
            'mapped' => false,
            'constraints' => new UserPassword(),
        ));
```

... be something like the following...

```
$builder->add('current_password', LegacyFormHelper::getType('Symfony\Component\Form\Extension\Core\Type\PasswordType'), array(
            'label' => 'form.current_password',
            'translation_domain' => 'FOSUserBundle',
            'mapped' => false,
            'constraints' => new UserPassword(!empty($options['validation_groups']) ? array('groups' => array(reset($options['validation_groups']))) : null),
        ));
```

...?

**Comment by XWB** [comment]
Can you try https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2256 ?

**Comment by djardine** [comment]
Looks good to me!

**Comment by XWB** [comment]
Fixed via https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2256
