### ISSUE TITLE
fos_user_registration_register cannot be accessed by a logged in user anymore?

### ISSUE THREAD

**Issue by picks44** [FriendsOfSymfony/FOSUserBundle#2248]
I don't want the /register path to be public, as I want to register users myself (website admin), so I made it private with the access_control in security.yml. But it looks like the new release is now redirecting me (as I'm logged to do this) to my profile page when I'm trying to access this page and register a new user. 

Is there a workaround ?

**Comment by core23** [comment]
You could include only some routes that you need instead of using the `all.xml` routing file.
 https://github.com/FriendsOfSymfony/FOSUserBundle/tree/master/Resources/config/routing

**Comment by picks44** [comment]
@core23 I don't see how this would help me? I want to access /register only when a user with the correct permissions is logged in.

**Comment by picks44** [comment]
My **security.yml** has :
```
 access_control:
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/register/confirmed, role: ROLE_USER }
        - { path: ^/admin/register, role: ROLE_SUPER_ADMIN }
        - { path: ^/admin/, role: ROLE_USER }
```

Then in my admin section if I'm a ROLE_SUPER_ADMIN I have a "Add user" button that should open the **fos_user_registration_register** route so I can create a new one. This way i have control of my users and noone from "outside" can try to register by himself.

**Comment by XWB** [comment]
Fixed in https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2273
