### ISSUE TITLE
FOSUserEvents::REGISTRATION_FAILURE appears to be missing?

### ISSUE THREAD

**Issue by pnsean** [FriendsOfSymfony/FOSUserBundle#2266]
I've been using FOSUserEvents::REGISTRATION_FAILURE for a week now.  Just went to go update a few libraries through composer on a production server, and now it appears this event is missing from the bundle.

I've checked all the releases and it no longer appears in any build?  Was this recently removed?

**Comment by XWB** [comment]
It's still present.

https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/FOSUserEvents.php#L162
https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Controller/RegistrationController.php#L88

**Comment by pnsean** [comment]
Hmm, interesting yea I get it if I pull down dev-master, but if I pull down the latest release 2.x alpha it's missing now.  Strange.
