### ISSUE TITLE
Problem with fosOauthServerBundle

### ISSUE THREAD

**Issue by manuelDistefano** [FriendsOfSymfony/FOSUserBundle#2272]
Hi folsk,

i have a project with FosUserBundle and FOSOauthServerBundle:

`        
"friendsofsymfony/oauth-server-bundle": "^1.5",
 "friendsofsymfony/user-bundle": "~2.0@dev",
`

After the last upgrade i have this error:
`Argument 5 passed to FOS\OAuthServerBundle\Storage\OAuthStorage::__construct() must implement interface Symfony\Component\Security\Core\User\UserProviderInterface, instance of FOS\UserBundle\Doctrine\UserManager given`

caused by [https://github.com/FriendsOfSymfony/FOSUserBundle/commit/f7a1f513753517601e94a0c208fdf8d24d1b85ce](url) 

Can someone help me?

**Comment by stof** [comment]
this is because using the ``fos_user.user_manager`` as a UserProvider was deprecated since a long time, and we finally got rid of the deprecated code. Inject the actual user provider instead

**Comment by manuelDistefano** [comment]
Yeah! I checked it just 1 minutes after my post. 

Tnx

**Comment by vaziuok** [comment]
This helped me: 

`user_provider: fos_user.user_provider.username`

**Comment by yohann-teisseire** [comment]
@vaziuok , thank you very much.

**Comment by pboethig** [comment]
fos_user.user_provider.username works like a charm for me. Thx very much! Saved my day

**Comment by rodrigolopezguerra** [comment]
fos_user.user_provider is the actual correct parameter i think , but fos_user.user_provider.username will do th ejob as well

**Comment by rodrigolopezguerra** [comment]
+1 

user_provider: fos_user.user_provider.username

thanks !

**Comment by aqeelrepoowner** [comment]
Thanks it worked for me

**Comment by petforsberg** [comment]
`
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username`

**Comment by irwinv** [comment]
Yes, i confirm this solution ! check it out [https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Upgrade.md#user-provider](url) Thank you @stof

**Comment by woshiwenquan** [comment]
@erikassojunovas thank you
