### ISSUE TITLE
@ install, FATAL "[Doctrine\Common\Persistence\Mapping\MappingException]  Class 'AppBundle\Entity\User' does not exist"

### ISSUE THREAD

**Issue by user58258** [FriendsOfSymfony/FOSUserBundle#2279]
Following

```
http://symfony.com/doc/master/bundles/FOSUserBundle/index.html
```

Starting with

```
egrep "symfony/symfony|doctrine/doctrine-bundle|doctrine/orm" composer.json
    "symfony/symfony": "3.1.*",
    "doctrine/orm": "^2.5",
    "doctrine/doctrine-bundle": "^1.6",
```

I installed FOSUserBundle

```
grep friendsofsymfony/user-bundle composer.json
    "friendsofsymfony/user-bundle": "2.0.x-dev"
```

added

```
edit app/AppKernel.php
    ...
    public function registerBundles()
    {
        $bundles = array(
            // ...
+            new FOS\UserBundle\FOSUserBundle(),
            // ...
        );
    ...

edit app/config/config.yml

+    fos_user:
+        db_driver: orm
+        firewall_name: main
+        user_class: AppBundle\Entity\User

edit src/AppBundle/Resources/config/doctrine/User.orm.yml
+    AppBundle\Entity\User:
+        type:  entity
+        table: fos_user
+        id:
+            id:
+                type: integer
+                generator:
+                    strategy: AUTO

cat app/config/security.yml
    security:
        encoders:
            FOS\UserBundle\Model\UserInterface: bcrypt

        role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: ROLE_ADMIN

        providers:
            fos_userbundle:
                id: fos_user.user_provider.username

        firewalls:
            main:
                pattern: ^/
                form_login:
                    provider: fos_userbundle
                    csrf_token_generator: security.csrf.token_manager

                logout:       true
                anonymous:    true

        access_control:
            - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin/, role: ROLE_ADMIN }

edit app/config/routing.yml
+    fos_user:
+        resource: "@FOSUserBundle/Resources/config/routing/all.xml"
```

When I exec

```
php bin/console doctrine:schema:update --force
```

I get the following error

```
[Doctrine\Common\Persistence\Mapping\MappingException]
  Class 'AppBundle\Entity\User' does not exist
```

**Comment by xabbuh** [comment]
You forgot to add a custom `User` class in the `AppBundle\Entity` namespace.

**Comment by user58258** [comment]
@xabbuh 

Isn't that the

    edit src/AppBundle/Resources/config/doctrine/User.orm.yml

    +    AppBundle\Entity\User:
    +        type:  entity
    +        table: fos_user
    +        id:
    +            id:
    +                type: integer
    +                generator:
    +                    strategy: AUTO

?

That's directly from

    a) Doctrine ORM User class¶

    If you're persisting your users via the Doctrine ORM, then your User class should live in the Entity namespace of your bundle and look like this to start:

    ...

**Comment by xabbuh** [comment]
That's your mapping definition. Yo are missing the actual class (see https://symfony.com/doc/master/bundles/FOSUserBundle/index.html#step-3-create-your-user-class before part a)).

**Comment by user58258** [comment]
I don't mean to be thickheaded abt this, but

> In the **_following_** sections, you'll see examples of **_how your User class should look_**, depending on how you're storing your users (Doctrine ORM, MongoDB ODM, or CouchDB ODM).

So I go to the **_following section_** , choose the YAML option, and create that file.

If I'm misunderstanding the instructions, can you provide an example of exactly what I'm supposed to add & where?

**Comment by xabbuh** [comment]
@user58258 Your `User` class should basically look like the example in the "Annotations" format at https://symfony.com/doc/master/bundles/FOSUserBundle/index.html#a-doctrine-orm-user-class (but you will leave out the mapping annotations).

Maybe that's not clear enough, but is basically described with these steps:

> 1. Extend the base `User` class (from the `Model` folder if you are using any of the doctrine variants, or `Propel` for propel 1.x)
1. Map the `id` field. It must be protected as it is inherited from the parent class.

**Comment by user58258** [comment]
No, not at all clear to me :-( Which is why i'm spinning here ...

To me, it reads as if we have a *choice* from among those **_following options_** as to how to create the User class, and hence how the

> User class should look

So, do I have to create BOTH the

    src/AppBundle/Entity/User.php

and

    src/AppBundle/Resources/config/doctrine/User.orm.yml

&/or also the

    src/AppBundle/Resources/config/doctrine/User.orm.xml

??

Ideally, in docs, it'd be clear to read

> Extend  the base User class

then id the files and provide an example.  and then, for

> Map the id field

the same -- id the files and provide an example.

**Comment by xabbuh** [comment]
Yes, you **always** have to create the entity class. You are just free to choose how you like to define the metadata that configure the mapping of your entity to the database schema. Don't know how this could be changed to make it more clear. But I am sure the bundle maintainers are happy to review a PR improving the documentation.

**Comment by user58258** [comment]
Right.  The question's not whether the User class has to be created.

The issue is that the docs present three tabs to a single window,

'Annotations', 'YAML' & 'XML', which elsewhere across the symfony site seems to suggest alternative methods of doing the same thing ...

e.g., http://symfony.com/doc/current/routing.html#routing-examples

If you need to create the Annotations file AND create the YAML file, then it should aguably be in two separate steps.

**Comment by xabbuh** [comment]
You do not have to create the annotations and the YAML file. It's up to you to choose the preferred config format.

**Comment by XWB** [comment]
See above.
