### ISSUE TITLE
Custom user manager error since latest release > Argument 1 passed to FOS\UserBundle\Doctrine\UserManager::__construct()

### ISSUE THREAD

**Issue by adadgio** [FriendsOfSymfony/FOSUserBundle#2280]
After todays composer update with FOS User bundle `"friendsofsymfony/user-bundle": "~2.0@dev",` , i get this new error.

```
Catchable Fatal Error: Argument 1 passed to FOS\UserBundle\Doctrine\UserManager::__construct() must be           
  an instance of FOS\UserBundle\Util\PasswordUpdaterInterface, instance of Symfony\Component\Security\Core\Encoder\  
  EncoderFactory given...
```

My user managet looks like this.

```
public function __construct(
        EncoderFactoryInterface $encoderFactory,
        CanonicalizerInterface $usernameCanonicalizer,
        CanonicalizerInterface $emailCanonicalizer,
        EntityManager $em
    )
```

**Comment by stof** [comment]
Well, if you use the master branch, you need to be prepared to changes, as it is the dev version of a new major release. And we indeed have changes (and if you use the master branch, you have to check the git history as the changelog may not have been updated yet for them, until the next release).

The signature of the UserManager constructor in FOSUserBundle has indeed changed (merge done a few hours ago).
