### ISSUE TITLE
Accessing app.user in twig even if path is anonymous (the user is logged in)

### ISSUE THREAD

**Issue by atim140** [FriendsOfSymfony/FOSUserBundle#2290]
Hello,

I can't figure out how to make it possible to getting app.user or is_granted in twig if the user is logged in.

Use case : it's very common to have a homepage which could be accessed anonymously but also the user can log in. Then, he browse the same page now with his username shown and the possibility to logout.

Now : I've set the path as "anonymous : true" in security.yml. 
Result : Even if the user get logged in, I can't get his username. The symfony debug toolbar show obviously anonymous user too.

I think it's very common use case but I couldn't get help elsewhere.

Thank you :)

**Comment by damienalexandre** [comment]
Hi,
this is not a FOSUserBundle issue but more likely a Symfony issue. Could you please share your security.yml configuration?

One possible cause is the "path" option of your firewall not covering the homepage.

**Comment by atim140** [comment]
Hello, thank you for replying @damienalexandre. There is an extract of my security.yml

`    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/(login$|register|resetting)
            anonymous: true

        index_root:
            pattern: ^/frontal/index$
            anonymous: true

        main:
            pattern: ^\/.+
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                remember_me: true
                default_target_path: /frontal/index0

            remember_me:
                secret: %secret%
            anonymous: false
            logout: true
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/base, role: IS_AUTHENTICATED_ANONYMOUSLY }
`
So I can't access app.user in index_root path because it's anonymous. Is it expected?

**Comment by damienalexandre** [comment]
Yes, the `index_root` firewall does not have anything to do with the `main` firewall, so it can't access the session or the user provider.

I suggest you do as follow:
- remove the index_root firewall
- set the main firewall as anonymous: true
- use `access_control` rules allow not fully authenticated user on `^/frontal/index$`, and force IS_AUTHENTICATED_FULLY for everything else

**Comment by XWB** [comment]
Closing as this is not a `FOSUserBundle` issue.
