### ISSUE TITLE
Missing %email% in password reset

### ISSUE THREAD

**Issue by sfenne** [FriendsOfSymfony/FOSUserBundle#2293]
Hi all,

All of the sudden, the %email% parameter is empty when resetting an e-mail.

Result after successful password reset:
"An email has been sent to . It contains an activation link you must click to activate your account."

The e-mail is sent and everything is fine, except this message. The e-mail column is filled as well (the user has an e-mail).

Any suggestions to why this happens? I've added listeners, but also tried to remove then (and clearing cache)  - so they aren't the reason.

In before, thanks.

**Comment by XWB** [comment]
The message is just "An email has been sent.", see https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Resources/translations/FOSUserBundle.en.yml#L54

**Comment by sfenne** [comment]
Thank you!
