### ISSUE TITLE
SF3 / FOSUserBundle ~1.3 Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by andreas-glaser** [FriendsOfSymfony/FOSUserBundle#2297]
I have just tried to install your this bundle on a new symfony 3 installation and faced dependency issues i did not expect and was not able to resolve easily.

To my best knowledge the commands below should work just fine?!

`andreas@vm-mint-18 ~/development $ symfony new test

 Downloading Symfony...

    5.2 MiB/5.2 MiB ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  100%

 Preparing project...

 ✔  Symfony 3.1.6 was successfully installed. Now you can:

    * Change your current directory to /home/andreas/development/test

    * Configure your application in app/config/parameters.yml file.

    * Run your application:
        1. Execute the php bin/console server:start command.
        2. Browse to the http://localhost:8000 URL.

    * Read the documentation at http://symfony.com/doc

andreas@vm-mint-18 ~/development $ cd test
andreas@vm-mint-18 ~/development/test $ composer require friendsofsymfony/user-bundle "~1.3"
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove symfony/symfony v3.1.6
    - Conclusion: don't install symfony/symfony v3.1.6
    - friendsofsymfony/user-bundle v1.3.0 requires symfony/security-bundle 2.1.* -> satisfiable by symfony/security-bundle[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.12, v2.1.13, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9].
    - friendsofsymfony/user-bundle v1.3.1 requires symfony/security-bundle >=2.1,<2.3-dev -> satisfiable by symfony/security-bundle[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.12, v2.1.13, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9].
    - friendsofsymfony/user-bundle v1.3.2 requires symfony/security-bundle ~2.1 -> satisfiable by symfony/security-bundle[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.12, v2.1.13, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.38, v2.3.39, v2.3.4, v2.3.40, v2.3.41, v2.3.42, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9].
    - friendsofsymfony/user-bundle v1.3.3 requires symfony/security-bundle ~2.1 -> satisfiable by symfony/security-bundle[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.12, v2.1.13, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.38, v2.3.39, v2.3.4, v2.3.40, v2.3.41, v2.3.42, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9].
    - friendsofsymfony/user-bundle v1.3.4 requires symfony/security-bundle ~2.1 -> satisfiable by symfony/security-bundle[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.12, v2.1.13, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.38, v2.3.39, v2.3.4, v2.3.40, v2.3.41, v2.3.42, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9].
    - friendsofsymfony/user-bundle v1.3.5 requires symfony/security-bundle ~2.1 -> satisfiable by symfony/security-bundle[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.12, v2.1.13, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.38, v2.3.39, v2.3.4, v2.3.40, v2.3.41, v2.3.42, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9].
    - friendsofsymfony/user-bundle v1.3.6 requires symfony/security-bundle ~2.1 -> satisfiable by symfony/security-bundle[v2.1.0, v2.1.1, v2.1.10, v2.1.11, v2.1.12, v2.1.13, v2.1.2, v2.1.3, v2.1.4, v2.1.5, v2.1.6, v2.1.7, v2.1.8, v2.1.9, v2.2.0, v2.2.1, v2.2.10, v2.2.11, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.2.7, v2.2.8, v2.2.9, v2.3.0, v2.3.1, v2.3.10, v2.3.11, v2.3.12, v2.3.13, v2.3.14, v2.3.15, v2.3.16, v2.3.17, v2.3.18, v2.3.19, v2.3.2, v2.3.20, v2.3.21, v2.3.22, v2.3.23, v2.3.24, v2.3.25, v2.3.26, v2.3.27, v2.3.28, v2.3.29, v2.3.3, v2.3.30, v2.3.31, v2.3.32, v2.3.33, v2.3.34, v2.3.35, v2.3.36, v2.3.37, v2.3.38, v2.3.39, v2.3.4, v2.3.40, v2.3.41, v2.3.42, v2.3.5, v2.3.6, v2.3.7, v2.3.8, v2.3.9, v2.4.0, v2.4.1, v2.4.10, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.4.9, v2.5.0, v2.5.1, v2.5.10, v2.5.11, v2.5.12, v2.5.2, v2.5.3, v2.5.4, v2.5.5, v2.5.6, v2.5.7, v2.5.8, v2.5.9, v2.6.0, v2.6.1, v2.6.10, v2.6.11, v2.6.12, v2.6.13, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9, v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.3, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9].
    - don't install symfony/security-bundle v2.1.0|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.1.1|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.1.10|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.1.11|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.1.12|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.1.13|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.1.2|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.1.3|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.1.4|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.1.5|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.1.6|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.1.7|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.1.8|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.1.9|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.2.0|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.2.1|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.2.10|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.2.11|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.2.2|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.2.3|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.2.4|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.2.5|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.2.6|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.2.7|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.2.8|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.2.9|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.0|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.1|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.10|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.11|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.12|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.13|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.14|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.15|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.16|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.17|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.18|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.19|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.2|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.20|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.21|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.22|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.23|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.24|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.25|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.26|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.27|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.28|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.29|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.3|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.30|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.31|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.32|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.33|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.34|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.35|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.36|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.37|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.38|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.39|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.4|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.40|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.41|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.42|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.5|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.6|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.7|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.8|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.3.9|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.4.0|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.4.1|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.4.10|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.4.2|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.4.3|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.4.4|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.4.5|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.4.6|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.4.7|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.4.8|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.4.9|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.5.0|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.5.1|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.5.10|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.5.11|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.5.12|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.5.2|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.5.3|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.5.4|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.5.5|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.5.6|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.5.7|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.5.8|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.5.9|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.6.0|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.6.1|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.6.10|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.6.11|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.6.12|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.6.13|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.6.2|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.6.3|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.6.4|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.6.5|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.6.6|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.6.7|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.6.8|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.6.9|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.7.0|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.7.1|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.7.10|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.7.11|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.7.12|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.7.13|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.7.14|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.7.15|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.7.16|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.7.17|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.7.18|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.7.19|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.7.2|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.7.20|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.7.3|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.7.4|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.7.5|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.7.6|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.7.7|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.7.8|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.7.9|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.8.0|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.8.1|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.8.10|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.8.11|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.8.12|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.8.13|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.8.2|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.8.3|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.8.4|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.8.5|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.8.6|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.8.7|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.8.8|don't install symfony/symfony v3.1.6
    - don't install symfony/security-bundle v2.8.9|don't install symfony/symfony v3.1.6
    - Installation request for symfony/symfony == 3.1.6.0 -> satisfiable by symfony/symfony[v3.1.6].
    - Installation request for friendsofsymfony/user-bundle ~1.3 -> satisfiable by friendsofsymfony/user-bundle[v1.3.0, v1.3.1, v1.3.2, v1.3.3, v1.3.4, v1.3.5, v1.3.6].

Installation failed, reverting ./composer.json to its original content.
`

Any help would be appreciated!

**Comment by xabbuh** [comment]
FOSUserBundle 1.3 does not work with Symfony 3. You have to switch to the upcoming 2.0 release.

**Comment by andreas-glaser** [comment]
Ok got it... i guess the documentation is a bit misleading.

> This version of the bundle requires Symfony 2.1+. If you are using Symfony 2.0.x, please use the 1.2.x releases of the bundle.
