### ISSUE TITLE
redirect after registering in RegistrationController.php

### ISSUE THREAD

**Issue by iometrine** [FriendsOfSymfony/FOSUserBundle#2303]
Hi, 
I don't know if it's really what your want in your last commit

```
                  $url = $this->getParameter('fos_user.registration.confirmation.enabled')
                        ? $this->generateUrl('fos_user_registration_confirmed')
                        : $this->generateUrl('fos_user_profile_show');
```

if you put fos_user.registration.confirmation.enabled true, you are redirect to check_email
if you put fos_user.registration.confirmation.enabled false, you are redirect to profile
So you re never redirect towards fos_user_registration_confirmed

How do we do if we want to keep the page confirmed.twig.html ?

**Comment by XWB** [comment]
> if you put fos_user.registration.confirmation.enabled true, you are redirect to check_email

When true, it goes to `fos_user_registration_confirmed`?

**Comment by iometrine** [comment]
no, because there is a redirection to EmailConfirmationListener, so when it's true you're redirect on fos_user_registration_check_email

**Comment by XWB** [comment]
I see what you mean. Not sure yet how to fix that.

**Comment by XWB** [comment]
@iometrine Can you try https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2307 ?

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2308

**Comment by iometrine** [comment]
Just to understand  before to try,  what did you do and  what is the workflow now ?

**Comment by XWB** [comment]
I simply reverted https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2274

There's no need to perform this check in the controller because the listener is not leaded when `fos_user.registration.confirmation.enabled` is set to false.

https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/DependencyInjection/FOSUserExtension.php#L150

**Comment by iometrine** [comment]
Ok, this is perfect.
if you put fos_user.registration.confirmation.enabled  at true, you are forwarded to check_email
if you put fos_user.registration.confirmation.enabled at  false, you are forwarded to fos_user_registration_confirmed
You've  just lost jsut the forward  to fos_user_profile_show but it's ok for me
Thank you.
