### ISSUE TITLE
How to set work FOS via sendmail?

### ISSUE THREAD

**Issue by jack-fdrv** [FriendsOfSymfony/FOSUserBundle#2304]
Hello, I try to set up work FOS via send mail. 

How I can do this?

**Comment by damienalexandre** [comment]
Hi,

There is nothing to do in FOSUserBundle to dispatch your emails via Sendmail, you just have to configure SwiftMailer the right way, using the "sendmail" transport: http://symfony.com/doc/current/reference/configuration/swiftmailer.html#transport

**Comment by XWB** [comment]
See above.
