### ISSUE TITLE
Recover works for not exists usernames and emails.

### ISSUE THREAD

**Issue by jack-fdrv** [FriendsOfSymfony/FOSUserBundle#2305]
If I enter non existing email or user name on recover page it will continue say please check your email, I want it say the user not exists, you should register first.
How to fix it?

**Comment by core23** [comment]
This is a general message to stop sniffing who's using your page. If we show the message only to existing users, someone can bruteforce emails.

**Comment by XWB** [comment]
This behavior is as intended.
