### ISSUE TITLE
[Question] When is there a new release?

### ISSUE THREAD

**Issue by hipio** [FriendsOfSymfony/FOSUserBundle#2310]
When will a new release be done? The last one is from `15 September 2015` and 258 commits behind master (including the change which adds support for Symfony3). This creates issues for people using Symfony3 as they are forced to use an annotation that is not preferred in their `composer.json`-file. 

```
  "require": {
    "friendsofsymfony/user-bundle": "^2.0@dev",
  },
```

**Comment by XWB** [comment]
Please continue in https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2206
