### ISSUE TITLE
Salt field is null 

### ISSUE THREAD

**Issue by gicush0r** [FriendsOfSymfony/FOSUserBundle#2326]
Hi,

Few minutes ago I'm update composer libraries, after this registration page failed, the message is this: Not null violation: 7 ERROR: null value in column "salt" violates not-null constraint

After this I see the code of User.php from Model and in the __construct there aren't setting for salt. 

I'm add the salt setting with "base_convert(sha1(uniqid(mt_rand(), true)), 16, 36)" on my Users.php but it doesn't work. 

Composer up output:

  - Updating friendsofsymfony/user-bundle dev-master (c62c727 => d95bd92)
    Checking out d95bd92eb23d113b54830a6e98bc154c7da635a9

Any idea ?

P.S: Sorry my english.

**Comment by stof** [comment]
This is totally expected, as we made the field nullable in the latest master branch.

**Comment by gicush0r** [comment]
Ok, 

Tks stof,

I'm try to update schema and there are some changes:

ALTER TABLE users DROP locked;
ALTER TABLE users DROP expires_at;
ALTER TABLE users DROP credentials_expire_at;
ALTER TABLE users ALTER salt DROP NOT NULL;

Now all is ok.
