### ISSUE TITLE
Use existing table with FOSUserBundle

### ISSUE THREAD

**Issue by danitome24** [FriendsOfSymfony/FOSUserBundle#2336]
Hi,

I have an existing table called users_web with fields user (username), email, password... And I want to use FOSRestBundle with existing mapping. How to handle it?

Thanks!

**Comment by XWB** [comment]
If you use Doctrine you can use annotations to define the mappings.

**Comment by danitome24** [comment]
@XWB Could you show me a sample?

**Comment by XWB** [comment]
Something like this:

```php
use Doctrine\ORM\Mapping as ORM;
use FOS\UserBundle\Model\User as BaseUser;

/**
 * @ORM\Entity
 * @ORM\Table(name="users_web")
 */
class User extends BaseUser
{
    /**
     * @ORM\Column(name="my_field", type="string")
     */
    private $myField;
}
```

**Comment by XWB** [comment]
@danitome24 Did it work?

**Comment by danitome24** [comment]
Hi @XWB,

We've already decided that we'll use a custom user management system. In the future, we'll take a look again of this bundle because nowadays it's difficult for us to merge with our project.

Thanks for all!!
