### ISSUE TITLE
Blank page in production after recent update

### ISSUE THREAD

**Issue by jhice** [FriendsOfSymfony/FOSUserBundle#2339]
Hi,
we've done a composer update recently, updating this bundle.

The update implies the deletions of some fields like "credentientialsExpireAt.
There was bugs, we put those fields in our User class and it was ok.

Doctrine schema update done, caches cleared.

At this time all is ok in local but not in the pre-prod environment, with the app_dev.php all is ok but in prod mode the login URL gives a blank page. If we log in dev mode and go to an admin URL we're logged and can use the admin interface.

I thought It could come from the override of templates but reverting to default templates gives the same blank page.

We tried all the ways to have a trace or debug but no success.

Do you have a hint on this or a way to debug in prod mode ?

Thanks !

**Comment by XWB** [comment]
> Do you have a hint on this or a way to debug in prod mode ?

Well you could check the server error logs.

**Comment by jhice** [comment]
I did it but I'm on a shared server and the error logs shows... nothing :/

**Comment by XWB** [comment]
If `app/logs/prod.log` is empty, the next step would be to check the Apache log. Is that possible on the shared server?

**Comment by stof** [comment]
maybe you have a doctrine metadata cache in prod ?
Be careful that when using APC as cache, you cannot clear it from the CLI, as APC (and APCu) has separate caches for each SAPI.

**Comment by jhice** [comment]
Thanks to your hint XWB I read the logs in the prod folder (it's a copy of the pre-prod folder that doesnt throw any error) and *the error was there*. The field "locked" were missing, I updated the User entity and it's ok.

But it still crashes on the pre-prod environment (again, same machine, same bdd, same git source) there is something failing somewhere...

@stof : no doctrine metadata cache configured in prod.

I close the issue because the problem left in certainly elsewhere than the bundle.

Thanks !
