### ISSUE TITLE
Symfony 3 mise ajout des champs à partir de formulaire (action Ajout)

### ISSUE THREAD

**Issue by missaouiaymen** [FriendsOfSymfony/FOSUserBundle#2342]
Bonjour,
Je suis débutant en Symfony3 Php framework ,j'ai créé mon premier projet **Maps** qui contient deux classes intitulé
 **Continent(**id continent**, nom, population, nombre de pays) 
Pays(**id pays,** nom, population,id_continent)** 
**mon problème :** lorsque j'ajout un pays je veux que le nombre de population s'additionnent avec celui-ci dans leur continent .
solution en algorithme : continent.population=continent.population+pays population .
et merci d'avance.

**Comment by dcognata** [comment]
L'issue n'est pas une aide.
Un forum de prog te sera d'une meilleure aide.

**Comment by stof** [comment]
Closing this issue, as it has strictly nothing to do with FOSUserBundle
