### ISSUE TITLE
SymfonyCon Hackday: General issues cleanup

### ISSUE THREAD

**Issue by damienalexandre** [FriendsOfSymfony/FOSUserBundle#2354]
A bunch of us at SymfonyCon tried to list a bunch of issues that are either:
- not relevant anymore (because fixed i.e.)
- out of date
- answered and not closed
- just not belonging to this repository

Most of the ~200 issues of FOSUserBundle are not real bugs or features to fix, and getting rid of them could help a lot building a more clear road-map and vision for this bundle.

I also would like to suggest the use of labels, to mark issues as they arrive.

## Issues to close :red_circle: 

- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1701
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1699
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1687
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1684
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1680
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1643
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1631
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1597 (groups could be removed soon)
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1595
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1861
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1860 (maybe add the example to documentation as it a valid use case)
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1788
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1784
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1762
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1688 (Propel support was removed)
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1644
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1757
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1755 (no better solution)
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1745 (just asking implementation help)
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1744
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1716 (invalid, duplicate of the username/email issues)
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1735 not related to FOSUserBundle 
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1975
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1972
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1965
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1962
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1896 the provided solution is fine
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1894 fixed
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1893 
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1888 nothing to do with FOSUser
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1879 no feedback from the user
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1877 not relevant anymore
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1867 not an issue
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2083 invalid
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2036 fixed
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1984 
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1979 duplicate
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1720 Not hard but lots of code to write (search for existing token while generating one) Out-of-date issue, the column is defined to be unique (see: 
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1728 recent comment added in GH to say it's no-longer valid

Thanks a lot,
Cheers

**Comment by XWB** [comment]
Thanks for the feedback, I just closed several issues.

**Comment by stof** [comment]
Closing this as all issues listed above are now closed.

Thanks a lot for your work on this
