### ISSUE TITLE
Missing attributes for model User

### ISSUE THREAD

**Issue by rudirocha** [FriendsOfSymfony/FOSUserBundle#2355]
Hey,
I just ran ` composer update ` and for the last commit it seems some attributes were missing on User model class
`Updating friendsofsymfony/user-bundle dev-master (3015f09 => 507ae09) `

```
/**
     * @var bool
     */
    protected $locked;

    /**
     * @var bool
     */
    protected $expired;

    /**
     * @var \DateTime
     */
    protected $expiresAt;

    /**
     * @var bool
     */
    protected $credentialsExpired;

    /**
     * @var \DateTime
     */
    protected $credentialsExpireAt;
```

Has someone the same problem?

**Comment by damienalexandre** [comment]
Hi, what error did you get?
The  expired and credentialsExpired field have been removed from beta1, see https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Changelog.md

**Comment by rudirocha** [comment]
I got ReflectionException.
After create the issue I've tried to update Symfony to v3.2 and that lead to update again FosUserBundle
`  Updating friendsofsymfony/user-bundle dev-master (507ae09 => a38940d) `
Same error came out. One ReflectionException for each missing property until I added them to the file.

```
[ReflectionException]                                                    
    Property FOS\UserBundle\Model\User::$locked does not exist   
```

**Comment by XWB** [comment]
Try removing the cache and run composer again.

**Comment by rudirocha** [comment]
I've tried that. I manually removed the ` /var/cache ` folder and running ` composer update ` again 
```
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

                                                              
  [ReflectionException]                                       
  Property FOS\UserBundle\Model\User::$locked does not exist  
                                                              

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-update-cmd event terminated with an exception

                                                                             
  [RuntimeException]                                                         
  An error occurred when executing the "'cache:clear --no-warmup'" command:  
                                                                             
    [ReflectionException]                                                    
    Property FOS\UserBundle\Model\User::$locked does not exist   
```
It could be some other dependency or something else?

**Comment by christophe-44-27** [comment]
I have the same problem, some fields are deleted as locked for example. 

Why ? And why there is not stable branch ? We use the master as reference for the symfony versions 2.7+

**Comment by core23** [comment]
> Why ? And why there is not stable branch ? We use the master as reference for the symfony versions 2.7+

There were several discussion why there is not stable branch. The team is working very hard on a stable version. Using the `dev-master` for production is always a bad idea. Don't do this, ever!

**Comment by christophe-44-27** [comment]
I understand that the team is working hard on a stable version, but in the documentation we can see that they give us this step 1 :

Step 1: Download FOSUserBundle using composer¶
Require the bundle with composer:

$ composer require friendsofsymfony/user-bundle **"~2.0@dev"**

And they also said that " **This version of the bundle requires Symfony 2.7+. If you are using an older Symfony version, please use the 1.3.x releases of the bundle.** "

So, ok if you are in under 2.7 you can use the 1.3.x but if you are in 2.7+ you have to use the dev branch.

We are now in 3.0+ and there no stable branch, since many years. Does the team need help to do this quickly ? Why the V2 is always in development ? Well btw, there are some attributes left, and we don't have any other choice to use the v2 dev branch of this bundle.

**Comment by rudirocha** [comment]
@christophe-44-27 we have always chance to keep a stable version for our application. A composer update, in my opinion, should be done like a "test approach" and ensure that no errors exist before send to production like @core23 said.

Regarding this issue, I think FOS team can check if they have this error. If some information is need please ping :)
And any help need as @christophe-44-27 suggested can be also provided!

**Comment by XWB** [comment]
Well you can always use the latest beta release instead of relying on master.

https://github.com/FriendsOfSymfony/FOSUserBundle/releases/tag/v2.0.0-beta1

**Comment by stof** [comment]
If you use the APC cache for Doctrine mapping, you need to clear the APC cache, otherwise the cache will still be trying to reference the removed fields until you clear it.

**Comment by XWB** [comment]
@rudirocha Did you try clearing the APC cache?

**Comment by rudirocha** [comment]
I'm not able to try it now. But later i'll do it and post the result. I configured Redis to cache some doctrine and session stuff.

**Comment by rudirocha** [comment]
And it seems to be cache problem. After flush all REDIS data related to application, composer update had no problem neither the application running.
This can be closed!
Thanks guys

**Comment by icamys** [comment]
Got a similar problem using APCu. I've enabled APCu by:

1. Adding few lines to production configs:

```
# app/config/config_prod.yml

framework:
    validation:
        cache: validator.mapping.cache.doctrine.apc

doctrine:
    orm:
        metadata_cache_driver: apcu
        result_cache_driver: apcu
        query_cache_driver: apcu
```

2. Enabling ApcClassLoader in `web/app.php`:

```
// Enable APC for autoloading to improve performance.
// You should change the ApcClassLoader first argument to a unique prefix
// in order to prevent cache key conflicts with other applications
// also using APC.
$apcLoader = new Symfony\Component\ClassLoader\ApcClassLoader(sha1(__FILE__), $loader);
$loader->unregister();
$apcLoader->register(true);
```

After that I've got error in production logs:


> [2016-12-08 14:41:11] request.CRITICAL: Uncaught PHP Exception ReflectionException: "Property ?FOS\UserBundle\Model\User::$locked does not exist" at /home/cdn/www/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/RuntimeReflectionService.php line 80 {"exception":"[object] (ReflectionException(code: 0): Property FOS\\UserBundle\\Model\\User::$locked does not exist at /home/cdn/www/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/RuntimeReflectionService.php:80)"} []


Had to comment out cache driver configs to get rid of this error. However I believe it's rather a hack than a fix.

Regular `cache:clear` command does not solve the issue for me. @XWB How do you suggest to clear APCu cache?

**Comment by stof** [comment]
you need to clear you doctrine mapping cache when upgrading the bundle to beta1.

And when using APCu, it has a separate cache per SAPI. So the command will not clear the cache used by php-fpm. You need to clear it as well. The easiest way to clear APCu for php-fpm is to restart php-fpm.

**Comment by XWB** [comment]
@icamys I usually clear the APC cache by reloading Apache.

**Comment by stof** [comment]
yeah, which is the equivalent of restarting php-fpm when using mod_php rather than php-fpm

**Comment by Jurigag** [comment]
Why those properties were removed anyway ?

**Comment by mvrhov** [comment]
Because the bundle didn't use them.

**Comment by stof** [comment]
And because applications really wanting to use the features need to write some custom code anyway, so it is better if they implement the method in a way fitting their needs exactly instead of trying to fit their use case into the storage structure provided by FOSUserBundle arbitrarily.

**Comment by christophe-44-27** [comment]
Personally, I deleted FOSUserBundle because of this deletion of attributes that was not announced anywhere, overnight and I switched to a custom system using Guard, and since all is well in the best of worlds ! Indeed if projects need these attributes they can put it in custom code for the bundle, but the least of the things when developing a project as big as this one is to clearly announce its roadmap And not to put evolutions as critical only in log changes once it's done.

**Comment by stof** [comment]
@christophe-44-27 We announced it in the changelog of the beta release, and adding these attributes back if you need them is dead simple, as FOSUserBundle already forces you to have a child class anyway.
And we had complains in the past about these fields either being unnecessary (as they are about advanced features not handled by the bundle anyway, and not used by many people) or being not flexible enough for their needs.

And if you want to use an unstable (next major) version of the bundle, you should follow the list of PRs/issues of the bundle if you want announcements in advance.

**Comment by christophe-44-27** [comment]
I don't read every changelog for every project that i use.
And yes, indeed the change is simple but if I decided to change my strategy it is to be sure that this does not happen again.

The fact is that for the FOSUserBundle project, you have only one version, and that the recommendations of the bundle in the implementation of an SF 2.8 or even 3.x project are to put on the master branch which is In constant evolution.

You should have a stable version by Symfony version (or less if it's not important to change the bundle version for each SF version). And when such critical updates must be made, they are carried over to major versions of the bundle (1.5 for example then 1.6), while knowing that the branch would continue in 1.5.x (so put a corresponding require in the composer. Json) so users do not undergo these updates automatically as soon as they upload the bundle but when they choose it.

**Comment by stof** [comment]
@christophe-44-27 the upgrade from 1.5 to 1.6 is **not** a major version. But the master branch of FOSUserBundle is the dev version for 2.0 currently

**Comment by christophe-44-27** [comment]
I think you understood what I meant. 
In production, you can not use a dev branch that can change so quickly.

**Comment by xabbuh** [comment]
@christophe-44-27 As long as you commit the Composer lock file to your VCS (what you really should do) I do not see any issues with that as you can check from time to time whether or not you can safely update.

**Comment by stof** [comment]
yeah, and this is also why there are alpha and beta releases from time to time.

**Comment by oparin** [comment]
Hi,
I'm trying to run a test that worked until the last update
public function testRegister()
    {
        /** @var $client \Symfony\Bundle\FrameworkBundle\Client */
        $client = static::createClient();
        $client->request('GET', '/register');
........
but I get error:
ReflectionException: Property FOS\UserBundle\Model\User::$locked does not exist
What is the problem?

**Comment by Laurent3170** [comment]
`locked` has been removed, see #2315

**Comment by oparin** [comment]
I understand, 
In my entity, there is nowhere field 'locked'.
Why is the standard test that accesses the some page return error?
How do I change the code, to the test passed?

**Comment by Tomsgu** [comment]
Have you tried all suggestions in this issue e.g. clear apcu cache?

**Comment by oparin** [comment]
@Tomsgu  I not use apc cache, project on localhost
I used:
```
php app/console doctrine:cache:clear-metadata
php app/console doctrine:cache:clear-query
php app/console doctrine:cache:clear-result

php app/console doctrine:cache:clear-metadata  --env=prod
php app/console doctrine:cache:clear-query  --env=prod
php app/console doctrine:cache:clear-result --env=prod

rm -rf app/cache/*
```

but it did not help

**Comment by Tomsgu** [comment]
With rm app/cache/* you **can't** clear apc cache. It was already said in this thread. For example [here](https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2355#issuecomment-265778234).

**Comment by oparin** [comment]
@Tomsgu
In the previous message I said what not use apc cache. 
In my system apc not installed. 
In my system php - module apache. Apc disabled.

**Comment by Tomsgu** [comment]
@oparin sorry I missread your post completely. Have you tried 
`php app/console doctrine:cache:clear-metadata  --env=test
php app/console doctrine:cache:clear-query  --env=test
php app/console doctrine:cache:clear-result --env=test` ?

**Comment by Jurigag** [comment]
Also keep in mind if you are using this property somewhere like in view, just way to fix it is obviously remove it before clearing cache.

**Comment by oparin** [comment]
@Tomsgu 
Thank you, but it does not work :(
We'll have to go back on old version FOSUser

**Comment by Jurigag** [comment]
Maybe you actually using somehwer `{{ user.locked }}` or something like this which was in my case.

**Comment by oparin** [comment]
@Jurigag 
No no, this is not twig template. The site itself works
This is unit test.
A very simple test code:
```
public function testCode()
    {
        $client = static::createClient();
        $client->request('GET', '/blablabla');
    }
```
returned error:
`ReflectionException: Property FOS\UserBundle\Model\User::$locked does not exist`

**Comment by Jurigag** [comment]
But what createClient is doing ? Maybe accessing there locked property?

**Comment by oparin** [comment]
@Jurigag 
I dont know:( This is Symfony Kernel   https://symfony.com/doc/2.8/testing.html
Maybe incompatibility with new version FOS ;(

**Comment by oparin** [comment]
Well. This works! The question is closed!

**Comment by maxlipsky** [comment]
```
php app/console doctrine:cache:clear-metadata  --env=test 
php app/console doctrine:cache:clear-query  --env=test
php app/console doctrine:cache:clear-result --env=test
```

and for **prod**:

`app/console cache:warmup --env=prod`

**Comment by diriy** [comment]
Doesn't work anything suggested above.
Symfony 3.1.10
I don't have any APC.
Cache cleared manually form the folder var/cache. Didn't help.
Need support.

**Comment by rudirocha** [comment]
@diriy do you use any custom cache? Did you change anything regarding caching on your application? Did you ran cache clear commands?

**Comment by Jurigag** [comment]
And what error exactly you have? Are you sure that you don't have perhaps somewhere in view access to this non-existing currently property?

**Comment by diriy** [comment]
@rudirocha no, I don't. It a small app and it doesn't require in any custom caching at this stage

@Jurigag it is the same error. 
`[ReflectionException]                                                    
    Property FOS\UserBundle\Model\User::$locked does not exist   `
And I've also faced it during `composer update`. 
`Updating friendsofsymfony/user-bundle dev-master (dc8e624 => a314d4a)`

**Comment by Jurigag** [comment]
`[ReflectionException] Property FOS\UserBundle\Model\User::$locked does not exist`

This for sure means you have someowhere view with locked property. I had same problem. Just look for `.locked` in your view files.

**Comment by PaddyLock** [comment]
For me, as well as clearing doctrine and symfony caches, I also had to restart memcached

sudo /etc/init.d/memcached restart
