### ISSUE TITLE
Add custom fields input to create user command

### ISSUE THREAD

**Issue by cadavre** [FriendsOfSymfony/FOSUserBundle#2359]
`fos:user:create` let you create user only with default fields (required ones: username, email, password), but as soon as you add any single field that is `nullable=false` you're done with using this command. Can we add some custom params handler to fill this fields?

**Comment by XWB** [comment]
I feel this is out of scope for this bundle. You would need to extend the CreateUserCommand and add some custom logic. Have a look at https://github.com/FriendsOfSymfony/FOSUserBundle/pull/1917
