### ISSUE TITLE
Error after upgrade to  03ce036

### ISSUE THREAD

**Issue by LoZio** [FriendsOfSymfony/FOSUserBundle#2363]
Having a working Symfony 2.8.5 setup since months.

**Description of the problem including expected versus actual behavior**:
```
Catchable Fatal Error: Argument 1 passed to FOS\UserBundle\Doctri          
  ne\UserManager::__construct() must implement interface FOS\UserBundle\Util\  
  PasswordUpdaterInterface, instance of Symfony\Component\Security\Core\Encod  
  er\EncoderFactory given, called in XXX/app/cache/dev/appDevDe  
  bugProjectContainer.php on line 732 and defined
```

**Steps to reproduce**:
 1. run composer update in my symfony project
 2. Version involved "Updating friendsofsymfony/user-bundle dev-master (def2746 => 03ce036)"

Doctrine was upgraded flawlessy
```
  - Removing doctrine/dbal (v2.5.4)
  - Installing doctrine/dbal (v2.5.5)
    Downloading: 100%         
  - Removing doctrine/doctrine-bundle (1.6.2)
  - Installing doctrine/doctrine-bundle (1.6.4)
    Downloading: 100% 
```

Basically upgrading to newer version of userbundle breaks something.
Any ideas?

**Comment by XWB** [comment]
Did you try clearing the cache?

**Comment by stof** [comment]
Are you replacing the service definition for the user manager ?

**Comment by LoZio** [comment]
It is while clearing the cache that the problem arises (the upgrade itself finishes).   
I am NOT replacing the service definition anywhere, maybe I'm missing something. Could you point me to the doc regarding that? I'm stuck with the problem that is related to this, I suppose https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Upgrade.md#usermanager.

**Comment by stof** [comment]
Can you past the content of ``app/cache/dev/appDevDe  
  bugProjectContainer.php`` around line 732 (as this is the line mentionned in the error message) ? Pasting the code of the whole method surrounding this line would be enough.

**Comment by LoZio** [comment]
![untitled](https://cloud.githubusercontent.com/assets/869890/21143186/f20f0758-c145-11e6-8a4a-023a141f1100.png)

**Comment by stof** [comment]
Well, this is not using the UserManager class from FOSUserBundle but your own custom class. So it means you **are** overwriting the service definition somewhere

**Comment by LoZio** [comment]
Got it, thanks. I'm maintaining some code from other dev so I'll check with them.
Thank you

**Comment by xDaizu** [comment]
> We indeed made a BC break (...)

[Once again](Related: https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2048), I strongly advocate for having proper versioning in this )bundle, aswell as a "stable" and a "develop" branch.  :)

**Comment by core23** [comment]
Once again, there is a stable version! Please have a look at the 1.x branch. If you want symfony 3 support, feel free to contribute to the master, which will become the next stable release. Without any contribution, there is no symfony 3 support.

**Comment by jsbuilder** [comment]
Symfony version 3.1.5
Updating friendsofsymfony/user-bundle dev-master (9c64d6f => c0ba632)
The same problem.
Catchable Fatal Error: Argument 1 passed to FOS\UserBundle\Doctrine\UserManager::__construct() must be an instance of FOS\UserBundle\Util\PasswordUpdaterInterface ..
):

**Comment by stof** [comment]
@jsbuilder look whether you have a custom UserManager class. This was the case in the previous report

**Comment by jsbuilder** [comment]
Yes, it is bitfriends/sonata-user-bundle
--
var/cache/dev/appDevDebugProjectContainer.php
--
`    /**
     * Gets the 'fos_user.user_manager' service.
     *
     * This service is shared.
     * This method always returns the same instance of the service.
     *
     * @return \Sonata\UserBundle\Entity\UserManager A Sonata\UserBundle\Entity\UserManager instance
     */
    protected function getFosUser_UserManagerService()
    {
        $a = $this->get('fos_user.util.email_canonicalizer');

        return $this->services['fos_user.user_manager'] = new \Sonata\UserBundle\Entity\UserManager($this->get('security.encoder_factory'), $a, $a, $this->get('fos_user.object_manager'), 'AppBundle\\Entity\\User');
    }`

**Comment by XWB** [comment]
It needs to be resolved in `sonata-user-bundle`.
