### ISSUE TITLE
Bug in password resetting

### ISSUE THREAD

**Issue by apfz** [FriendsOfSymfony/FOSUserBundle#2366]
In the password reset form, I can enter any email address / username without the system throwing an error saying the user does not exist. 

I believe this was available in previous versions of FOSUserBundle, as it was redirecting the user to the form again. With invalid_username I was then able to provide a notification to the user.

**Comment by stof** [comment]
This was done on purpose, as the message displayed previously allowed to identify existing accounts

**Comment by apfz** [comment]
ok. 

so basically the user would have to be informed in the check-email page that in case no email came the email may have been misspelled?

Or what is the new suggested method of doing this?

**Comment by skonsoft** [comment]
I got the same problem. Users requesting the reset password do not undrestand what happens exactly.

I think that informing users that the entred email is wrong and not tell them that they have receieved the email and should check their inbox..

Thanks

**Comment by core23** [comment]
Maybe we could send an email to the address to inform that this address isn't registered yet? Looks like a more secure way.

**Comment by abhinavkumar940** [comment]
and a bit spammy @core23 don't you think? I can use any emails and can abuse not just the server sending emails but also the email accounts.

The current implementation makes sense to me, if you want to be more verbose you can alter/translate the message shown to the user.

**Comment by XWB** [comment]
You can always override the translation files and add a custom message.
