### ISSUE TITLE
Seeing Login Inputfields twice

### ISSUE THREAD

**Issue by Selion05** [FriendsOfSymfony/FOSUserBundle#2367]
friendsofsymfony/user-bundle         dev-master 03ce036 Symfony FOSUserBundle
symfony/symfony                      v3.2.0 

**Description of the problem including expected versus actual behavior**:

After changing the login form template  I added 
`    access_control:
        #... 
        - { path: ^/, role: ROLE_USER }`

to security.yml.

Now I'm seeing the input fields inside the form twice.

It's fine with app.php/login or when I rename the FOSUserBundle folder where my custom templates are in.

I deleted the cache as well but it didn't  change anything

**Comment by damienalexandre** [comment]
Could you show us your custom login template? Because it looks like an issue with the template itself.

Thanks

**Comment by Selion05** [comment]
sure.

app/Resources/FOSUserBundle/views/layout.html.twig
`{% extends 'base.html.twig' %}

{% block main %}
{% block fos_user_content %}{% endblock %}
{% endblock %}
`

app/Resources/FOSUserBundle/views/Security/login.html.twig
`{% extends "FOSUserBundle::layout.html.twig" %}
{% block nav %}{% endblock %}

{% trans_default_domain 'FOSUserBundle' %}

{% block fos_user_content %}


{% if error %}
    <div>{{ error.messageKey|trans(error.messageData, 'security') }}</div>
{% endif %}

      <form class="form-signin" action="{{ path("fos_user_security_check") }}" method="post" class="form-signin">
          {% if csrf_token %}
              <input type="hidden" name="_csrf_token" value="{{ csrf_token }}" />
          {% endif %}
      <label for="username" class="sr-only">{{ 'security.login.username'|trans }}</label>
      <input type="text" id="username" name="_username" class="form-control" value="{{ last_username }}" placeholder="{{ 'security.login.username'|trans }}" required="required" autofocus />

      <label for="password" class="sr-only">{{ 'security.login.password'|trans }}</label>
      <input type="password" id="password" class="form-control" name="_password" required="required" placeholder="{{ 'security.login.password'|trans }}"/>

      <label for="remember_me">
          <input type="checkbox" id="remember_me" name="_remember_me" value="on" />
          {{ 'security.login.remember_me'|trans }}
      </label>

      <input class="btn btn-lg btn-primary btn-block" type="submit" id="_submit" name="_submit" value="{{ 'security.login.submit'|trans }}" />
      </form>

{% endblock fos_user_content %}`

Thanks!

**Comment by Selion05** [comment]
okay I figured out what's wrong.  I just copy pasted the security.yml from http://symfony.com/doc/current/bundles/FOSUserBundle/index.html  and the
```        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false```
part wasn't in there
