### ISSUE TITLE
Profile edit not submiting.

### ISSUE THREAD

**Issue by victorluisaguadoleon** [FriendsOfSymfony/FOSUserBundle#2368]
Profile edit not submiting. Symfony report:
Symfony\Component\Validator\ConstraintViolation
Object(Symfony\Component\Form\Form).data.plainPassword = null

**Comment by damienalexandre** [comment]
We can't help you without more informations. Please provide:
- the FOSUB version and Symfony version
- your configuration and any particular override you may have done

**Comment by victorluisaguadoleon** [comment]
This problem appear after 'php composer.phar update'


Symfony version 2.8.14 - app/dev/debug
friendsofsymfony/user-bundle         dev-master 03ce036 Symfony FOSUserBundle

/*config.yml*/
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: UserBundle\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    registration:
        form:
            type:     fos_user_registration
        confirmation:
            enabled: true
            template: UserBundle:Email:email.txt.twig
            from_email: { address: '%mailer_user%', sender_name: '%mailer_user_name%' }
    resetting:
        email:
            template: UserBundle:Email:password_resetting.email.twig
            from_email: { address: '%mailer_user%', sender_name: '%mailer_user_name%' }
    profile:
        form:
            type:     acme_user_profile

/*acme_user_profile*/
<?php


namespace UserBundle\Form\Type;

use SmallCompany\DefaultBundle\Form\PhoneType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use FOS\UserBundle\Form\Type\ProfileFormType as BaseType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use UserBundle\Entity\User;

class ProfileFormType extends BaseType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options);
        $builder->add('full_name')
            ->add('avatarFile', 'vich_file', array(
                'label' => 'Buscar',
                'required'      => false,
                'allow_delete'  => false, // not mandatory, default is true
                'download_link' => false
            ))->add('phones', CollectionType::class, array(
                'label' => 'Telefonos',
                'entry_type' => PhoneType::class,
                'allow_add' => true,
                'allow_delete' => true,
                'by_reference' => false,
                'required' => false,
                'cascade_validation' => true,
            ));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        parent::configureOptions($resolver);

        $resolver->setDefaults(array(
            'data_class' => User::class,
            'required' => false,
            'cascade_validation' => true,
        ));
    }

    public function getName()
    {
        return 'acme_user_profile';
    }
    
}
