### ISSUE TITLE
Stable release for version 2, plans / issues

### ISSUE THREAD

**Issue by nlzet** [FriendsOfSymfony/FOSUserBundle#2372]
Are there any plans or open issues that can be contributed to in order to release a stable 2.0 release? The [2.0 Milestone](https://github.com/FriendsOfSymfony/FOSUserBundle/milestone/4) seems completed, and I couldn't find any other answers.

**Comment by TerjeBr** [comment]
I also wonder about this. What is the current issues that need to be fixed before the 2.0.0-beta1 can transform into a stable 2.0.0?

What can we do to contribute to speed up this process? @stof @XWB

**Comment by ethernal** [comment]
From what I was told (can't find that thread now) only translations are missing, but that's also a minor thing and can be handled when 2.0 is released.

**Comment by XWB** [comment]
Will release the next beta shortly. After that, we can have one more beta before releasing the final version.

**Comment by weaverryan** [comment]
Woohoo! @XWB Are you planning on having a shorter beta release cycle time (e.g. 1 month)? The actual, stable 2.0 release will be a sigh of relief for Symfony users (and we're waiting on KnpUniversity for a release to upgrade our screencast) :)

**Comment by XWB** [comment]
Beta 2 has been released. The next release should be smaller, thus should come quicker.
