### ISSUE TITLE
Can't pass custom interface to custom UserManager

### ISSUE THREAD

**Issue by gevarap** [FriendsOfSymfony/FOSUserBundle#2373]
**dev-master 03ce036 **:

**How to extend \FOS\UserBundle\Model\UserInterface and pass it to custom UserManager extended from BaseUserManager for using new UserInterface for example in deleteUser(CustomUserInterface $user)**:

**Comment by stof** [comment]
Wel, you cannot change the signature of the method, this is expected (otherwise, your UserManager would not be compatible with the UserManagerInterface).

but nothing forbids you to pass your own implementing your extended interface, and doing additional work when the User implements the extended interface.

**Comment by gevarap** [comment]
Sorry, I do not fully understand.
**I have custom UserManager Extended from \FOS\UserBundle\Model\UserManager**
 --there are implimintation of \FOS\UserBundle\Model\UserManagerInterface methods
 ----such us 
 ------reloadUser(\FOS\UserBundle\Model\UserInterface $user)
 ------updateUser(\FOS\UserBundle\Model\UserInterface $user)
 **i want on updateUser setPicture(Method of extended UserInterface from \FOS\UserBundle\Model\UserInterface)**
How to call $user->setPicture() of custom  UserInterface in updateUser of custom UserManager?

**Comment by Tomsgu** [comment]
I am not sure if I fully understand your question. But for example [here](https://github.com/sonata-project/SonataUserBundle/blob/3.x/Entity/UserManager.php) you can find an example how to implement the UserManagerInterface.

**Comment by XWB** [comment]
The UserManager was changed in 2.0, you need to update your code. See the Upgrade note for more details.
