### ISSUE TITLE
Extends view not found

### ISSUE THREAD

**Issue by Thibault34** [FriendsOfSymfony/FOSUserBundle#2376]
Hello,

Since the implementation of the latest version two days ago, the heritagle of the views (to use those of my bundle and not those of FOSUserBundle) no longer works. Can someone explain me why please?

**Comment by Laurent3170** [comment]
They have been renamed. Have a look at Resources > views to have the new name. Mainly the "_" replace the "-".

**Comment by Thibault34** [comment]
Thank you

**Comment by Thibault34** [comment]
I have look, but, I don't undertrand, my view name is "login.html.twig"

**Comment by axzx** [comment]
this commit https://github.com/FriendsOfSymfony/FOSUserBundle/commit/ed6a1a931b438da361eb76f5145a9c25616cb0ca makes problem

**Comment by Thibault34** [comment]
What is the solution please ?

**Comment by Thibault34** [comment]
There is no way to use the views of my bundle that inherits from FOSUserBundle so?

**Comment by axzx** [comment]
I also would like to know:)
@stof

**Comment by stof** [comment]
hmm, so the bundle inheritance does not allow to overwrite templates using the native Twig notation ? This looks like a bug in Symfony then.
However, I suggest you to use the ``app/Resources/FOSUserBundle/views`` folder to overwrite the FOSUserBundle templates anyway, as this is what the Symfony documentation is recommending since months (and maybe even years).

Regarding the bundle inheritance issue, I suggest you to open an issue on the symfony repo.

**Comment by axzx** [comment]
If I use the `app/Resources/FOSUserBundle/views` folder, then I can't extend like this:
```
{% extends "@CustomUser/base.html.twig" %}
```

I've got an error:
`resource is hidden by a resource from the "CustomUserBundle" derived bundle`

**Comment by stof** [comment]
Can you give the full error message ? This is only part of it.

**Comment by Thibault34** [comment]
@axzx 
Although I would like to keep all the views in my bundle, for me, the given solution works.
I think you put all the views in app/resources/views. You also have to move base.html.twig. It should be left in /src/CustomUserBundle/views this one.

**Comment by axzx** [comment]
> [RuntimeException]                                                                                                                                                                                        
  "app/Resources/FOSUserBundle/views/Security/login.html.twig" resource is hidden by a resource from the "CustomUserBundle" derived bundle. Create a "app/Resources/Custom  
  UserBundle/views/Security/login.html.twig" file to override the bundle resource.

It occurs only in command line cach:clear

**Comment by Laurent3170** [comment]
Using Symfony 3.2.1 and latest FOSUserBundle commit, having templates in `app/Resources/FOSUserBundle/views` I can use both `{% extends "FOSUserBundle::layout.html.twig" %}` and `{% extends "@FOSUser/layout.html.twig" %}`. This takes my templates.

**Comment by stof** [comment]
Well, if you access it as ``@CustomUSer/base.html.twig``, it should indeed stay in CustomUserBundle (or in ``app/Resources/CustomUserBundle/views``. If you want to put it in ``app/Resources/FOSUserBundle/views``, you indeed need to reference it as FOSUserBundle.

**Comment by Discutea** [comment]
Hi,
I have difficulties to understand. This problem comes from symfony?
If you are in prod and need to fix quickly

cd vendor/friendsofsymfony/user-bundle && git checkout 612649c4efe02fb7d618652a449999d3b6c935d6

**Comment by kmelia** [comment]
Or downgrade to `"friendsofsymfony/user-bundle": "2.0.x-dev#612649c",` into your `composer.json` file.

**Comment by lucagtc** [comment]
See [Symfony documentation - Overriding Resources: Templates, Routing, etc](https://symfony.com/doc/current/bundles/inheritance.html#overriding-resources-templates-routing-etc)
Try use long version @FOSUserBundle/Resources/views/.... instead of short @BundleName/... in the FOSUserBundle action render.

**Comment by gondo** [comment]
another ridiculous `update`.
i had enough. until i completely remove this broken bundle, i ended up fixing specific commit in composer:
`"friendsofsymfony/user-bundle": "dev-master#c0ba63245f4155b3bc7060298089c2bf806cc002",`

**Comment by Discutea** [comment]
@gondo
I do not agree with you.
If bundle developers do not meet symfony best practices it will become unreasonable.
FOSUser is still a great job that no more restructuring time would be wasted for sf developers.

@kmelia Thank you I just discovered this practice

**Comment by mvrhov** [comment]
Why so many pissed of developers. Using development branch you should expect a lot of breakage especially when this in the process of refactoring.
I started with symfony way before it was stable. and in one of our product we I had to rewrite forms at least 4 times. Am I pissed of no.

**Comment by kmelia** [comment]
@Discutea you're welcome ;)

@mvrhov totally agree! We use development branch to get latest updates, but we know that is dev ;)
Do composer install only (with the composer.lock file) on production platforms ;)

**Comment by xabbuh** [comment]
Can you please check if symfony/symfony#21077 would solve your issue?

**Comment by kmelia** [comment]
@xabbuh yes, it's works for me!

**Comment by Thibault34** [comment]
@kmelia it's fix in Symfony 3.2.1 ?

**Comment by stof** [comment]
@Thibault34 https://github.com/symfony/symfony/pull/19586 is not merged yet

**Comment by Thibault34** [comment]
Ha ok, thank

**Comment by kmelia** [comment]
@Thibault34 nope, I just try the fix on my project ;)

**Comment by chalasr** [comment]
@kmelia Could you try out symfony/symfony#19586 instead and let us know if it works for you ?

**Comment by kmelia** [comment]
@chalasr I will try tomorrow morning.

**Comment by kmelia** [comment]
@chalasr the PR does not work on a 3.x branch, so I could not test!

**Comment by stof** [comment]
Closing in favor of #2378 (no need to keep 2 opened issues tracking this)
