### ISSUE TITLE
Overrinding registration form: Could not load type <...>

### ISSUE THREAD

**Issue by Toumm** [FriendsOfSymfony/FOSUserBundle#2384]
Hello,

I am facing the following issue while overriding the registration form:
Well, here are the symptoms:
This is the Form Type class:
//src/UserBundle/From/RegistrationForm.php
![image](https://cloud.githubusercontent.com/assets/3797095/21598215/c5a2dcee-d158-11e6-8fac-70f5e7c7c67d.png)
This is the service declaration statement:
//src/UserBundle/Ressources/config/services.yml - imported in //app/config/services.yml
![image](https://cloud.githubusercontent.com/assets/3797095/21598219/dd83fe56-d158-11e6-8c43-a745ed4e9fcf.png)
And this is the FOSUserBundle config:
//app/config/config.yml
![image](https://cloud.githubusercontent.com/assets/3797095/21598222/ee54d296-d158-11e6-8f05-f4ac4fcd36f9.png)

But at the end, the error still the same: Could not load type "toum_user_registration".
When I run "bin/console debug:container", I got a line
  toum_user_registration                                               UserBundle\Form\RegistrationType
So I believe my service is well declared but then, I don't have a clue where I forgot something.
Can someone help me with this? I read many other topics on that but none helpfull for me... 

Thanks in advance,
Toum

**Comment by mvrhov** [comment]
I'm not following the development of the bundle exactly, but I'm going to guess. 
If you are using symfony 3.x then form type is probably your class name and not service id/alias

**Comment by Toumm** [comment]
Hi mvrhoc,
Thanks for your answer. Your right! and then I have to change the getParent function in the new from type. It works!.
Thanks

**Comment by xabbuh** [comment]
@Toumm You can then also remove the `getName()` method from your form type and the `alias` attribute from the `form.type` tag of your service definition.
