### ISSUE TITLE
Always use twig for form rendering

### ISSUE THREAD

**Issue by core23** [FriendsOfSymfony/FOSUserBundle#2386]
**FOSUserBundle**: 2.0@dev

There are currently two template who have hardcoded `<form` elements. They should use `form_start` instead like in the other templates.

https://github.com/FriendsOfSymfony/FOSUserBundle/blob/52ec2944d700651d51b198c5b1d8097af2e8e594/Resources/views/Security/login_content.html.twig#L7
https://github.com/FriendsOfSymfony/FOSUserBundle/blob/ea743354f76e246fecb828c925471d7c377128c6/Resources/views/Resetting/request_content.html.twig#L3

**Comment by stof** [comment]
Well, this would force using the Symfony Form component while the processing of the form does not use it, which would make things even worse

**Comment by abhinavkumar940** [comment]
Relevant 
https://github.com/sonata-project/SonataUserBundle/issues/784

**Comment by XWB** [comment]
Feel free to open a PR.

**Comment by core23** [comment]
Will work on this next weekend
