### ISSUE TITLE
/Model/UserManager.php not fully PHP7 compliant?

### ISSUE THREAD

**Issue by CoalaJoe** [FriendsOfSymfony/FOSUserBundle#2399]
**Symfony FOSUserBundle versions**:

friendsofsymfony/user-bundle         dev-master c0ba632

**Description of the problem including expected versus actual behavior**:
I am using PHP7 and constrain my User constructor with the PHP7 Types. But when the UserManager wants to create my bundle, it does not pass the expected type (obviously). How can I go arround that without mitigating my constraints?

**Provide logs (if relevant)**:
`[2017-01-12 08:54:48] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to AppBundle\Entity\User::__construct() must be of the type string, none given, called in /var/www/remote.kvbl/vendor/friendsofsymfony/user-bundle/Model/UserManager.php on line 40" at /var/www/remote.kvbl/src/AppBundle/Entity/User.php line 95 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to AppBundle\\Entity\\User::__construct() must be of the type string, none given, called in /var/www/remote.kvbl/vendor/friendsofsymfony/user-bundle/Model/UserManager.php on line 40 at /var/www/remote.kvbl/src/AppBundle/Entity/User.php:95)"} []`

![image](https://cloud.githubusercontent.com/assets/5689499/21881876/5dbdea54-d8a8-11e6-99d9-3fde3b166385.png)

**Comment by stof** [comment]
Well, if you add mandatory arguments to your User constructor, you must override the ``createUser`` implementation of the UserManager (or avoid calling any code relying on this method)

**Comment by stof** [comment]
btw, having mandatory constructor arguments would not be compatible with the registration feature (as it relies on a form to set these values, so it does not have them at the time the object is instantiated)

**Comment by CoalaJoe** [comment]
Thanks for the quick response.
The users are getting created with the Fr3dLdap bundle.
I think i got it.
