### ISSUE TITLE
overide Fosuserbundle  registration  to use it with fosrestbundle

### ISSUE THREAD

**Issue by iometrine** [FriendsOfSymfony/FOSUserBundle#2405]
Hello,

Sorry i post the question here because i didn't find any answer.
I create a symfony project with fosuserbundle and all is great.
But now i need, to create an api to register and update my users with fosrestbundle.
So i tried to override registerAction to post my data with postman or angular.
My problem is my form is not valid and i can't see the error.

Do you know if it's possible ? What is the best way to do that ?

Let's my code below
`
public function postRegisterAction(Request $request) {

  

        //** @var $formFactory FactoryInterface 
        $formFactory = $this->get('fos_user.registration.form.factory');
        //** @var $userManager UserManagerInterface 
        $userManager = $this->get('fos_user.user_manager');
        //** @var $dispatcher EventDispatcherInterface 
        $dispatcher = $this->get('event_dispatcher');

        $user = $userManager->createUser();

        
        $user->setAge($request->get('age'));
        $user->setSexe($request->get('sexe'));
        $user->setVille($request->get('ville'));
        $user->setLatitude($request->get('lat'));
        $user->setLongitude($request->get('lng'));

        $user->setEnabled(true);
        
        $event = new GetResponseUserEvent($user, $request);
        $dispatcher->dispatch(FOSUserEvents::REGISTRATION_INITIALIZE, $event);

        if (null !== $event->getResponse()) {
            return $event->getResponse();
        }

        $form = $formFactory->createForm();
        $form->setData($user);

        $form->handleRequest($request);

        //if ($form->isSubmitted()) {

        if ('POST' === $request->getMethod()) {
            if ($form->isValid()) {
                $user = $form->getData();
                $event = new FormEvent($form, $request);
                $dispatcher->dispatch(FOSUserEvents::REGISTRATION_SUCCESS, $event);
                
                $uploadableManager = $this->get('stof_doctrine_extensions.uploadable.manager');
                $uploadableManager->markEntityToUpload($user, $user->getPhoto());
                
                $userManager->updateUser($user);
                
                if (null === $response = $event->getResponse()) {
                    $logger->info('fos_user_registration_confirmed');
                    $url = $this->generateUrl('fos_user_registration_confirmed');
                    //$response = new RedirectResponse($url);
                    $response = $this->redirectToRoute('online');
                }

                $dispatcher->dispatch(FOSUserEvents::REGISTRATION_COMPLETED, new FilterUserResponseEvent($user, $request, $response));
                $logger->info('REGISTRATION_COMPLETED');
                $view = $this->view(array('token' => $this->get("lexik_jwt_authentication.jwt_manager")->create($user)), Response::HTTP_CREATED);
                return $this->handleView($view);

                //return $response;
            }
            

            $event = new FormEvent($form, $request);
            $dispatcher->dispatch(FOSUserEvents::REGISTRATION_FAILURE, $event);
           

            if (null !== $response = $event->getResponse()) {
                $logger->info('REGISTRATION_FAILURE');
                return $response;
            }
        }
        $logger->info('FOSUserBundle:Registration:register.html.twig');
        
        $view = $this->view($form, Response::HTTP_BAD_REQUEST);
        return $this->handleView($view);
    }

`

**Comment by XWB** [comment]
Please navigate to http://symfony.com/doc/current/bundles/inheritance.html on how to override parts of a bundle.

**Comment by iometrine** [comment]
Hello XWB,

thank you for your anwer but I'm already read this document. And as you can see i know already override a part od a bundle.
I want just to know you if have some advice to work with fosrest bundle ? what is best pratice ?
