### ISSUE TITLE
adding a user column not nullable make the unit test fail

### ISSUE THREAD

**Issue by brunocombodo** [FriendsOfSymfony/FOSUserBundle#2407]
Hello,
I created a custom User entity (by inheriting the bundle) and added a : 
```php
    /**
     * @var string $country
     *
     * @ORM\Column(name="country", type="string", length=100)
     *
     * @Serializer\Exclude()
     */
    protected $country; 
```
in result, I have this error when I run the unit test : 

>  [Doctrine\DBAL\Exception\NotNullConstraintViolationException]                                                                                                                                                   
>   An exception occurred while executing 'INSERT INTO fos_user (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, confirmation_token, password_requested_at, roles, country,) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["Alexandre", "alexandre", "Alexandre@monsite.com", "alexandre@monsite.com", 0,  
>    null, "Alexandre", null, null, null, "a:0:{}", null]:                                                                                                                       
>   SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'country' cannot be null       

How should I correct this error? By not testing your whole bundle in my test suite?

**Comment by stof** [comment]
Unit tests of the bundle are not meant to be run as part of a separate project. They are unlikely to pass in this case, as you are not running them in the way they are meant to be run.

If you want to run the FOSUserBundle tests in your own CI server, you should go inside the FOSUserBundle folder and run our testsuite from there (see the .travis.yml file to see the different steps needed for that). But I don't see any benefit for that, as our CI is already running the tests on each commit (unless you modify the FOSUserBundle code itself in your project of course, but I don't provide support for such use case)

**Comment by brunocombodo** [comment]
thanks
