### ISSUE TITLE
Using removed service "fos_user.registration.form.handler" in documentation

### ISSUE THREAD

**Issue by Holicz** [FriendsOfSymfony/FOSUserBundle#2408]
[Here in docs](http://symfony.com/doc/master/bundles/FOSUserBundle/overriding_controllers.html) there is used this code

`$formHandler = $this->container->get('fos_user.registration.form.handler');`

but in master this service doesn't exists anymore. I believe, that this doc is old and should be updated. It would help me too, because now I don't know, what to do next.

**Comment by XWB** [comment]
Related to https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2288
