### ISSUE TITLE
PDOException since composer install

### ISSUE THREAD

**Issue by ArnaudTarroux** [FriendsOfSymfony/FOSUserBundle#2409]
Hi,

I have a problem since a composer install

Doctrine\DBAL\Driver\PDOException·SQLSTATE[42S22]: Column not found: 1054 Unknown column 'u0_.locked' in 'field list'

I've seen in the Upgrade.md that the $locked field has been removed, I never use this field, why the request keep use the locked field ?

Edit: After a test, each removed fields return this problem. Why the request continue to uses the fields (In private navigation the problem is solved) ?

Thanks

**Comment by stof** [comment]
Maybe you have a persistent metadata cache or DQL query cache for the ORM (in APC for instance) and you have not cleared this cache after upgrading the bundle.
If you have a persistent mapping cache or query cache, you must clear it when changing the mapping of your entities.

Btw, if you use APC, be careful: you cannot use the CLI to clear the APC cache used by the webserver. APC has separate caches for each SAPI.

**Comment by ArnaudTarroux** [comment]
@stof Thanks for the reply, When I try in private navigation, everything work fine. I don't understand…

**Comment by XWB** [comment]
Please try resetting the APC cache.
