### ISSUE TITLE
Translation files to be updated, help needed

### ISSUE THREAD

**Issue by XWB** [FriendsOfSymfony/FOSUserBundle#2419]
There are currently a lot of translation files not up-to-date with the English translation. We need some help from the community to update these files.

Below is a list of locales that need to be updated.

- [x] af
- [x] ar
- [x] bg
- [ ] ~~ca~~
- [x] cs
- [x] da
- [x] de
- [x] el
- [x] en
- [x] es
- [ ] ~~et~~
- [ ] ~~eu~~
- [ ] ~~fa~~
- [ ] ~~fi~~
- [x] fr
- [x] he
- [ ] ~~hr~~
- [x] hu
- [x] id
- [x] it
- [ ] ~~ja~~
- [ ] ~~ky~~
- [ ] ~~lb~~
- [ ] ~~lt~~
- [ ] ~~lv~~
- [ ] ~~nb~~
- [x] nl
- [x] pl
- [x] pt_BR
- [x] pt
- [x] ro
- [x] ru
- [ ] ~~sk~~
- [ ] ~~sl~~
- [x] sr_Latn
- [x] sv
- [ ] ~~th~~
- [x] tr
- [x] uk
- [ ] ~~vi~~
- [ ] ~~zh_CN~~

**Comment by stof** [comment]
for people looking at contributing to this update, the locales being checked above are the one being updated already.

To contribute to this effort, update the translation files for a locale, and open a PR for it (and reference this issue in the PR description for best discovery).
The English files are the reference for messages.

Btw, if you know a language not listed above, you can also contribute a *new* translation in the same way.

**Comment by raul3k** [comment]
If all translation files are under Resources / translations, pt_BR are already translated.
No need for more effort.

**Comment by XWB** [comment]
Thank you @raul3k

**Comment by stof** [comment]
@raul3k translations are there, but they are not uptodate. they still contain the 1.x messages. Some messages were updated in 2.x (in particular the resetting ones). So pt_BR still needs to be updated

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2427

**Comment by eduardoconceicao** [comment]
@XWB Added some fixes to the `pt` translations in #2430

**Comment by XWB** [comment]
@eduardoconceicao :+1:

**Comment by olegsv** [comment]
updated Hebrew translation #2447

**Comment by martin-georgiev** [comment]
Update Bulgarian translation #2454

**Comment by carlblock** [comment]
Update swedish translation #2463

**Comment by core23** [comment]
Is this the only reason for the 2.0 delay? What about dropping incomplete translations to finally release this bundle.

**Comment by rusanter** [comment]
Hi @stof, can you make 2.0 stable release #2455 with these PRs?

**Comment by XWB** [comment]
Added https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2542

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2547
