### ISSUE TITLE
Invalid CRSF TOKEN

### ISSUE THREAD

**Issue by AntoineTesson** [FriendsOfSymfony/FOSUserBundle#2429]
Hi since SF 3.2 and fosuserbundle beta1 i have sometimes  Invalid CRSF TOKEN when i'm trying to authenticate. I think its happen when i stay on the form long time with no actions.

How disable CRSF token  only on the authenticate form ? (or maybe change the configuration for this problem ? )

Thank's.

**Comment by phpetra** [comment]
@AntoineTesson You're probably running into a Symfony bug with the session path that some people seem to have in SF 3.x (as I did)
Have a look here as to some of the fixes: [CSRF token invalid](http://stackoverflow.com/questions/35208299/symfony-3-0-1-csrf-token-present-but-invalid)

Setting `save_path: ~` worked for me

**Comment by AntoineTesson** [comment]
Hi,
Tank's for this answer, i will try this "fix", i cant say if its works because i have only sometimes not always. And its strange because i save my data on the dbb, not on the disk.


    session: 
        name: SESSID
        handler_id: session.handler.pdo
        cookie_lifetime: 259200
        gc_maxlifetime: 259200
        save_path: ~

**Comment by XWB** [comment]
Closing as this seems not related to this bundle.
