### ISSUE TITLE
Please put removal of locked field also in the Changelog

### ISSUE THREAD

**Issue by phpetra** [FriendsOfSymfony/FOSUserBundle#2432]
I just found out (the hard way) about the removal of the `locked` field and other properties from the user model as described [here](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Upgrade.md#200-alpha3-to-200-beta1).

I was using an earlier version of dev-master with the fields still in it and was using the locked property to check whether users should be able to reset a password for instance, and after an update that suddenly breaks.

Since removing these fields could potentially be a big security hole for people that have implemented custom solutions, I think it might be worth mentioning in the Changelog as a [BC break] ?

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSUserBundle/commit/6a12083d0f6b53ca312021b15277d92be571cbe6
