### ISSUE TITLE
Composer update failed

### ISSUE THREAD

**Issue by lpitteloud** [FriendsOfSymfony/FOSUserBundle#2433]
I got the following error when updating dependencies with composer earlier today :

`The service "fos_user.security.login_manager" has a dependency on a non-existent service "security.token_storage".`

I tried to downgrade both symfony/symfony or friendsofsymfony/user-bundle versions, but I still got the error.

How can I fix this ?

symfony/symfony actual version **3.2.2**
friendsofsymfony/user-bundle actual version **2.0.0-beta2**

**Comment by xabbuh** [comment]
Did you disable the SecurityBundle?

**Comment by lpitteloud** [comment]
Not at all...

**Comment by xabbuh** [comment]
Did you completely disable the security config then?

**Comment by lpitteloud** [comment]
Yes, but it didn't change a thing

**Comment by xabbuh** [comment]
I mean was it already disabled when you got this error?

**Comment by lpitteloud** [comment]
Oh sorry ! It was enabled when I got the error message

**Comment by xabbuh** [comment]
I fail to see why the `security.token_storage` service should be missing then.

**Comment by stof** [comment]
hmm, going back to a Symfony version before 2.6 ?

@lpitteloud make sure that SecurityBundle is enabled *and configured*. When the bundle is not configured, it won't enable its services

**Comment by lpitteloud** [comment]
I can't downgrade to Symfony < 3.1 because I'm using api-platform 2 on my project.
I configured providers, encoders, roles, role_hierarchy and acces_control keys into security.yml.

The weird part is that I just ran the command, I did not update my bundles

**Comment by xabbuh** [comment]
You could try to debug if the `SecurityExtension` class from the SecurityBundle is loading all the files. You could also try to disable all others third-party bundles in your kernel to make sure that the failure is not related to any of them.

**Comment by lpitteloud** [comment]
Ok, fresh start this morning to finally understand what's going wrong. 
And as usual, it was my code : I simply forgot to load security config for dev env...

Thank you for your time !
