### ISSUE TITLE
non-existent service "security.token_storage" revisited

### ISSUE THREAD

**Issue by gmuehl** [FriendsOfSymfony/FOSUserBundle#2435]
**Symfony FOSUserBundle versions**:

friendsofsymfony/user-bundle         dev-master a314d4a

**Description of the problem including expected versus actual behavior**:

 1. Install SonataAdminBundle
 2. Get FOSUserBundle Up & Running
 3. Remove SonataAdminBundle

**Provide logs (if relevant)**:

The service "fos_user.security.login_manager" has a dependency on a non-existent service "security.token_storage".

**Describe the feature**:

Actually there already is a Ticket #1993 with the same Topic, though the Solution is an old Version of Symfony and the error has been solved with an Update of Symfony. At the Moment i am Using Version 3.2 of Symfony. Everything worked well with SonataAdmin. For some reasons i removed SonataAdmin and since that i am getting this Error. The Security Bundle is installed, i already checked if the File TokenStorage.php exists.

It is totally confusing that it worked with SonataAdmin installed. The only difference i have found so far is, that Sonata requires symfony/security-acl. When requiring symfony/security-bundle and symfony/security.acl manually the Error still pops up.

At the Moment i have no Idea how to solve this, any Ideas?

**Comment by stof** [comment]
Well, SecurityBundle defines this ``security.token_storage``, and FOSUserBundle requires that the SecurityBundle is configured properly (it depends on it). So the service should be there.

Can you build a reproducing case that you could share with us, to allow debugging the issue ?

**Comment by gmuehl** [comment]
Actually it is not that hard to reproduce:

Add to AppKernel.php

```
new Symfony\Bundle\SecurityBundle\SecurityBundle(),
new FOS\UserBundle\FOSUserBundle(),
```
Right after that an Error occurs that there is no db_driver for fos_user, so add the Following to config.yml:

```
fos_user:
  db_driver: orm
  firewall_name: main
  user_class: AppBundle\Entity\User
```

Ends up with error:

> The service "fos_user.security.login_manager" has a dependency on a non-existent service "security.token_storage".


I have just updated to Symfony 3.2.3 btw. Everything else needed to use FOSUSerBundle is not configured at this point. I could remove the Comments (so that i have a full Configuration), but the Error still pops up

**Comment by gmuehl** [comment]
Fun fact, added:

`$this->get('security.token_storage')->getToken()->getProviderKey();`

to the DefaultController which ends up with 

> You have requested a non-existent service "security.token_storage".

So i guess the Service is not initialized.

**Comment by gmuehl** [comment]
Ok, what a mess, got it to work! After uninstalling SonataAdmin i had to

- wipe the whole Vendor-Dir
- Delete composer.lock
- reinstall FOSUSerBundle
- **make really sure that security.yml still gets imported in config.yml**

No Idea who removed it from config.yml, maybe Composer during Deinstallation. Looks like Security gets only initialized when security.yml is included (and does not say a word if it isn't). So, no security.yml, no Service plus a whole Mess in all these Caches.

**Comment by stof** [comment]
unless you have a composer plugin doing weird things, the security.yml import cannot disappear automaticall during deinstallation. The issue was more likely a human mistake when removing the sonata admin configuration from the config.yml (removing too much things).

SecurityBundle is indeed initialized only when it is configured (which is why I asked to ensure it was configured in the previous issue). It does not care whether it is in security.yml or elsewhere (but the standard edition puts it in security.yml to separate it from other bundle configurations)
