### ISSUE TITLE
Change Password screen shows a page with just the text "fos_user_change_password"

### ISSUE THREAD

**Issue by jdbenito** [FriendsOfSymfony/FOSUserBundle#2438]
**Symfony FOSUserBundle versions**:
dev-master c0ba632

**Description of the problem including expected versus actual behavior**:
Loading the /profile/change-password route returns an empty that simply says "fos_user_change_password"

![screen shot 2017-02-08 at 4 51 21 pm](https://cloud.githubusercontent.com/assets/2699638/22763043/ac9bac9c-ee1f-11e6-956f-1558f30d547d.png)

**Describe the feature**:
I am currently in the middle of integrating the change-password function into my project. 
When the page loads, I simply get a screen that says "fos_user_change_password".

I was originally wanting to integrate the said function inside my user-edit form which overrides the registration form. UserType.php form is declared as follows:
```
class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        // Some code here
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\User'
        ));
    }

    public function getParent()
    {
        return 'FOS\UserBundle\Form\Type\RegistrationFormType';
    }

    public function getBlockPrefix()
    {
        return 'app_user_registration';
    }
}
```

My routing file is as follows:

```
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
```

I'm not really sure what else to check. When I tried to debug, it's worth noting that in line 56, `$event->getResponse()` is always `null`:

```
        if (null !== $event->getResponse()) {
            return $event->getResponse();
        }
```

I would appreciate some direction or input on how to fix. Thanks!

**Comment by stof** [comment]
> I'm not really sure what else to check. When I tried to debug, it's worth noting that in line 56, `$event->getResponse()` is always `null`:

Well, if you don't register a listener using our extension point, that's expected.

Please show your ``fos_user`` config section in the config.yml file. And also the ``framework`` section.

**Comment by jdbenito** [comment]
Thanks stof.

Here's what I have in config.yml:

```
framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

#FOS User Bundle
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: <some_email>
        sender_name:  <some sender>
    registration:
        confirmation:
            enabled: false
            template: FOSUserBundle:Registration:email.txt.twig
        form:
            type: AppBundle\Form\UserType

```

**Comment by stof** [comment]
hmm, are you overwriting the bundle templates ?

**Comment by jdbenito** [comment]
stof, if you're ever in Edmonton, Alberta, Canada, remind me to buy you a beer!

It was tripping because some of the overridden templates' names changed. Also, the base twig file from which most of the overridden files inherit, assumed there's always a logged in user.

Thanks for the assist!

**Comment by XWB** [comment]
:+1:
