### ISSUE TITLE
Can't override template in child bundle

### ISSUE THREAD

**Issue by rsukonovs** [FriendsOfSymfony/FOSUserBundle#2439]
By changing ``bundle:directory:filename`` syntax to namespaced syntax with 'at' sybmol it is impossible to override template in child bundle.

Commit: https://github.com/FriendsOfSymfony/FOSUserBundle/commit/dd1fa8fbb6df2d6037c136cc2b29a568f250069e

As far as I understand now only way to override login template is placing it into app/resources directory or by extending controller.

Reference to docs:
http://symfony.com/doc/current/templating.html#referencing-templates-in-a-bundle

**Comment by mvrhov** [comment]
This was supposed to be fixed in the symfony. And also in latest released versions of it.

**Comment by XWB** [comment]
What Symfony version are you using?

**Comment by stof** [comment]
This issue has been fixed in Symfony 2.7.23, 2.8.16, 3.1.9, 3.2.2 and master (i.e. 3.3.x-dev).

If your Symfony version is older than that for the branch you are using, you need to update Symfony.

**Comment by XWB** [comment]
See above.
