### ISSUE TITLE
Salt is empty and login manually

### ISSUE THREAD

**Issue by kironet** [FriendsOfSymfony/FOSUserBundle#2440]
Hello,

I have a two questions:

1) I've just installed FOSUserBundle, and checked user table. I'm seeing here "salt" column, but it's empty. I'm doing stn wrong that it's empty? 

2) How could I login manually in controller? I want to send HTTPRequest from mobile app to get user details, but before that I want to authenticate user(compare recieved password with password in DB). 

Thanks

**Comment by mvrhov** [comment]
1. Newest hashing algorithms e.g password_hash or hashed with crypt then the salt is embedded into the password itself.
2. For mobile app use something that most people use. OAUth.

**Comment by kironet** [comment]
Thanks, 

but still, is it possible to login manually from controller?

**Comment by mvrhov** [comment]
For automatic login look at the password reset confirmation function.

**Comment by XWB** [comment]
Have a look at the `AuthenticationListener`.

https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/EventListener/AuthenticationListener.php

**Comment by stof** [comment]
your code will work. ``$encoder->isPasswordValid()`` ignores the salt argument anyway for encoders where the salt is embedded in the hash (bcrypt, and also the new argon2i algorithm coming in symfony 3.3)

**Comment by stof** [comment]
however, you should not check this in your controller. Authenticating incoming request should be processed by the Security system itself, instead of replacing it with a custom implementation and then trying to re-input it in the security system

**Comment by XWB** [comment]
See comments above.
