### ISSUE TITLE
Consider adding GitHub Topics to this repository

### ISSUE THREAD

**Issue by javiereguiluz** [FriendsOfSymfony/FOSUserBundle#2441]
Dear bundle maintainer(s), if you want to make this bundle easier to discover and want to help us creating a stronger Symfony ecosystem, please consider adding some GitHub topics to this repository.

[The official Symfony recommendation](https://symfony.com/blog/standardizing-the-github-topics-for-symfony-repositories) is to add `php`, `symfony`, `bundle` and `symfony-bundle` topics ... and then, your own specific topics.

Thanks for your help!

**Comment by stof** [comment]
Please check the repo before opening such comment. Topics are here since the first day Github made them available: 
![fosub_topics](https://cloud.githubusercontent.com/assets/439401/22893251/76dbc8b8-f215-11e6-935e-f385dd431a60.png)

**Comment by javiereguiluz** [comment]
I'm sorry. I swear I didn't see these topics  🙈
