### ISSUE TITLE
Drop support for outdated php version? 

### ISSUE THREAD

**Issue by core23** [FriendsOfSymfony/FOSUserBundle#2443]
The latest master branch / next major require at least php [5.5.9](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/composer.json#L23), also it is unsupported. Is there a reason for it? Could we increase the min version to php 7?

**Comment by core23** [comment]
Same question for phpunit 4.x

**Comment by XWB** [comment]
Well Symfony 3 supports PHP 5.5 so we decided to inherit the same settings.

https://github.com/symfony/symfony/blob/3.2/composer.json#L19

**Comment by core23** [comment]
Symfony was released 2 years ago where there was an active php 5.5 support.

**Comment by stof** [comment]
PHPUnit 4.8 is here because of our support of PHP 5.5 (as PHPUnit 5 requires PHP 5.6+).

Regarding dropping support for PHP 5.5, I don't see a benefit here. We don't *need* any 5.6+ feature in our codebase, so keeping support for all versions supported by Symfony 3 is a valid argument IMO.

**Comment by core23** [comment]
> We don't need any 5.6+ feature in our codebase

That's the actual point of view but can you guarantee this for the future? Maybe we need this in the near future and we'll be stucked because of supporting old (unsupported) versions. 

An other problem is PHPunit. We need to write tests for PHPunit 4.8, because PHPunit 5.x won't run on [PHP 5.5](https://github.com/sebastianbergmann/phpunit/blob/5.1/composer.json#L25). So every contributor must write tests for an unsupported PHPunit version.

We should step forword and reduce future problems.

**Comment by XWB** [comment]
> That's the actual point of view but can you guarantee this for the future? Maybe we need this in the near future and we'll be stucked because of supporting old (unsupported) versions.

We won't be stuck. If we follow semver, we can simply drop PHP 5 support in `FOSUserBundle` 3.0. As version 2.0 is almost final, dropping PHP 5 support at the stage would be a huge BC break.

**Comment by XWB** [comment]
Will close this for now.
