### ISSUE TITLE
Issue to authenticate when migrating from Symfony 3.0.* to 3.2.*

### ISSUE THREAD

**Issue by Omar1123** [FriendsOfSymfony/FOSUserBundle#2445]
Hello, I have recently migrated from Symfony 3.0. * To Symfony 3.2. * At the time of logging out and authenticating a user I get the following error.

The route is http://127.0.0.1:8000/es/login_check

When I update the fosuserbundle to the **dev-master** version I get the following error

> An exception occurred while executing 'UPDATE fosuser SET last_login = ? WHERE id = ?' with params ["2017-02-14 15:56:07.000000", 4]:
>SQLSTATE [42S22, 207]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid column name 'locked'.
>SQLSTATE [42S22, 207]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid column name 'expired'.
>SQLSTATE [42S22, 207]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid column name 'expires_at'.
>SQLSTATE [42S22, 207]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid column name 'credentials_expired'.
>SQLSTATE [42S22, 207]: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Invalid column name 'credentials_expire_at'.

I would like to know if these fields are no longer used or should I add something else to use them.

Best regards

**Comment by core23** [comment]
Please have a look at the upgrade guide: https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Upgrade.md#200-alpha3-to-200-beta1

**Comment by stof** [comment]
and make sure you clear your Doctrine metadata and query caches, so that Doctrine forgets about these old columns

**Comment by Omar1123** [comment]
I already cleaned my Doctrine Metadata with this commands

php bin\console doctrine:cache:clear-result --env=dev
php bin\console doctrine:cache:clear-query --env=dev
php bin\console doctrine:cache:clear-metadata --env=dev

But still not working

**Comment by Omar1123** [comment]
I already cleaned my Doctrine Metadata with this commands

`php bin\console doctrine:cache:clear-result --env=dev`
`php bin\console doctrine:cache:clear-query --env=dev`
`php bin\console doctrine:cache:clear-metadata --env=dev`

But still not working

**Comment by XWB** [comment]
@Omar1123 Can you try clearing the APC/XCache caches?

**Comment by Omar1123** [comment]
It worked by cleaning the APC/XCache, thanks

**Comment by XWB** [comment]
:+1:
