### ISSUE TITLE
2.0 stable release?

### ISSUE THREAD

**Issue by mmucklo** [FriendsOfSymfony/FOSUserBundle#2455]
The SonataUserBundle folks have decided not to update their bundle to support Symfony 3.0 until FOSUserBundle 2.0 is stable.

[SonataUserBundle#768](https://github.com/sonata-project/SonataUserBundle/issues/768)

Is there a release time frame for 2.0 stable?

**Comment by stof** [comment]
I will do it tomorrow.
We wanted to give time for the community to update translations (see #2419), but remaining locales will stay incomplete in the 2.0.0 release. We cannot wait forever for other locales.

**Comment by XWB** [comment]
Alternatively we could remove the incomplete translation files.

**Comment by mmucklo** [comment]
Awesome, thanks!

**Comment by stof** [comment]
@XWB I was thinking about commenting translations that we changed in 2.0 rather than removing the translation entirely (many strings are still the same)

**Comment by XWB** [comment]
@stof Ok :+1:

**Comment by vladim1** [comment]
Any news about v2.0 stable release?

**Comment by mvhirsch** [comment]
@stof any news so far?

**Comment by XWB** [comment]
@stof Is there anything I can do to help?

**Comment by vladim1** [comment]
@stof 2 weeks have already passed after announcement. Could you share any info, plans or problems about v2 stable?

**Comment by jontorrado** [comment]
@stof could you please finally tag 2.0 version?

**Comment by jontorrado** [comment]
@XWB please, do something with this. One of the most used bundles and no one is answering.

**Comment by lenybernard** [comment]
He's dead Jim.

**Comment by tacman** [comment]
Symfony 3 was released at the end of 2015, nearly 18 months ago.  It seems reasonable to me that FOSUserBundle require Symfony3, developers using Symfony2 can continue to use FOSUserBundle 1.3, but I imagine that once FOSUserBundle 2.0 is officially released there will be a significant shift to Symfony 3, given how widely-used this is.

On another note, you can remove Propel from the github header, since Propel 2 is still in alpha and Propel 1 is officially unmaintained.

![image](https://cloud.githubusercontent.com/assets/619585/23996637/848acaaa-0a24-11e7-8840-0f786e2649bd.png)

**Comment by fodaveg** [comment]
maybe they want to wait until symfony4 in november to fully support symfony3. weird...

**Comment by devartbvba** [comment]
@stof can you give an update? It's quite clear a lot of people and other packages are waiting for news here, and you did say 'I will do it tomorrow' 23 days ago... 
I can understand something else intervened with that plan, but a bit of communication has never hurt anyone ;-)

**Comment by tacman** [comment]
@stof How about just a note as to what's holding you back from releasing 2.0?  You mentioned #2419 -- is that the only thing?

**Comment by vladim1** [comment]
@stof @XWB Can anybode give a note about what is going on here?

**Comment by acrobat** [comment]
I've asked @stof yesterday for a status update

> @acrobat remaining stuff is only identifying outdated keys in translations (not all of them have been updated by the community) to comment them in the release (better having it untranslated than translated with old placeholders which are not replaced anymore). But I was on vacations last week and weekends are busy currently (for non-development things)

**Comment by vladim1** [comment]
@acrobat @stof Thanks for information!

**Comment by XWB** [comment]
@acrobat Sure, feel free to open a PR :)

**Comment by vladim1** [comment]
How can we get what translations should be updated?

**Comment by dragosprotung** [comment]
@vladim1 see #2419

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSUserBundle/releases/tag/v2.0.0
