### ISSUE TITLE
How i make show two errors on plainPassword?

### ISSUE THREAD

**Issue by novuscom** [FriendsOfSymfony/FOSUserBundle#2466]
Now when an error occurs when a different password, the error shows only one field. How to show form error for the two fields of type RepeatedType?

**Comment by dmaicher** [comment]
This is more a question for StackOverflow as its not an issue with this bundle :wink:

**Comment by HeahDude** [comment]
Hello @novuscom the RepeatedType is configured in Symfony to map any error to the first child. Doing otherwise is not possible for now, you should use a form event listener to add it yourself, anyway this is an issue for [symfony/symfony](https://github.com/symfony/symfony). We should close here.
