### ISSUE TITLE
Error forgotten password

### ISSUE THREAD

**Issue by Hesiode** [FriendsOfSymfony/FOSUserBundle#2467]
Hi,

I have this error message when an user try to reset password :

> [2017-03-01 09:05:36] request.INFO: Matched route "fos_user_resetting_send_email". {"route":"fos_user_resetting_send_email","route_parameters":{"_controller":"FOS\\UserBundle\\Controller\\ResettingController::sendEmailAction","_route":"fos_user_resetting_send_email"},"request_uri":"http://xxxxxxxx/resetting/send-email","method":"POST"} []
> [2017-03-01 09:05:36] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
> [2017-03-01 09:05:36] request.CRITICAL: Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: "The parameter "fos_user.resetting.retry_ttl" must be defined." at /xxxxxxxxxx/var/cache/prod/appProdProjectContainer.php line 4022 {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\InvalidArgumentException(code: 0): The parameter \"fos_user.resetting.retry_ttl\" must be defined. at /xxxxxxxxxxxx/var/cache/prod/appProdProjectContainer.php:4022)"} []

I deleted cache and its ok but i dont why i have this error message.

Thank you

**Comment by viviengaetan** [comment]
Hey,

This parameter was added a month ago [link](https://github.com/FriendsOfSymfony/FOSUserBundle/commit/ad993482bb04088a227323efbb0156beed25d186).

I think you have updated your dependencies (composer update) without clearing your cache thus the parameter was not found in your PROD env (var/cache/prod) resulting in your error.

**Comment by Hesiode** [comment]
Oh, thank you
