### ISSUE TITLE
"Invalid CSRF token" message when resetting password

### ISSUE THREAD

**Issue by buzzbold-george** [FriendsOfSymfony/FOSUserBundle#2469]
**Symfony FOSUserBundle versions**:
$ composer info
friendsofsymfony/user-bundle         dev-master 182457a Symfony FOSUserBundle

**Description of the problem including expected versus actual behavior**:

I receive the error **Invalid CSRF token.** and have been unable to find the cause.  I have attempted the various suggestions in [this thread](http://stackoverflow.com/questions/35208299/symfony-3-0-1-csrf-token-present-but-invalid). I have also read through all issue that are returned from [this search](https://github.com/FriendsOfSymfony/FOSUserBundle/search?p=1&q=csrf&type=Issues&utf8=%E2%9C%93) and tried any suggestions that seemed like they may have any remote sort of impact.

I only receive this error when I am in the resetting flow.  I do not receive this error if I simply try to log in.  

**Steps to reproduce**:
 1. Click on "Reset Password" on Login form
 2. Enter email address for reset
 3. Receive email and click on the link that appears like this: **To reset your password – please visit http://localhost/resetting/reset/G0Ss8CK2NCkwixVagDrwv4pBe2buQU_bIbdpPTaLLyI**
 4. Enter the new password twice
 5. Get redirected to the login form with the error "Invalid CSRF token"

**Provide logs (if relevant)**:
There are no errors or informative log entries.

**Comment by buzzbold-george** [comment]
Was able to resolve this on my own.

**Comment by thibzh** [comment]
Hi, i've got exactly the same problem. 
Do you remember how you solve it ?

**Comment by Anassdev** [comment]
> Was able to resolve this on my own.

at least tell us what was the solution :) 
 ty

**Comment by WickedSilver** [comment]
My first guess would be that the hidden csrf token has not been rendered in the twig. Always make sure you have `{{ form_rest(form) }}` at the end.

**Comment by Anassdev** [comment]
@WickedSilver ty ; 
but as i read i found that the form_rest was added to form_end

**Comment by WickedSilver** [comment]
@Anassdev, np,
Can you check if your rendered HTML contains the `_crsf` input field and is rendered within the `<form>` tag?

**Comment by Anassdev** [comment]
`<form name="fos_user_resetting_form" method="post" action="/app_dev.php/resetting/reset/07YquU-oEgq3GfJHIgrULg6kstzB9asqDO-seXRuiPs" class="fos_user_resetting_reset" enctype="multipart/form-data">
                             <div id="fos_user_resetting_form"><div class="form-group"><label class="control-label required" for="fos_user_resetting_form_plainPassword_first">New password</label><input type="password" id="fos_user_resetting_form_plainPassword_first" name="fos_user_resetting_form[plainPassword][first]" required="required" class="form-control" /></div><div class="form-group"><label class="control-label required" for="fos_user_resetting_form_plainPassword_second">Repeat new password</label><input type="password" id="fos_user_resetting_form_plainPassword_second" name="fos_user_resetting_form[plainPassword][second]" required="required" class="form-control" /></div><input type="hidden" id="fos_user_resetting_form__token" name="fos_user_resetting_form[_token]" value="1mg9-3osK4UVz4CfXB6jmnIXuzotn1AJq81BVi_4iGA" /></div>
                


                <input type="submit" class="btn btn-primary aq-btn-login aq-btn-login-blue" id="submit" name="submit"
                           value="Change password"/>
                </form>`

this is HTML rendered by : 
`{{ form_start(form, { 'action': path('fos_user_resetting_reset', {'token': token}), 'attr': { 'class': 'fos_user_resetting_reset', 'enctype': 'multipart/form-data' } }) }}
                {{ form_widget(form) }}
                {{ form_rest(form) }}
   <input type="submit" class="btn btn-primary aq-btn-login aq-btn-login-blue" id="submit" name="submit"
                           value="{{ 'resetting.reset.submit'|trans }}"/>
                {{ form_end(form) }}`

**Comment by Anassdev** [comment]
this is the HTML rendered:

 ```
<form name="fos_user_resetting_form" method="post" action="/app_dev.php/resetting/reset/07YquU-oEgq3GfJHIgrULg6kstzB9asqDO-seXRuiPs" class="fos_user_resetting_reset" enctype="multipart/form-data">
                             <div id="fos_user_resetting_form"><div class="form-group"><label class="control-label required" for="fos_user_resetting_form_plainPassword_first">New password</label><input type="password" id="fos_user_resetting_form_plainPassword_first" name="fos_user_resetting_form[plainPassword][first]" required="required" class="form-control" /></div><div class="form-group"><label class="control-label required" for="fos_user_resetting_form_plainPassword_second">Repeat new password</label><input type="password" id="fos_user_resetting_form_plainPassword_second" name="fos_user_resetting_form[plainPassword][second]" required="required" class="form-control" /></div><input type="hidden" id="fos_user_resetting_form__token" name="fos_user_resetting_form[_token]" value="1mg9-3osK4UVz4CfXB6jmnIXuzotn1AJq81BVi_4iGA" /></div>
                


                <input type="submit" class="btn btn-primary aq-btn-login aq-btn-login-blue" id="submit" name="submit"
                           value="Change password"/>
                </form>
```

**Comment by WickedSilver** [comment]
The HTML looks good as far as i can see. It might be worth checking out if the the input key `_token` is indeed the right one. I'm not sure if that is the default or that something like `_csrf_token` is the default.
You might want to check the settings that are explained in this link: http://symfony.com/doc/current/security/csrf_in_login_form.html

The above link is somewhat the same as step 4 of the guide for this bundle which you should check out as well if not done already. (https://symfony.com/doc/master/bundles/FOSUserBundle/index.html#step-4-configure-your-application-s-security-yml)

**Comment by Anassdev** [comment]
ty @WickedSilver for your time ; 
i use the same configuration mentioned in the both links :) , but didnt work i still have the same error
in my login form there are a field named **_csrf_token** 
`<input type="hidden" name="_csrf_token" value="8AfG20OmVCBhlzsLy4qIQghV0V6jQQqMJmZop1jKjDs">`
and in reset password form there are just token 
`<input type="hidden" id="fos_user_resetting_form__token" name="fos_user_resetting_form[_token]" value="deNc65K88veCwW4Tz-Eb-q6RBsxOZhN3FcA4-vEJmQ0">`

is that normal ?

**Comment by WickedSilver** [comment]
Hmmm, i just checked and this is actually normal behavior. I'm not sure why you get the `invalid CSRF token` message. Someone else might have a better understanding of the error but it might be a version specific issue as well. It might help if you could provide the versions of Symfony and FOSUserBundle you are using.

**Comment by Anassdev** [comment]
@WickedSilver 
"symfony/symfony": "3.2.*",
"friendsofsymfony/user-bundle": "~2.0@dev",

**Comment by zannorman** [comment]
I was getting invalid CSRF after a password reset because my login page was attempting to REFRESH the password reset page, and the password reset token was in the URL. Making the LOGIN.Success() action redirect to '/' instead of refreshing /passwordreset/blahsomepasswordresetcode/ fixed the CSRF issue.

**Comment by Anassdev** [comment]
@zannorman it was a conflit between 2 bundles FOS user and FOS OAuthServer :)

**Comment by blackarcanis** [comment]
Got the same error "Invalid CSRF token" if I clear cookies on the reset password form.
We could imagine this user case:
1/ generating the mail of reset password on a device A
2/ open the mail on a device B (different browser) and so trying to resetting password
3/ You will get the CSRF error...

Any solution ?
