### ISSUE TITLE
Login with email and password

### ISSUE THREAD

**Issue by IhorTk** [FriendsOfSymfony/FOSUserBundle#2471]
Hi
I'm trying to implement user login with email. I have added username_email to security.yml, but login page remains the same

```
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
```

I'm currently on symfony 3.1.4 version
Please help, how can I solve this issue?

**Comment by stof** [comment]
I don't understand what you mean. The login page has no reason to change. This change the way users are loaded when submitting the form. It does not change the login page.

**Comment by IhorTk** [comment]
Sorry for this misunderstanding. I just want to know how to disallow user to login with usernames
