### ISSUE TITLE
Can I login throw external API

### ISSUE THREAD

**Issue by osavchenko** [FriendsOfSymfony/FOSUserBundle#2472]
I want to check username and password throw external API. Can I do it with FOSUser or I should implement it by myself?

**Comment by damienalexandre** [comment]
This is more a Symfony question, you should read about the Symfony Security Firewall and I suggest you take a look at Guard, which make it simple to implement any kind of custom authentication.

FOSUserBundle is about storing users in the database, if yours are from an external API, that may not be what you are looking for.

- http://symfony.com/doc/current/security.html
- http://symfony.com/doc/current/security/guard_authentication.html

**Comment by stof** [comment]
Closing this issue, because this is indeed outside the scope of the bundle. FOSUserBundle implements a user provider for the security component. authenticating users is provided by the security component itself, not by FOSUserBundle.
