### ISSUE TITLE
Pass request to show action

### ISSUE THREAD

**Issue by Arhius** [FriendsOfSymfony/FOSUserBundle#2474]
Hi
I have override Profile controller and need to send request in show action
Please recommend me the best way to do that?

**Comment by viviengaetan** [comment]
Hey
Since you cannot break SOLID, you can do it this way:
```php
/**
* Show the user.
*/
public function showAction()
{
    $request = $this->container->get('request_stack')->getCurrentRequest();
}
```

:wink:

**Comment by core23** [comment]
You could add a new optional parameter in the action method: 
`Request $request = null`

**Comment by XWB** [comment]
This is pretty basic: http://symfony.com/doc/current/bundles/inheritance.html
