### ISSUE TITLE
how do i redirect to some of the other page after changeing passowd secussfully 

### ISSUE THREAD

**Issue by anil-ku-in** [FriendsOfSymfony/FOSUserBundle#2477]
**Steps to reproduce**:
 1.login as a user
 2.go to change password 
 3.after change password successfully, it's redirect "{{home}}/profile"
4. instead of that profile need to redirect some point of Url
5. I tried with creating new route "fos_user_profile_show" but it doesn't work properly

**Comment by stof** [comment]
For FOSUserBundle 2 (currently in beta, and ready to become stable), register a listener on ``FOSUserEvents::RESETTING_RESET_SUCCESS`` setting its own response in the event instead of relying on the default redirect response generated by the bundle.

**Comment by HeahDude** [comment]
@stof May be closed?
