### ISSUE TITLE
In fact, I want to allow the user to connect with a phone number or email. For the phone number I use PhoneNumber Bundle

### ISSUE THREAD

**Issue by raphydev** [FriendsOfSymfony/FOSUserBundle#2480]
<---- french---->
En fait , je veux permettre à l'utilisateur de se connecté avec un numero de télephone ou par email. Pour le numero de téléphone j'utilise PhoneNumber Bundle. Donc pour le cour j'ai modifier mon userProvider. Dans le repository loadUserByUsername. Avec ce code j'arrive , on me ramène identifiant invalide. Mais quand je fais avec un formulaire Traditionnel, il fonctionne avec l'email, mais avec le numero de téléphone : l'utilisateur est obliger de mettre son indicatif pays pour qu'il soit connecté. or PhoneNumberBundle me donne la possibilité de demander à l'utilisateur de choisir son code pays et renseigner son num et son pass par la suite. En conclusion le code sur l'affichage fonctionne bien mais la connexion ne passe pas ? Vraiment besoins de votre aide. merci d'avance  ||

 In fact, I want to allow the user to connect with a phone number or email. For the phone number I use PhoneNumber Bundle. So for the court I modify my userProvider. In the loadUserByUsername repository. With this code I arrive, they bring me invalid identifier. But when I do with a Traditional form, it works with the email, but with the phone number: the user is obliged to put his country code so that it is connected. Or PhoneNumberBundle gives me the opportunity to ask the user to choose his / her country code and to inform his / her num and its pass thereafter. In conclusion the code on the display works well but the connection does not pass? Really needs your help. thank you in advance

Mon code : 
https://gist.github.com/raphydev/7a9d541c545e90ee137c388539f57e13

**Comment by stof** [comment]
You are using your own user provider, so the loading of the user is in your own code and does not involve FOSUserBundle at all anymore.

**Comment by raphydev** [comment]
When I use the traditional form the connection passes very well. But with the formBuilder, I have errors like identifier invalid ? why ?
