### ISSUE TITLE
Request Body Converter with Param Converter

### ISSUE THREAD

**Issue by FlorinAsavoaie** [FriendsOfSymfony/FOSUserBundle#2481]
I would expect to have the following feature:

```php
/**
 * @View()
 * @ParamConverter(null, converter="fos_rest.request_body", options={"object_to_populate" = "post"})
 */
public function putAction(Post post) {
    return $post;
}
```

When doing an HTTP PUT to /posts/{id} where {id} is a valid ID of a post, the body converter would automatically use the `object_to_populate` option of the Serializer component to update the `post` parameter in place, after retrieving the `post` from the ParamConverter.

I did not get the time to look into how difficult this would be to implement but any suggestions would be welcome.

**Comment by dmaicher** [comment]
This seems to belong here instead? https://github.com/FriendsOfSymfony/FOSRestBundle

Can you close this issue?
