### ISSUE TITLE
Notice: removed fields causing issues with existing installation of Symfony 3

### ISSUE THREAD

**Issue by bertoost** [FriendsOfSymfony/FOSUserBundle#2483]
Hi guys,

Because I don't have any other option to contact you, a issue post here;

Since FOSUserBundle ^1.3 doesn't work with Symfony 3 (and higher) we need to use @dev annotation in the composer.json file. This makes us very depending on what you do or decide.

See http://symfony.com/doc/current/bundles/FOSUserBundle/index.html

Today I updated Symfony to the latest v3.2.6 and this forced me to update the latest FOSUserBundle too.

I discovered some fields where removed, see https://github.com/FriendsOfSymfony/FOSUserBundle/commit/7ad2a4ba08a4f038e49227abf1b893968af1c995
The reason is even more frustrated;
```
- people complaining about useless fields in the DB when they don't use
  the feature
- people complaining about the implementation not fitting their business
  needs.
```

Can you answer me two questions?
1. When can we expect a versioning tag for Symfony 3 version of FOSUserBundle? (so we can decide for our self what version to use, and to stay on)
2. Why do you remove such fields if you don't know if people are using these fields?

Like to hear from you again.

Regards, Bert

**Comment by eduardoconceicao** [comment]
@bertoost As a rule you should never use your dependencies in dev versions. You should use the most recent tagged version that works wit symfony 3 (v2.0.0-beta1) this way only you can choose when to update the bundle by changing the version that you're using

**Comment by bertoost** [comment]
@eduardoconceicao True! but therefor I wasn't aware of beta-versions and the current docs on Symfony.com are also not noticing anything about the beta versions
But I will change to use a beta at least.

**Comment by eduardoconceicao** [comment]
There are a lot of projects that are/were waiting for the 2.0 version of this bundle to migrate to symfony 3. I know that a great effort was made on the last times to get the 2.0 version out and the 2.0 should be out real soon (at least that's what i expect). You can see a discussing about it here #2455

@stof @XWB any news about the that?

**Comment by bertoost** [comment]
@eduardoconceicao can you tell me the annotation of the 2.0 beta version for the composer.json file? Cannot find this anywhere. Just "~2.0.0-beta2" ?

**Comment by raphydev** [comment]
Symfony 3 : http://symfony.com/doc/master/bundles/FOSUserBundle/index.html
or 
http://symfony.com/doc/current/bundles/FOSUserBundle/index.html

Look Prerequisites section

**Comment by raphydev** [comment]
in Your config override :          
handler_id:  session.handler.native_file
save_path:   ~

And FosUserBundle Install

**Comment by bertoost** [comment]
@raphydev Thanks! but that doesn't work. Also; the docs are showing `"~2.0@dev"` and that's what I am using. Curious what to use instead.
Also using ORM session storage.

**Comment by eduardoconceicao** [comment]
@bertoost I'm not sure why the beta2 tag was gone but you can you the v2.0.0-beta1. I have 1 project where i'm using it `"friendsofsymfony/user-bundle": "2.0.0-beta1"`

Hope it helps

**Comment by XWB** [comment]
@eduardoconceicao Feel free to open a PR, but please use `2.0.0-beta2` which is the latest release.

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2503
