### ISSUE TITLE
Mon code

### ISSUE THREAD

**Issue by raphydev** [FriendsOfSymfony/FOSUserBundle#2489]
`<?php

namespace Labs\AuthBundle\Form;
use libphonenumber\PhoneNumberFormat;
use Misd\PhoneNumberBundle\Form\Type\PhoneNumberType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;

class LoginFormPhone extends  AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('_username', HiddenType::class)
            ->add('phone',
                PhoneNumberType::class, [
                    'label' => false,
                    'format' => PhoneNumberFormat::NATIONAL,
                    'widget' => PhoneNumberType::WIDGET_COUNTRY_CHOICE,
                    'preferred_country_choices' => array( 'FR', 'US'),
                ]
            )
            ->add('_password',PasswordType::class,
                [
                    'label' => false,
                    'attr'  => [
                        'class' => 'form-control',
                        'placeholder' =>'Mot de passe',
                        'required'    => false
                    ]
                ]
            )
            ->addEventListener(FormEvents::PRE_SUBMIT, function (FormEvent $event){
                $user = $event->getData();
                $form = $event->getForm();

                if (!$user) {
                    return;
                }
                if(null === $user['_username']){
                    $user['_username'] = "raphael";
                    $event->setData($user);
                }
            })
        ;

    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->getBlockPrefix();
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'login_form_email';
    }

}`

**Comment by GuilhemN** [comment]
With nothing more, we can't help you.
