### ISSUE TITLE
[Feature Request] See the number of failed attempts to login

### ISSUE THREAD

**Issue by Omar1123** [FriendsOfSymfony/FOSUserBundle#2491]
**It would be nice to be able to configure a number of attempts allowed when authenticating a user.**

**How can I implement a logon attempt counter and be able to lock an account when a certain number of failed attempts are reached at the time of authentication.**:

**Comment by stof** [comment]
this is out of scope of this bundle, as the authentication is handled by Symfony's SecurityBundle
