### ISSUE TITLE
I want to log in automatically after registering using a custom form

### ISSUE THREAD

**Issue by mkhinini-motaz** [FriendsOfSymfony/FOSUserBundle#2494]
I asked this question on stackoverflow but got no answer, i hope you guys can help me, thanks a lot 

http://stackoverflow.com/questions/42876465/symfony-fosuserbundle-add-account-entity-to-a-person-entity

**Comment by mpaquet** [comment]
You have to dispatch the REGISTRATION_COMPLETED event like in the default Controller : https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Controller/RegistrationController.php#L78

This will trigger the authentication : https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/EventListener/AuthenticationListener.php

**Comment by mkhinini-motaz** [comment]
it works, thanks a lot

**Comment by XWB** [comment]
:+1:
