### ISSUE TITLE
UserManager->findUserByUsernameOrEmail causes problems when impersonating a user

### ISSUE THREAD

**Issue by ami-m** [FriendsOfSymfony/FOSUserBundle#2500]
if a user's username is a valid email address which is different from his email address, then the impersonating will fail.

This is happening because the findUserByUsernameOrEmail method recieves the "$usernameOrEmail" parameter and has to decide how to treat it, and seeing as it is a valid email in the example above it will be treated as the email field, and the query will fail.

Honestly, I don't see how you can easily fix this, but maybe it should be mentioned in the docs...

**Comment by mpaquet** [comment]
What about falling back to findUserByUsername if findUserByEmail doesn't return anything ?

**Comment by ami-m** [comment]
seems like that would solve it, but the price seems kind of high...

**Comment by mpaquet** [comment]
Allowing loging in with username or email seems to be a weird feature to me.
Is not the issue there ?

**Comment by ami-m** [comment]
actually it's quite a useful feature, definitely one that users requested in my projects.
