### ISSUE TITLE
Registration redirects directly to fos_user_registration_confirmed

### ISSUE THREAD

**Issue by JHeimbach** [FriendsOfSymfony/FOSUserBundle#2504]
**Symfony FOSUserBundle versions**:
v2.0.0-beta1 

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. register new User
 2. directly redirected to confirmed page and user is logged in

**Expected:**
 1. User gets info about email confirmation
 2. User has to click on confirmation link
 3. User gets confirmed page and is logged in

Is this a Bug or a Feature from 2.0?
If this is a feature: How can I get the old behavior back? Do I need to write my own Controller?

Redirect happens in [Line 74](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Controller/RegistrationController.php#L74)

**Comment by mpaquet** [comment]
You have to enable the feature to make it works : https://symfony.com/doc/master/bundles/FOSUserBundle/emails.html#registration-confirmation

This is handled by this listener : https://github.com/FriendsOfSymfony/FOSUserBundle/blob/v2.0.0-beta1/EventListener/EmailConfirmationListener.php

**Comment by JHeimbach** [comment]
Thanks, that explained it, i'll close the issue.
