### ISSUE TITLE
Exception for translation version: ~2.0@dev

### ISSUE THREAD

**Issue by milos-ilic** [FriendsOfSymfony/FOSUserBundle#2508]
**Symfony FOSUserBundle versions*~2.0@dev*:

**Steps to reproduce**:
 1. When running composer install I am getting exception

**Provide logs (if relevant)**:
[Symfony\Component\Translation\Exception\InvalidResourceException]                                                                               
  Error parsing YAML, invalid file "/vendor/friendsofsymfony/user-bundle/Resources/translations/FOSUserBundle.da.yml"  
                                                                                                                                                     
  [Symfony\Component\Yaml\Exception\ParseException]                                                                                                    
  Unable to parse at line 57 (near "En e-mail er blevet sendt til %email%. Den indeholder et link, du skal følge for at nulstille din adgangskode.").

**Comment by XWB** [comment]
Fixed in https://github.com/FriendsOfSymfony/FOSUserBundle/commit/400001b0897d53114e820b9cc1a0a4b1fbcc3ca8
