### ISSUE TITLE
Translation file malformated

### ISSUE THREAD

**Issue by CedrickOka** [FriendsOfSymfony/FOSUserBundle#2530]
**Symfony FOSUserBundle versions**:
"friendsofsymfony/user-bundle" : "~2.0@dev",
friendsofsymfony/user-bundle         dev-master 43127ad Symfony FOSUserBundle

**Description of the problem including expected versus actual behavior**:
After updating my project every time I try to clear the cache I get an error from the bundle

**Steps to reproduce**:
 1. composer update
 2. php app/console c:clear --env=prod

**Provide logs (if relevant)**:
  [Symfony\Component\Translation\Exception\InvalidResourceException]                                                                 
  Error parsing YAML, invalid file "/home/www/beta/vendor/friendsofsymfony/user-bundle/Resources/translations/FOSUserBundle.da.yml"  
                                                                                                                                                     
  [Symfony\Component\Yaml\Exception\ParseException]                                                                                                  
  Unable to parse at line 57 (near "En e-mail er blevet sendt til %email%. Den indeholder et link, du skal følge for at nulstille din adgangskode."  
  ).  

**Describe the feature**:

**Comment by WickedSilver** [comment]
This should be fixed if you get the latest version using `composer update`.
If not try using the `beta2` version

**Comment by XWB** [comment]
Please use the latest master version or use beta2 instead.

**Comment by CedrickOka** [comment]
Thanks you.
