### ISSUE TITLE
Brand new Install: Register CSRF issue & Login doesn't work with no errors

### ISSUE THREAD

**Issue by iamromeo** [FriendsOfSymfony/FOSUserBundle#2533]
Hello there, 

I have just installed FOSUserBundle using the guide at: https://symfony.com/doc/master/bundles/FOSUserBundle/index.html

I am on the latest version of Symfony3 (also clean install) 
I am using a MySQL  database

I have followed the instructions top to bottom:
I was able to create a new user using the console and to promote it. 

When I tried to register a new user using /register I got this error:

> The CSRF token is invalid. Please try to resubmit the form.

When I tried to use /login to login with my console created user I get the page to reload but nothing happens and I get no errors neither on the page or the app_dev's debug bar. 

Any ideas of what this might be?

**Comment by stof** [comment]
Invalid CSRF issue and non-working login might be related to an issue writing the PHP session (the CSRF token is stored in the session, and the session is used to store the current user too).
Please make sure your server can save the session properly. It might be a permission issue on the folder in which sessions are saved, especially if your webserver and your CLI are not using the same user.

This issue does not seem related to FOSUserBundle itself (the login handling is not performed by FOSUserBundle)

**Comment by XWB** [comment]
Closing as this doesn't seem related to `FOSUserBundle`.
