### ISSUE TITLE
Update to latest version prevents login by throwing runtime exception

### ISSUE THREAD

**Issue by ixM** [FriendsOfSymfony/FOSUserBundle#2534]
**Symfony FOSUserBundle versions**: 2e0243e

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. Update to latest version
 2. Try to login with existing configuration

**Provide logs (if relevant)**:
Error thrown: `There is no user provider for user "xxx\CoreBundle\Entity\FosUser".`

Last element of stack trace

`in vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/ContextListener.php at line 174
throw new \RuntimeException(sprintf('There is no user provider for user "%s".', get_class($user)));
at ContextListener ->refreshUser (object(UsernamePasswordToken)) 
in vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/ContextListener.php at line 91`

**Comment by mrblur** [comment]
Check your ```fos_user.user_class``` for "redundant" backslash:

```yaml
fos_user: \AppBundle\Entity\User
```
becomes
```yaml
fos_user: AppBundle\Entity\User
```

**Comment by ixM** [comment]
Indeed, this solved the problem. Thanks
