### ISSUE TITLE
Check email page content contains unrendered `%email%`

### ISSUE THREAD

**Issue by brad** [FriendsOfSymfony/FOSUserBundle#2538]
**Symfony FOSUserBundle versions**:
2.8

**Description of the problem including expected versus actual behavior**:
The content of `/resetting/check-email/` shows `%email%` instead of the actual email address. Full content:

> An email has been sent to %email%. It contains a link you must click to reset your password.

**Steps to reproduce**:
 1. Submit the password reset form
 2. Observe the `%email%` text in the `/resetting/check-email/` contents

**Comment by stof** [comment]
Are you overwriting the translations of the bundle ? the bundle translation does not use `%email%` anymore.

If you redefined translations, you indeed need to update them when upgrading to FOSUserBundle 2.0

**Comment by brad** [comment]
@stof :man_facepalming: Yes, I see we have overridden the translations. I'm a bit new to Symfony/PHP so please excuse my ignorance

**Comment by brad** [comment]
@stof And thanks so much for the quick help!
