### ISSUE TITLE
[Question] about UserManipulator

### ISSUE THREAD

**Issue by rmed19** [FriendsOfSymfony/FOSUserBundle#2548]
Hi,
My question is why the properties of FOS\UserBundle\Util\UserManipulator was privates?
I need to extend it and this is will be a problem.

Thanks for answers

**Comment by XWB** [comment]
Protected properties are a nightmare to maintain backwards compatibility. You could of course use the getters.

**Comment by rmed19** [comment]
UserManipulator doesn't contain getters.

The problem comes from adding required attributes to the User entity, then the fos:user:create command not working anymore due to a SQL error related to no null fields.

So, in this case, I need to overwrite the command and by consequence overwrite the UserManipulator and it can't be possible.
