### ISSUE TITLE
Doctrine Problem

### ISSUE THREAD

**Issue by Modius22** [FriendsOfSymfony/FOSUserBundle#2568]
Hello,
Have the following problem.

**Symfony FOSUserBundle versions**: v2.0.1

**Description of the problem including expected versus actual behavior**:
I have created the entity with the corresponding doctrine command:

`php bin / console doctrine:schema:update --force
`

If I now call this command again, because I have made a change to another entity, for example, I get the following error:
```
php bin/console doctrine:schema:update --force
Updating database schema...


  [Doctrine\DBAL\Exception\TableExistsException]
  An exception occurred while executing 'CREATE TABLE   user (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(180) NOT NULL, username_canonical VARCHAR(180) NOT NULL, email
   VARCHAR(180) NOT NULL, email_canonical VARCHAR(180) NOT NULL, enabled TINYINT(1) NOT NULL, salt VARCHAR(255) DEFAULT NULL, password VARCHAR(255) NOT NULL, last_login DATE
  TIME DEFAULT NULL, confirmation_token VARCHAR(180) DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT '(DC2Type:array)', UNIQUE IND
  EX UNIQ_DB7882C492FC23A8 (username_canonical), UNIQUE INDEX UNIQ_DB7882C4A0D96FBF (email_canonical), UNIQUE INDEX UNIQ_DB7882C4C05FB297 (confirmation_token), PRIMARY KEY(i
  d)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB':
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'user' already exists



  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'user' already exists



  [PDOException]
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'user' already exists
```

Am I doing something wrong? Can it be in the call an "if not exist"?

thanks for your help

Modius

**Comment by nlzet** [comment]
Do you have two Entities with the same table name? Happened to me when I copied a class and forgot to change the table name.

**Comment by Modius22** [comment]
Hi nlzet,

No I have not found another user entity.

**Comment by Modius22** [comment]
sry guys, i found the problem. An Space in the annotation:
@ORM\Table(name=" user")

**Comment by Modius22** [comment]
I have a question, which is not directly a problem. Should I make another issue open for it or there is another possibility to ask questions (discord channel or so)

**Comment by XWB** [comment]
Please open a new issue.
