### ISSUE TITLE
not rendered login form in IE and Edge

### ISSUE THREAD

**Issue by st0at** [FriendsOfSymfony/FOSUserBundle#2573]
**Symfony FOSUserBundle versions**: 2.0.1

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. Open default login page with a default bundle login template with newest IE or Edge browsers.
 2. Template is not rendered, plain html text is returned.

**Comment by TolotraRam** [comment]
Hi,

Got the same issue how did you solve it ?

**Comment by st0at** [comment]
Hi,
Problem was in a completely another place bundle. I fixed FOS Rest bundle config to return HTML format for all routes which are not API routes.

**Comment by TolotraRam** [comment]
Thx, gotta see it !!!
