### ISSUE TITLE
adding entity within collection type. Expected argument of type "array or (\Traversable and \ArrayAccess)"

### ISSUE THREAD

**Issue by lil-works** [FriendsOfSymfony/FOSUserBundle#2575]
I'm trying to add a entity to the register form. I managed to add single field with no problem. My attach entity have a OneToOne relationship within userBundle

I had this collectionType form to my extended register form. 
```
$builder->add('customer', CollectionType::class, array(
            'mapped'=>true,
            'allow_add'=>true,
            'required' => false,
            'allow_delete' => true,
            'delete_empty' => true,
            'entry_type'   => CustomerType::class
        ));

```
Of course, registering a new user this field stay empty and my CustomerType form doesn't show any field

So I try to use event listener to pre fill my customer form

```
 $builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event)
        {
         
            $user = new User();
            $customer = new Customer();
            $user->setCustomer($customer); //avec ça l'ArrayCollection aura un item Professional vide

            $event->setData($user);
        });
```

This give me this error...

> Expected argument of type "array or (\Traversable and \ArrayAccess)", "LilWorks\StoreBundle\Entity\Customer" given

I'm completly stuck at this point... Thanks for your help

I'm running with FOSUserBundle 2 and symfony 3.2.9

**Comment by dmaicher** [comment]
Your problem is totally unrelated to this bundle and should be asked on StackOverflow instead :wink: 

You are trying to use a collection form type but actually its not a collection in your user model.

**Comment by XWB** [comment]
Closing as this issue is not related to this bundle.
