### ISSUE TITLE
UserManager, login, broke after composer update (UserProvider docs unclear on how to proceed)

### ISSUE THREAD

**Issue by kcaporaso** [FriendsOfSymfony/FOSUserBundle#2577]
**Symfony FOSUserBundle versions**:
friendsofsymfony/user-bundle           dev-master a1b3867

**Description of the problem including expected versus actual behavior**:
Today I did a composer update, as expected I've had to update some things.  I updated the schema for the deleted columns like locked, expires*, etc. Also, had to stop calling several missing functions, all of which was documented here:
https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Upgrade.md

Problem:  
   Now, users can no longer login.
Expected:
  Users login as usual.

So my questions are related specifically to overriding the UserManager.  Docs state (http://symfony.com/doc/current/bundles/FOSUserBundle/user_manager.html):
> Your custom implementation can extend FOS\UserBundle\Model\UserManager to reuse the common logic.

I have had this defined and in working order for quite a long time now.
UserManager class defined as:
```class UserManager extends FOSUserManager implements UserManagerInterface, UserProviderInterface```

I see deprecated messages telling me to use ```FOS\UserBundle\Security\UserProvider instead```, however, this is the part that is really unclear.  

In the Upgrade doc I see where there's something related to UserManager to UserProvider, before/after.
```
The public methods refreshUser, loadUserByUsername and supportsClass have been removed. Please use the UserProvider instead.

Before:

$userManager->refreshUser($user);
$userManager->loadUserByUsername($username);
$userManager->supportsClass($class);
After:

$userProvider->refreshUser($user);
$userProvider->loadUserByUsername($username);
$userProvider->supportsClass($class);
```
However, this doesn't tell me how the overridden UserManager class needs to be restructured.
Am I supposed to now extend my UserManager class from UserProvider?  Am I supposed to implement a UserProviderInterface? Do I inject a UserProvider into my UserManager class and on those methods above I use the injected UserProvider?

If someone could spell it out a bit more in the way of steps to go from previous version of overriding UserManager to the "new" way to override UserManager that'd be ideal and would benefit the documentation greatly.  

**Steps to reproduce**:
 1. Have slightly older version of dev-master
 2. composer update
 3. Fix user table schema, removing locked, expires*, credentials*, etc.
 4. Try to login as usual.

**Provide logs (if relevant)**:
```
[2017-06-29 16:58:11] security.INFO: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\
\Core\\Exception\\BadCredentialsException(code: 0): Bad credentials. at /private/var/www/portal/project/vendor/symfon
y/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/UserAuthenticationProvider.php:73, Symfony\\Compone
nt\\Security\\Core\\Exception\\UsernameNotFoundException(code: 0): Username \"user1\" does not exist. at /private/var/www/
portal/project/vendor/friendsofsymfony/user-bundle/Security/UserProvider.php:46)"} []
[2017-06-29 16:58:11] security.DEBUG: Authentication failure, redirect triggered. {"failure_path":"/login"} []
```
Thank you.

**Comment by Tomsgu** [comment]
Do you have the same problem in the recent dev-master?

**Comment by stof** [comment]
if you want to customize the UserManager, you can extend the UserManager class. But implementing a *Symfony* UserProvider should be done by composition rather than by inheritance. This is why there is such deprecation. Simply don't implement UserProviderInterface in your own user manager directly.
