### ISSUE TITLE
Autowiring services based on the types they implement is deprecated

### ISSUE THREAD

**Issue by s4astliv** [FriendsOfSymfony/FOSUserBundle#2603]
**Symfony FOSUserBundle versions**:

friendsofsymfony/user-bundle         v2.0.1  Symfony FOSUserBundle

**Description of the problem including expected versus actual behavior**:

When injecting UserManagerInterface, getting the following deprecation:

> Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0. You should rename (or alias) the "fos_user.user_manager.default" service to "FOS\UserBundle\Model\UserManagerInterface" instead.

**Steps to reproduce**:
 1. Inject UserManagerInterface into any method
 2. Check deprecations in profiler

**Provide logs (if relevant)**:
`./var/cache/dev/appDevDebugProjectContainerDeprecations.log:1:a:1:{i:0;a:6:{s:4:"type";i:16384;s:7:"message";s:253:"Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0. You should rename (or alias) the "fos_user.user_manager.default" service to "FOS\UserBundle\Model\UserManagerInterface" instead.";s:4:"file";s:132:"..../vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php";s:4:"line";i:344;s:5:"trace";a:1:{i:0;a:5:{s:4:"file";s:132:"..../vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AutowirePass.php";s:4:"line";i:117;s:8:"function";s:21:"getAutowiredReference";s:5:"class";s:59:"Symfony\Component\DependencyInjection\Compiler\AutowirePass";s:4:"type";s:2:"->";}}s:5:"count";i:1;}}`

**Fix**:

Apparently this is fixed in https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2595

**Comment by Aalpaka** [comment]
Hi, s4astliv, have you managed to fix this?

I have the same issue, and it doesn't disappear even with the fix you refferenced.

Thanks!

**Comment by s4astliv** [comment]
For me fix https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2595 worked. However in the end I implemented my own user provider so I am afraid this answer wont help to fix your issue, sorry.

**Comment by Aalpaka** [comment]
So just adding those two (or actually one relevant) line did it for you?

Thanks for the help!

**Comment by s4astliv** [comment]
Glad it works for you 👍

**Comment by danaki** [comment]
I get following error: 
```
"Controller "...\ComponentsController::localeSwitchAction()" requires that you provide a value for the "$userManager" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one."
```

while my action signature looks like:
```
    public function localeSwitchAction(
        Request $request,
        RouterInterface $router,
        \FOS\UserBundle\Model\UserManagerInterface $userManager,
        TokenStorageInterface $tokenStorage,
        $locale
    ) {
```

Do you know what I do wrong?

Composer.json:
```
        "symfony/symfony": "~3.3.0",
        "friendsofsymfony/user-bundle": "^2.0@dev",
```

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2595
