### ISSUE TITLE
PostgreSQL-9.4.14-1-Windows and FOSUserBundle ~2.0

### ISSUE THREAD

**Issue by methodeprog** [FriendsOfSymfony/FOSUserBundle#2610]

**Comment by stof** [comment]
Closing as there is no explanation of what the issue is, so there is nothing we can do.

**Comment by methodeprog** [comment]
Hi Christophe
Its Ok thanks



2017-09-28 9:40 GMT+02:00 Christophe Coevoet <notifications@github.com>:
