### ISSUE TITLE
GetResponse is Declare Twice

### ISSUE THREAD

**Issue by CyrilCharlier** [FriendsOfSymfony/FOSUserBundle#2618]
Hi,

In this file : FOSUserBundle/Event/GetResponseUserEvent.php,  SetResponse is declare twice.

**Steps to reproduce**:
 1. Juste use FosUser Dev Branch

To resolve it, juste remove a SetResponse

**Comment by CyrilCharlier** [comment]
Sorre not GetResponse, but setResponse ;)

**Comment by doctoome** [comment]
Yes :)

**Comment by CyrilCharlier** [comment]
Resolve by 
https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2617

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2617
