### ISSUE TITLE
La fonction setResponse dans le fichier GetResponseUserEvent.php est redefinie avec le même parametre

### ISSUE THREAD

**Issue by amaraSanoh** [FriendsOfSymfony/FOSUserBundle#2620]
**Symfony FOSUserBundle versions**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:

A la date du 7 octrobre FOSUserBundle requiert un petit probleme dans le repertoire: 
/vendor/friendsofsymfony/user-bundle/Event , il s'agit du fichier :  
GetResponseUserEvent.php         
dans lequel la fonction setResponse est redefinie avec le même parametre . 

De ce fait, pour se servir de la page /register de ce bundle, il serait donc nécessaire de supprimer la redefinition de setResponse.

**Comment by remoteclient** [comment]
More people would be able to answer if you write in english since this is an international issue tracker.

**Comment by Laurent3170** [comment]
@amaraSanoh effectivement la fonction est indiquée 2 fois, Cela est(sera) résolu par #2617 mais vous pouvez aussi indiquer `"friendsofsymfony/user-bundle": "2.*"` dans la partie require du fichier `composer.json` au lieu de `dev-master` ce qui évitera ces problèmes.
Par aillleurs, effectivement, comme dit @remoteclient vous obtiendrez plus de réponses en vous exprimant en anglais (si vous en avez la possibilité).

**Comment by XWB** [comment]
Fixed in https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2617
