### ISSUE TITLE
Compile Error: Cannot redeclare FOS\UserBundle\Event\GetResponseUserEvent::setResponse()

### ISSUE THREAD

**Issue by twog93** [FriendsOfSymfony/FOSUserBundle#2622]
**Symfony FOSUserBundle versions**: 2.0.1

**Description of the problem including expected versus actual behavior**:
I have a problem with this route "fos_user_registration_register" on acces

Compile Error: Cannot redeclare FOS\UserBundle\Event\GetResponseUserEvent::setResponse()

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Compile Error: Cannot redeclare FOS\UserBundle\Event\GetResponseUserEvent::setResponse()" at /var/virtual_www/afbiodiversite.fr/dev.gmp.afbiodiversite.fr/htdocs/vendor/friendsofsymfony/user-bundle/Event/GetResponseUserEvent.php line 44
Hide context

[▼
  "exception" => FatalErrorException {#2306 ▼
    #message: "Compile Error: Cannot redeclare FOS\UserBundle\Event\GetResponseUserEvent::setResponse()"
    #code: 0
    #file: "/var/virtual_www/afbiodiversite.fr/dev.gmp.afbiodiversite.fr/htdocs/vendor/friendsofsymfony/user-bundle/Event/GetResponseUserEvent.php"
    #line: 44
    #severity: E_COMPILE_ERROR
  }
]
**Describe the feature**:

**Comment by twog93** [comment]
i do not declare this method anywhere in the code...

**Comment by xabbuh** [comment]
looks like a duplicate of #2618 which was fixed in #2617

**Comment by twog93** [comment]
Ok thx , but i think i comment this function in this file febore. Resolved.
