### ISSUE TITLE
Compile Error: Cannot redeclare FOS\UserBundle\Event\GetResponseGroupEvent::setResponse()

### ISSUE THREAD

**Issue by Marquis-H** [FriendsOfSymfony/FOSUserBundle#2623]
**Symfony FOSUserBundle versions**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. edit group
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:

**Comment by xabbuh** [comment]
duplicated of #2618 which was fixed in #2617

**Comment by Marquis-H** [comment]
@xabbuh  GetResponseGroupEvent !

**Comment by Marquis-H** [comment]
#2624

**Comment by lamjack** [comment]
@xabbuh GetResponseGroupEvent both, #2617 just fixed the GetResponseUserEvent.

**Comment by lamjack** [comment]
@xabbuh urgent!!!!!

<img width="920" alt="2017-10-12 6 26 20" src="https://user-images.githubusercontent.com/8164447/31491734-e9f6bd8e-af0d-11e7-9d10-a2b6f6fe857d.png">

**Comment by xabbuh** [comment]
Sorry, I missed the class name difference. But apart from that I don't have any merge access here and this is IMO not so urgent as you could easily switch back to a stable tag if you need this to work right now.

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2624
