### ISSUE TITLE
mail templates are incompatible to Mailer class

### ISSUE THREAD

**Issue by swis** [FriendsOfSymfony/FOSUserBundle#2628]
(At least) in the 2.0.* branch(es), the default email templates

* Registration/email.txt.twig, and
* Resetting/email.txt.twig

consists of twig blocks ```subject```, ```body_text```, ```body_html```.
On the other hand, the FOS\UserBundle\Mailer\Mailer::sendEmailMessage() doesn't render the templates like expected ("Render the email, use the first line as the subject, and the rest as the body"). Maybe this works under some circumstances, but the SwiftMailer docs say, that html parts of any email should be added explicitly.

My suggestion is to render the blocks (in the Mailer) as given by the templates and handle them like expected:

```
$template = $this->twig->load($filename);
$message = \Swift_Message::newInstance()
    ->setSubject($template->renderBlock('subject', $context));

$htmlBody = $template->renderBlock('body_html', $context);
if (!empty($htmlBody)) {
    $message->setBody($htmlBody, 'text/html');
    $message->addPart($template->renderBlock('body_text', $context), 'text/plain');
} else {
    $message->setBody($template->renderBlock('body_text', $context));
}
```

Any comments? Pros and cons?

**Comment by stof** [comment]
Use the TwigSwiftMailer instead, which is much better. The Mailer class should be deprecated.
