### ISSUE TITLE
Composer.json, requires strictly 5.5.9

### ISSUE THREAD

**Issue by allabakash** [FriendsOfSymfony/FOSUserBundle#2629]
**Symfony FOSUserBundle versions**: 2.0

when, I try to install FOSUserBundle 2.0, using composer, it's showing the following error.
`Problem 1
    - friendsofsymfony/user-bundle v2.0.1 requires php ^5.5.9 || ^7.0 -> your PHP version (5.5.9-1ubuntu4.22) overridden by "config.platform.php" version (5.3.9) does not satisfy that requirement.
    - friendsofsymfony/user-bundle v2.0.0 requires php ^5.5.9 || ^7.0 -> your PHP version (5.5.9-1ubuntu4.22) overridden by "config.platform.php" version (5.3.9) does not satisfy that requirement.
    - Removal request for friendsofsymfony/user-bundle == 2.0.0.0-alpha3
    - Installation request for friendsofsymfony/user-bundle ~2.0 -> satisfiable by friendsofsymfony/user-bundle[v2.0.0, v2.0.1, v2.0.0-alpha3].
`
**Description of the problem including expected versus actual behavior**:
Since  friendsofsymfony/user-bundle v2.0.1 requires php ^5.5.9 || ^7.0 
Though my PHP version is 5.5.9, it's not being installed, because of PHP version.
`php --version
PHP 5.5.9-1ubuntu4.22 (cli) (built: Aug  4 2017 19:40:28) `

Please update composer file to accept 'PHP 5.5.9*'

**Comment by stof** [comment]
no, your versions during resolution is **not** 5.5.9. It is 5.3.9. The error message says `overridden by "config.platform.php" version (5.3.9)`

**Comment by allabakash** [comment]
installed successfully, after deleting the following lines in composer.json
`"config": {
        "platform": {
            "php": "5.3.9"
        },
    },`

Thanks .
