### ISSUE TITLE
Unrecognized option "fos_user" under "doctrine" 

### ISSUE THREAD

**Issue by buddy94** [FriendsOfSymfony/FOSUserBundle#2630]
After all the configuration i did the command: php bin/console doctrine:database:create
But then i got this message: 

[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
  Unrecognized option "fos_user" under "swiftmailer.mailers.default" 

So i tried to comment the swiftmail section. I tried again but i got this:

[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
  Unrecognized option "fos_user" under "doctrine" 

In theory i followed all the configuration.

Sorry i'm very new in all of this! I don't know what document is pertinent to attach.

Thank you very much for your help

**Comment by stof** [comment]
Check your config.yml file. I suspect that the indentation of your `fos_user` config is broken, making it nested into the previous YAML block.

**Comment by buddy94** [comment]
This is my config.yml file:
(Thanks for your fast reply! I had really really appreciated your support)


imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }


    # app/config/config.yml
    fos_user:
        db_driver: orm # other valid values are 'mongodb' and 'couchdb'
        firewall_name: main
        user_class: AppBundle\Entity\User
        from_email:
            address: "%mailer_user%"
            sender_name: "%mailer_user%"

**Comment by Tomsgu** [comment]
Sorry, but this is impossible to read. Have you checked what stof proposed to you? `fos_user` should be in the beginning of a line.

**Comment by stof** [comment]
OK, after editing the comment to make it use a code block, it is clear than this is an indentation issue for the `fos_user` config. It should be a top-level key, not a key nested inside the config of the previous bundle (which is `swiftmailer` in the config you gave us, not `doctrine`, so this is not even the original file).

I'm closing this issue as it is not a bung in the bundle.
