### ISSUE TITLE
Support Symfony 4.0

### ISSUE THREAD

**Issue by piotrantosik** [FriendsOfSymfony/FOSUserBundle#2632]
Hi,
Any plan to prepare bundle with incoming Symfony 4.0?

Regards

**Comment by teeyo** [comment]
I was shocked not seeing the UserBundle in the Symfony recipes, it's one of the most popular bundles out there!. 

+1

**Comment by alejandroguille** [comment]
It seems to me that we have to wait a long time for everything to mature.

**Comment by stayeronglass** [comment]
+1

**Comment by stayeronglass** [comment]
any news?

**Comment by xabbuh** [comment]
@stayeronglass #2639

**Comment by bogdandovgopol** [comment]
Wow didn't expect that this bundle is not compatible with 4.0 yet. Have to downgrade back :(

**Comment by yonisolo** [comment]
I had such a pain to finally manage to autowire the registration controller to inject service via DI... here are the 2 files, take cautions, this is quite new to me so probably need patch...
[RegistrationController-registrationXmlService](https://github.com/FriendsOfSymfony/FOSUserBundle/files/1526783/Bureau.zip)
Hope you'll manage to do the best, good luck for all

**Comment by jimAC2016** [comment]
Any progress on this? I want to migrate to Symfony 4 and the only bundle that is not compatible to Symfony 4 is FosUserBundle. Please make it a priority.

**Comment by enboig** [comment]
I just started learning and creating a new project with symfony (so it will be a long way before it enters production). Any way to use it (could be Beta or release candidate). I don't want to start a project which may be obsolete when finished.

Thanks

**Comment by alejandroguille** [comment]
@enboig Symfony is going to change a lot and it will bring you some problems.
Use only version 3.4.

**Comment by yonisolo** [comment]
@enboig the pull request is quite ready to merge, you have 2 choices, if you have time you can wait a little for the symfony4 compatibility, if you're in a hurry, stick to symfony3.4, try to remove all deprecated, and you'll have to migrate your project later to symfony4.
Presently, i began a project with symfony4, the FOS user is not working very well, but if you patch some controllers, it will work for the basis (no console commands however). symfony v4 philosophy change quite a lot, so i suggest you to begin with it, even if you begin in degraded for this bundle, it wiill saves you some time...

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2639

**Comment by RoestVrijStaal** [comment]
Reopen this ticket please.

Both #2632 AND #2639 are closed and the docs still lack updates for SF4
