### ISSUE TITLE
Is there a way to make the password required for the register

### ISSUE THREAD

**Issue by nlefebvre1410** [FriendsOfSymfony/FOSUserBundle#2636]
Symfony 3 FOSUserBundle versions 2.0

Hello,
Is there a way to make the password required for the register?
thank you in advance

valodation.yml:
`AppBundle\Entity\User:
    properties:
        plainPassword:
          - NotBlank:
              message: "not blank message"
          - Length:
              min: 5
              max: 255
              minMessage: "too short"
              maxMessage: "too large"
              groups: [Profile]`

form:
`'validation_groups'=> null,`

**Comment by stof** [comment]
Well, if you set validation groups to null, the constraints set in FOSUserBundle won't be used (as the `Profile` group won't run).

Having the password required for registration is the default behavior.

**Comment by nlefebvre1410** [comment]
how can I do  password no required ?

**Comment by MarvinCourcier** [comment]
If you do not want the password, you can override the registration formtype and set the password to Hidden so he won't be seen.
You can even remove the username so the user just has to give you his email.

**Comment by nlefebvre1410** [comment]
thank you
