### ISSUE TITLE
Symfony 3.4 support

### ISSUE THREAD

**Issue by DamienHarper** [FriendsOfSymfony/FOSUserBundle#2642]
Do you plan to support Symfony 3.4 ?

**Comment by xabbuh** [comment]
see #2632 and #2639

**Comment by luishdez** [comment]
I hope this gets priority. I mean 4.0 is pretty much ready…

**Comment by yonisolo** [comment]
I had such a pain to finally manage to autowire the registration controller to inject service via DI... here are the 2 files, take cautions, this is quite new to me so probably need patch...
[Bureau.zip](https://github.com/FriendsOfSymfony/FOSUserBundle/files/1526783/Bureau.zip)
Hope you'll manage to do the best, good luck for all

**Comment by moag1000** [comment]
for anyone that ist struggling with the logout issue on Symfony 3.4, just implement an EquatableInterface to your user class like mentioned here:[fix for auto-logout]( https://stackoverflow.com/questions/47675301/symfony-login-token-was-deauthenticated-after-trying-to-refresh-it) 
At least this does the trick in a dirty way for now as long as this package officially supports it.

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2639
