### ISSUE TITLE
Using the activation-link for a new user more than once leads to an exception

### ISSUE THREAD

**Issue by sqrt-1764** [FriendsOfSymfony/FOSUserBundle#2644]
UserBundle Version: 2.0.1

 1. Create a new User with the FOSUserBundle
 2. Click on the activation-link
 3. Click on the activation-link again

As far as I can see this is currently the indented behaviour. (confirmAction in RegistrationController) that provides no hooks to display a customized message to the user.  

Maybe there is an option to catch this exception that I haven't found yet?

**Comment by Laurent3170** [comment]
Have a look at #2106
