### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by fredericlam** [FriendsOfSymfony/FOSUserBundle#2652]
Hi

looking at the code of sendEmailAction() method, in ResettingController.php, it looks like there are no messages handled when the user enters a wrong "username" or "email".

The line 

`<?php if (null !== $user && !$user->isPasswordRequestNonExpired($ttl)) ?>`
with no "else" indicates that nothing makes the difference between these 2 errors:
- user not found
- password request has no expired, and the user has to wait until $ttl is available again.

Is that correct ? 

I have ideas to do it myself but I just wanted to be sure that FOSUserBundle does not cover these features.

Thanks.

**Comment by stof** [comment]
indeed, we don't send an email in this case.

And as long as we allow resetting by username, we cannot do it as we would not have the corresponding email btw

**Comment by fredericlam** [comment]
Many thanks Christophe !
