### ISSUE TITLE
Integration Symfony 4

### ISSUE THREAD

**Issue by Tchekda** [FriendsOfSymfony/FOSUserBundle#2659]
I have installed the bundle on Symfony4 but there is a bug : 
I can't register because it says that the csrf token isn't valid, but it's work on login and I can create users from the terminal. 
I precise that the token is sent with the form and the controller returns FALSE on isvalid() function

**Comment by xabbuh** [comment]
How did you do that? Currently, the bundle's version constraints are not compatible with Symfony 4.

**Comment by Tchekda** [comment]
> How did you do that? Currently, the bundle's version constraints are not compatible with Symfony 


Why not? My projet is on Symfony4 and i need this bundle

**Comment by stof** [comment]
Well, what we mean is, how did you install the bundle then ? The support of SF 4 has not been merged in it yet

**Comment by Tchekda** [comment]
I did it with composer and there were any problem, but this is not my question but why the csrf is not working on register while it's working on login and groups

**Comment by xabbuh** [comment]
Without knowing what exactly you did we are not able to help you.

**Comment by Tchekda** [comment]
I just overrides the registration form

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2639

**Comment by asmaHemden** [comment]
I installed to the bundle FOS user but I can't to the configuration because the cofiguration files are not the same as symfony 3!! 
how did you configurated it ? even the login page i didn't do it.

**Comment by Tchekda** [comment]
> how did you configurated it ? even the login page i didn't do it.
If I remember well, you just need to add the bundle in the composer.json manually, then you do a composer install and add the fos configuration part in the framework.yaml instead of config.yml (Symf 3), other configurations still the same

**Comment by asmaHemden** [comment]
can you send a functional project with FosUser to show how the configuration is?  thanks

**Comment by Tomsgu** [comment]
@asmaHemden Here https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2562#issuecomment-333575348 you have an example how to configure it in flex.

**Comment by Evertt** [comment]
When will FOSUserBundle be completely compatible with symfony 4 out of the box? I'm dying to use it.

**Comment by Tchekda** [comment]
I don't think there will be a version on 4.0, only if there will be a long maintained version like 3.4

**Comment by Evertt** [comment]
@Tchekda really? oh damn, that's unexpected. I thought FOSUserBundle was the most popular bundle of symfony so to me it made sense that they would keep it up to date with the most recent versions of symfony.

Anyhow, is there a good alternative to FOSUserBundle for symfony 4?

**Comment by petegore** [comment]
Without any version for Symfony4, I'm also wondering if a good alternative exists... Or at least good article to create mine.

**Comment by mirkorap** [comment]
How can I override form with Symfony 4? I followed the guide with the old version, but it doesn't work.
![image](https://user-images.githubusercontent.com/33153699/36277632-b5d35188-1291-11e8-9b6e-1fb053d6a6d2.png)

![image](https://user-images.githubusercontent.com/33153699/36277667-cfb6b680-1291-11e8-86e8-304c1e9b40cc.png)

I got this error: "Neither the property "firstname" nor one of the methods "firstname()", "getfirstname()"/"isfirstname()"/"hasfirstname()" or "__call()" exist and have public access in class "Symfony\Component\Form\FormView"."

**Comment by MartinLyne** [comment]
@mirkorap have you checked https://symfony.com/doc/master/form/create_form_type_extension.html ?

**Comment by amiriskander** [comment]
Check this article about how to install and configure FOSUserBundle on Symfony 4

https://vfac.fr/blog/how-install-fosuserbundle-with-symfony-4
