### ISSUE TITLE
ServiceNotFoundException The service "fos_user.profiler.controller" has a dependency on a non-existent service "fos_user.email_update_confirmation".

### ISSUE THREAD

**Issue by maanas** [FriendsOfSymfony/FOSUserBundle#2670]
I am getting this error after doing composer update

ServiceNotFoundExceptionThe service "fos_user.profiler.controller" has a dependency on a non-existent service "fos_user.email_update_confirmation".
--
in CheckExceptionOnInvalidReferenceBehaviorPass.php (line 31)
at CheckExceptionOnInvalidReferenceBehaviorPass->processValue(object(Reference), false)in AbstractRecursivePass.php (line 57)
at AbstractRecursivePass->processValue(array(object(Reference), object(Reference), object(Reference), object(Reference), object(Reference)), false)in CheckExceptionOnInvalidReferenceBehaviorPass.php (line 35)
at CheckExceptionOnInvalidReferenceBehaviorPass->processValue(array(object(Reference), object(Reference), object(Reference), object(Reference),object(Reference)))in AbstractRecursivePass.php (line 64)
at AbstractRecursivePass->processValue(object(Definition), true)in CheckExceptionOnInvalidReferenceBehaviorPass.php (line 35)
at CheckExceptionOnInvalidReferenceBehaviorPass->processValue(object(Definition), true)in AbstractRecursivePass.php (line 57)

**Comment by XWB** [comment]
Duplicate issue https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2667
