### ISSUE TITLE
fos_user.email_update_confirmation

### ISSUE THREAD

**Issue by samoussa** [FriendsOfSymfony/FOSUserBundle#2672]
Hi,

After composer update : commit 85bf9f1 

[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
 The service "fos_user.profiler.controller" has a dependency on a non-existent service "fos_user.email_update_confirmation".

Could you help me to resolve ?

**Comment by emudojo** [comment]
I'm also seeing this, quite annoying as my builds are not passing, why introducing a breaking change all the sudden?

to fix it add

fos_user:
    registration:
        confirmation:
              enabled: false #or true of you want to use the feature

**Comment by samoussa** [comment]
Thank you for your help.

I don't know if it's a bug.
For me no problem with changes when it's in documentation !

`fos_user:
    registration:
        confirmation:
              enabled : false   #still return The service "fos_user.profiler.controller" has a dependency on a non-existent service "fos_user.email_update_confirmation".`

**Comment by samoussa** [comment]
New problem : All login forms return "Invalid CSRF token"

**Comment by bnbc** [comment]
I went back to version 2.0.2 to fix this problems, my project dont work with last new version... and this fix dont solve the problem : 
fos_user:
    registration:
        confirmation:
              enabled: false #or true of you want to use the feature

**Comment by runawaycoin** [comment]
see my pull request: https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2681

**Comment by anisAllan** [comment]
How you went back to version 2.0.2 ?

**Comment by bnbc** [comment]
I change version in my composer.json file
`        "friendsofsymfony/user-bundle": "2.0.2",`
And i do a 
`composer update`

**Comment by XWB** [comment]
Should be fixed in master.

**Comment by anisAllan** [comment]
Thank you for your help.
