### ISSUE TITLE
non-existent service "fos_user.email_update_confirmation"

### ISSUE THREAD

**Issue by adequat-bi** [FriendsOfSymfony/FOSUserBundle#2678]
**Symfony FOSUserBundle versions**:
"friendsofsymfony/user-bundle": "~2.0@dev",

friendsofsymfony/user-bundle         dev-master 5d1c3ff Symfony FOSUserBundle

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.composer update
 2.centeev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

                                                                                                                               
  [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                                                   
  The service "fos_user.profiler.controller" has a dependency on a non-existent service "fos_user.email_update_confirmation". 
 3.

**Provide logs (if relevant)**:

**Comment by adequat-bi** [comment]
registration:
            confirmation:
                enabled: true
helps to go through composer update. Then : 

Attempted to load class "AbstractController" from namespace "Symfony\Bundle\FrameworkBundle\Controller".
Did you forget a "use" statement for another namespace?
500 Internal Server Error - ClassNotFoundException 

Stack Trace
    in vendor/friendsofsymfony/user-bundle/Controller/SecurityController.php at line 28 

28 : class SecurityController extends AbstractController

**Comment by adequat-bi** [comment]
Thanks for your commit ... I dit copy / paste to the file, to have : 

```
<service id="fos_user.profiler.controller" class="FOS\UserBundle\Controller\ProfileController" public="true">
            <argument type="service" id="event_dispatcher" />
            <argument type="service" id="fos_user.profile.form.factory" />
            <argument type="service" id="fos_user.user_manager" />
            <argument type="service" id="fos_user.email_update_confirmation" on-invalid="null" />
            <argument type="service" id="translator" />
        </service>
```

Apache log says : 

> PHP Fatal error:  Class 'Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController' not found in /var/www/mdm/vendor/friendsofsymfony/user-bundle/Controller/SecurityController.php on line 28

Still hoping to get a running app before Xmas .... 
Merry Christmas to all readers.

**Comment by adequat-bi** [comment]
http://127.0.0.1/mdm/web/app_dev.php/console/_console  works, I can get the list of command.
Then a cache:clear gives :

`PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /var/www/mdm/vendor/symfony/symfony/src/Symfony/Component/Debug/Exception/OutOfMemoryException.php on line 1, referer: http://127.0.0.1/mdm/web/app_dev.php/console/_console
`

**Comment by XWB** [comment]
Should be fixed in master.
