### ISSUE TITLE
fosuser bundle not overriding in versions > 2.0@dev for symfony 3.3.14

### ISSUE THREAD

**Issue by inforob** [FriendsOfSymfony/FOSUserBundle#2683]
We have a problem updating composer.json with the following dependency from fos:

 "friendsofsymfony/user-bundle": "**~2.0@de**v",

On update, we can not override the default controllers from the bundle.

For now and for security purposes, we'll stay in 2.0 update with : 
"friendsofsymfony/user-bundle": "2.0@dev",

**Comment by Chev12** [comment]
Nos sure if related but since I updated the bundle my app is really messed up, and I am not getting error messages so I can't be sure.

**Comment by xub** [comment]
change this 

"friendsofsymfony/user-bundle": "2.0@dev",

for

"friendsofsymfony/user-bundle": "2.0",

**Comment by XWB** [comment]
Master branch is not stable yet, please do not use it as long as you are on Symfony < 3.4.
