### ISSUE TITLE
Proposal: split the fat user interface into several small interfaces

### ISSUE THREAD

**Issue by ossinkine** [FriendsOfSymfony/FOSUserBundle#2686]
Right now user interface (as well as user model) contains a lot of fields for all occasions.
It's convenient if you use all these fields. But if you extend the model and use only the part of these fields you still should implement setters and getters for this fields (of course, if you want to use controllers from this bundle).
For example, I use all bundle functionality except enabled users (my users are always enabled). I still should create dummy methods `setEnabled` and `getEnabled` instead of don't implement `EnabledAwareUserInterface`.
Or if I use password encryption that does not require separate field for salt, I should not implement `PasswordSaltAwareUserInterface`.
Of course, the service should check the interface before using the corresponding functionality.

**Comment by XWB** [comment]
Actually we should get rid of the `AdvancedUserInterface`.

**Comment by Tomsgu** [comment]
I think getting rid of the `AdvancedUserInterface` is a good idea. At least we fix the first issue with enabled field. Users should implement the interface if they need. But do you think we should still keep some functionality connected with user activation/deactivation? In the symfony documentation is already a good documentation on how to do it. And should this be done before releasing a new major version?

**Comment by Hanmac** [comment]
Symfony did deprecate AdvancedUserInterface
FOSUser might see what it need to change for that

**Comment by stof** [comment]
Well, we would have to handle our `enabled` flag directly in the bundle rather than relying on the core UserChecker.

regarding `getSalt`, it is part of the Symfony interface, so we cannot remove the getter.

And optional fields would make things harder to use, as we would have to remove them from the base model class (otherwise Doctrine would still create and expect the fields) and then it would be a BC break for all people using them today.

**Comment by Hanmac** [comment]
@stof i think for now FOS should move the things it did for AdvancedUserInterface in the BaseUser class
with that it would still make the samage fields in doctrine and it wouldn't change much for the User

if fields can be removed later

**Comment by stof** [comment]
Closing this. As FOSUserBundle is in maintenance-only mode, there won't be a split of the UserInterface.
