### ISSUE TITLE
deprecation of service in symfony 3.4

### ISSUE THREAD

**Issue by zskiredj** [FriendsOfSymfony/FOSUserBundle#2690]
hello,

when openning the route "fos_user_profile_edit", i got this message: 
`User Deprecated: The "fos_user.profile.form.factory" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.`
How can I solve this problem ? Either by making service public, or by calling it by injection...

**Comment by runawaycoin** [comment]
see: https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2691

**Comment by XWB** [comment]
Fixed; thanks @runawaycoin
