### ISSUE TITLE
/admin/login_check is redirecting to /login instead of /admin/login

### ISSUE THREAD

**Issue by sanchobouillant** [FriendsOfSymfony/FOSUserBundle#2701]
I want to use FosUserBundle only for my admin interface (/admin) with SF4.

I can access to /admin/login but when I submit the form, /admin/login_check say:

>  "Access denied, the user is not fully authenticated; redirecting to authentication entry point."

Then, login_check redirect to /login instead of /admin/login.

My security config:

```
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
```

routes.yaml:

```
fos_user_security:
    prefix: /admin
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
```

How can I prefix fosuser routes with /admin ?

**Comment by Tomsgu** [comment]
The problem is that you're accessing route /admin/login_check as anonymous user [Here](https://symfony.com/doc/current/security/form_login_setup.html#be-sure-check-path-is-behind-a-firewall) you can find more information. In your access_control only admin can access route /admin/... with exception to route /admin/login.
So your access_control should look something like this:

```yaml
access_control:
    - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin/, role: ROLE_ADMIN }
```

**Comment by sanchobouillant** [comment]
Perfect ! Thank you
