### ISSUE TITLE
[SF4] Configuration path "fos_user.db_driver" cannot be overwritten

### ISSUE THREAD

**Issue by 0xMatt** [FriendsOfSymfony/FOSUserBundle#2712]
**Full Errror Message**

```
Configuration path "fos_user.db_driver" cannot be overwritten. You have to define all options for this path, and any of its sub-paths in one configuration section.
```

**Symfony FOSUserBundle versions**:

```
friendsofsymfony/user-bundle         dev-master 6731b46 Symfony FOSUserBundle
```

**Issue**

When I set `db_driver: orm` I get this error, when I leave out the config key, I get:
```
The child node "db_driver" at path "fos_user" must be configured.
```

**fos_user.yaml**

```
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: test@test.com
        sender_name: test
    registration:
        confirmation:
            enabled: true
    resetting:
        email:
            from_email:
                address:        resetting@example.com
                sender_name:    Demo Resetting
```

So I obviously need to configure this key, but the values I used are throwing the above error. Any tips?

**Comment by covex-nn** [comment]
@0xMatt may be your fos_user.yaml is included twice?

**Comment by 0xMatt** [comment]
It was, thanks @covex-nn!

**Comment by mauriau** [comment]
I got the same error. 
It was for a similar mistake.
I migrate my application form sf3 to sf4, but I keep my configuration as services.yaml import packages/fos_user.yaml.
But fos_user.yaml is automatically loaded if we put the files in folder package.
So the file fos_user.yaml was called twice. Once by my import services.yaml and second automatically by FosUser.
