### ISSUE TITLE
Notice: Undefined index: template "resetting" / from email => Mailer.php

### ISSUE THREAD

**Issue by fayange** [FriendsOfSymfony/FOSUserBundle#2720]
Hi :)
I wanted to update  to symfony 4 but  there was a error in FOS\UserBundle\Mailer\Mailer::sendResettingEmailMessage

Notice: Undefined index: resetting

 $template = $this->parameters['resetting.template']
$email = $this->parameters['from_email']['resetting']

**Comment by stof** [comment]
This file has been removed in 3.0.0
