### ISSUE TITLE
Please make clear which symfony versions are supported

### ISSUE THREAD

**Issue by Sozialarchiv** [FriendsOfSymfony/FOSUserBundle#2721]
The gibhub description seems to be outdated:

https://github.com/FriendsOfSymfony/FOSUserBundle:
> Provides user management for your Symfony2 project. Compatible with Doctrine ORM & ODM, and Propel.

> The FOSUserBundle adds support for a database-backed user system in Symfony2.

2 and 3 in stable? 4 in dev-master?

**Comment by vchebotarev** [comment]
yeap
so, there is no commits updatind docs for symfony support even in master ... 
everything we can do is wait or Contribute !

**Comment by jedi58** [comment]
Support is detailed on: https://symfony.com/doc/current/bundles/FOSUserBundle/index.html

**Comment by stayeronglass** [comment]
Step 2: Enable the bundle¶

Enable the bundle in the kernel:

**Comment by someniatko** [comment]
By the way, is any official release supporting Symfony 4 coming soon?

**Comment by stof** [comment]
@someniatko 2.1.0 is out.

@Sozialarchiv the bets way to get info about support version is to check the requirement in the composer.json (and this works for any package)

**Comment by Sozialarchiv** [comment]
@stof: Thank you very much.

I know that I can see it in composer. 

But imho it is very confusing, that on the main page of the git repository it's written it is for Symfony 2:
https://github.com/FriendsOfSymfony

Imho I would remove the version number or correct it.

**Comment by stof** [comment]
I remove the version number in the repo description (this was written at the time of Symfony 2 vs symfony 1)

**Comment by Sozialarchiv** [comment]
Thank you very much.
