### ISSUE TITLE
Update from ~2.0@dev to~2.0 not working

### ISSUE THREAD

**Issue by picks44** [FriendsOfSymfony/FOSUserBundle#2722]
Hello,

I've successfully updated an old project to ~2.0 on my local machine, but on the prod server I get this Composer message when doing php composer.phar update

```
Problem 1
    - The requested package friendsofsymfony/user-bundle ~2.0 is satisfiable by friendsofsymfony/user-bundle[2.0.0-beta2, 2.0.x-dev, v2.0.0-alpha1, v2.0.0-alpha2, v2.0.0-alpha3, v2.0.0-beta1] but these conflict with your requirements or minimum-stability.
```

I've deleted the package just in case but I get the same message afterwards.

Please help!

**Comment by xabbuh** [comment]
You should rather commit your `composer.lock` file and then run `composer install` during deployment.

**Comment by picks44** [comment]
Worked nicely, thanks!
