### ISSUE TITLE
NEW FEATURE: Encode option for personal information such as Email and Names for GDPR

### ISSUE THREAD

**Issue by mogilvie** [FriendsOfSymfony/FOSUserBundle#2726]
# NEW FEATURE: Provide an option to encode Personal Information for GDPR
Designing for privacy would be improved if we could configure the users names and email addresses to be encrypted in the bundle.

**Comment by Hanmac** [comment]
@mogilvie : i don't know if that would be enough for GDPR but for some other project where i needed to insert a password that would be used for a third party service, and encrypt it into the database with openssl

for that i did a Listener that check on postLoad and prePersist/preUpdate
as secret for the ssl i used the parameters.secret

i can show you the Listener/Subscriber if you want to, it might be done in a more generic way for your cases too

**Comment by mogilvie** [comment]
Thanks @Hanmac ,
I've using the same type of doctrine events subscriber for the rest of my Personal data.
[https://github.com/mogilvie/GdprBundle](https://github.com/mogilvie/GdprBundle).
I'll apply it to this data and see how it goes.

**Comment by stof** [comment]
Encrypting the username and email fields of the bundle would break the database uniqueness constraints we have (as you would require the encrypted blob to be unique, which can be achieved even by reusing the same username), and would make it very hard to implement loading of the user by username (mandatory for login purposes).
How would you implement the security UserProvider in case these fields are encrypted in the database ?

and besides these fields used as login identifiers, we don't have personal data in FOSUserBundle directly (you can have some in your child classes).

**Comment by Hanmac** [comment]
@mogilvie there is what i do for just the Secret attribute
https://gist.github.com/Hanmac/aeac16b491d7665c15bc2f46d7b98763

@stof yeah username and/or email doesn't seems to be able to work because of the uniqueness :(

**Comment by mogilvie** [comment]
The email address is enough to identify someone. Possibly the username too if they select a name that is identifiable.
Unique constraints shouldn't break. The encryption process should generate the same encrypted result consistently so long as the same keys were used.

**Comment by Hanmac** [comment]
@mogilvie depending on the algorym, i use openssl_random_pseudo_bytes, which would make each data different even if the content is the same

**Comment by stof** [comment]
@mogilvie a robust encryption process does *not* produce the same output for the same input, because all algos have a initialization vector which is generated randomly (the goal being to forbid creating tables of mapping between encrypted and raw data). This is the exact same reason why password hashes are using a salt and not just the raw password.

Building a system which works only when using weak encryption is worse than not encrypting in the bundle IMO, because it makes people expect the safety related to encryption.

**Comment by mogilvie** [comment]
Cheers @stof 
I might have to go down the route of generating an anonymous username (similar to how many banks provide you with your client id).
Or instead separating the fos user entity from my application user and pseudoanonymise the relationship.
Thanks for your time.

**Comment by mogilvie** [comment]
@encreinformatique 
I'm still considering how to deal with this. I'm leaning towards generating an anonymous username programatically and using the email addresses for authentication.
I'll then separate the fos_user entity from my application and its data, and create my own user provider to get my application_user. The link between fos_user entity and application_user entity will be pseudonymized.
Unfortunately I have no time to work on it at this point, thats just the outline.

**Comment by stof** [comment]
Closing this as it won't be implemented given the maintenance status of the bundle.
