### ISSUE TITLE
is_granted() not working

### ISSUE THREAD

**Issue by polnetwork** [FriendsOfSymfony/FOSUserBundle#2729]
**Symfony FOSUserBundle versions**:
symfony/symfony                      v3.4.3  
friendsofsymfony/user-bundle         v2.0.2  

**Description of the problem including expected versus actual behavior**:
Everything is working (register, login, role assignment...) but is_granted() does not work. 
With app.user.roles I can confirm the roles are there. 

**Steps to reproduce**:
On Twig if I do
```twig
{% if 'SUPER ADMIN' in app.user.roles %}
    SUPER ADMIN
{% endif %}
```
it works.

But If I do 
```twig
{% if is_granted("ROLE_SUPER_ADMIN") %}
SUPER ADMIN
{% endif %}
```
it does not work.

**Comment by stof** [comment]
if you have `SUPER ADMIN` in `app.user.roles`, this is actually totally expected. you need to have `ROLE_SUPER_ADMIN` in it.

**Comment by polnetwork** [comment]
You are right but I tryed all the combinations.
It's solved now, I found the roles MUST start with ROLE_.
Thank's for all!
