### ISSUE TITLE
Too few arguments to function FOS\UserBundle\Controller\RegistrationController::__construct()

### ISSUE THREAD

**Issue by axzx** [FriendsOfSymfony/FOSUserBundle#2733]
**Symfony FOSUserBundle versions**:
v2.1.0

Symfony v3.4.4

**Description of the problem including expected versus actual behavior**:
`
Type error: Too few arguments to function FOS\UserBundle\Controller\RegistrationController::__construct(), 0 passed in /home/adam/www/lug-main/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ControllerResolver.php on line 195 and exactly 4 expected
`
**Steps to reproduce**:
 1. composer update
`- Updating friendsofsymfony/user-bundle (v2.0.2 => v2.1.0): Downloading (100%)`
 2.
```
/**
 * @Route("/registration")
 */
class RegistrationController extends \FOS\UserBundle\Controller\RegistrationController
{
}
```
 3. app.localhost/registration

**Comment by axzx** [comment]
ok, my fault

**Comment by imen-developer** [comment]
Have you resolve this issue please, I've got the same problem? can you help me 👍

**Comment by imen-developer** [comment]
Type error: Too few arguments to function FOS\UserBundle\Controller\RegistrationController::__construct(), 0 passed in /Applications/MAMP/htdocs/startup/nekrinet/var/cache/dev/Container9m07ghj/getPugxMultiUser_RegistrationManagerService.php on line 14 and exactly 4 expected

**Comment by axzx** [comment]
RegistrationController:

```
/**
 * @Route("/registration")
 */
class RegistrationController extends \Symfony\Bundle\FrameworkBundle\Controller\Controller
{
```

**Comment by scott-r-lindsey** [comment]
For anyone wandering in here from Google, I worked around this error with Symfony 4.2 and FOSUserBundle 2.1.2 by changing my template rendering from:

```
        {{ render(controller('FOSUserBundle:Registration:register')) }}
```

To this:

```
        {{ render(url('fos_user_registration_register')) }}
```

Cheers.
