### ISSUE TITLE
csrf error

### ISSUE THREAD

**Issue by magdoss** [FriendsOfSymfony/FOSUserBundle#2741]
im using symfony 3.4.4 i tried to install fosuserbundle following the FOSUser docs

When I execute the command:
bin/console doctrine:schema:update --force
 
i got this error 
The service "security.authentication.listener.form.main" has a dependency on a non-existent service "security.csrf.token_manager"

how can i resolve it ?

**Comment by pmdevelopment** [comment]
Tried `composer require "symfony/security-csrf"`? I cannot reproduce your bug but noticed, that the CSRF token integration won't work anymore:

    {% if csrf_token %}
        <input type="hidden" name="_csrf_token" value="{{ csrf_token }}" />
    {% endif %}

I had to use this integration to get my login working:

    <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}"/>

**Comment by magdoss** [comment]
problem solved with adding enabled: true 

csrf_protection: { enabled: true }

**Comment by stof** [comment]
The doc indeed shows a config example enforcing CSRF protection on the login form, and this won't work if the CSRF protection layer is not enabled in your project.

**Comment by pmdevelopment** [comment]
I tought it could be related to #2736 but this issue was just missing one part of the setup instructions.
