### ISSUE TITLE
How to get current logged user list?

### ISSUE THREAD

**Issue by jatinhs** [FriendsOfSymfony/FOSUserBundle#2743]
Hello,

I am using FOS User Bundle for User management. 
Now i want all users list who is currently logged in. So how to get logged in user list?

Thank You

**Comment by Tomsgu** [comment]
You can see an answer to your question on [stackoverflow symfony-how-to-return-all-logged-in-active-users](https://stackoverflow.com/questions/21096689/symfony-how-to-return-all-logged-in-active-users?answertab=votes#tab-top).

But it has nothing to do with fos user bundle. Please read a first paragraph [here](https://symfony.com/doc/master/bundles/FOSUserBundle/index.html).

**Comment by XWB** [comment]
Closing as it is not related to this bundle.
