### ISSUE TITLE
Type error: Too few arguments to function FOS\UserBundle\Controller\RegistrationController::__construct(), 0 passed in /Applications/MAMP/htdocs/startup/nekrinet/var/cache/dev/Container9m07ghj/getPugxMultiUser_RegistrationManagerService.php on line 14 and exactly 4 expected

### ISSUE THREAD

**Issue by imen-developer** [FriendsOfSymfony/FOSUserBundle#2745]
I've got this issue, when I'm trying to use pugmuliuser bundle and fosuserbundle

**Comment by phpeek** [comment]
@imen-developer See https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2744

**Comment by imen-developer** [comment]
@phpeek , This link can't resolve my issue :/

**Comment by imen-developer** [comment]
https://github.com/PUGX/PUGXMultiUserBundle/issues/156

**Comment by XWB** [comment]
Have a look at https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2744#issuecomment-369042634

**Comment by fcpauldiaz** [comment]
I'm having the same issue
