### ISSUE TITLE
confirmationUrl with http://localhost/... in prod

### ISSUE THREAD

**Issue by picks44** [FriendsOfSymfony/FOSUserBundle#2755]
I've written a Symfony command with sends confirmation emails to my users, but in the mail they receive, the confirmationUrl is set with the "dev" URL `http://localhost/register/confirm/UNIQUE_KEY` instead of the real domain.

I launch my command in a CRON like this `php app/console reset:users --env=prod`

How can I force the confirmationUrl to use the domain instead of localhost ?

**Comment by lambertbeekhuis** [comment]
Take a look at How to Generate URLs from the Console:

https://symfony.com/doc/current/console/request_context.html

**Comment by picks44** [comment]
@lambertbeekhuis The **confirmationUrl**  is generated by FOSUB, not by my command. My command only triggers the process through the s`endConfirmationEmailMessage($user)` method of FOSUB, which send the confirmation email to the user.

```
 /**
     * @param User $user
     * @return User
     */
    public function sendConfirmationEmail(User $user)
    {
        if (null === $user->getConfirmationToken()) {
            $user->setConfirmationToken($this->generator->generateToken());
        }
        $this->mailer->sendConfirmationEmailMessage($user);
        return $user;
    }
```

**Comment by noccy80** [comment]
Similar issue here; the link in the confirmation e-mail is using http, and furthermore *points to the name of the docker container* running the nginx instance... Modifying the parameters as @lambertbeekhuis suggested does nothing, as there is a valid request context for the docker host and thus my defaults are ignored. 

There really should be a way to override this information for the e-mails sent. In my case the front server handles all the certificates with the docker sites defined as upstreams, meaning requests are internally http but externally forced as https. I could change the internal docker hostname to match the public domain but this would still give me a http:// url... Something like this, that would customize the request context before generating the URLs would be really useful. 

    fos_user
      url_generator:
        override:
          host: myhostname.com
          https: true
