### ISSUE TITLE
How to add a field that references another table

### ISSUE THREAD

**Issue by Vallery347** [FriendsOfSymfony/FOSUserBundle#2761]
Please, tell me how to add a custom column to the Users table, which will refer to another table.

**Comment by Roman-1812** [comment]
Add in entity: 
/**
     * @ORM\OneToMany(targetEntity="SiteBundle\Entity\Basket", mappedBy="user", fetch="EAGER", cascade={"ALL"})
     */
    protected $basket;

**Comment by stof** [comment]
@Roman-1812 I even suggest you to avoid using a bidirectional relation if you don't strictly need it (in 90% of cases, you don't actually need it)

**Comment by OsvalGuiany** [comment]
Please I 'm using FOSUserBundle, when my  user entity don't  bas relations with others entity, thé users  can  login well but when I use relations. Users are redirected to the  login page and  Symfony tells me that account is disable. Please I want to know how can't I do to rectify it.
