### ISSUE TITLE
FOSUser authentication failed.

### ISSUE THREAD

**Issue by OsvalGuiany** [FriendsOfSymfony/FOSUserBundle#2762]
Please I'm using FOSUserBundle. when I use User entity without associations with others entities, the  users can  be authenticated succesfully after registration and  login. But when I use relations/associations, the  user is authenticated anonymous and  Symfony tells me that the account disable after login. Please I need  your help.

**Comment by janmyszkier** [comment]
@OsvalGuiany which FOSUserBundle and Symfony/symfony versions you're using?

**Comment by OsvalGuiany** [comment]
Symfony 3.4.2 and FOSUser 2.1.2.

**Comment by janmyszkier** [comment]
Seems like you're having the same issue as the guy here, feel free to check the solution posted there.
https://stackoverflow.com/questions/47675301/token-was-deauthenticated-after-trying-to-refresh-it

**Comment by OsvalGuiany** [comment]
@janmyszkier, it really seems to be  the same problem but when I don't  use associations the  login and  registration work well but whe I use them the registration and login stop work well and  users are diasbled  everytime but by debugging annotation, I don't have a problem.

**Comment by OsvalGuiany** [comment]
I want to know something, the user entity allows particular  annotation ?

**Comment by OsvalGuiany** [comment]
I want to know something, the user entity allows particular  annotation  when FOSUser is used ?

**Comment by janmyszkier** [comment]
@OsvalGuiany I finally reproduced the issue you mentioned, but I'll check on this tomorrow at earliest, but WILL post back with a solution later, once I find out what they did there.

**Comment by OsvalGuiany** [comment]
Thank  !!!

**Comment by janmyszkier** [comment]
@OsvalGuiany Sorry but turns out my demo Symfony logged me out because two of my routes have been parts of each other in `routing.yml` which may not be the same problem as yours:
```
projects_list:
    path:     /projects
    defaults: { _controller: AppBundle:Project:list }

projects_css:
    path:     /projects/projects.css
    defaults: { _controller: AppBundle:Project:css }
```
(see how `/projects` is part of ` /projects/projects.css` ?)
If your issue is not the same, feel free to ping me on skype (same ID as on github) and let's have a look at your source to resolve your issue.

**Comment by OsvalGuiany** [comment]
After login the  user is not authenticated even anonymous until he  is redirected to the  login page but he is on the main firewall. But I have seen  irregular  thing. The crurent controller is n/a.

**Comment by OsvalGuiany** [comment]
I don't  have skype seession. I can  commit my  configuration files on github and  you will sée thème if you want.

**Comment by OsvalGuiany** [comment]
I have resolved My. I had override the isEnabled method  in my  user entity for orther goal. it wrigth now. Thank  you for your help.

**Comment by OsvalGuiany** [comment]
But I have a new issue, I'm authenticated but the  container don't  have security.token_storage.

**Comment by janmyszkier** [comment]
I think this issue should be closed, it is not longer the issue you reported and the bug you're trying to get support on is not properly described.

**Comment by OsvalGuiany** [comment]
Thank you for your help.

**Comment by janmyszkier** [comment]
Notes to other having this issues that usually helps resolving those:
- turn on development mode and see into profiler Entity warnings (Symfony Profiler -> Entities Mapping section) 
- make sure you're not using BOTH YML and annotation for entity definition (or just make sure they match each other everywhere) 
- make sure google chrome (or whatever browser you are using) is not playing tricks on you with it's "cached redirects" either append the unique (never used before) parameter to the url you are having problems with (like `?test=123`) or remove browser redirect caches.

All other issues - report your exact doctrine entity configs, classes content and errors. Bug reports are welcome. Thank you in advance :)
