### ISSUE TITLE
Registration : confirmAction should not throw 404 if link clicked more than one time

### ISSUE THREAD

**Issue by benjaminb-** [FriendsOfSymfony/FOSUserBundle#2763]
Hello,

I had this case mutiples times : 

Users click a second time on the email registration confirm link, and it throws a NotFoundHttpException.

It could be better to handle that case ? The users could be redirect to the login page or something else..

What do you think ? I can work on a pull request.

**Comment by COil** [comment]
Can this ticket be closed?

**Comment by benjaminb-** [comment]
Yes thanks
