### ISSUE TITLE
Feature request, login using "only" email

### ISSUE THREAD

**Issue by yurtesen** [FriendsOfSymfony/FOSUserBundle#2768]
It seems like it is possible to login using `username` by using provider `fos_user.user_provider.username` and it is possible to login using `username` or `email` using provider `fos_user.user_provider.username_email`

What seems to be missing is what to use if one wants to allow login with "only" email. Perhaps there should be an `fos_user.user_provider.email` provider? I could not find out anywhere if it is possible to force use of "only" email for logins.

Would this feature be simple to implement?

**Comment by Devtronic** [comment]
EmailProvider added in #2781, waiting for PR approval

**Comment by XWB** [comment]
Added in https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2781
