### ISSUE TITLE
Documentation for 1.3.x is not available

### ISSUE THREAD

**Issue by pmpr** [FriendsOfSymfony/FOSUserBundle#2771]
**Symfony FOSUserBundle versions**: 1.3.x

**Description of the problem including expected versus actual behavior**:
Documentation for 1.3.x is not available. It is being forwarded to 2.x

**Steps to reproduce**:
 1. try to visit [https://symfony.com/doc/1.3.x/bundles/FOSUserBundle/index.html](https://symfony.com/doc/1.3.x/bundles/FOSUserBundle/index.html)

**Comment by MarvinCourcier** [comment]
Maybe it's because the documentation is the same so they merged both pages ?

**Comment by peyman-mohamadpour** [comment]
I think, one should be able to use documentation dropdown and choose different versions. Visit the provided url and you will see the dropdown is on 2.x, but there you see:

```
$ composer require friendsofsymfony/user-bundle "~1.3"
```
