### ISSUE TITLE
Caching user once authenticated

### ISSUE THREAD

**Issue by etshy** [FriendsOfSymfony/FOSUserBundle#2774]
Hi
I wanted to know if ther eis a way to prevent the query to search the authenticated user on every page ?

I develop with the DebugBar, and I always see 1 DB query, even if my action is empty, so I guess it's the query to get the user and would like to know if I can cache that ?

**Comment by Tomsgu** [comment]
Duplicate of #499. You can see some suggestions in this comment: https://github.com/FriendsOfSymfony/FOSUserBundle/issues/499#issuecomment-36684406

**Comment by etshy** [comment]
Thanks, didn't see it since it's old.

will take a look.
