### ISSUE TITLE
The service "fos_user.resetting.controller" has a dependency on a non-existent service "templating".

### ISSUE THREAD

**Issue by shm-vadim** [FriendsOfSymfony/FOSUserBundle#2776]
symfony/framework-bundle            v4.0.8/v4.0.5
friendsofsymfony/user-bundle        v2.1.2

Hello!

I cannot start to use FOSUserBundle with smf4 project, which has been created by runing "composer create-project symfony/website-skeleton" command. Always after bundle's configuring i have next error in my console:

In CheckExceptionOnInvalidReferenceBehaviorPass.php line 32:
The service "fos_user.resetting.controller" has a dependency on a non-existent service "templating".

I have the same error , when i attempt to open the homepage of my project in browser.

The project stage: https://github.com/shm-vadim/examples/commit/4ae2f64bf892b0f15200f4358a403601d82f5b98
framework.yaml: https://github.com/shm-vadim/examples/blob/4ae2f64bf892b0f15200f4358a403601d82f5b98/config/packages/framework.yaml
security.yaml: https://github.com/shm-vadim/examples/blob/4ae2f64bf892b0f15200f4358a403601d82f5b98/config/packages/security.yaml
routes.yaml: https://github.com/shm-vadim/examples/blob/4ae2f64bf892b0f15200f4358a403601d82f5b98/config/routes.yaml
composer.json: https://github.com/shm-vadim/examples/blob/4ae2f64bf892b0f15200f4358a403601d82f5b98/composer.json

Is it a bug? What should i do?

Thanks for help and attention!

**Comment by AgusQuiroga** [comment]
This one solved the issue for me:
- https://stackoverflow.com/questions/33404302/symfony2-error-the-service-templating-has-a-dependency-on-a-non-existent-serv

Extra info: 
- https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2679

**Comment by shm-vadim** [comment]
Thank you, it was helpful!
