### ISSUE TITLE
Ovveride login form in symfony 4

### ISSUE THREAD

**Issue by modogo2000** [FriendsOfSymfony/FOSUserBundle#2779]
Hello,

How can I ovveride the login view with symfony. The document is not up to date . Symfony 4 is totally different.

Best regards

**Comment by Devtronic** [comment]
Take a look on this guide: https://symfony.com/doc/current/templating/overriding.html

You can override the login form with this file: `templates/bundles/FOSUserBundle/Security/login_content.html.twig`

**Comment by kcaporaso** [comment]
@stof, Good day.  I just migrated a 3.x sf project to 4.4 and moved to the new flex directory structure.  I moved my ./app/Resources/FOSUserBundle/* to the new location ./templates/bundles/FOSUserBundle/* and none of my template overrides are getting picked up.  I'm only seeing the FOSUserBundle default templates.  Would love any suggestions as to what I missed in the migration.  I'm on "friendsofsymfony/user-bundle": "^2.1" Thank you.

**Comment by stof** [comment]
In Symfony 3.x, the location for overrides was `app/Resources/FOSUserBundle/views/*`, not `app/Resources/FOSUserBundle/*`.

So if you did the move you described, you have an extra level of a `views` folder inside `templates/bundles/FOSUserBundle`

**Comment by kcaporaso** [comment]
@stof , wow, that did it, thanks for the super fast response.
