### ISSUE TITLE
Override default templates in Symfony 4

### ISSUE THREAD

**Issue by kironet** [FriendsOfSymfony/FOSUserBundle#2783]
Hi,

how to override default templates in symfony 4?
Documentation has not changed:

https://symfony.com/doc/current/bundles/FOSUserBundle/overriding_templates.html
> a) Define New Template In app/Resources
> 
> The easiest way to override a bundle's template is to simply place a new one in your app/Resources folder. To override the layout template located at Resources/views/layout.html.twig in the FOSUserBundle directory, you would place your new layout template at app/Resources/FOSUserBundle/views/layout.html.twig.

**Comment by covex-nn** [comment]
@kironet place your templates into `src/Resources/FOSUserBundle/views` directory

**Comment by Devtronic** [comment]
@covex-nn: In SF4 the template must be placed in templates/bundles/{BundleName}.

@kironet: see: https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2779

**Comment by yceruto** [comment]
> Documentation has not changed

However still `app/Resources/FOSUserBundle/views` should work fine.

**Comment by XWB** [comment]
Closing as the answer has been given by @Devtronic
