### ISSUE TITLE
"Cannot create SSL client. SSL is not enabled in this build" when login

### ISSUE THREAD

**Issue by etshy** [FriendsOfSymfony/FOSUserBundle#2786]
Hi.
I just set up a server to develop on it.
I installed the mongo extension for php7.2 vie PECL command (and add the `extension=mongodb.so` line in php.ini)

Open ssl is installed and enabled but I have no ca file : https://puu.sh/A8qjo/e023fa4184.png

mongo is installed and enabled but the `libmongoc SSL` is markes as disabled, and I don't find how to enable it : https://puu.sh/A8qlX/e1f6bd3eea.png

And when I try to login (the user exists) I have an exception with the message  : "Cannot create SSL client. SSL is not enabled in this build"  and the login_check action redirect to login with the message "La requête d'authentification n'a pas pu être executée à cause d'un problème système." (sorry for the french language : "The request for authentication could not be executed because of a system problem." or something like that in english).

I guess I have this error because of the  `libmongoc SSL` line is disabled in php_info but as I said, I don't know how to enable it.

**Comment by etshy** [comment]
The problem came with the configuration during the build with `pecl install mongodb` command.

with `apt-get install php7.2-mongodb` it install it correctly with SSL and other options enabled.

**Comment by maniflames** [comment]
Since this issue is ranking high in google: 

I had to run PHP 7.3 and there is no php7.3-mongodb.
What helped me out is installing `libssl-dev` and `pkg-config` before installing the mongodb driver through pecl. So long story short: 

```
sudo apt-get install libssl-dev pkg-config
sudo pecl install mongodb
```
