### ISSUE TITLE
Symfoyn 3.4 : FOS User Bundle : Override Controller

### ISSUE THREAD

**Issue by garalimedkarim** [FriendsOfSymfony/FOSUserBundle#2791]
**Symfony version**:
```
            "name": "symfony/symfony",
            "version": "v3.4.8",
```

**Symfony FOSUserBundle versions**:
```
            "name": "friendsofsymfony/user-bundle",
            "version": "v2.1.2",
```

**Description of the problem including expected versus actual behavior**:
I'm trying to override loginAction, but it doesn't work, I think the documents are not very detailed So it must provide at least one exemple for override Controller, Template,etc ...

**Steps to reproduce**:
 1. I know that the inheritance was deprecated but I have created a bundle in which I will override FOS User Bundle functionnalities, I called this Bundle src/MyVendor/MyVendorFOSUserBundle.
test autoload => OK.

 2.I copied **SecurityController.php** from the **vendor/**  in my bundle **MyVendorFOSUserBundle/Controller**/ And I add the **@Route** Decorator above the **loginAction** but I get an issue when submiting login form => Invalid CSRF token: by debuggin I fount that the **$tokenManager** doesn't be injected in the Controller so it's take null value: In this code I just added the @Route decorator and extends **BaseController** to the Contoller copied.

The result Controller:
```
#src/MyVendor/MyVendorFOSUserBundle/Controller/SecurityController.php:

    class SecurityController extends BaseController
    {
    private $tokenManager;

    public function __construct(CsrfTokenManagerInterface $tokenManager = null)
    {
        $this->tokenManager = $tokenManager;
    }
     /**
      * @param Request $request
      * @return Response
      * @Route("/login")
      */
    public function loginAction(Request $request)
    { ... }

```

 3. tried to add the attribute name in @Route Decorator and I kept the same route name as it is in FOS User Bundle but in this case the Controller of FOS User bundle which is executed and my new Controller was ignored ( I test this by putting die('test') on Controller contructor)

The Question What is the solution to correctly override this action ?

**Comment by DeveloperSlope3** [comment]
I had the same problem. Take a look here: https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2778
