### ISSUE TITLE
FOSUBundle error with symfony 4

### ISSUE THREAD

**Issue by Dine90** [FriendsOfSymfony/FOSUserBundle#2793]
The service "fos_user.resetting.controller" has a dependency on a non-existent service "templating"
I got this when i try to use doctrine project
Thanks for help

**Comment by cklingsporn** [comment]
Symfony 4 does not come with twig installed.

Install through composer via:
`composer require twig`

Then add the config for twig (under config/framework.yaml):

```
framework:
    templating:
        engines: ['twig']
```

**Comment by XWB** [comment]
See above :)

**Comment by Corncakes** [comment]
Excelent!!!!!! This work for me!!! Thanks

**Comment by mehranhadidi** [comment]
Thanks. Worked for me

**Comment by jayjaycfg** [comment]
Nice, this work for me!!!
