### ISSUE TITLE
The path "fos_user.from_email.address" cannot contain an empty value, but got null.

### ISSUE THREAD

**Issue by flik** [FriendsOfSymfony/FOSUserBundle#2794]
This error is coming : 
The path "fos_user.from_email.address" cannot contain an empty value, but got null.

**Symfony FOSUserBundle versions**: ~2.0

$ composer info
doctrine/annotations                 v1.2.7  Docblock Annotations Parser
doctrine/cache                       v1.6.0  Caching library offering an o...
doctrine/collections                 v1.3.0  Collections Abstraction library
doctrine/common                      v2.6.1  Common Library for Doctrine p...
doctrine/dbal                        v2.5.4  Database Abstraction Layer
doctrine/doctrine-bundle             1.6.2   Symfony DoctrineBundle
doctrine/doctrine-cache-bundle       1.3.0   Symfony Bundle for Doctrine C...
doctrine/inflector                   v1.1.0  Common String Manipulations w...
doctrine/instantiator                1.0.5   A small, lightweight utility ...
doctrine/lexer                       v1.0.1  Base library for a lexer that...
doctrine/orm                         v2.5.4  Object-Relational-Mapper for PHP
friendsofsymfony/user-bundle         v2.1.2  Symfony FOSUserBundle
incenteev/composer-parameter-handler v2.1.2  Composer script handling your...
jdorn/sql-formatter                  v1.2.17 a PHP SQL highlighting library
monolog/monolog                      1.19.0  Sends your logs to files, soc...
paragonie/random_compat              v2.0.2  PHP 5.x polyfill for random_b...
psr/cache                            1.0.0   Common interface for caching ...
psr/log                              1.0.0   Common interface for logging ...
sensio/distribution-bundle           v5.0.6  Base bundle for Symfony Distr...
sensio/framework-extra-bundle        v3.0.16 This bundle provides a way to...
sensio/generator-bundle              v3.0.6  This bundle generates code fo...
sensiolabs/security-checker          v3.0.2  A security checker for your c...
swiftmailer/swiftmailer              v5.4.2  Swiftmailer, free feature-ric...
symfony/monolog-bundle               2.11.1  Symfony MonologBundle
symfony/phpunit-bridge               v3.1.0  Symfony PHPUnit Bridge
symfony/polyfill-apcu                v1.2.0  Symfony polyfill backporting ...
symfony/polyfill-intl-icu            v1.2.0  Symfony polyfill for intl's I...
symfony/polyfill-mbstring            v1.2.0  Symfony polyfill for the Mbst...
symfony/polyfill-php56               v1.2.0  Symfony polyfill backporting ...
symfony/polyfill-php70               v1.2.0  Symfony polyfill backporting ...
symfony/polyfill-util                v1.2.0  Symfony utilities for portabi...
symfony/swiftmailer-bundle           v2.3.11 Symfony SwiftmailerBundle
symfony/symfony                      v3.1.0  The Symfony PHP framework
twig/twig                            v1.35.3 Twig, the flexible, fast, and...

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. php bin/console doctrine:schema:update --force

[37;41m  [Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]        [39;49m
[37;41m  The path "fos_user.from_email.address" cannot contain an empty value, but got null.  [39;49m
[37;41m    

**Describe the feature**:

**Comment by Devtronic** [comment]
You need to configure the bundle: https://symfony.com/doc/master/bundles/FOSUserBundle/index.html#step-5-configure-the-fosuserbundle

**Comment by XWB** [comment]
Please following the configuration guide.

**Comment by drilla** [comment]
it is not related to Bundle.
Fill these fields in parameters.yml
```
    mailer_user: null
    mailer_password: null
```

**Comment by mohamedchibani** [comment]
Hi !
try this solution , it can help you : https://stackoverflow.com/a/47942577/8808725
it worked perfectly for me
