### ISSUE TITLE
 (1/1) Twig_Error_Loader is coming when to access url app_dev.php/login!

### ISSUE THREAD

**Issue by flik** [FriendsOfSymfony/FOSUserBundle#2797]
**Symfony FOSUserBundle versions**:2.x

**Description of the problem including expected versus actual behavior**:
I am trying to access url after config and getting errors on login url: 
http://localhost:8081/app_dev.php/login!

**Steps to reproduce**:
 1. done all instructions : https://symfony.com/doc/master/bundles/FOSUserBundle/index.html
 2. accessing url: http://localhost:8081/app_dev.php/login!
 3. getting error: 

**Provide logs (if relevant)**:

(1/1) Twig_Error_LoaderThe "/var/www/html/src/AppBundle/Resources/views" directory does not exist ("/var/www/html/src/AppBundle/Resources/views").
--
in Filesystem.php line 101
at Twig_Loader_Filesystem->addPath('/var/www/html/src/AppBundle/Resources/views', 'AppBundle')in appDevDebugProjectContainer.php line 2157
at appDevDebugProjectContainer->getTwig_LoaderService()in appDevDebugProjectContainer.php line 1122
at appDevDebugProjectContainer->getTwigService()in appDevDebugProjectContainer.php line 1052
at appDevDebugProjectContainer->getProfilerService()in appDevDebugProjectContainer.php line 1873
at appDevDebugProjectContainer->getProfilerListenerService()in appDevDebugProjectContainer.php line 1457
at appDevDebugProjectContainer->ContainerQ25oaoc\{closure}()in EventDispatcher.php line 229
at EventDispatcher->sortListeners('kernel.exception')in EventDispatcher.php line 61
at EventDispatcher->getListeners('kernel.exception')in ContainerAwareEventDispatcher.php line 128
at ContainerAwareEventDispatcher->getListeners('kernel.exception')in TraceableEventDispatcher.php line 250
at TraceableEventDispatcher->preProcess('kernel.exception')in TraceableEventDispatcher.php line 134
at TraceableEventDispatcher->dispatch('kernel.exception', object(GetResponseForExceptionEvent))in HttpKernel.php line 228
at HttpKernel->handleException(object(NotFoundHttpException), object(Request), 1)in HttpKernel.php line 79
at HttpKernel->handle(object(Request), 1, true)in Kernel.php line 202
at Kernel->handle(object(Request))in app_dev.php line 26

**Describe the feature**:

**Comment by Devtronic** [comment]
That's no FOS UserBundle error. Please check, if the `src/AppBundle/Resources/views` directory exists. If it does not, create it.

**Comment by XWB** [comment]
^^

**Comment by flik** [comment]
thanks
