### ISSUE TITLE
fos:user:create user1 not creating user and giving error

### ISSUE THREAD

**Issue by flik** [FriendsOfSymfony/FOSUserBundle#2798]
**Symfony FOSUserBundle versions**: 2.x

**Description of the problem including expected versus actual behavior**: 
want to create the user with 

**Steps to reproduce**:

 1. php app/console fos:user:create user1

**Provide logs (if relevant)**:
 php bin/console -vvv fos:user:create user1
Please choose an email:user1@gmail.com
Please choose a password:

In User.php line 340:

  [Symfony\Component\Debug\Exception\ContextErrorException]
  Warning: array_search() expects parameter 2 to be array, null given

Exception trace:
 FOS\UserBundle\Model\User->removeRole() at /var/www/html/vendor/friendsofsymfony/user-bundle/Model/User.php:426
 FOS\UserBundle\Model\User->setSuperAdmin() at /var/www/html/vendor/friendsofsymfony/user-bundle/Util/UserManipulator.php:78
 FOS\UserBundle\Util\UserManipulator->create() at /var/www/html/vendor/friendsofsymfony/user-bundle/Command/CreateUserCommand.php:89
 FOS\UserBundle\Command\CreateUserCommand->execute() at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:252
 Symfony\Component\Console\Command\Command->run() at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:964
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:86
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:248
 Symfony\Component\Console\Application->doRun() at /var/www/html/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:74
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:148
 Symfony\Component\Console\Application->run() at /var/www/html/bin/console:27

fos:user:create [--super-admin] [--inactive] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> <username> <email> <password>

**Describe the feature**:

**Comment by Devtronic** [comment]
Can you please show us your User.php?

**Comment by flik** [comment]
`
<?php

namespace AppBundle\Entity;

use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
 
/**
 * User
 *
 * @ORM\Table(name="fos_user")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\UserRepository")
 * @ORM\AttributeOverrides({
 *  @ORM\AttributeOverride(
 *      name="name",
 *      column=@ORM\Column(name="name", type="string", nullable=true)
 *      )
 *  })
 */

class User extends BaseUser
{
    /**
     * One User has Many Projects.
     * @ORM\OneToMany(targetEntity="Projects", mappedBy="user")
     */
    private $projects;
    
    public function __construct() {
		parent::__construct();
        $this->projects = new ArrayCollection();
    }
    
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=191, nullable=true)
     * 
     */

    protected $name;

    /**
     * @var string
     *
     * @ORM\Column(name="surname", type="string", length=191, nullable=true)
     * 
     */
    private $surname;

    /**
     * @var string
     *
     * @ORM\Column(name="company", type="string", length=191, nullable=true)
     */
    private $company;

    /**
     * @var string
     *
     * @ORM\Column(name="university", type="string", length=191, nullable=true)
     */
    private $university;


    /**
     * Get id.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name.
     *
     * @param string $name
     *
     * @return User
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name.
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set surname.
     *
     * @param string $surname
     *
     * @return User
     */
    public function setSurname($surname)
    {
        $this->surname = $surname;

        return $this;
    }

    /**
     * Get surname.
     *
     * @return string
     */
    public function getSurname()
    {
        return $this->surname;
    }

    /**
     * Set company.
     *
     * @param string $company
     *
     * @return User
     */
    public function setCompany($company)
    {
        $this->company = $company;

        return $this;
    }

    /**
     * Get company.
     *
     * @return string
     */
    public function getCompany()
    {
        return $this->company;
    }

    /**
     * Set university.
     *
     * @param string $university
     *
     * @return User
     */
    public function setUniversity($university)
    {
        $this->university = $university;

        return $this;
    }

    /**
     * Get university.
     *
     * @return string
     */
    public function getUniversity()
    {
        return $this->university;
    }


    /**
     * Add project.
     *
     * @param \AppBundle\Entity\Projects $project
     *
     * @return User
     */
    public function addProject(\AppBundle\Entity\Projects $project)
    {
        $this->projects[] = $project;

        return $this;
    }

    /**
     * Remove project.
     *
     * @param \AppBundle\Entity\Projects $project
     *
     * @return boolean TRUE if this collection contained the specified element, FALSE otherwise.
     */
    public function removeProject(\AppBundle\Entity\Projects $project)
    {
        return $this->projects->removeElement($project);
    }

    /**
     * Get projects.
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getProjects()
    {
        return $this->projects;
    }
}

`

**Comment by flik** [comment]
problem fixed. thanks

**Comment by dustinfabre** [comment]
what is the fix though

**Comment by LadghemSaid** [comment]
I would like to know what solved your issue thanks 

> problem fixed. thanks
