### ISSUE TITLE
fos:user:promote error.

### ISSUE THREAD

**Issue by fabionvs** [FriendsOfSymfony/FOSUserBundle#2800]
Hello,
I have upgraded my symfony version to 3.4.8 and FosUserBundle is getting error when I am going to promote a user permission.
When I run `php7.1 fos:user:promote`, I get the following error:

```
 Error thrown while running command "fos:user:promote". 
Message: "Warning: in_array() expects parameter 2 to be array, null given" ["error" => Symfony\Component\Debug\Exception\ContextErrorException { …},"command" => "fos:user:promote","message" => 
"Warning: in_array() expects parameter 2 to be array, null given"] []

In User.php line 130:
                                                                   
  Warning: in_array() expects parameter 2 to be array, null given  
```
                                                                   
composer.json
`
"php": ">=7.1",
"symfony/symfony": "3.4.*",
"friendsofsymfony/user-bundle": "~2.0@dev",
`
What it should it be?

**Comment by Devtronic** [comment]
@fabionvs Still getting the error? If no, please close the issue

**Comment by fabionvs** [comment]
I´ve found what was wrong. The user was not activated.
