### ISSUE TITLE
Deprecation with Symfony 4.1 - AdvancedUserInterface

### ISSUE THREAD

**Issue by back-2-95** [FriendsOfSymfony/FOSUserBundle#2803]
Updated Symfony components to 4.1 and got following deprecation:

```
The "FOS\UserBundle\Model\UserInterface" interface extends "Symfony\Component\Security\Core\User\AdvancedUserInterface" that is deprecated since Symfony 4.1 *.
```

**Comment by hasanozbey** [comment]
any updates for 4.1?

**Comment by sharkman79** [comment]
I cannot understood what is the solution final for this "issue".
It is possible to have a list of steps to execute?

**Comment by aluisco** [comment]
I read as many possible I can and don't find any solution for the deprecation ... any updates???

**Comment by KevinArtus** [comment]
Is there any solution to use this bundle with symfony 4.1 ?
It's really annoying.

**Comment by hasanozbey** [comment]
Now i am clearly seeing that FOSUserBundle is regret. Use security component and write your own instead.

**Comment by Devtronic** [comment]
Do not you just have to copy this into FOS UserBundle?
https://github.com/symfony/symfony/blob/4.0/src/Symfony/Component/Security/Core/User/UserChecker.php

and put this Methods in the UserInterface class of FOS UserBundle? 
```
public function isAccountNonExpired();
public function isAccountNonLocked();
public function isCredentialsNonExpired();
public function isEnabled();
```

https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Model/UserInterface.php

**Comment by back-2-95** [comment]
Changing status to `Well begun is half done`

**Comment by Devtronic** [comment]
PR: https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2815

**Comment by sinner** [comment]
When is going to be implemented that change? I'm still having troubles with that issue. I'm working with the latest version 2.1.2 of FOSUserBundle.

**Comment by lucascardoso-egsys** [comment]
I'm too. Any solution?

**Comment by devtronic** [comment]
You can use the specific revision hash in the composer.json:
`friendsofsymfony/user-bundle": "dev-master#b93d732209ecd5eab35ed4e32e931760cb329122",`

**Comment by oliverfehmel** [comment]
So now SF5 is released, any updates here?
