### ISSUE TITLE
"Type Error: Too few arguments to constructor" on Forward

### ISSUE THREAD

**Issue by ianmclaughlin** [FriendsOfSymfony/FOSUserBundle#2805]
**Symfony FOSUserBundle versions**:
friendsofsymfony/user-bundle         v2.1.2             Symfony FOSUserBundle
symfony/symfony                      v3.4.11            The Symfony PHP framework

**Description of the problem including expected versus actual behaviour**:
Bug moving for 2.0.2 to 2.1.2. I have my own route for confirmEmailRegistrationAction which sits in front of FOSUserBundle and catches any 404s that it produces. My users need this because Bing seems to pre-click the link before showing it to users of Hotmail, Outlook etc - so when the user clicks it for the first time they get a 404 and don't understand why.

**Steps to reproduce**:
 1. Create a wrapper action
`public function confirmEmailRegistrationAction(Request $request, $token)
    {
        $response = $this->forward('FOSUserBundle:Registration:confirm', array(
            'request' => $request,
            'token' => $token
        ));

        if ($response->getStatusCode() == Response::HTTP_NOT_FOUND){
            if (!$this->isGranted('IS_AUTHENTICATED_REMEMBERED')) {
                $this->addFlash(
                    Message::SUCCESS,
                    "Email address confirmed, please login"
                );
            }
            return $this->redirectToRoute('account');
        }

        return $response;
    }
`
 2. Add a route for this new action, before the FOSUserBundle route
 3. Create a new user, and click the confirmation link

Unlike #2745 etc I'm not overriding FOSUserBundle, I'm forwarding to a FOSUserBundle action.

**Comment by xabbuh** [comment]
What happens when you try `$this->forward('fos_user.registration.controller:confirmAction');` instead?

**Comment by ianmclaughlin** [comment]
Thank you - that works. But why does that work?

**Comment by xabbuh** [comment]
The first argument that you pass to forward is passed as the controller to be executed to the kernel. When using the bundle notation that you used, Symfony will instantiate the controller class without passing any arguments to the constructor. In FOSUserBundle, the controller is registered as a service with the argument injected so you need to tell the kernel that it needs to use a method from that specific service as the controller that handles the forwarded request.

**Comment by xabbuh** [comment]
see also https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Resources/config/registration.xml and https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Resources/config/routing/registration.xml

**Comment by ianmclaughlin** [comment]
Okay, thank you. Closing.
