### ISSUE TITLE
Translations in symfony 4 not working

### ISSUE THREAD

**Issue by albawan** [FriendsOfSymfony/FOSUserBundle#2813]
In Symfony 4 storing translation files in <project>/translations/  and changing them does not override the original file. For example, when saving FOSUserBundle.en.yml and changing the messages, this does nothing for me.

**Comment by Devtronic** [comment]
Did you cleared the cache (`php bin/console cache:clear`) after you copied the `FOSUserBundle.en.yml` to the `/translations` Directory? I can not reproduce the problem (Symfony 4.1 + FOS UserBundle v2.1.2)

**Comment by albawan** [comment]
You were right, thanks. Stupid mistake. I'll close this issue.
