### ISSUE TITLE
User Deprecated: Referencing controllers with a single colon is deprecated since Symfony 4.1. Use fos_user.security.controller::loginAction instead.

### ISSUE THREAD

**Issue by bartoszmichalski** [FriendsOfSymfony/FOSUserBundle#2818]
**Symfony FOSUserBundle versions**:
2.1.2

 I'm getting deprecated info in Symfony 4.1 application, probably connected with calling controller's methods in configuration files:
   Resources/config/routing/*.xml

**Comment by Devtronic** [comment]
https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2806
