### ISSUE TITLE
Make private variables protected for better reusability & less duplicate code definitions

### ISSUE THREAD

**Issue by develth** [FriendsOfSymfony/FOSUserBundle#2820]
Hi there,

i recognized that, if i want to override some functions of Classes (e.g. EmailConfirmationListener) and made the original class as parent, i can´t use the variables because they are private, so i have to define them again and produce some duplicate code. 

Is it possible (and a good way to go) to make those vars protected instead of private?

Thanks,
Thomas

**Comment by Tomsgu** [comment]
IMO a good way to go is to implement your own `EmailConfirmationListener` and don't mess with inheritance especially if the class is so small. And simply change a service definition of fos user bundle. http://symfony.com/doc/3.4/bundles/override.html#services-configuration

**Comment by XWB** [comment]
^^
