### ISSUE TITLE
Tag new version to resolve paragonie dep issue

### ISSUE THREAD

**Issue by respinoza** [FriendsOfSymfony/FOSUserBundle#2830]
For 2.1.2, it still requires pargonie as ^1 and ^2 but now that paragonie has the special version 9.99.99 when using PHP7, ^9 is needed.
Now, this has been fixed in master but no tag since March and it is not very nice to depend on master to make it work.

Any ETA on when the next tag will be done?

Thank you

**Comment by stof** [comment]
Released in 2.2
