### ISSUE TITLE
Overriding command line tools

### ISSUE THREAD

**Issue by Ultimade** [FriendsOfSymfony/FOSUserBundle#2831]
**Symfony FOSUserBundle versions**: 2.1
**Symfony  versions**: 4.1

**Description of the problem including expected versus actual behavior**:
I try to override fos:user:create because my user entyty have some required data which cannot be null. Like: full name, phone number, etc. 
I created an own CreateUserCommand, but need override UserManipulator too. When i create own UserManipulator which override the default I got error which I cant handle.

**Steps to reproduce**:
 1. Copy :
vendor/friendsofsymfony/user-bundle/Command/CreateUserCommand  to App/src/Command/CreateUserCommand
and
vendor/friendsofsymfony/user-bundle/Util/UserManipulator  to App/src/Util/UserManipulator

 2. Change namespaces FOS\UserBundle\Command to App/Command
 3. In CreateUserCommand :
 - configure function change string in setname() and  add new ImputArguments like: fullname, phoneneumber
 - execute function add getters to the new variables
 - interact function new if for fullname and phonenumber 
4. In UserManipulator
 - create function add setters to the user entyti like setFullname, setPhonenumber

**Provide logs (if relevant)**:
$ php bin/console own:user:create
2018-08-10T10:52:11+02:00 [error] Error thrown while running command "'own:user:create'". Message: "Argument 1 passed to App\Util\UserManipulator::__construct() must be an instance of FOS\UserBundle\Model\UserManagerInterface, instance of Doctrine\ORM\EntityManager given, called in /var/www/html/myproject/var/cache/dev/ContainerVH06jr2/getCreateUserCommandService.php on line 13"
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Argument 1 passed to App\Util\UserManipulator::__construct() must be an instance of FOS\UserBundle\Model\UserManagerInterface, instance of Doctrine\ORM\EntityManager given, called in /var/www/html/myproject/var/cache/dev/ContainerVH06jr2/getCreateUserCommandService.php on line 13 in /var/www/html/myproject/src/Util/UserManipulator.php:53

**Describe the feature**:

**Comment by Ultimade** [comment]
### The user create command:
`<?php

/*
 * This file is override the part of the FOSUserBundle package.
 *
 * (c) FriendsOfSymfony <http://friendsofsymfony.github.com/>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Command;

use App\Util\UserManipulator;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Question\Question;


class CreateUserCommand extends Command
{
    protected static $defaultName = 'titan:user:create';

    protected $userManipulator;

    public function __construct(UserManipulator $userManipulator)
    {
        parent::__construct();

        $this->userManipulator = $userManipulator;
    }

    /**
     * {@inheritdoc}
     */
    protected function configure()
    {
        $this
            ->setName('titan:user:create')
            ->setDescription('Create a user.')
            ->setDefinition(array(
                new InputArgument('username', InputArgument::REQUIRED, 'The username'),
                new InputArgument('email', InputArgument::REQUIRED, 'The email'),
                new InputArgument('fullanem', InputArgument::REQUIRED, 'The full name'),
                new InputArgument('sex', InputArgument::REQUIRED, 'The sex (Female F  Male M)'),
                new InputArgument('password', InputArgument::REQUIRED, 'The password'),
                new InputOption('super-admin', null, InputOption::VALUE_NONE, 'Set the user as super admin'),
                new InputOption('inactive', null, InputOption::VALUE_NONE, 'Set the user as inactive'),
            ))
            ->setHelp(<<<'EOT'
The <info>fos:user:create</info> command creates a user:

  <info>php %command.full_name% matthieu</info>

This interactive shell will ask you for an email and then a password.

You can alternatively specify the email and password as the second and third arguments:

  <info>php %command.full_name% matthieu matthieu@example.com mypassword</info>

You can create a super admin via the super-admin flag:

  <info>php %command.full_name% admin --super-admin</info>

You can create an inactive user (will not be able to log in):

  <info>php %command.full_name% thibault --inactive</info>

EOT
            );
    }

    /**
     * {@inheritdoc}
     */
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $username = $input->getArgument('username');
        $email = $input->getArgument('email');
        $fullname = $input->getArgument('fullname');
        $sex = $input->getArgument('sex');
        $password = $input->getArgument('password');
        $inactive = $input->getOption('inactive');
        $superadmin = $input->getOption('super-admin');

        $this->userManipulator->create($username, $password, $email, $fullname, $sex, !$inactive, $superadmin);

        $output->writeln(sprintf('Created user <comment>%s</comment>', $username));
    }

    /**
     * {@inheritdoc}
     */
    protected function interact(InputInterface $input, OutputInterface $output)
    {
        $questions = array();

        if (!$input->getArgument('username')) {
            $question = new Question('Please choose a username:');
            $question->setValidator(function ($username) {
                if (empty($username)) {
                    throw new \Exception('Username can not be empty');
                }

                return $username;
            });
            $questions['username'] = $question;
        }

        if (!$input->getArgument('email')) {
            $question = new Question('Please choose an email:');
            $question->setValidator(function ($email) {
                if (empty($email)) {
                    throw new \Exception('Email can not be empty');
                }

                return $email;
            });
            $questions['email'] = $question;
        }

        if (!$input->getArgument('email')) {
            $question = new Question('Please choose an email:');
            $question->setValidator(function ($email) {
                if (empty($email)) {
                    throw new \Exception('Email can not be empty');
                }

                return $email;
            });
            $questions['email'] = $question;
        }

        if (!$input->getArgument('fullname')) {
            $question = new Question('Please give  the full name of the user:');
            $question->setValidator(function ($fullname) {
                if (empty($fullname)) {
                    throw new \Exception('Full name can not be empty');
                }

                return $fullname;
            });
            $questions['fullname'] = $question;
        }

        if (!$input->getArgument('sex')) {
            $question = new Question('Please give the sex of the user:');
            $question->setValidator(function ($sex) {
                if (empty($sex)) {
                    throw new \Exception('Sex can not be empty');
                }

                return $sex;
            });
            $questions['sex'] = $question;
        }

        if (!$input->getArgument('password')) {
            $question = new Question('Please choose a password:');
            $question->setValidator(function ($password) {
                if (empty($password)) {
                    throw new \Exception('Password can not be empty');
                }

                return $password;
            });
            $question->setHidden(true);
            $questions['password'] = $question;
        }

        foreach ($questions as $name => $question) {
            $answer = $this->getHelper('question')->ask($input, $output, $question);
            $input->setArgument($name, $answer);
        }
    }
}
`
### The user manipulator:
I need EntityManager because I need load other entity, but I got same error before I add this 2 lines and define EntityManager as $em:

use Doctrine\ORM\EntityManager;

public function create($username, $password, $email, $fullname, $sex, $active, $superadmin, EntityManager $em)

 $sex = $em->getRepository("App:Sexmaster")->findOneBy(array("type"=>$sex));
`<?php

/*
 * This file is  override the part of the FOSUserBundle package.
 *
 * (c) FriendsOfSymfony <http://friendsofsymfony.github.com/>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Util;

use Doctrine\ORM\EntityManager;
use FOS\UserBundle\Event\UserEvent;
use FOS\UserBundle\FOSUserEvents;
use FOS\UserBundle\Model\UserInterface;
use FOS\UserBundle\Model\UserManagerInterface;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use Symfony\Component\HttpFoundation\RequestStack;

/**
 * Executes some manipulations on the users.
 *
 * @author Christophe Coevoet <stof@notk.org>
 * @author Luis Cordova <cordoval@gmail.com>
 */
class UserManipulator
{
    /**
     * User manager.
     *
     * @var UserManagerInterface
     */
    private $userManager;

    /**
     * @var EventDispatcherInterface
     */
    private $dispatcher;

    /**
     * @var RequestStack
     */
    private $requestStack;

    /**
     * UserManipulator constructor.
     *
     * @param UserManagerInterface     $userManager
     * @param EventDispatcherInterface $dispatcher
     * @param RequestStack             $requestStack
     */
    public function __construct(UserManagerInterface $userManager, EventDispatcherInterface $dispatcher, RequestStack $requestStack)
    {
        $this->userManager = $userManager;
        $this->dispatcher = $dispatcher;
        $this->requestStack = $requestStack;
    }

    /**
     * Creates a user and returns it.
     *
     * @param string $username
     * @param string $password
     * @param string $email
     * @param string $fullname
     * @param integer $sex
     * @param bool   $active
     * @param bool   $superadmin
     *
     * @return \FOS\UserBundle\Model\UserInterface
     */
    public function create($username, $password, $email, $fullname, $sex, $active, $superadmin, EntityManager $em)
    {
        $user = $this->userManager->createUser();
        $user->setUsername($username);
        $user->setEmail($email);
        $sex = $em->getRepository("App:Sexmaster")->findOneBy(array("type"=>$sex));
        $user->setSex($sex);
        $user->setFullname($fullname);
        $user->setPlainPassword($password);
        $user->setEnabled((bool) $active);
        $user->setSuperAdmin((bool) $superadmin);
        $this->userManager->updateUser($user);

        $event = new UserEvent($user, $this->getRequest());
        $this->dispatcher->dispatch(FOSUserEvents::USER_CREATED, $event);

        return $user;
    }

    /**
     * Activates the given user.
     *
     * @param string $username
     */
    public function activate($username)
    {
        $user = $this->findUserByUsernameOrThrowException($username);
        $user->setEnabled(true);
        $this->userManager->updateUser($user);

        $event = new UserEvent($user, $this->getRequest());
        $this->dispatcher->dispatch(FOSUserEvents::USER_ACTIVATED, $event);
    }

    /**
     * Deactivates the given user.
     *
     * @param string $username
     */
    public function deactivate($username)
    {
        $user = $this->findUserByUsernameOrThrowException($username);
        $user->setEnabled(false);
        $this->userManager->updateUser($user);

        $event = new UserEvent($user, $this->getRequest());
        $this->dispatcher->dispatch(FOSUserEvents::USER_DEACTIVATED, $event);
    }

    /**
     * Changes the password for the given user.
     *
     * @param string $username
     * @param string $password
     */
    public function changePassword($username, $password)
    {
        $user = $this->findUserByUsernameOrThrowException($username);
        $user->setPlainPassword($password);
        $this->userManager->updateUser($user);

        $event = new UserEvent($user, $this->getRequest());
        $this->dispatcher->dispatch(FOSUserEvents::USER_PASSWORD_CHANGED, $event);
    }

    /**
     * Promotes the given user.
     *
     * @param string $username
     */
    public function promote($username)
    {
        $user = $this->findUserByUsernameOrThrowException($username);
        $user->setSuperAdmin(true);
        $this->userManager->updateUser($user);

        $event = new UserEvent($user, $this->getRequest());
        $this->dispatcher->dispatch(FOSUserEvents::USER_PROMOTED, $event);
    }

    /**
     * Demotes the given user.
     *
     * @param string $username
     */
    public function demote($username)
    {
        $user = $this->findUserByUsernameOrThrowException($username);
        $user->setSuperAdmin(false);
        $this->userManager->updateUser($user);

        $event = new UserEvent($user, $this->getRequest());
        $this->dispatcher->dispatch(FOSUserEvents::USER_DEMOTED, $event);
    }

    /**
     * Adds role to the given user.
     *
     * @param string $username
     * @param string $role
     *
     * @return bool true if role was added, false if user already had the role
     */
    public function addRole($username, $role)
    {
        $user = $this->findUserByUsernameOrThrowException($username);
        if ($user->hasRole($role)) {
            return false;
        }
        $user->addRole($role);
        $this->userManager->updateUser($user);

        return true;
    }

    /**
     * Removes role from the given user.
     *
     * @param string $username
     * @param string $role
     *
     * @return bool true if role was removed, false if user didn't have the role
     */
    public function removeRole($username, $role)
    {
        $user = $this->findUserByUsernameOrThrowException($username);
        if (!$user->hasRole($role)) {
            return false;
        }
        $user->removeRole($role);
        $this->userManager->updateUser($user);

        return true;
    }

    /**
     * Finds a user by his username and throws an exception if we can't find it.
     *
     * @param string $username
     *
     * @throws \InvalidArgumentException When user does not exist
     *
     * @return UserInterface
     */
    private function findUserByUsernameOrThrowException($username)
    {
        $user = $this->userManager->findUserByUsername($username);

        if (!$user) {
            throw new \InvalidArgumentException(sprintf('User identified by "%s" username does not exist.', $username));
        }

        return $user;
    }

    /**
     * @return Request
     */
    private function getRequest()
    {
        return $this->requestStack->getCurrentRequest();
    }
}
`


### The error:
`Argument 1 passed to App\Util\UserManipulator::__construct() must be an instance of FOS\UserBundle\Model\UserManagerInterface, instance o  
  f Doctrine\ORM\EntityManager given, called in /var/www/html/titansquestionnaire/var/cache/dev/ContainerRdXxoh8/getCreateUserCommandServic  
  e.php on line 13 `

**Comment by Tomsgu** [comment]
Can you please make your code redable? I cannot find anything in it. Using ` ```php ` in the begginning and ` ``` ` at the end of code block. Can you also post your service definition?

**Comment by Ultimade** [comment]
```<?php

/*
 * This file is part of the FOSUserBundle package.
 *
 * (c) FriendsOfSymfony <http://friendsofsymfony.github.com/>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Command;

use App\Util\UserManipulator;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Question\Question;


class CreateUserCommand extends Command
{
    protected static $defaultName = 'titan:user:create';

    protected $userManipulator;

    public function __construct(UserManipulator $userManipulator)
    {
        parent::__construct();

        $this->userManipulator = $userManipulator;
    }

    /**
     * {@inheritdoc}
     */
    protected function configure()
    {
        $this
            ->setName('titan:user:create')
            ->setDescription('Create a user.')
            ->setDefinition(array(
                new InputArgument('username', InputArgument::REQUIRED, 'The username'),
                new InputArgument('email', InputArgument::REQUIRED, 'The email'),
                new InputArgument('fullanem', InputArgument::REQUIRED, 'The full name'),
                new InputArgument('sex', InputArgument::REQUIRED, 'The sex (Female F  Male M)'),
                new InputArgument('password', InputArgument::REQUIRED, 'The password'),
                new InputOption('super-admin', null, InputOption::VALUE_NONE, 'Set the user as super admin'),
                new InputOption('inactive', null, InputOption::VALUE_NONE, 'Set the user as inactive'),
            ))
            ->setHelp(<<<'EOT'
The <info>fos:user:create</info> command creates a user:

  <info>php %command.full_name% matthieu</info>

This interactive shell will ask you for an email and then a password.

You can alternatively specify the email and password as the second and third arguments:

  <info>php %command.full_name% matthieu matthieu@example.com mypassword</info>

You can create a super admin via the super-admin flag:

  <info>php %command.full_name% admin --super-admin</info>

You can create an inactive user (will not be able to log in):

  <info>php %command.full_name% thibault --inactive</info>

EOT
            );
    }

    /**
     * {@inheritdoc}
     */
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $username = $input->getArgument('username');
        $email = $input->getArgument('email');
        $fullname = $input->getArgument('fullname');
        $sex = $input->getArgument('sex');
        $password = $input->getArgument('password');
        $inactive = $input->getOption('inactive');
        $superadmin = $input->getOption('super-admin');

        $this->userManipulator->create($username, $password, $email, $fullname, $sex, !$inactive, $superadmin);

        $output->writeln(sprintf('Created user <comment>%s</comment>', $username));
    }

    /**
     * {@inheritdoc}
     */
    protected function interact(InputInterface $input, OutputInterface $output)
    {
        $questions = array();

        if (!$input->getArgument('username')) {
            $question = new Question('Please choose a username:');
            $question->setValidator(function ($username) {
                if (empty($username)) {
                    throw new \Exception('Username can not be empty');
                }

                return $username;
            });
            $questions['username'] = $question;
        }

        if (!$input->getArgument('email')) {
            $question = new Question('Please choose an email:');
            $question->setValidator(function ($email) {
                if (empty($email)) {
                    throw new \Exception('Email can not be empty');
                }

                return $email;
            });
            $questions['email'] = $question;
        }

        if (!$input->getArgument('email')) {
            $question = new Question('Please choose an email:');
            $question->setValidator(function ($email) {
                if (empty($email)) {
                    throw new \Exception('Email can not be empty');
                }

                return $email;
            });
            $questions['email'] = $question;
        }

        if (!$input->getArgument('fullname')) {
            $question = new Question('Please give  the full name of the user:');
            $question->setValidator(function ($fullname) {
                if (empty($fullname)) {
                    throw new \Exception('Full name can not be empty');
                }

                return $fullname;
            });
            $questions['fullname'] = $question;
        }

        if (!$input->getArgument('sex')) {
            $question = new Question('Please give the sex of the user:');
            $question->setValidator(function ($sex) {
                if (empty($sex)) {
                    throw new \Exception('Sex can not be empty');
                }

                return $sex;
            });
            $questions['sex'] = $question;
        }

        if (!$input->getArgument('password')) {
            $question = new Question('Please choose a password:');
            $question->setValidator(function ($password) {
                if (empty($password)) {
                    throw new \Exception('Password can not be empty');
                }

                return $password;
            });
            $question->setHidden(true);
            $questions['password'] = $question;
        }

        foreach ($questions as $name => $question) {
            $answer = $this->getHelper('question')->ask($input, $output, $question);
            $input->setArgument($name, $answer);
        }
    }
}
```
```services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    app.form.registration:
        class: App\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    App\Util\UserManipulator:
        arguments: ['@doctrine.orm.entity_manager']
        tags:
```
I think this is the problem:
```App\Util\UserManipulator:
        arguments: ['@doctrine.orm.entity_manager']
        tags:```

**Comment by Tomsgu** [comment]
Your `UserManipulator` has 3 dependencies. None of them is EntityManagerInterface. If you want to use EntityManager you should define it as fourth dependency. Note that it should work without service definition here.

On github there is an edit button. So there is no need to post things twice. There is also a preview tab so you can review what you've written.

**Comment by Tomsgu** [comment]
Exactly. Of course your error also comes from your service definition. I see 4 dependencies and you have 1.
```yaml
 App\Util\UserManipulator:
        arguments: ['@doctrine.orm.entity_manager']
        tags:
```

**Comment by Ultimade** [comment]
Solved!
In own CreateUserCommand.php add some lines:
add usage ContainerAwareCommand
```use Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand;```

Change command extension to ContainerAwareCommand:
```class CreateUserCommand extends ContainerAwareCommand```

Load doctrine in function wgere I needed:
       ``` $doctrine = $this->getContainer()->get('doctrine');
        $sex = $doctrine->getRepository("App:Sexmaster")->findAll();```


in services.yaml change this:
```App\Util\UserManipulator:
        arguments: ['@doctrine.orm.entity_manager']
        tags:```
to this:
```App\Util\UserManipulator:
        class: App\Util\UserManipulator```
not the best solution but work well.
