### ISSUE TITLE
[Login form]  _target_path and _failure_path doesn't work in dev mode

### ISSUE THREAD

**Issue by yamapi** [FriendsOfSymfony/FOSUserBundle#2832]
Hi FOS community,

Configuration:
- Symfony: 3.4
- FOSUserBundle: 2.1.2
- php: 7.1.8
- OS: MacOSX
- Apache: 2.0
- MySQL: 5.6.35

I'm looking how to override the redirect URL via POST using a hidden form field

```twig
<form action="{{ path('login') }}" method="post">

    <input type="hidden" name="_target_path" value="{{ path('account') }}" />
    <input type="submit" name="login" />

</form>
```

But when I submit the form i have this error:

> No route found for "GET /app_dev.php/account" 

Because the URL look like 
> http://localhost:8888/app_dev.php/app_dev.php/account

Do I misunderstand something ?
Is it a bug in the bundle ?

**Comment by gponty** [comment]
_target_path need only a route name, like :

<input type="hidden" name="_target_path" value="account" />
