### ISSUE TITLE
change password throws exception

### ISSUE THREAD

**Issue by bjoernLillydoo** [FriendsOfSymfony/FOSUserBundle#2833]
**Symfony FOSUserBundle versions**: 
2.0.0

**Description of the problem including expected versus actual behavior**:
After trying to change the password on myapp/profile/change-password I get an exception "UniqueConstraintViolationException". Password will not be changed.

**Steps to reproduce**:
 1. When logged in as User go to change-password page myapp/profile/change-password
 2. fill in the form and submit

I could track this to a line of code in
friendsofsymfony/user-bundle/Doctrine/UserManager.php
in method updateUser($user, ...) 
you find "$this->objectManager->persist($user);".
Without this line, everything works fine.
As I understand, this line tells Symfony/Doctrine to create a new user-object, which is not needed here.

Exception Message:
An exception occurred while executing 'INSERT INTO user (username, username_canonical, email, email_canonical, enabled, salt, password, last_login, locked, expired, expires_at, confirmation_token, password_requested_at, roles, credentials_expired, credentials_expire_at, invitation) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' 

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '?' for key '?'

**Comment by stof** [comment]
`persist` does not tell Doctrine to create a new user. It depends whether the object is already managed by Doctrine or no.

It looks like you made something special, leading to the User object not being known by Doctrine at the time you edit it. So please provide a reproducing case.
