### ISSUE TITLE
password encryption issue

### ISSUE THREAD

**Issue by fr51** [FriendsOfSymfony/FOSUserBundle#2834]
**Symfony FOSUserBundle version**: 2.1.2

**Description of the problem including expected versus actual behavior**:

I'm creating new users on my database with bcrypt password encryption and the stored password isn't the same as the one I defined, so I can't log in.

For instance, I'm creating a user named "fr" and setting "fr" as email and password. Using bcrypt, the password should be `$2y$10$jWNEsxKEaW.BXbEO73vXjOKuGl8Qp2wC9ocnwQTRzHFsEVtIAvfoq` instead of actual `$2y$13$qnBgBcoPqucD9YvzLl6ugOaXEWyEhnDjNOhloy0c8ksBM7PL4Z73e`.

This issue also occurs with sha512 encryption

**Steps to reproduce**:
 1. run `php bin/console fos:user:create`
 2. set "fr" as username, email and password
 3. confirm

**Comment by Tomsgu** [comment]
According to what do you think that the generated password is wrong? Every time you hash it you will get a different value, because a salt differs. Please read e.g. http://php.net/manual/en/function.password-hash.php first.

**Comment by fr51** [comment]
You're right for SHA512. But with bcrypt, the field `salt` is null and the password is only stored in the `password` field

**Comment by Tomsgu** [comment]
Have you read http://php.net/manual/en/function.password-hash.php? 

> salt (string) - to manually provide a salt to use when hashing the password. Note that this will override and prevent a salt from being automatically generated.

>If omitted, a random salt will be generated by password_hash() for each password hashed. This is the intended mode of operation.

>Warning
>The salt option has been deprecated as of PHP 7.0.0. It is now preferred to simply use the salt that is generated by default.

If your entity has a salt field set to null it doesn't mean that algorithm does not generate salt. See: https://stackoverflow.com/questions/6832445/how-can-bcrypt-have-built-in-salts

**Comment by fr51** [comment]
In fact, I've been looking in the database because I can't log in with the credentials I defined while running `php bin/console fos:user:create`

**Comment by stof** [comment]
Without providing more details to reproduce the issue, there is nothing we can do to help you. 
how are you passing the password to the command ? Using the CLI option or the interactive prompt ?

https://3v4l.org/onsRX indeed tells me that the hashed password is not `fr` in your case (no idea what it is though, of course)

**Comment by fr51** [comment]
I use the interactive prompt and the issue is that I set the password to `fr` but the database-stored hashed password isn't `fr`
