### ISSUE TITLE
Add `/config/packages/fos_user.yaml` on `composer require` for symfony 4

### ISSUE THREAD

**Issue by polishExperiment** [FriendsOfSymfony/FOSUserBundle#2862]
Currently `/config/packages/fos_user.yaml` file is not being generated when doing `composer require friendsofsymfony/user-bundle "~2.0"`.

This feature request would like it to be so.

**Comment by XWB** [comment]
This would be related to Symfony Flex, and not Symfony 4.

**Comment by alfonsodev** [comment]
related to #2861
