### ISSUE TITLE
The child node "db_driver" at path "fos_user" must be configured.

### ISSUE THREAD

**Issue by mcl12345** [FriendsOfSymfony/FOSUserBundle#2865]
Hi,

I have this : "The child node "db_driver" at path "fos_user" must be configured."

even if I put this :

    # app/config/config.yml
    fos_user:
         db_driver: orm # other valid values are 'mongodb' and 'couchdb'
         firewall_name: main
         user_class: UserBundle\Entity\User
         from_email:
             address: "%mailer_user%"
             sender_name: "%mailer_user%"

**Comment by stof** [comment]
make sure you don't have 2 `fos_user` keys in the same file (as one of them would get ignored), and make sure that your file is properly loaded. That's the first ideas I have.

**Comment by tacman** [comment]
check if you have an fos_user.yaml file in /config

**Comment by XWB** [comment]
^^
