### ISSUE TITLE
The service "fos_user.resetting.controller" has a dependency on a non-existent service "templating"

### ISSUE THREAD

**Issue by christiankasse** [FriendsOfSymfony/FOSUserBundle#2870]
How can i configure **FOSUser Bundle** Using SYMFONY 4.1 because it's create much errors

**Comment by stof** [comment]
which version of FOSUserBundle are you using ?

**Comment by christiankasse** [comment]
I'm using version 2.1.2

**Comment by christiankasse** [comment]
what would I do at this stage

**Comment by christiankasse** [comment]
I already did, but the problem still lingers

**Comment by devtronic** [comment]
Needed deps installed?
`composer require annotations doctrine migrations twig translations`

And cache cleared? (`php bin/console cache:clear`)

**Comment by christiankasse** [comment]
**and here is my configuration**
`security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            # id: fos_user.user_provider.username
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            user_checker: fos_user.user_checker
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }`

**Comment by christiankasse** [comment]
Help Please

**Comment by arthur-nora** [comment]
Hi, you need to change 
`user_checker: fos_user.user_checker` 
to 
`user_checker: security.user_checker`
Duplicate of #2855

**Comment by vkhramtsov** [comment]
@christiankasse @stof How about close this ticket?

**Comment by AlexandreKilian** [comment]
this should be added to the documentation… I keep running into the same issues because the docs aren't up to date

**Comment by eved42** [comment]
I've just created a new Symfony 3.4 project and installed FOSUserBundle 2.1 and I had the same issue too.
Please, correct the documentation.

**Comment by nmeirik** [comment]
I'm wondering if the original issue here perhaps needs to be reopened in preparation for Symfony 5. Since the [templating component integration](https://symfony.com/blog/new-in-symfony-4-3-deprecated-the-templating-component-integration) is removed in Symfony 5, I've followed [these steps](https://stackoverflow.com/questions/58380812/symfony-4-3-user-deprecated-the-symfony-bundle-twigbundle-loader-filesystemloa) in an attempt to fix a deprecation warning related to the templating component.

However, when I do, the following error is thrown:

```
The service "fos_user.resetting.controller" has a dependency on a non-existent service "templating".
```

It's not clear to me what's causing the error though, as I can see no `templating` dependency in the `fos_user.resetting.controller` [service definition](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Resources/config/resetting.xml#L27). Perhaps the problem is that the entire `service_container` is being set on the controller?

**Comment by Gibbo3771** [comment]
A year later, problem still exists?.... I just updated a symfony 3.4 app to symfony 4.4 and I am getting this error. I have no idea how to even debug it.

**Comment by nmeirik** [comment]
@Gibbo3771 You might want to try https://bytenota.com/symfony-4-fosuserbundle-the-service-fos_user-resetting-controller-has-a-dependency-on-a-non-existent-service-templating/

**Comment by jmeyo** [comment]
More specifically, setting the proper mailing implementation setting, which is used by the resetting controller (among other) and is somehow related to a direct injection of @templating.

```
fos_user:
# [...]
    service:
        mailer: fos_user.mailer.twig_swift    
```

**Comment by vipinbose** [comment]
> More specifically, setting the proper mailing implementation setting, which is used by the resetting controller (among other) and is somehow related to a direct injection of @templating.
> 
> ```
> fos_user:
> # [...]
>     service:
>         mailer: fos_user.mailer.twig_swift    
> ```
This resolved my issue
