### ISSUE TITLE
composer update throws : Unrecognized options "memory_cost, time_cost, threads" under "security.encoders.FOS\UserBundle\Model\UserInterface"

### ISSUE THREAD

**Issue by etshy** [FriendsOfSymfony/FOSUserBundle#2873]
**Symfony FOSUserBundle versions**:
versions : * v2.1.2

**Description of the problem including expected versus actual behavior**:
tried to `composer update` my project and I had the message : `Unrecognized options "memory_cost, time_cost, threads" under "security.encoders.FOS\UserBundle\Model\UserInterface"`

**Steps to reproduce**:
 1. `composer update`

**Provide logs (if relevant)**:
```
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  PHP Warning:  Module 'mongodb' already loaded in Unknown on line 0
!!
!!  In ArrayNode.php line 307:
!!
!!    Unrecognized options "memory_cost, time_cost, threads" under "security.enco
!!    ders.FOS\UserBundle\Model\UserInterface"
!!
!!
!!
Script @auto-scripts was called via post-update-cmd
```

I guess it's related to my password encoding config
```
security:
  encoders:
    FOS\UserBundle\Model\UserInterface:
      algorithm: argon2i
      memory_cost:          16384 # Amount in KiB. 16 MiB
      time_cost:            2 # Number of iterations
      threads:              4 # Number of parallel threads
```

Edit : I tried to change my `FOS\UserBundle\Model\UserInterface` with the User Class stated in Symfony Docs and I still have the error.
I'll create an issue on Symfony Repo.

**Comment by devtronic** [comment]
Please provide the Symfony Version which are you using. Argon2i-Configuration is available from SF 4.1 https://symfony.com/blog/new-in-symfony-4-1-argon2i-configuration

**Comment by etshy** [comment]
I was with Symfony 4.1.5 or 4.1.6 before update, and now 4.1.8.

I have argon2i configured for at least 3 or 4 months already and had the problem during an update today

**Comment by stof** [comment]
The configu you are showing here is not the config of FOSUserBundle, but the config of SecurityBundle (the top-level key is `security`, not `fos_user`). This issue is not reported to the right place.
