### ISSUE TITLE
Unrecognized field: emailCanonical

### ISSUE THREAD

**Issue by webiummedia** [FriendsOfSymfony/FOSUserBundle#2887]
I am new to Symfony 3.4 and was tasked to add a password reset feature to an exsting website. I have followed a tutorial on using friendsofsymfony/user-bundle and got up to the point where i am sending a Json request to my controler and it responds back :

    {"code":500,"message":"Unrecognized field: emailCanonical"}

The line causing the problem is:

    $user = $this->get('fos_user.user_manager')->findUserByUsernameOrEmail($username);

This is the complete file src/AppBundle/RestPasswordManagementController.php

    <?php
    namespace AppBundle\Controller;
    
    use FOS\RestBundle\Controller\Annotations;
    use FOS\RestBundle\Controller\FOSRestController;
    use FOS\RestBundle\Routing\ClassResourceInterface;
    use FOS\RestBundle\Controller\Annotations\RouteResource;
    use FOS\UserBundle\Event\FilterUserResponseEvent;
    use FOS\UserBundle\Event\GetResponseNullableUserEvent;
    use FOS\UserBundle\Event\GetResponseUserEvent;
    use FOS\UserBundle\FOSUserEvents;
    use FOS\UserBundle\Event\FormEvent;
    use Symfony\Component\EventDispatcher\EventDispatcherInterface;
    use Symfony\Component\HttpFoundation\JsonResponse;
    use Symfony\Component\HttpFoundation\Request;
    use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
    use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;
    use Symfony\Component\Security\Core\User\UserInterface;
    use Doctrine\ORM\EntityManager;
    use Symfony\Component\Routing\RouterInterface;
    use Symfony\Component\Security\Core\Security;
    use Symfony\Component\Security\Core\Encoder\UserPasswordEncoder;
    use Symfony\Component\Security\Core\User\UserProviderInterface;
    use Symfony\Component\Security\Guard\Authenticator\AbstractFormLoginAuthenticator;
    
    /**
     * @Annotations\Prefix("password")
     * @RouteResource("/password", pluralize=false)
     */
    class RestPasswordManagementController extends FOSRestController implements ClassResourceInterface
    {
       
        /**
         * @Annotations\Post("/reset/request")
         */
        public function requestResetAction(Request $request)
        {
    
            $username = $request->get('email');        
    
            /** @var $user UserInterface */
            $user = $this->get('fos_user.user_manager')->findUserByUsernameOrEmail($username);
                
                return new JsonResponse(
                    $user,
                    JsonResponse::HTTP_FORBIDDEN
                );
    
            /** @var $dispatcher EventDispatcherInterface */
            $dispatcher = $this->get('event_dispatcher');
            /* Dispatch init event */
            $event = new GetResponseNullableUserEvent($user, $request);
            $dispatcher->dispatch(FOSUserEvents::RESETTING_SEND_EMAIL_INITIALIZE, $event);
            if (null !== $event->getResponse()) {
                return $event->getResponse();
            }
            if (null === $user) {
                return new JsonResponse(
                    'User not recognised',
                    JsonResponse::HTTP_FORBIDDEN
                );
            }
            $event = new GetResponseUserEvent($user, $request);
            $dispatcher->dispatch(FOSUserEvents::RESETTING_RESET_REQUEST, $event);
            if (null !== $event->getResponse()) {
                return $event->getResponse();
            }
            if ($user->isPasswordRequestNonExpired($this->container->getParameter('fos_user.resetting.token_ttl'))) {
                return new JsonResponse(
                    $this->get('translator')->trans('resetting.password_already_requested', [], 'FOSUserBundle'),
                    JsonResponse::HTTP_FORBIDDEN
                );
            }
            if (null === $user->getConfirmationToken()) {
                /** @var $tokenGenerator \FOS\UserBundle\Util\TokenGeneratorInterface */
                $tokenGenerator = $this->get('fos_user.util.token_generator');
                $user->setConfirmationToken($tokenGenerator->generateToken());
            }
            /* Dispatch confirm event */
            $event = new GetResponseUserEvent($user, $request);
            $dispatcher->dispatch(FOSUserEvents::RESETTING_SEND_EMAIL_CONFIRM, $event);
            if (null !== $event->getResponse()) {
                return $event->getResponse();
            }
            $this->get('fos_user.mailer')->sendResettingEmailMessage($user);
            $user->setPasswordRequestedAt(new \DateTime());
            $this->get('fos_user.user_manager')->updateUser($user);
            /* Dispatch completed event */
            $event = new GetResponseUserEvent($user, $request);
            $dispatcher->dispatch(FOSUserEvents::RESETTING_SEND_EMAIL_COMPLETED, $event);
            if (null !== $event->getResponse()) {
                return $event->getResponse();
            }
            return new JsonResponse(
                $this->get('translator')->trans(
                    'resetting.check_email',
                    [ '%tokenLifetime%' => floor($this->container->getParameter('fos_user.resetting.token_ttl') / 3600) ],
                    'FOSUserBundle'
                ),
                JsonResponse::HTTP_OK
            );
        }
        /**
         * Reset user password
         * @Annotations\Post("/reset/confirm")
         */
        public function confirmResetAction(Request $request)
        {
            $token = $request->request->get('token', null);
            if (null === $token) {
                return new JsonResponse('You must submit a token.', JsonResponse::HTTP_BAD_REQUEST);
            }
            /** @var $formFactory \FOS\UserBundle\Form\Factory\FactoryInterface */
            $formFactory = $this->get('fos_user.resetting.form.factory');
            /** @var $userManager \FOS\UserBundle\Model\UserManagerInterface */
            $userManager = $this->get('fos_user.user_manager');
            /** @var $dispatcher \Symfony\Component\EventDispatcher\EventDispatcherInterface */
            $dispatcher = $this->get('event_dispatcher');
            $user = $userManager->findUserByConfirmationToken($token);
            if (null === $user) {
                return new JsonResponse(
                // no translation provided for this in \FOS\UserBundle\Controller\ResettingController
                    sprintf('The user with "confirmation token" does not exist for value "%s"', $token),
                    JsonResponse::HTTP_BAD_REQUEST
                );
            }
            $event = new GetResponseUserEvent($user, $request);
            $dispatcher->dispatch(FOSUserEvents::RESETTING_RESET_INITIALIZE, $event);
            if (null !== $event->getResponse()) {
                return $event->getResponse();
            }
            $form = $formFactory->createForm([
                'csrf_protection'    => false,
                'allow_extra_fields' => true,
            ]);
            $form->setData($user);
            $form->submit($request->request->all());
            if (!$form->isValid()) {
                return $form;
            }
            $event = new FormEvent($form, $request);
            $dispatcher->dispatch(FOSUserEvents::RESETTING_RESET_SUCCESS, $event);
            $userManager->updateUser($user);
            if (null === $response = $event->getResponse()) {
                return new JsonResponse(
                    $this->get('translator')->trans('resetting.flash.success', [], 'FOSUserBundle'),
                    JsonResponse::HTTP_OK
                );
            }
            // unsure if this is now needed / will work the same
            $dispatcher->dispatch(FOSUserEvents::RESETTING_RESET_COMPLETED, new FilterUserResponseEvent($user, $request, $response));
            return new JsonResponse(
                $this->get('translator')->trans('resetting.flash.success', [], 'FOSUserBundle'),
                JsonResponse::HTTP_OK
            );
        }
        /**
         * Change user password
         *
         * @ParamConverter("user", class="AppBundle:User")
         *
         * @Annotations\Post("/{user}/change")
         */
        public function changeAction(Request $request, UserInterface $user)
        {
            if ($user !== $this->getUser()) {
                throw new AccessDeniedHttpException();
            }
            /** @var $dispatcher \Symfony\Component\EventDispatcher\EventDispatcherInterface */
            $dispatcher = $this->get('event_dispatcher');
            $event = new GetResponseUserEvent($user, $request);
            $dispatcher->dispatch(FOSUserEvents::CHANGE_PASSWORD_INITIALIZE, $event);
            if (null !== $event->getResponse()) {
                return $event->getResponse();
            }
            /** @var $formFactory \FOS\UserBundle\Form\Factory\FactoryInterface */
            $formFactory = $this->get('fos_user.change_password.form.factory');
            $form = $formFactory->createForm([
                'csrf_protection'    => false
            ]);
            $form->setData($user);
            $form->submit($request->request->all());
            if ( ! $form->isValid()) {
                return $form;
            }
            /** @var $userManager \FOS\UserBundle\Model\UserManagerInterface */
            $userManager = $this->get('fos_user.user_manager');
            $event = new FormEvent($form, $request);
            $dispatcher->dispatch(FOSUserEvents::CHANGE_PASSWORD_SUCCESS, $event);
            $userManager->updateUser($user);
            if (null === $response = $event->getResponse()) {
                return new JsonResponse(
                    $this->get('translator')->trans('change_password.flash.success', [], 'FOSUserBundle'),
                    JsonResponse::HTTP_OK
                );
            }
            $dispatcher->dispatch(FOSUserEvents::CHANGE_PASSWORD_COMPLETED, new FilterUserResponseEvent($user, $request, $response));
            return new JsonResponse(
                $this->get('translator')->trans('change_password.flash.success', [], 'FOSUserBundle'),
                JsonResponse::HTTP_OK
            );
        }
    }

The longin form is not using the same Bundle. Just is case this could help, heres the file: src/AppBundle/Security/LoginFormAuthenticator.php

    <?php
    
    namespace AppBundle\Security;
    
    use AppBundle\Form\LoginForm;
    use Doctrine\ORM\EntityManager;
    use Symfony\Component\Form\FormFactoryInterface;
    use Symfony\Component\HttpFoundation\Request;
    use Symfony\Component\Routing\RouterInterface;
    use Symfony\Component\Security\Core\Security;
    use Symfony\Component\Security\Core\Encoder\UserPasswordEncoder;
    use Symfony\Component\Security\Core\User\UserInterface;
    use Symfony\Component\Security\Core\User\UserProviderInterface;
    use Symfony\Component\Security\Guard\Authenticator\AbstractFormLoginAuthenticator;
    
    class LoginFormAuthenticator extends AbstractFormLoginAuthenticator
    {
        private $formFactory;
        private $em;
        private $router;
        private $passwordEncoder;
    
        public function __construct(FormFactoryInterface $formFactory, EntityManager $em, RouterInterface $router, UserPasswordEncoder $passwordEncoder)
        {
            $this->formFactory = $formFactory;
            $this->em = $em;
            $this->router = $router;
            $this->passwordEncoder = $passwordEncoder;
        }
    
        public function getCredentials(Request $request)
        {
            $isLoginSubmit = $request->getPathInfo() == '/login' && $request->isMethod('POST');
            if (!$isLoginSubmit) {
                // skip authentication
                return;
            }
    
            $form = $this->formFactory->create(LoginForm::class);
            $form->handleRequest($request);
    
            $data = $form->getData();
            $request->getSession()->set(
                Security::LAST_USERNAME,
                $data['_username']
            );
    
            return $data;
        }
    
        public function getUser($credentials, UserProviderInterface $userProvider)
        {
            $username = $credentials['_username'];
    
            return $this->em->getRepository('AppBundle:User')
                ->findOneBy(['email' => $username]);
        }
    
        public function checkCredentials($credentials, UserInterface $user)
        {
            $password = $credentials['_password'];
    
            if ($this->passwordEncoder->isPasswordValid($user, $password)) {
                return true;
            }
    
            return false;
        }
    
        protected function getLoginUrl()
        {
            return $this->router->generate('security_login');
        }
    
        protected function getDefaultSuccessRedirectUrl()
        {
            return $this->router->generate('app-dashboard');
        }
    }

As for the view, it's pretty straight forward. Theres a jQuery script that toggle between the login form and the lost password.

    {% extends '::base.html.twig' %}
    
    {# -- PAGE TITLE --  #}
    {% block title %}
        {{ title }}
    {% endblock %}
    
    {# -- PAGE CONTENT --  #}
    {% block body %}
    
        <div class="account-pages"></div>
        <div class="clearfix"></div>
        <div class="wrapper-page">
    
            <div class="account-bg">
                <div class="card-box m-b-0">
                    <div class="text-xs-center">
                        <a href="/" class="logo">
                            <img src="{{ asset('assets/images/app/login-logo.png') }}" alt="SSTenligne">
                        </a>
                    </div>
    
                    <div class="m-t-10 p-20 login_form">
    
                        {{ form_start(form, {'autocomplete': 'off'}) }}
                            {{ form_row(form._username) }}
                            {{ form_row(form._password) }}
    
                            <div class="form-group text-center row m-t-30">
                                <div class="col-xs-12">
                                    <button class="btn btn-primary btn-block waves-effect waves-light" type="submit">{{ 'Login'|trans }}</button>
                                </div>
                            </div>
                        {{ form_end(form) }}
                        
                        <a class="mdp_resset" href="#">Mot de passe perdu?</a>
    
                    </div>
                    
                    <div class="m-t-10 p-20 password_resset">
    
                        {{ form_start(form2, {'autocomplete': 'off'}) }}
                            {{ form_row(form2._username_resset) }}
    
                            <div class="form-group text-center row m-t-30">
                                <div class="col-xs-12">
                                    <button class="btnResset btn btn-primary btn-block waves-effect waves-light" type="submit">{{ 'Récupération'|trans }}</button>
                                </div>
                            </div>
                        {{ form_end(form2) }}
                        
                        <a class="mdp_login" href="#">Retour</a>
    
                    </div>
    
                    <div class="clearfix"></div>
                </div>
            </div>
            
    
        </div>
        
    
    {% endblock %}
    
    
    {# -- SPECIFIC SCRIPTS --  #}
    {% block scripts %}
    
        <script>
            {% if error %}
                toastr.error('{{ error.messageKey|trans(error.messageData, 'security') }}');
            {% endif %}
            
            $(".password_resset form").submit(function(e){
                e.preventDefault();
    
                $.ajax({
                    type: "POST",
                    dataType: "JSON",
                    url: "password/reset/request",
                    data:{
                        email:$("#resset_form__username_resset").val()
                    },
                    error: function (jql, code, returnMsgError) {
                        alert('Une erreur est survenue');
                    },
                    success: function ($data) {
                        alert('It\'s posted!');
                    }
                });
            });
    
        </script>
    {% endblock %}

The request is posted to password/reset/request and thats where I get error message:

{"code":500,"message":"Unrecognized field: emailCanonical"}

I am really new to Symfony and don't know where to start to debug this problem. Any help would be geatly appreciated. If you need me to show more code to help me find a solution le me know and I will edit.

**Comment by tarjei** [comment]
Hi, I would guess you either haven't extended the base FOS User object in your model or you have a mismatch between form handling and JSON serialization.
