### ISSUE TITLE
FOSUserBundle "use_flash_notifications" config option has no effect

### ISSUE THREAD

**Issue by Preclowski** [FriendsOfSymfony/FOSUserBundle#2898]
**Symfony FOSUserBundle versions**:
2.1.2

**Description of the problem including expected versus actual behavior**:
When I set "use_flash_notifications" to false I expect that session service should not be required. It is.

**Steps to reproduce**:
 1. set "use_flash_notifications" to false
 2. disable "session" service
 3. see the error message

**Provide logs (if relevant)**:

```php
In CheckForSessionPass.php line 37:
                                                                                                                                                     
  FOSUserBundle requires the "session" service to be available. Uncomment the "session" section in "config/packages/framework.yaml" to activate it.  
```

**Comment by nmeirik** [comment]
I think you have to set both these two parameters in order for the session service not to be required:

```
fos_user:
    use_flash_notifications: false
    registration: false
```

**Comment by stof** [comment]
Indeed. The registration feature also relies on the session.
