### ISSUE TITLE
A tree builder without a root node is deprecated since Symfony 4.2 

### ISSUE THREAD

**Issue by klodoma** [FriendsOfSymfony/FOSUserBundle#2901]
Hi all, 

![Screenshot_325](https://user-images.githubusercontent.com/944350/55167356-1ced9f80-5171-11e9-9eb8-d05f5276f2e0.png)

Any idea when will this be released? I see it's been implemented since a while, but not sure how your release process is running. 

https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2882

https://github.com/FriendsOfSymfony/FOSUserBundle/blame/master/DependencyInjection/Configuration.php

Thanks in Advance!

**Comment by daemonfire300** [comment]
+1 on this. And I would glad to offer my help if there is anything that can be aided with in the process.

**Comment by ankita-kellton** [comment]
+1 for this. I have upgraded symfony to 4.3 version and getting the same deprecation warning.  A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0.

**Comment by shakaran** [comment]
This seems [fixed in dev-master you can see the commit](https://github.com/FriendsOfSymfony/FOSUserBundle/commit/c10ef5981f2f5c375ae3c2bd7eca4f9bfe919b5b)

This issue should be closed as far a new minor would be released with the change

@XWB @goetas could you release a new minor with this change for people using Symfony 4.3? Thanks

**Comment by nmeirik** [comment]
Please consider relasing this as Symfony 5 is fast approaching.

**Comment by emfox** [comment]
+1
just get here and a new tag release please.

**Comment by skiner68** [comment]
+1 on this

**Comment by eerison** [comment]
+1 on this

**Comment by netandreus** [comment]
+1, цhen can we see 2.1.3 version with this fix?

**Comment by Herz3h** [comment]
Why is it NOT released if it's implemented in code long ago ??

**Comment by stof** [comment]
Released in 2.2
