### ISSUE TITLE
Automatic logout after some time of inactivity

### ISSUE THREAD

**Issue by Joozty** [FriendsOfSymfony/FOSUserBundle#2903]
Hi, I would like to ask if is in FOSUserBundle implemented some mechanism of automatic logout after inactivity. If so, how to adjust the time when a user should be logout and what's the default time constant?

Thanks.

**Comment by Tomsgu** [comment]
1) This has nothing to do with FOSUserBundle. (See [the first paragraph](https://github.com/FriendsOfSymfony/FOSUserBundle#fosuserbundle))
2) Please ask on stackoverflow or use search engines. There are plenty of answers on this question.
