### ISSUE TITLE
No route found for "GET /login/"

### ISSUE THREAD

**Issue by GeekGuste** [FriendsOfSymfony/FOSUserBundle#2918]
Hi
I installed and configured fosUserBundle 2.1 on symfony. I access the fosUserBundle routes in developer mode without any problem. But in production mode the roads are working except the / login when I try to connect (on the road / login) I have the following error: No route found for "GET / login /". I have this error in 2 projects and since 2 weeks. I need help to solve this problem.

I am  using symfony 3.4.15

**Comment by devtronic** [comment]
Did you add the routing? https://symfony.com/doc/current/bundles/FOSUserBundle/index.html#step-6-import-fosuserbundle-routing-files

**Comment by GeekGuste** [comment]
Yes I have added it. And fosuser other routes(/register, /profile, /logout...) are working in both the production and dev mode. Only the /login path is returning a Not Found Error in production mode but  works in dev mode.

**Comment by devtronic** [comment]
did you cleared the cache in prod?

**Comment by GeekGuste** [comment]
Yes many times.

**Comment by katendemich** [comment]
How do you clear the cache in prod?
