### ISSUE TITLE
Roles in a new table

### ISSUE THREAD

**Issue by Gonzalo1987** [FriendsOfSymfony/FOSUserBundle#2921]
Why the field 'roles' is not store as a new table?

When I started to use fos_user, I realized that the table roles was difficult to use, hard to find with doctrine, and not very easy to modify or view from the db.

I think of the ROLE as a new Entity, with the relationship ManyToMany with User and Group. 
User have Roles[] and Group have Roles[]

Have passed about 4 or 5 years, and I can see that there are still people with problems to make a simple query like get the users that have an especific role #258. And the 'best' solution is make a like query (that is very insufficient, because you can have 2 roles that share the same string (ROLE_USER, ROLE_USER_MANAGER) -> the query like '%ROLE_USER%' get both.

You could make a request (aprox, I've not checked, but as example...)
```
$qb->createQueryBuilder('u')
      ->leftJoin('u.groups', 'g')
      ->leftJoin('u.roles', 'ur')
      ->leftJoin('g.roles', 'gr')
      ->andWhere('gr.name=:role or ur.name=:role')
      ->setParameter('role', 'ROLE_USER');
```

I can't understand (because I'm not inside the project) two facts.
First. Why the roles is string encoded in the DB. It's probably the best, but only to learn... why? (If I need my own project with users and roles, Is it better make a field with the roles?
Second. If a field with roles wasn't the best option, it's so hard to change? As I've said I'm not inside the project and I can't imagine the cost, or the effects of the change.

Could someone that have a little more knowledge than me help me with my doubts?

**Comment by stof** [comment]
Changing the storage of roles is a BC break, as it changes the database structure. And it is one for which projects have to deal with migrating from the old storage to the new one (we cannot provide a BC layer there, and we cannot implement the DB migration ourselves).

Thus, this kind of storage has a performance cost, as we will always need to load roles during the authentication.
And finally, defining roles as an entity goes against the Symfony expectation (`getRoles` must return an array of strings).
