### ISSUE TITLE
New release version

### ISSUE THREAD

**Issue by core23** [FriendsOfSymfony/FOSUserBundle#2927]
I was wondering, why the last version was tagged 1,5 years ago and the [milestone list](https://github.com/FriendsOfSymfony/FOSUserBundle/milestone/4) is empty.

Can you please tag a new release to remove some deprecations or do you need help somewhere? Using a non-stable dev version is a little risky for everyone.

**Comment by SebastienTouze** [comment]
Hi, 
maybe you should check #2917 and #2874

**Comment by core23** [comment]
Closing this in favor of the other issues
