### ISSUE TITLE
symfony 5.0

### ISSUE THREAD

**Issue by gulaandrij** [FriendsOfSymfony/FOSUserBundle#2943]
Do you plan to support symfony 5?

**Comment by TheLoneUs** [comment]
Most likely it is no longer maintained:
https://github.com/FriendsOfSymfony/FOSUserBundle/issues/2874

Also in my case I ended up copying the bundle and moving it to my own project and removing the deprecations myself.

**Comment by jethrohicks** [comment]
I ended up forking it also. If anyone needs a diff of the changes:  https://github.com/FriendsOfSymfony/FOSUserBundle/compare/master...jethrohicks:bugfix

**Comment by gulaandrij** [comment]
@jethrohicks maybe you could create PR to this repo?

**Comment by Caedendi** [comment]
@jethrohicks im interested in this as well

**Comment by argoitzT** [comment]
Hi @jethrohicks, I want to migrate to Symfony 5 and im insterested in how to install your fork into my project too. Can anyone help us?
Thank You

**Comment by 01e9** [comment]
_I started using [this solution](https://medium.com/@ger86/10-packages-you-should-know-if-you-are-going-to-work-with-symfony-497b116be428) with MakerBundle._

**Comment by rumours86** [comment]
@Caedendi @argoitzT 
add to composer.json

```
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/jethrohicks/FOSUserBundle.git"
        }
    ],
```

and execute command
`composer require friendsofsymfony/user-bundle "dev-bugfix"`

**Comment by argoitzT** [comment]
Wow @rumours86 .
This works for me!! I plan to use MakerBundle but I have no time to make changes for now. 
Then this solution saves me a lot of time.
Thank you very much

**Comment by Caedendi** [comment]
As FOSUserBundle is no longer maintained, it is not recommended to use it in future projects and Symfony 5. If you want more arguments on why not to use it, take a look at this:
[](https://jolicode.github.io/fosuserbundle-conf/#/)

Of course you need fast and easy user validation and authentication, but there are other options.

Your safest bet is to implement user authentication on your own using Symfony's documentation on Security:
[](https://symfony.com/doc/current/security.html)

**Comment by nickicool** [comment]
In my project I use Twig v.3.0.4. Than I try install ` composer require friendsofsymfony/user-bundle "dev-bugfix"` get error:

`
Problem 1
    - friendsofsymfony/user-bundle dev-bugfix requires twig/twig ^1.28 || ^2.0 -> satisfiable by twig/twig[1.x-dev, 2.x-dev, v1.28.0, v1.28.1, v1.28.2, v
1.29.0, v1.30.0, v1.31.0, v1.32.0, v1.33.0, v1.33.1, v1.33.2, v1.34.0, v1.34.1, v1.34.2, v1.34.3, v1.34.4, v1.35.0, v1.35.1, v1.35.2, v1.35.3, v1.35.4, v1.36.0, v1.37.0, v1.37.1, v1.38.0, v1.38.1, v1.38.2, v1.38.3, v1.38.4, v1.39.0, v1.39.1, v1.40.0, v1.40.1, v1.41.0, v1.42.0, v1.42.1, v1.42.2, v1.42.3, v1.42.4, v1.42.5, v1.43.0, v2.0.0, v2.1.0, v2.10.0, v2.11.0, v2.11.1, v2.11.2, v2.11.3, v2.12.0, v2.12.1, v2.12.2, v2.12.3, v2.12.4, v2.12.5, v2.13.0, v2.2.0, v2.3.0, v2.3.1, v2.3.2, v2.4.0, v2.4.1, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.5.0, v2.6.0, v2.6.1, v2.6.2, v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.8.0, v2.8.1, v2.9.0] but these conflict with your requirements or minimum-stability.
    - friendsofsymfony/user-bundle dev-bugfix requires twig/twig ^1.28 || ^2.0 -> satisfiable by twig/twig[1.x-dev, 2.x-dev, v1.28.0, v1.28.1, v1.28.2, v1.29.0, v1.30.0, v1.31.0, v1.32.0, v1.33.0, v1.33.1, v1.33.2, v1.34.0, v1.34.1, v1.34.2, v1.34.3, v1.34.4, v1.35.0, v1.35.1, v1.35.2, v1.35.3, v1.35.4, v1.36.0, v1.37.0, v1.37.1, v1.38.0, v1.38.1, v1.38.2, v1.38.3, v1.38.4, v1.39.0, v1.39.1, v1.40.0, v1.40.1, v1.41.0, v1.42.0, v1.42.1, v1.42.2, v1.42.3, v1.42.4, v1.42.5, v1.43.0, v2.0.0, v2.1.0, v2.10.0, v2.11.0, v2.11.1, v2.11.2, v2.11.3, v2.12.0, v2.12.1, v2.12.2, v2.12.3, v2.12.4, v2.12.5, v2.13.0, v2.2.0, v2.3.0, v2.3.1, v2.3.2, v2.4.0, v2.4.1, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.5.0, v2.6.0, v2.6.1, v2.6.2, v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.8.0, v2.8.1, v2.9.0] but these conflict with your requirements or minimum-stability.
    - friendsofsymfony/user-bundle dev-bugfix requires twig/twig ^1.28 || ^2.0 -> satisfiable by twig/twig[1.x-dev, 2.x-dev, v1.28.0, v1.28.1, v1.28.2, v1.29.0, v1.30.0, v1.31.0, v1.32.0, v1.33.0, v1.33.1, v1.33.2, v1.34.0, v1.34.1, v1.34.2, v1.34.3, v1.34.4, v1.35.0, v1.35.1, v1.35.2, v1.35.3, v1.35.4, v1.36.0, v1.37.0, v1.37.1, v1.38.0, v1.38.1, v1.38.2, v1.38.3, v1.38.4, v1.39.0, v1.39.1, v1.40.0, v1.40.1, v1.41.0, v1.42.0, v1.42.1, v1.42.2, v1.42.3, v1.42.4, v1.42.5, v1.43.0, v2.0.0, v2.1.0, v2.10.0, v2.11.0, v2.11.1, v2.11.2, v2.11.3, v2.12.0, v2.12.1, v2.12.2, v2.12.3, v2.12.4, v2.12.5, v2.13.0, v2.2.0, v2.3.0, v2.3.1, v2.3.2, v2.4.0, v2.4.1, v2.4.2, v2.4.3, v2.4.4, v2.4.5, v2.4.6, v2.4.7, v2.4.8, v2.5.0, v2.6.0, v2.6.1, v2.6.2, v2.7.0, v2.7.1, v2.7.2, v2.7.3, v2.7.4, v2.8.0, v2.8.1, v2.9.0] but these conflict with your requirements or minimum-stability.
    - Installation request for friendsofsymfony/user-bundle dev-bugfix -> satisfiable by friendsofsymfony/user-bundle[dev-bugfix].
Installation failed, reverting ./composer.json to its original content.`

it is possible to fix? I'm not pro programmer... Is it generally compatible with twig 3?

**Comment by haivala** [comment]
Has someone written migration instructions from this bundle to the recommended way of using MakerBundle?

**Comment by matteodem** [comment]
What is the latest supported version? I think it would be nice to write that into the README file so people don't have to search for this issue.

**Comment by nickicool** [comment]
> What is the latest supported version? I think it would be nice to write that into the README file so people don't have to search for this issue.

On 5.1.10 still work, but on 5.2 it doesn't work anymore.

**Comment by JackKFouani** [comment]
is it supported for v5.3 ? i am wanna upgrade from symfony 3.1 to 5.3

**Comment by NoelLH** [comment]
> Has someone written migration instructions from this bundle to the recommended way of using MakerBundle?

Hey @haivala – not exactly as I think the steps will vary a fair bit from app to app, but I wrote [a blog here](https://noellh.com/blog/escape-from-fosuserbundle/) with some of what I did and highlighting notable pain points. In my case there were steps where the path of least resistance was to copy the FOS approach to minimise the (still big) refactor, and some where I used the Maker bundle for reference but combined pieces from both that output and the FOS bundle.

I'm afraid the actual work was done some months ago so I won't necessarily be able to fill in any gaps I've left, but feel free to ask if the post raises specific questions – I will attempt to dredge my memory and improve the blog if I can!

**Comment by haivala** [comment]
@NoelLH I have done the migration few times and it is pretty easy to do. I used the symfony security documentation to make everything from the ground up, inserted my old users to the database and made sure everything is in sync. After that I implemented console command to manage the users. done.

**Comment by JackKFouani** [comment]
@haivala , do you have contact information you can share with me ? i need assistant with upgrading i am stuck

**Comment by stof** [comment]
Done in #3020

**Comment by joan16v** [comment]
Any news on this?

**Comment by nickicool** [comment]
Now bundle work fine on 5.4.0, but...

> The package only receives minimal maintenance to allow existing projects to upgrade. Existing projects are expected to plan a migration away from this bundle.
> **New projects should not use this bundle.**

**Comment by crmpicco** [comment]
> Has someone written migration instructions from this bundle to the recommended way of using MakerBundle?

This would be very useful.

**Comment by crmpicco** [comment]
> I ended up forking it also. If anyone needs a diff of the changes: [master...jethrohicks:bugfix](https://github.com/FriendsOfSymfony/FOSUserBundle/compare/master...jethrohicks:bugfix)

Does this work with Symfony 5?

**Comment by nickicool** [comment]
With 5.4 this still work, but strongly not recomend this doing.

Good tutorial by new security system (witch introduced in SF 5.3) you can found here https://symfonycasts.com/screencast/symfony-security
