### ISSUE TITLE
App\Entity\User not recognized

### ISSUE THREAD

**Issue by mchojrin** [FriendsOfSymfony/FOSUserBundle#2946]
Hi:

  I'm in the process of migrating an app built using Sf 3.1.7 into 4.4. I think I'm almost done but there's this issue I can't solve. Here's what I'm seeing in the log files:

`[2019-12-03 21:09:00] security.ERROR: Authentication request failed. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AuthenticationServiceException(code: 0): The class 'App\\Entity\\User' was not found in the chain configured namespaces FOS\\UserBundle\\Model at /home/vagrant/followapp/vendor/symfony/security-core/Authentication/Provider/DaoAuthenticationProvider.php:92, Doctrine\\Common\\Persistence\\Mapping\\MappingException(code: 0): The class 'App\\Entity\\User' was not found in the chain configured namespaces FOS\\UserBundle\\Model at /home/vagrant/followapp/vendor/doctrine/persistence/lib/Doctrine/Common/Persistence/Mapping/MappingException.php:22)"} []`

  What does "chain configured namespaces" mean?

  Thanks

**Comment by stof** [comment]
Closing this as it is not an issue about FOSUserBundle, but about configuring DoctrineBundle to support entities in a bundle-less app structure.
