### ISSUE TITLE
version 2.2, version 3 - deprecation of Groups

### ISSUE THREAD

**Issue by ovgray** [FriendsOfSymfony/FOSUserBundle#2968]
I am glad to see that the maintainers are planning a version 3.0 [https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2947].

I am puzzled why Groups will be deprecated [https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2953]. Could someone please explain this?

**Comment by stof** [comment]
Well, groups are a feature inherited from the symfony 1 sfUserPlugin (not sure that this is the exact name of the plugin, but anyway). The role hierarchy and custom voters are a much better way to manage permissions that using groups to assign roles to users.
And projects for which this solution is the right one can perfectly implement this on their own (and in a better way, as they will be able to fit exactly their project needs).

**Comment by eerison** [comment]
When version 2.2 going to be released?
