### ISSUE TITLE
Wrong implementaion of User::getRoles()

### ISSUE THREAD

**Issue by pvcnt** [FriendsOfSymfony/FOSUserBundle#297]
If we follow the phpDoc of the UserInterface getRoles() method, it must return an array of Role and not an array of strings as the FOSUserBuncle does. The Role class is quite useless as it basically just holds a string as property, but it's used internally and returning strings can lead to edge cases.

I think the User methods related to roles must accept both string en Role instance, just as the Security component often does. Additionally User::getRoles() and Group::getRoles() methods should be modified to return array of Role instance to be coherent with the security API.

**Comment by Lewik** [comment]
"This implementation has been written by the developer of the security component so we can trust him it works :)"

Omg
Annotations contains example of code with array of strings, @return contains Role[]. Code that used this method may fail if there are object with no __toString or it have if(is_string).
