### ISSUE TITLE
Symfony\Component\EventDispatcher\Event deprecation since Symfony 4.3

### ISSUE THREAD

**Issue by wlasnapl** [FriendsOfSymfony/FOSUserBundle#2971]
**Symfony FOSUserBundle versions**: 2.2.0

**Description of the problem including expected versus actual behavior**:
On Symfony >4.3 there is deprecation:

>  The "FOS\UserBundle\Event\UserEvent" class extends "Symfony\Component\EventDispatcher\Event" that is deprecated since Symfony 4.3, use "Symfony\Contracts\EventDispatcher\Event" instead.

This relates also to other events.

**Steps to reproduce**:
 1. install Symfony 4.4
 2. check files in Events which extends Event. Check deprecation in Event file.

**Comment by stof** [comment]
Fixed in #3015 for the upcoming 3.0 version
