### ISSUE TITLE
FOSUser always trigger deprecation notice

### ISSUE THREAD

**Issue by dunglas** [FriendsOfSymfony/FOSUserBundle#2978]
**Symfony FOSUserBundle versions**: 2.2-dev
**Description of the problem including expected versus actual behavior**:

In this PR, groups (both the interface and the base class) have been deprecated: https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2953
However, the `FOS\UserBundle\Model\User` class, which isn't deprecated, still depends of the deprecated interface. It means that any class extending `User` (as recommended in the documentation) currently triggers a deprecation notice.
For instance, it breaks the API Platform CI: https://github.com/api-platform/core/runs/602079822

**Steps to reproduce**:

 1. Install FOSUserBundle

**Provide logs (if relevant)**:

Remaining direct deprecation notices (1)

  1x: Using Groups is deprecated since version 2.2 and will be removed in 3.0.
    1x in BooleanFilterTest::setUp from ApiPlatform\Core\Tests\Bridge\Doctrine\Orm\Filter

/cc @XWB

**Comment by Allislove** [comment]
> 1x: Using Groups is deprecated since version 2.2 and will be removed in 3.0.

How to solve this Log?? I'm getting this Deprecation logs now.
