### ISSUE TITLE
Will this bundle be upgraded to support Doctrine ORM 2.8?

### ISSUE THREAD

**Issue by crmpicco** [FriendsOfSymfony/FOSUserBundle#2997]
**Symfony FOSUserBundle versions**:

dev-master

**Description of the problem including expected versus actual behavior**:
Can anyone advise if there are any plans to upgrade this bundle to support `doctrine/orm` 2.8? Currently I need to lock my versions to:

```
doctrine/common => 2.13.3
doctrine/orm => 2.7.5
```

I'd rather not get stuck on old versions and obviously for log noise i'd rather get rid of the deprecation notices.

**Steps to reproduce**:
`User Deprecated: The "Doctrine\Common\Inflector\Inflector::classify" method is deprecated and will be dropped in doctrine/inflector 2.0. Please update to the new Inflector API.`

**Comment by stof** [comment]
Compatibility with doctrine/persistence 2.x has been released in the 2.2.0 version of the bundle.
