### ISSUE TITLE
composer require not working

### ISSUE THREAD

**Issue by vld666** [FriendsOfSymfony/FOSUserBundle#3027]
Hi!

$ composer require friendsofsymfony/user-bundle "~2.0"

./composer.json has been updated
Running composer update friendsofsymfony/user-bundle
Loading composer repositories with package information
Restricting packages listed in "symfony/symfony" to "5.3.*"
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - friendsofsymfony/user-bundle[v2.0.0, ..., v2.0.2] require symfony/form ^2.7 || ^3.0 -> found symfony/form[v2.7.0, ..., v2.8.52, v3.0.0, ..., v3.4.47] but it conflicts with your root composer.json require (5.3.*).
    - friendsofsymfony/user-bundle[v2.1.0, ..., v2.1.2] require symfony/form ^2.8 || ^3.0 || ^4.0 -> found symfony/form[v2.8.0, ..., v2.8.52, v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.33] but it conflicts with your root composer.json require (5.3.*).
    - friendsofsymfony/user-bundle[v2.2.0, ..., v2.2.2] require symfony/config ^4.4 -> found symfony/config[v4.4.0, ..., v4.4.33] but it conflicts with your root composer.json require (5.3.*).
    - Root composer.json requires friendsofsymfony/user-bundle ~2.0 -> satisfiable by friendsofsymfony/user-bundle[v2.0.0, ..., v2.2.2].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by stof** [comment]
For Symfony 5, you need to use the 3.x-dev version of the bundle right now (I hope releasing it stable soon, but I cannot make any promise about when this will happen, as I'm working on open-source on my free time)

**Comment by vld666** [comment]
it seems that this worked
`$ composer require friendsofsymfony/user-bundle dev-master`

thanks!
