### ISSUE TITLE
Release version 3.0

### ISSUE THREAD

**Issue by ajgarlag** [FriendsOfSymfony/FOSUserBundle#3029]
**Symfony FOSUserBundle versions**: 3.x-dev

@stof Now that Symfony 5.4 have been finally released, do you plan to tag and release `friendsofsymfony/user-bundle:3.0.0`? Can I help in any way to reach the release milestone?

Thanks for your work here!

**Comment by stof** [comment]
#3032 proves that the work is not done yet (our CI was not actually using Symfony 5).. but yes, that's on my todo list.

**Comment by abdurrahmanriyad** [comment]
@stof Any plan to support it with Symfony 6 soon?

**Comment by biji** [comment]
@abdurrahmanriyad even symfony 5.4 is not yet fully supported. this bundle will probably increase the adoption of symfony 5, yeah I'm stuck in 4.4

**Comment by stopfstedt** [comment]
> @abdurrahmanriyad even symfony 5.4 is not yet fully supported. this bundle will probably increase the adoption of symfony 5, yeah I'm stuck in 4.4

anything that you could use help with in particular to get a SF5 release out the door?

**Comment by biji** [comment]
my project is using 4.4 and fos user bundle (production state)
most depreciation warning to sf5 already settled 
except fos user bundle

**Comment by NajibBoun** [comment]
Any update for Symfony 5 ?

**Comment by stof** [comment]
In the last few weeks, I worked on fixing compatibility with Symfony 5 and fixing deprecations reported by Symfony 5.4. My goal is to release FOSUserBundle 3.0 next week.
If you can already try using the master branch (both in 4.4 and 5.x), it might catch mistakes before the release.

**Comment by stof** [comment]
Of course, if you try the master branch which is 3.0-dev, read the changelog file as there are some BC breaks.
