### ISSUE TITLE
FlashListener fix not included in the release

### ISSUE THREAD

**Issue by ErdemUyanik** [FriendsOfSymfony/FOSUserBundle#3034]
**Symfony FOSUserBundle versions**: 2.2.4

**Description of the problem including expected versus actual behavior**:

FlashListener implementing the old, deprecated TranslatorInterface

**Steps to reproduce**:
 1. install FOSUserBundle 2.2.4
 2. check the file

**Additional information**:
The problem seems to be fixed in the master branch already but for some reason was not included in a release(?). @stof Could you maybe release a 2.2.5 to include the fix?

**Comment by stof** [comment]
The fix is available in 3.0
