### ISSUE TITLE
please consider supporting PHP 7.2.5, as that's the SF 5.x requirement

### ISSUE THREAD

**Issue by derpue** [FriendsOfSymfony/FOSUserBundle#3043]
Symfony 5.x has as minimum requirement PHP version 7.2.5. 
As this package status is "to allow existing projects to upgrade" please consider supporting php 7.2.5 for FOSUserBundle 3.0, as that is the only Version supporting SF 5.
I'm aware that PHP 7.2.x is EOL, but sadly more often than not there are servers out there, outside of our control.

Thank you for your consideration.

**Comment by stof** [comment]
I'm closing this as the master branch is now targeting Symfony 6.4+ and PHP 8.1
