### ISSUE TITLE
fos_user.listener.email_confirmation depends on non-existent service "session"

### ISSUE THREAD

**Issue by phucwan91** [FriendsOfSymfony/FOSUserBundle#3049]
I got this error message while I'm upgrading to symfony 6.2

`The service "fos_user.listener.email_confirmation" has a dependency on a non-existent service "session"`

please update it !

**Comment by cbeyer** [comment]
Same error for me :/

**Comment by phucwan91** [comment]
it can be solved simply in the meantime:

```
session:
    class: Symfony\Component\HttpFoundation\Session\SessionInterface
```
