### ISSUE TITLE
Can't use incorrect type mixed for collection in FOS\UserBundle\Model\User:id

### ISSUE THREAD

**Issue by aurelienpiquet** [FriendsOfSymfony/FOSUserBundle#3054]
Hello, i'm having a weird issue with this bundle: 

"Can't use incorrect type mixed for collection in FOS\UserBundle\Model\User:id"

php8.2, symfony 5.4.20, friendsofsymfony/user-bundle:dev-master. 

I have to change the type of the id from the vendor to string to remove this error.

I didn't have the problem with php8.1

**Comment by stof** [comment]
Where are you getting this error ?

**Comment by aurelienpiquet** [comment]
Have the issue in /doc from NelnioApiDoc, and anytime i serialize a user

**Comment by aurelienpiquet** [comment]
Hello, an update from jms_serializer fixed the issue.
