### ISSUE TITLE
Symfony 6 LastLoginListener:: error

### ISSUE THREAD

**Issue by gekomod** [FriendsOfSymfony/FOSUserBundle#3070]
php 8.3
Symfony 6.4
sonata-project/admin-bundle              4.30.2  The missing Symfony Admin Generator

**Symfony FOSUserBundle versions**:

friendsofsymfony/user-bundle             v3.2.1  Symfony FOSUserBundle

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide logs (if relevant)**:

**Describe the feature**:
FOS\UserBundle\EventListener\LastLoginListener::__construct(): Argument #1 ($userManager) must be of type FOS\UserBundle\Model\UserManagerInterface, Sonata\UserBundle\Entity\UserManager given, called in /home/vwcoding/public_html/var/cache/dev/Container2p6M38q/getFosUser_Security_InteractiveLoginListenerService.php on line 23

**Comment by stof** [comment]
this seems to be an issue related to SonataUserBundle.

FOSUserBundle never injects a `Sonata\UserBundle\Entity\UserManager` in its listener.
