### ISSUE TITLE
Brute force protection.

### ISSUE THREAD

**Issue by xaav** [FriendsOfSymfony/FOSUserBundle#324]
This may be already implemented, I just couldn't find it anywhere in the docs.

**Comment by RowanReid** [comment]
For Brute Force Protection, this bundle looks good: https://github.com/codeconsortium/CCDNUserSecurityBundle

**Comment by safwan74** [comment]
This is a good bundle and it is needed.

**Comment by JHGitty** [comment]
I think we should add this feature to FOSUserBundle directly because it is a really important security feature.

**Comment by stof** [comment]
> I think we should add this feature to FOSUserBundle directly because it is a really important security feature.

I don't think so, because FOSUserBundle is not responsible for the authentication part (SecurityBundle is), which means that this feature would be totally independent of the current features of the bundle (and would as easily work for any user provider rather than only the FOSUserBundle one)

**Comment by JHGitty** [comment]
Okay, agree! :+1:

**Comment by stof** [comment]
I'm closing this issue as I won't implement this in FOSUserBundle. People wanting such feature should build it in a separate bundle (or take over the maintenance of the bundle listed above, which is not maintained anymore)
