### ISSUE TITLE
How to change names of columns?

### ISSUE THREAD

**Issue by ondrowan** [FriendsOfSymfony/FOSUserBundle#338]
I'm working on a legacy database and would like to use this extension for handling users. But I don't see any way to change names of table columns (via annotations) in User class (and I cannot rename columns in database). I cannot override them in child User class as Doctrine starts to complain then:

```
Property "email" in "Acme\MyBundle\Entity\User" was already declared, but it must be declared only once
```

To clarify more. I'd like to do something similar in my child User class:

``` php
/**
 * @var string $email
 *
 * @ORM\Column(name="c_email", type="string", length=64, nullable=false)
 */
protected $email;
```

Is it even possible at the moment?

**Comment by sampart** [comment]
For anyone who finds this via Google like me, you can use Doctrine to change column attributes now.  See http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/tutorials/override-field-association-mappings-in-subclasses.html / https://stackoverflow.com/a/20899258/328817.
