### ISSUE TITLE
Can't create User after adding groups support

### ISSUE THREAD

**Issue by CBeloch** [FriendsOfSymfony/FOSUserBundle#347]
Hi,
I have enabled Usergroups in my setup and now I get an error message when I call fos:user:create from the command line:

```
[ErrorException]                                                                                                                                                              
  Warning: in_array() expects parameter 2 to be array, null given in [...]/Symfony/vendor/bundles/FOS/UserBundle/Model/User.php line 160  
```

It asks for username, email and password, and this message comes after that.
Some idea why?

**Comment by polnetwork** [comment]
I had the same issue, here I add the way to call the parent to help future users.

public function __construct()
{
    parent::__construct ();
}
