### ISSUE TITLE
Promote command : "Unrecognized field: usernameCanonical"

### ISSUE THREAD

**Issue by Papou** [FriendsOfSymfony/FOSUserBundle#351]
Hello everyone,

I installed FOSUserBundle, configured it in the kernel, registered it, i can create users without any problem but when i try to promote, for example, my admin user with this command :

php app/console fos:user:promote admin

and specify ROLE_ADMIN s role, i get the following error :

[Doctrine\ORM\ORMException]
Unrecognized field: usernameCanonical

Thanks for your help.
Regards

**Comment by LuisaBrito** [comment]
This solved not having auto_mapping

# app/config/config.yml
fos_user:    
    db_driver: orm    
    model_manager_name: non_default # the name of your entity manager
