### ISSUE TITLE
Can not login!!!

### ISSUE THREAD

**Issue by oopsFrogs** [FriendsOfSymfony/FOSUserBundle#355]
I'm a newbie of symfony2 and FOSuserbundle, but i found it's quite interesting to learn them step by step, However, I got a problem, I created the user, but I just couldn't login! It seemed that the system just can't recognize the password, I searched the web, but I didnt find anyone had the same problem with me. I wondered where I went wrong, please help.

app/config/security.yml

security:
    #default:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

```
#FOS setup
providers:
    fos_userbundle:
        id: fos_user.user_manager

firewalls:
    main:
        pattern: .*
        form_login:
            provider:     fos_userbundle
            login_path:   fos_user_security_login
            use_forward:  false
            check_path:   fos_user_security_check
            failure_path: null
        logout:           
            path:         fos_user_security_logout
            target:       /
        anonymous:        true

access_control:
    - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/(en|zh_TW)/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/(en|zh_TW)/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/(en|zh_TW)/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin/, role: ROLE_ADMIN }

#FOS setupe
role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    ROLE_SUPER_ADMIN: ROLE_ADMIN
```

app/config/routing.yml

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: /{_locale}

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /{_locale}/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/change-password

home:
    pattern: /{action}
    defaults: { _controller: FOSUserBundle:Security:login, action: 'login', _locale: 'zh_TW' }

**Comment by AmaliDeveloper** [comment]
you can get th solution in this tutorial [link](https://youtu.be/KT2JHTKziPo)
