### ISSUE TITLE
Issue with development and logging in with WDT

### ISSUE THREAD

**Issue by joshuataylor** [FriendsOfSymfony/FOSUserBundle#368]
So when you use the development environment, and logging into the system (say you went to index_dev.php/test), you'll be redirected to:
index_dev.php/_wdt/4e95412bc6871

Rather than the page (index_dev.php/test).

I expect this is because it thinks you want to log into the web profiler toolbar.

Anyone have a workaround for this?

**Comment by gggeek** [comment]
Hello

is this related: https://github.com/FriendsOfSymfony/FOSHttpCache/issues/287 ?
Shall I add a firewall rule for /_fos_user_context_hash ?
