### ISSUE TITLE
How to embed the login form

### ISSUE THREAD

**Issue by greg0ire** [FriendsOfSymfony/FOSUserBundle#399]
I helped a friend with FOSUserBundle yesterday. He asked me how to embed the login form, and I didn't know what to answer. Today, someone asked the very same question here : http://stackoverflow.com/questions/8040512/fosuserbundle-embedding-the-login-form-and-choosing-its-template
So, is it possible to embed the login form?
If yes, this issue is a documentation request, if not, this issue is a feature request.

**Comment by dheeraj-br** [comment]
@stof i managed to override the renderLogin() and inside it i use HTTP_REFERER to get the last login and use flashBags to display the error message. the only trouble is HTTP_REFERER may not be available all the time. so here's one way of doing it, but not at all reliable. an alternate way to get the last login would to have a hidden field in the form and then use it in place of http_referer
