### ISSUE TITLE
Adding new form to the bundle

### ISSUE THREAD

**Issue by Riki4321** [FriendsOfSymfony/FOSUserBundle#409]
Hey all,

I am using FOSUserBundle as core bundle for my UserBundle.
I wonder if I could add new form to my bundle like it is done in FOSUser?

I need to create multistep registration: first step is usual one, second is accessible after user clicks confirmation link in the email. 

I tried to override RegistrationController and add new action (like registerStep2Action) into it, but I don't know how to add new form into it. $this->createForm() doesn't work for me because RegistrationController does not extend Controller class.

Any ideas on the issue?

Thanks in advance.

**Comment by napestershine** [comment]
Hi
This should be helpful
https://github.com/craue/CraueFormFlowBundle
