### ISSUE TITLE
Model\User::isPasswordRequestNonExpired name is misleading

### ISSUE THREAD

**Issue by felds** [FriendsOfSymfony/FOSUserBundle#517]
Both the method name and the doc suggest that this method should return `true` if the password request is **not** expired. However it's doing the oposite.

Changing it's behavior could break some implementations that rely on it, but at the same time the API is confusing the way it is.

Any suggestions on how to handle this?

**Comment by Saracevas** [comment]
This has been closed, but it doesn't make any less confusing. For anyone wondering this checks if the password has been requested for the first time within the TTL period.
