### ISSUE TITLE
Route when something is wrong

### ISSUE THREAD

**Issue by Bieleke** [FriendsOfSymfony/FOSUserBundle#597]
Hi Guys,

I have installed the FOSUserBundle and have setted a {% render "FOSUserBundle:Security:login %} in my layout file, and for that to work i had to first disable the {% extends "FOSUserBundle::layout.html.twig" %} form the overridden login.html.twig.

Now however the problem is, when one of the credentials is incorrect, it goes to /login, but that displays ofcourse without the layout file as i had to disable it to be able to render it.

As my login is integrated in my layout i would just want it to return to the default index when one of the credentials is incorrect. How is that done with this bundle ? Must i overwrite the security controller ? And pass it too my index instead of the login.html.twig used by the bundle ?

**Comment by stof** [comment]
This should be solved by configuring the ``login_path`` to your own route in the firewall config
