### ISSUE TITLE
Same confirmation token

### ISSUE THREAD

**Issue by mhlavac** [FriendsOfSymfony/FOSUserBundle#674]
What happens if two confirmation tokens are same? I know the probabilty is very low, but recently one user registered and used confirmation link in email. He confirmed another account and was immidietly logged in as the different account.

The problem occured when two users had same confirmation tokens (-1) as they wanted to change their emails.

Should't be confirmation token set to unique in doctrine's entity settings?

**Comment by OskarStark** [comment]
@stof i would close this issue in favour of #1233 and put #1233 to the `2.0`milestone
