### ISSUE TITLE
[master]Problem with confirmation mail

### ISSUE THREAD

**Issue by n1c01a5** [FriendsOfSymfony/FOSUserBundle#675]
I have this error when the client click of the link to the validation of the registration.

The user with confirmation token "3ruk7721cgmc088owsc4ko84g844w8848gkc4o0wow4ss4swow" does not exist
404 Not Found - NotFoundHttpException

Any idea?

**Comment by krewetka** [comment]
The same when you click the link second time by accident when token is already gone. Definitely should be some nice message instead of error.

**Comment by boboldehampsink** [comment]
+1
