### ISSUE TITLE
userbundle in symfony2 standard-edition not working?

### ISSUE THREAD

**Issue by stoefln** [FriendsOfSymfony/FOSUserBundle#73]
checked out your newest revision (from today), and tried to install it twice. but can't get it running. error message:
"InvalidArgumentException: The service "security.user.provider.concrete.fos_userbundle" does not exist. in /Applications/MAMP/htdocs/symfony-standard/app/bootstrap.php on line 112"

after reloading i get 
"LogicException: Circular reference detected for service "security.context" (services currently loading: routing.loader.real, assetic.asset_manager, twig, security.context, security.authentication.manager, profiler, data_collector.security). in /Applications/MAMP/htdocs/symfony-standard/app/bootstrap.php on line 103"

guess thats some kind of cache issue....

any ideas on this one?

**Comment by AmaliDeveloper** [comment]
You can get the solution in this tutorial [Link](https://youtu.be/u4q_VqewQe4)
