### ISSUE TITLE
Reset Password allows discovery of valid email addresses

### ISSUE THREAD

**Issue by 2hat** [FriendsOfSymfony/FOSUserBundle#732]
There is a security concern with the reset functionality.   It is a lower risk item so I'll post it here.   

This issue is similar to the login fix where it says, "Invalid username or password" instead of "Invalid Username" in that error messages can leak private data in the database.

When a user resets a password they simply enter an email address and the system indicates if the email address is in the system or not.  If it is valid it indicates an email has been sent, if invalid it states so.

Someone could bruteforce a list of potential emails and clean the list so that based on the responses only valid email addresses appear.   The most likely application would be a phishing attack where someone has a huge spam database then they clean it against all the users in the system then send all those users targeted emails like, "Due to security reasons we have reset your password, click here to finish the process"   

There are two main paths that can be used to fix this:
- Add brute-force protection (https://github.com/FriendsOfSymfony/FOSUserBundle/issues/324)
- Change the wording of the response to "We are attempting to lookup that account and send a reset email.  If you do not get an email with the next few minutes take the following steps: ...."   This would parallel the login error message rational.

http://2hatsecurity.com

**Comment by samsch** [comment]
This is concerns me as well. It would seem the solution currently is to override the controller at the child bundle level.

I would like to see at least a configuration option that lets you give a generic message back to the user after submitting an email address. If the address is valid, send the email, if not, don't. But the user submitting the email address should not get feedback whether the email exist in the DB or not.

Really, that should be the default behavior.

**Comment by ninsuo** [comment]
FYI, with the recent major database leaks, attacks of this kind are on their ways.
By the way, discovery of valid email addresses is also possible using the registration form's validation

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2250
