### ISSUE TITLE
Expand the documentation about overriding User with propel

### ISSUE THREAD

**Issue by Martiusweb** [FriendsOfSymfony/FOSUserBundle#740]
Since Stof removed the proxy class when using the bundle with propel, I managed to refactor my code and find a correct way to extends the schema for the user and extends the `Propel\User` class without breaking anything.

The best solution I've found so far consist of :
- creating a new table/entity for my custom fields (a `Profile`), in my own bundle
- overriding the schema (copying the `schema.xml` file in `app/Resources/...`)
- adds to the fos_user table the delegate behavior:

```
<behavior name="delegate">
    <parameter name="to" value="scm_profile"/>
</behavior>
```

At the price of a 1:1 relation in my database and a bit of magic (`__call()` in `BaseUser.php`), I can now call from an `User` object the methods defined in the class `Profile`. It's effective and seems to be really flexible.

If you think this solution is a good one, I can write a PR and provide some details in the documentation of the bundle.

Regards,
Martin

**Comment by XWB** [comment]
Closing as Propel integration was moved to another bundle.
