### ISSUE TITLE
The handling of the remember_me does not work in the LoginManager

### ISSUE THREAD

**Issue by stof** [FriendsOfSymfony/FOSUserBundle#747]
The remember me services are private so they are removed from the container when optimizing it. This means that the [`has` checks in the LoginManager](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Security/LoginManager.php#L55) will return `false` even when the remember me is activated for the firewall.

/cc @schmittjoh

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2257
