### ISSUE TITLE
Argument 5 passed to RegistrationFormHandler::__construct() issue

### ISSUE THREAD

**Issue by GTheron** [FriendsOfSymfony/FOSUserBundle#777]
Hello!

So I just upgraded to Symfony 2.1, which is why I'm getting in a lot of trouble at the minute. I've fetched the master version of FOSUserBundle with Composer, and I've started reconfiguring my application.
I had overridden Registration forms handlers and types. Conscious that a lot of trouble could come from that, I systematically commented the function I was overriding so that only the native FOSUser functions be used.

I ran into an error I can't seem to find the origin of, the following:

Catchable Fatal Error: Argument 5 passed to FOS\UserBundle\Form\Handler\RegistrationFormHandler::__construct() must implement interface FOS\UserBundle\Util\TokenGeneratorInterface, none given, called in /var/www/LCSymfony/app/cache/dev/appDevDebugProjectContainer.php on line 1136 and defined in /var/www/LCSymfony/vendor/friendsofsymfony/user-bundle/FOS/UserBundle/Form/Handler/RegistrationFormHandler.php line 29 

I've tried emptying the cache as well, but no change after that. It seems to me that it's internal, I can't seem to determine what I'm doing wrong there. Any ideas?

**Comment by medhadj** [comment]
Good atrandafir
