### ISSUE TITLE
Add 'invalid_message' option into XXXFormType

### ISSUE THREAD

**Issue by demos77** [FriendsOfSymfony/FOSUserBundle#785]
Hi,

can you add the 'invalid_message' into this files :
- ChangePasswordFormType.php
- RegistrationFormType.php
- ResettingFormType.php

Where you use:
->add('plainPassword', 'repeated', array('type' => 'password',
                                                         'options' => array('translation_domain' => 'FOSUserBundle'),
                                                         'first_options' => array('label' => 'form.password'),
                                                         'second_options' => array('label' => 'form.password_confirmation'))

with per example :

'invalid_message' => [a_translation_var]

and with the translate var = 'The password fields must match.'

Because actualy, to use this feature we need to overide the complete FormType, but with just a translation var it's more simple.

It's a pull requets :)

thank you

**Comment by XWB** [comment]
This was added some time ago.
