### ISSUE TITLE
Invitation Cookbook Error

### ISSUE THREAD

**Issue by leevigraham** [FriendsOfSymfony/FOSUserBundle#800]
"You cannot search for the association field 'NSM\UserBundle\Entity\Invitation#user', because it is the inverse side of an association. Find methods only work on owning side associations."

I'm getting this error when I register a user. Removing `'user' => null` from `InvitationToCodeTransformer::reverseTransform()` seems to solve the issue.

**Comment by noreek** [comment]
I also keep relationships as in cookbook and i think easier solution:

    public function reverseTransform($value)
    {
        if (null === $value || '' === $value) {
            return null;
        }

        if (!is_string($value)) {
            throw new UnexpectedTypeException($value, 'string');
        }
        $invitation = $this->entityManager
            ->getRepository('Noreek\UserBundle\Entity\Invitation')
            ->findOneBy(array(
                'code' => $value,
            ));

        if ($invitation && !$invitation->getUser()) {
            return $invitation;
        }

        return null;
    }

So fetching invitation just by "code" and later make sure that there is no user  attached to this invitation.
