### ISSUE TITLE
UserBundle incompatible with FOSTwitterBundle and FOSFacebookBundle

### ISSUE THREAD

**Issue by lmcd** [FriendsOfSymfony/FOSUserBundle#807]
The documentation for FOSFacebookBundle details an example user provider to use with FOSUserBundle. The example code doesn't work though, because 'email_canonical' is not nullable. 

Sometimes you can populate the user's email on facebook, but what about twitter - where the API doesn't provide the user's email address?

See here: https://github.com/FriendsOfSymfony/FOSFacebookBundle#example-custom-user-provider-using-the-fosuserbundle

I'm working around this by storing [userid]@twitter.com - but this is far from ideal.

**Comment by XWB** [comment]
Closing as FOSTwitterBundle and FOSFacebookBundle are not relevant anymore.
