### ISSUE TITLE
Provide a renderRegister() method

### ISSUE THREAD

**Issue by MGaetan89** [FriendsOfSymfony/FOSUserBundle#828]
Hello,

In the [SecurityController](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Controller/SecurityController.php#L60), there is a `renderLogin()` method. I override it to be able to choose a template according to the page the user is requesting.
I would like to do the same on the register page, but there is no `renderRegister()` action in [RegistrationController](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Controller/RegistrationController.php). Is it possible to add one, so I don't have to override the whole registration logic just to choose a template ?

Thanks

**Comment by XWB** [comment]
Several events have been added.
