### ISSUE TITLE
remove the unique index on emailCanonical

### ISSUE THREAD

**Issue by ipartemk** [FriendsOfSymfony/FOSUserBundle#835]
How to remove the unique index on emailCanonical? (FOSUserBundle 1.2)

**Comment by xDaizu** [comment]
:+1:

**Comment by r4cker** [comment]
:+1:

**Comment by fredericlam** [comment]
I think we are all stuck with the same issue. After spending a couple of hours across stackoverflow, all topics lead to the #982 issue.
