### ISSUE TITLE
Overriding Default FOSUserBundle Controllers

### ISSUE THREAD

**Issue by Junus** [FriendsOfSymfony/FOSUserBundle#895]
Hi, in overriding_controllers.md you wrote 
```php
$this->authenticateUser($user);
$route = 'fos_user_registration_confirmed';
```
but in FOSUserBundle / Controller / RegistrationController.php authenticateUser function takes two parameters UserInterface and Response. I think it must be like this
```php
$route = 'fos_user_registration_confirmed';
$url = $this->container->get('router')->generate($route);
$response = new RedirectResponse($url);
$this->authenticateUser($user, $response);
```

**Comment by OskarStark** [comment]
@Junus can you provide the change as PR please?
After that you can ping me directly and i will review this.

Thank you :+1:

**Comment by Junus** [comment]
@OskarStark thank you for your reply, but this issue so old and I think it must be closed
