### ISSUE TITLE
Colon in form labels

### ISSUE THREAD

**Issue by EmmanuelVella** [FriendsOfSymfony/FOSUserBundle#941]
What about removing the form label colons ?

```
form:
    group_name: "Group name:"
    username: "Username:"
```

It should be possible to not display colons without overriding the translations.

**Comment by XWB** [comment]
https://github.com/FriendsOfSymfony/FOSUserBundle/commit/87bf9a92d8d3b15af41bdbaf7c061ca3636ceb90

**Comment by xabbuh** [comment]
Isn't this breaking applications that customised translations?
