### ISSUE TITLE
FOSUserEvents is missing in v1.3.1

### ISSUE THREAD

**Issue by dmb-dz** [FriendsOfSymfony/FOSUserBundle#945]
I installed v1.3.1 via composer following the instructions in the documentation.

I wanted to created a registration event listener and all I get is _Class 'FOS\UserBundle\FOSUserEvents'_.
Apparently the file is missing in the repo:
https://github.com/FriendsOfSymfony/FOSUserBundle/commits/v1.3.1/FOSUserEvents.php

Can I simply copy it from master or can you update the composer files?

**Comment by rparsi** [comment]
@stof This is a glaring oversight, why wasn't events included in the 1.3.x base version?  Events are core to symfony2 framework, one would think it's obvious that FOSUserBundle would need it from the start (ie event for successful user registration)

**Comment by stof** [comment]
@rparsi because triggering events in FOSUserBundle controllers was part of a full rewrite of these controllers, which is obviously not BC as it changes the way to hook in them.
