### ISSUE TITLE
Avoid Salt generator when using encoders like Bcrypt

### ISSUE THREAD

**Issue by runcom** [FriendsOfSymfony/FOSUserBundle#946]
This is not a big issue but FOSUserBundle generates and store in db the salt when i use my own Bcrypt encoder but bcrypt doesn't need a salt to be persisted so it's useless

**Comment by core23** [comment]
IMHO we can't fix this, because the [symfony encoder method](https://github.com/symfony/symfony/blob/v3.1.4/src/Symfony/Component/Security/Core/Encoder/PasswordEncoderInterface.php#L29) expects a valid salt.

**Comment by flip111** [comment]
@core23 where exactly in the code of FUB is the coupling between the user model and the symfony encoder?

**Comment by core23** [comment]
Here https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Model/UserManager.php#L161-L168
