### ISSUE TITLE
Security problem - Resetting

### ISSUE THREAD

**Issue by htomi** [FriendsOfSymfony/FOSUserBundle#965]
Hi!

If a disabled user reset his password, he will be enabled.

ResettingListener.php -> onResettingResetSuccess
$user->setEnabled(true); <-- always executed

**Comment by saulotoledo** [comment]
+1

**Comment by patrickmatsumura** [comment]
+1

**Comment by core23** [comment]
This was fixed in https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2076.

Think we should close this @XWB
