### ISSUE TITLE
not allowed to define new elements for path "security.providers"

### ISSUE THREAD

**Issue by tristanbes** [FriendsOfSymfony/FOSUserBundle#99]
Fatal error: Uncaught exception 'Symfony\Component\Config\Definition\Exception\InvalidConfigurationException' with message 'You are not allowed to define new elements for path "security.providers". Please define all elements for this path in one config file.' in /Users/Tristan/Sites/st2/vendor/symfony/src/Symfony/Component/Config/Definition/PrototypedArrayNode.php on line 247

Happening in PR10

Am I missing something ? does the config changed for UserBundle ?

Thanks

**Comment by kerdany** [comment]
Hi,

Just wonering about the reason for this constraint "All providers have to be defined in the same config file" in SecurityBundle?

Is it to prevent a bundle from overriding user (or other bundles') configuration?

Thanks

**Comment by stof** [comment]
@kerdany This constraint is not coming from FOSUserBundle at all. so it is the wrong place to ask

**Comment by kerdany** [comment]
Understood, thanks
